### ISSUE TITLE
Attempting to install pip-compile from pip opens browser window

### ISSUE THREAD

**Issue by layday** [jazzband/pip-tools#1000]
Assuming the `pip-compile` package on PyPI is owned by somebody from `pip-tools`: this is no way meant to detract from the work you've all put into `pip-tools` but opening a browser window when attempting to install a package from `pip` is intrusive.  Please remove that bit of code from your `setup.py`.

**Comment by atugushev** [comment]
Hello @layday,

> Assuming the `pip-compile` package on PyPI is owned by somebody from `pip-tools`

It's not correct, but you could ask @graingert, who is the owner of the package.

**Comment by graingert** [comment]
@layday the pip-compile package is not owned or managed by jazzband

**Comment by layday** [comment]
I know that, I tried to install it by accident.

**Comment by AndydeCleyre** [comment]
Can we close this as irrelevant?

**Comment by layday** [comment]
Happy new year to you too.

**Comment by AndydeCleyre** [comment]
I didn't mean to offend.

**Comment by layday** [comment]
That's alright, no offence taken.

**Comment by atugushev** [comment]
@graingert 

I thought, `pip-compile` package could require `pip-tools` instead of open a browser? `pytest-coverage` uses the same technic. What do you think?

**Comment by graingert** [comment]
that would work

**Comment by layday** [comment]
The `pip-compile` package should not open a browser window regardless. Just because you *can* execute arbitrary code from `setup.py` doesn't mean that you *should*.

**Comment by graingert** [comment]
@layday use pip `--only-binary` or take care and double check every package you download. Allow pip-tools to be a learning experience

**Comment by atugushev** [comment]
@graingert

> that would work

Great! Would you mind uploading a new release to `pip-compile` with the suggested change?

**Comment by layday** [comment]
> @layday use pip --only-binary or take care and double check every package before you download and execute it. Allow pip-compile to be a learning experience

I know that arbitrary code execution is a possibility and I know how to stave it off. What I had not realised in my folly is that you're a purveyor of "learning experiences".

**Comment by graingert** [comment]
@atugushev I can't find a way to depend on a package (pip-tools) so that package is installed and error the installation such that the current package (pip-compile) does not stay installed. Eg I want to prevent pip-compile ever being added to a `install_requires` or pinned into a requirements.txt

**Comment by atugushev** [comment]
@layday 

I would ask you to respect contributors and don't violate our [CoC](https://jazzband.co/about/conduct).

**Comment by atugushev** [comment]
> I can't find a way to depend on a package (pip-tools) so that package is installed and error the installation such that the current package (pip-compile) does not stay installed. Eg I want to prevent pip-compile ever being added to a `install_requires` or pinned into a requirements.txt

That's a trade-off, there is no way to prevent `pip-compile` from installing. But it's fine by me as long as `pip-tools` would be installed.

**Comment by layday** [comment]
My comment was meant to be taken humorously, hence the "purveyor".

**Comment by graingert** [comment]
@atugushev Let's close this issue as off-topic and move to https://github.com/graingert/pip-compile/issues/1

**Comment by atugushev** [comment]
@graingert 

Thank you! 🙏
