### ISSUE TITLE
Release 4.3.0

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1005]
Is someone interested in preparing [the next release](https://github.com/jazzband/pip-tools/milestone/30)? I'm up for doing this if no one else willing to take this up.

**Comment by hramezani** [comment]
I am interested. But don't know about the process. any documentation?

**Comment by atugushev** [comment]
@hramezani cool! Here is the [guideline](https://github.com/jazzband/pip-tools/blob/master/CONTRIBUTING.md#project-release-process). It's a little outdated since we can't push to the master without approvement, but we can push via PR. This is the latest reference: #936.

**Comment by atugushev** [comment]
Also, would be nice to merge #997 and #1004 before the release.

**Comment by atugushev** [comment]
I've updated the guidelines, see #1006.

**Comment by hramezani** [comment]
@atugushev [milestone 4.3.0](https://github.com/jazzband/pip-tools/milestone/30) is complete now.
Should we wait for #1004 for release?

**Comment by atugushev** [comment]
@hramezani I've merged the #1004. So nothing blocks the release now.

**Comment by atugushev** [comment]
@hramezani CI is green a3e18bd63bf555b78c06fc0356f7d3c6b923fd28, so you can draft [a new release](https://github.com/jazzband/pip-tools/releases/new).

**Comment by hramezani** [comment]
@atugushev, Thanks for your help. Here is the [releases 4.3.0](https://github.com/jazzband/pip-tools/releases/tag/4.3.0).

**Comment by atugushev** [comment]
`pip-tools v4.3.0` is released! The [milestone](https://github.com/jazzband/pip-tools/milestone/30) could be closed.

**Comment by atugushev** [comment]
Let's keep the issue be pinned for a while in case of users have any issues with the release.

**Comment by atugushev** [comment]
Huge thanks to @hramezani for managing this release!

**Comment by atugushev** [comment]
One wee without issues. Smooth release. Thanks to everyone involved! I'll close and unpin it.
