### ISSUE TITLE
A test fails when pytest ran with -k "not network"

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1014]
`test_locally_available_editable_package_is_not_archived_in_cache_dir` from `tests/test_cli_compile.py`

#### Environment Versions

1. OS Type: MacOs
1. Python version: `3.7`
1. pip version:  `19.3`
1. pip-tools version: 04ea3ad1ad31f27887bc09b8ba2de9f2aba184e8

#### Steps to replicate

1. `tox -e py37 -- -k 'not network'`

#### Expected result

Tests should pass.

#### Actual result

```pytb
Traceback (most recent call last):
  File "/Users/albert/Projects/pip-tools/tests/test_cli_compile.py", line 249, in test_locally_available_editable_package_is_not_archived_in_cache_dir
    assert not os.listdir(os.path.join(str(cache_dir), "pkgs"))
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/pytest-of-albert/pytest-448/test_locally_available_editabl0/cache_dir/pkgs'
```

**Comment by atugushev** [comment]
@hramezani git-bisect says this bug introduced in #998. Could you look into it?

**Comment by hramezani** [comment]
@atugushev Thanks for reporting. I will check it.
