### ISSUE TITLE
pip-compile on pyqt

### ISSUE THREAD

**Issue by piao217** [jazzband/pip-tools#1017]
I tried to use pip-compile on pyqt project.
The entry point is main.py so I ran _pip-compile main.py_.
But it shows the following error.
`pip._internal.exceptions.InstallationError: Invalid requirement: 'import fix_qt_import_error' (from line 1 of main.py)`
I have fix_qt_import_error.py in my local workspace and it seems like pip-tools is detecting it as a pypi package.
#### Environment Versions

1. OS Type : Windows 10
2. Python version: 3.7
3. pip version:  19.3.1
1. pip-tools version: 4.3.0

#### Expected result
requirements.txt for this pyqt project

#### Actual result
exception occured

**Comment by atugushev** [comment]
Hello @piao217,

It seems you're incorrectly using pip-compile, it should be run only with `setup.py`  or `requirements.in`. You can find more info about how to use `pip-compile` [here](https://github.com/jazzband/pip-tools#example-usage-for-pip-compile). Please, let me know if you have any questions.

**Comment by piao217** [comment]
OK, I just created setup.py in the workspace but not sure what to write there. In pyqt project, what are supposed to be in setup.py?

**Comment by atugushev** [comment]
what packages do you use for the project?

**Comment by piao217** [comment]
pyqt, selenium and some others

**Comment by piao217** [comment]
OK, no worries.

I added the following content to the setup.py and now I get a good result.
Thank you for your help.

`from setuptools import setup

setup(
    name="GMB_ALL",
    version="1.0",
    install_requires=[
        "ptvsd",
        "pandas",
        "numpy",
        "PyQt5",
        "selenium",
    ],
    # ...
)`

**Comment by atugushev** [comment]
Cool! 👍

**Comment by atugushev** [comment]
Also, you can use set the packages to `requirements.in` and compile, for example:

```
$ cat requirements.in
ptvsd
pandas
numpy
PyQt5
selenium

$ pip-compile
```

and got the same result :)

**Comment by piao217** [comment]
Thanks.
Actually the result is not as satisfactory as I initially expected from pip-tools.
If I run 'pip freeze', it outputs all libraries used.
I was hoping the similar result from pip-tools.
So e.g. if I run 'pip-compile' in my virtualenv, I want it to outputs all packages used in that workspace.
Please let me know any points that I am thinking wrong.

**Comment by atugushev** [comment]
'pip freeze' outputs all installed packages in the environment. `pip-compile` parses packages in `setup.py` (or `requirements.in`), resolves dependencies, pins them and writes to `requirement.txt` (as well as to the stdout). By compiled `requirements.txt` you can "sync" you packages `pip-sync` (it means pip-sync will install all packages from the `requirements.txt`). After the sync, you can check by `pip freeze` installed packages. That's the concept of pip-tools.

**Comment by piao217** [comment]
OK, thanks a lot for your instruction.
It makes sense now.

**Comment by atugushev** [comment]
@piao217 glad to help! Feel free to ask any questions.
