### ISSUE TITLE
pip-tools unable to find package in custom index url.

### ISSUE THREAD

**Issue by sathishbabu96** [jazzband/pip-tools#1025]
Pip tools is not able to find a package in the given index url.
#### Environment Versions

1. OS Type
1. Python version: 3.6.7
1. pip version:  19.3.1
1. pip-tools version: 4.3.0

We have a private server similar to PyPi to store our python packages. I am trying to install a package from the private server which is given as an argument to pip-tools as `--index-url`

#### Expected result

A requirements.txt file containing the package and its sub dependencies

#### Actual result

pip._internal.exceptions.DistributionNotFound: No matching distribution found for package==version (from -r requirements.in (line 1))

**Comment by atugushev** [comment]
Hello @sathishbabu96,

Thanks for the issue! If you attach the output of `pip-compile -v`, we'll try to figure out what's wrong. Do redact sensitive data if it's needed.

**Comment by sathishbabu96** [comment]
Yea, here's the output for the command `pip-compile -v`

`Using indexes:
  http://private-server

Configuration:
  -f http://private-server

                          ROUND 1                           
Current constraints:
  cherrypy==13.1.0 (from -r requirements.in (line 1))

Finding the best candidates:
  found candidate cherrypy==13.1.0 (constraint was ==13.1.0)

Finding secondary dependencies:
  cherrypy==13.1.0          requires cheroot>=5.9.1, portend>=2.1.1, six>=1.11.0

New dependencies found in this round:
  adding ['cheroot', '>=5.9.1', '[]']
  adding ['portend', '>=2.1.1', '[]']
  adding ['six', '>=1.11.0', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  cheroot>=5.9.1 (from cherrypy==13.1.0->-r requirements.in (line 1))
  cherrypy==13.1.0 (from -r requirements.in (line 1))
  portend>=2.1.1 (from cherrypy==13.1.0->-r requirements.in (line 1))
  six>=1.11.0 (from cherrypy==13.1.0->-r requirements.in (line 1))

Finding the best candidates:
Could not find a version that matches cheroot>=5.9.1 (from cherrypy==13.1.0->-r requirements.in (line 1))
No versions found
Was http://cm-server/python_downloads/ reachable?`

The package cheroot-6.0.0 is available in our server.

**Comment by sathishbabu96** [comment]
@atugushev Any update on this?

**Comment by atugushev** [comment]
@sathishbabu96 hard to tell what's wrong by the given log. More questions:
1. Are you sure about "Was http://private-server/ reachable?"? 
1. Could you CURL the http://private-server/simple/cheroot/?
1. Do you see cheroot-6.0.0 sources/wheel on http://private-server/simple/cheroot/?
1. Could you install `cheroot` directly via `pip install cheroot --verbose --index-url http://private-server/`? What was the output?

**Comment by sathishbabu96** [comment]
I was facing this issue in macOS, when I tried the same in Linux, everything worked perfectly. The package was not available for macOS version, hence I was facing this issue. I am closing the issue. Sorry for the inconvenience caused!.
