### ISSUE TITLE
setup.py install_requires should have `"click>=7"` not `"click>=6"`

### ISSUE THREAD

**Issue by DeTeReR** [jazzband/pip-tools#1038]
Thank you for all the work on this tool, it's very useful.

Issue:
As of 4.4.0 pip-tools now depends on version 7.0 of click, not 6.0.

The argument `show_envvar` is now being passed to `click.option()`
https://github.com/jazzband/pip-tools/compare/4.3.0...4.4.0#diff-c8673e93c598354ab4a9aa8dd090e913R183

That argument was added in click 7.0
https://click.palletsprojects.com/en/7.x/api/#click.Option
compared to 
https://click.palletsprojects.com/en/6.x/api/#click.Option

Fix: setup.py install_requires should have `"click>=7"` not `"click>=6"`

**Comment by atugushev** [comment]
Hello @DeTeReR,

Thanks for the heads up! Should be easy to fix.
