### ISSUE TITLE
Include the exact hash for VCS dependency.

### ISSUE THREAD

**Issue by devxpy** [jazzband/pip-tools#1059]
Currently, `pip-compile` doesn't include the commit hash for a git repo -

```
git+https://github.com/devxpy/django-pb-model.git
```

---

Of course, when a specific hash is made explicit in `setup.py`, it is honoured by `pip-compile` as well -

```
git+https://github.com/devxpy/django-pb-model.git@18778f769317ab9fab690ea2e581c2de47f46cf6
```

---

legit use-case -- git dependency was updated, but build server doesn't mark cache invalid since  `requirements.txt` doesn't change.

---

Really sorry if this is a dupe.
Thank you very much for taking the time and effort to maintain this awesome tool. Love it!

**Comment by atugushev** [comment]
Hello @devxpy,

Thanks for the issue! I’m not sure if I understand correctly, looks like it’s related to #161. Is it?

**Comment by devxpy** [comment]
Looks like a duo to me, thanks.
