### ISSUE TITLE
No handlers could be found for logger "pip._internal.deprecations"

### ISSUE THREAD

**Issue by gkalidas** [jazzband/pip-tools#1066]
#### Environment Versions

1. OS Type - Linux
1. Python version: `$ python -V` 2.7
1. pip version:  `$ pip --version` 20.0.2
1. pip-tools version: `$ pip-compile --version` not found

#### Steps to replicate

1. ... pip install requests
2. ... for any pip install operation
3. ...

#### Expected result

... It should install the required package

#### Actual result

...No handlers could be found for logger "pip._internal.deprecations"

Can anybody help me with this issue?

Steps taken:
Re-installed python2.7

**Comment by atugushev** [comment]
Hello @gkalidas,

Thanks for the issue! That should be fixed in the latest `4.4.1` release.

> 4\. pip-tools version: `$ pip-compile --version` not found

Could you check the version you're using?

**Comment by gkalidas** [comment]
Hello @atugushev,
Thanks for your prompt response.

I don't have pip-compile installed on my machine.
That's the reason I put "not found" in the version section.

The actual message is "bash: pip-compile: command not found".

**Comment by atugushev** [comment]
@gkalidas I see, looks like you should post issue on pip’s issue tracker if you don’t use pop-tools.

**Comment by gkalidas** [comment]
@atugushev Thanks.

Will post it on pip's issue tracker.

**Comment by atugushev** [comment]
I'll close this then. Feel free to rich as out if you have any questions regarding pip-tools.
