### ISSUE TITLE
pip-compile insists on newer versions despite sufficient version in link folder

### ISSUE THREAD

**Issue by derekbrokeit** [jazzband/pip-tools#1073]
I had the scenario where some wheels are packaged with a repository and I need to compile a requirements file. Given the existing wheels that are in the package, it would be ideal if those wheels did not need to update if they were sufficient. Instead, these wheels are being forced to update even though there are no hard requirements forcing this action.

#### Environment Versions

1. OS Type: `Linux`
1. Python version: `Python 3.7.4`
1. pip version:  `pip 20.0.2 from /home/derek.thomas/.python/lib/python3.7/site-packages/pip (python 3.7)`
1. pip-tools version: `4.5.0`

#### Steps to replicate

Perhaps I misunderstand the purpose of `--finds-link`, but given the following scenario, the compiled requirements file always ends up with the latest version:

```
# requirements.in
pip-tools>3.6
```
Filesystem:
```shell
$ ls linksdir
pip_tools-3.6.0-py2.py3-none-any.whl
```
#### Expected result

```shell
$ python3 -m piptools compile --find-links linksdir requirements.in
$ cat requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
click==7.0                # via pip-tools
pip-tools==3.6.0          # via -r requirements.in (line 1)
six==1.14.0               # via pip-tools
```

#### Actual result

```shell
$ python3 -m piptools compile --find-links linksdir requirements.in
$ cat requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
click==7.0                # via pip-tools
pip-tools==4.5.0          # via -r requirements.in (line 1)
six==1.14.0               # via pip-tools
```

My expectation was that it would require `pip-tools==3.6.0` because of the wheel present in the link directory. If this behavior is as expected, is there a way to achieve the desired outcome?

**Comment by atugushev** [comment]
Hello @derekbrokeit,

Thanks for the issue! `--find-links` is an option for additional package repositories. See [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#finding-packages):

> pip looks for packages in a number of places: on PyPI (if not disabled via --no-index), in the local filesystem, and in any additional repositories specified via --find-links or --index-url. There is no ordering in the locations that are searched. Rather they are all checked, and the “best” match for the requirements (in terms of version number - see PEP 440 for details) is selected.

**Comment by derekbrokeit** [comment]
Thanks @atugushev . I feel that there should be a way to prefer add a discovery order and "first-come-first-serve" preference in order to support local package repositories. Perhaps this is better suited as a feature request. From what I am understanding, the current implementation does not support this.

**Comment by atugushev** [comment]
@derekbrokeit 

you could request a feature on pip's issue tracker. Let's see how it goes.

**Comment by AndydeCleyre** [comment]
Workarounds that may or may not . . . work for you:

- Add `--no-index` to `requirements.in` -- This would apply to *all* the packages, though, which I doubt is what you want. It might be a neat feature to apply options like that to a subset of packages, or it might raise complexity levels through the roof :man_shrugging:.
- After compiling, manually downgrade the versions for those packages in the resulting `txt`, then compile again to iron out any dependency changes. This could be scripted, too.

Here's such a script in `zsh`. Not thoroughly tested, and sloppy enough to not care if the cached wheels work with the right python/arch. And it assumes GNU `sed`, because GNU `sed` is best `sed`.

```bash
#!/bin/zsh
downcompile () {  # <wheeldir> <reqstxt> [pip-compile options...]
    local all_cached=(${1:P}/*.whl)
    local reqstxt=$2
    shift 2
    local wheel pkgname pkgver
    for whl in ${(n)all_cached}; do  # numeric sorting
        wheel=(${(s:-:)whl:t:l})  # basename, lowercase, split on '-'
        pkgname=$wheel[1]
        pkgver=$wheel[2]
        sed -Ei 's/^('$pkgname'==)\S+(.*)/\1'$pkgver'\2/g' $reqstxt
    done
    pip-compile ${@:-${reqstxt:r}.in}  # if none specified, just pass reqsin based on reqstxt name
}
downcompile $@
```

Using it:

```console
$ print -l -- "-f $HOME/.cache/pip-tools/wheels" jinja2 > requirements.in
$ pip-compile --no-header requirements.in
--find-links /home/andy/.cache/pip-tools/wheels

jinja2==2.11.1            # via -r requirements.in (line 2)
markupsafe==1.1.1         # via jinja2
$ ./down-compile.zsh $HOME/.cache/pip-tools/wheels requirements.txt --no-header
--find-links /home/andy/.cache/pip-tools/wheels

jinja2==2.11.0            # via -r requirements.in (line 2)
markupsafe==1.1.1         # via jinja2
```

**Comment by AndydeCleyre** [comment]
@derekbrokeit 

- does that function achieve what you want?
- if so, is an external shell function a satisfactory solution, or will you try to get such a feature into pip?

**Comment by AndydeCleyre** [comment]
@derekbrokeit 

What do you think?

**Comment by AndydeCleyre** [comment]
@derekbrokeit ?

**Comment by AndydeCleyre** [comment]
Hey @derekbrokeit 

It's been about a year since you've been here, so I'm going to close this, but we can re-open any time.

Thanks!
