### ISSUE TITLE
Programmatic way to determine whether pip-sync would make changes

### ISSUE THREAD

**Issue by nchammas** [jazzband/pip-tools#1076]
#### What's the problem this feature will solve?

I want to write a script that warns users when their development environment is outdated. The team I'm on uses pyenv-virtualenv to associate a virtual environment with their local checkout of our repo. 

I want to use pip-sync in combination with something like [direnv](https://direnv.net) so that when they `cd` into the project directory, I can use pip-sync to check whether they have stale requirements and print a warning if they do.

I don't want to automatically modify their environment. I just want to post a clear message for the human to act on.

#### Describe the solution you'd like

I'm looking for a command to run that just flags whether or not the environment is up-to-date. `pip-sync --dry-run` comes close, but the return value is 0 whether or not there are changes, so it's clunky to use in a script. I'd have to parse the output, basically, to check whether any changes are pending. It's not a big deal.

I would prefer to be able to directly check the return value of pip-sync:

```sh
cat << EOM > .envrc
if [[ $(pip-sync --check) -ne 0 ]]; then
    echo "Your requirements are stale. Run pip-sync to update your environment."
fi
EOM
```

#### Alternative Solutions

```sh
if [[ $(pip-sync --dry-run | grep --quiet ^Would) -eq 0 ]]; then
   echo "Your requirements are stale..."
fi
```

**Comment by AndydeCleyre** [comment]
You don't really need to parse the output beyond checking that there is any, AFAICT, if you also use the `--quiet` flag:

```bash
[[ $(pip-sync requirements.txt -qn) ]] && echo 'STALE STALE STALE'
```

**Comment by AndydeCleyre** [comment]
@nchammas What do you think? Is output vs. no-output (as above) good enough, or are you still looking for a return code difference specifically?

**Comment by nchammas** [comment]
That's good enough. My only concern would be about future changes to this behavior since it may not be expressed formally enough that "no changes => no output with `-q`" is part of the API.

But since it appears [we have an explicit test for that](https://github.com/jazzband/pip-tools/blob/1d0883f79c94772254cb5c769da136d074b5dedd/tests/test_cli_sync.py#L40-L53), that's good enough for me.

Thanks for the suggestion.

**Comment by AndydeCleyre** [comment]
Excellent, thanks for confirming, and for linking the test. And thanks for that test, @atugushev .
