### ISSUE TITLE
Could sync please suppress script location warnings from pip

### ISSUE THREAD

**Issue by tim-mitchell** [jazzband/pip-tools#1079]
#### What's the problem this feature will solve?
Sync command issues a lot of warnings from pip, here is an example
```
  The script jwt.exe is installed in 'S:\components\win64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
#### Describe the solution you'd like
Sync command to run with no warnings from pip.

#### Alternative Solutions
Stop looking at innocuous warning messages from pip

#### Additional context
This could be an option exposed by sync or `--no-warn-script-location` could always be passed to pip.

**Comment by AndydeCleyre** [comment]
I think this is #321. I have a proposed solution posted there, but no feedback yet.

**Comment by tim-mitchell** [comment]
agreed
