### ISSUE TITLE
Add an option to not include paths in annotations

### ISSUE THREAD

**Issue by IRDonch** [jazzband/pip-tools#1084]
#### What's the problem this feature will solve?
My workflow involves using `pip-compile` on a requirements file from a software package installed on the local computer. This means that the output file includes annotations like `via -r /opt/foobar/requirements.txt`. However:

* different developers may have this requirements file installed in different locations;
* the location of the file may change between versions of the software.

As a result of this, different people (or the same person at different times) may get different annotations in `pip-compile`'s output, resulting in unnecessary diffs.

#### Describe the solution you'd like
An option like `--no-paths-in-annotations` that would replace the annotation with something like `via -r [...]`. Alternatively, `pip-compile` could automatically do it for any requirements file paths that are absolute.

#### Alternative Solutions
`--no-annotations` solves this, but it also removes annotations about package dependencies, which are nice to have.

**Comment by AndydeCleyre** [comment]
To be clear, you want the req-file's basename included in these annotations?

**Comment by IRDonch** [comment]
I don't really care about the basename either, although I wouldn't mind if it was included.

**Comment by kshpytsya** [comment]
As a workaround for this I just have a wrapper script do a `cd` to the directory containing the `requirements.in`.

`<repo>/scripts/make-requirements-txt`

```sh
#!/bin/bash

REPO_DIR="$(realpath "$(dirname "$0")/..")"
cd "$REPO_DIR" || exit 1

CUSTOM_COMPILE_COMMAND="scripts/make-requirements-txt" \
    pip-compile \
    "requirements.in" \
    -v \
    --generate-hashes \
    "$@"
```

**Comment by IRDonch** [comment]
I think I'm going to cancel this request, because it's a very specific use case, and in the end I worked around it by just removing the paths from the resulting `requirements.txt` file by post-processing.

Instead, I'm giving my vote to #1377, which is a lot more general and, if implemented, would help resolve this issue as well.
