### ISSUE TITLE
Require branches to be up to date before merging

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1085]
#### What's the problem this feature will solve?

Currently, the master might be broken by merging a PR that has not been tested with the latest code. I believe we could adjust the repository settings to avoid this issue.

#### Describe the solution you'd like

Update the repository settings to protect the master branch:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/7377671/75889570-b6ccca80-5e5f-11ea-8a99-559b0df8dcff.png">

#### Additional context
 
https://github.com/jazzband/pip-tools/pull/824#issuecomment-594512120

**Comment by atugushev** [comment]
kindly ping @jezdez

**Comment by jezdez** [comment]
@atugushev which of the status check should be required to be passing (as mentioned in the help text to the "Require branches to be up to date before merging")?

Status checks found in the last week for this repository:
codecov/patch
codecov/project
continuous-integration/appveyor/branch
continuous-integration/appveyor/pr
continuous-integration/travis-ci
coverage/coveralls
test (2.7, pipmaster, ubuntu-latest)
test (2.7, pipmaster, windows-latest)
test (3.5, pipmaster, ubuntu-latest)
test (3.5, pipmaster, windows-latest)
test (3.6, pipmaster, ubuntu-latest)
test (3.6, pipmaster, windows-latest)
test (3.7, pipmaster, ubuntu-latest)
test (3.7, pipmaster, windows-latest)
test (3.8, pipmaster, ubuntu-latest)
test (3.8, pipmaster, windows-latest)

**Comment by atugushev** [comment]
@jezdez I wouldn't require any of that, because the coverage could be decreased or tests failed (canceled for example) for any unimportant reason and it could be inappropriate to block merge on that.

**Comment by jezdez** [comment]
The feature requires enabling at least one:

![Screen-Shot-2020-04-24-20-07-59](https://user-images.githubusercontent.com/1610/80243498-9eab4780-8667-11ea-9a63-3477da20de09.png)

**Comment by atugushev** [comment]
Okay... Let's try these two then:

- continuous-integration/appveyor/pr
- continuous-integration/travis-ci

**Comment by altendky** [comment]
For GitHub Actions I add an `all` job that depends on the others so I can select a single item for the GitHub actions builds.  This way when you change matrixing, or even just job names, you don't have to update your GitHub branch policies.  Also, depending on other selections admins can override these conditions on the PR page when merging.  But yeah, if GitHub Actions isn't primary then this is a side-note FYI.

https://github.com/pytest-dev/pytest-twisted/blob/7cf213bacf37240995b8d6bb46cf90935b05f2fd/.github/workflows/ci.yml#L120-L130
```yaml
  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - linting
    steps:
      - name: This
        shell: python
        run: |
          import this
```

**Comment by jezdez** [comment]
@atugushev Done.

**Comment by atugushev** [comment]
@altendky thanks for the trick!  GitHub Actions CI is on the way.

@jezdez thank you!
