### ISSUE TITLE
pip-compile gives different ordered output of --no-binary flags each run

### ISSUE THREAD

**Issue by richafrank** [jazzband/pip-tools#1097]
Pip-compiling with the same, multiple `--no-binary` flags produces output with those flags in different orders each run.

It looks like `FormatControl.no_binary` is unordered (a `set()`), so we could sort them in `OutputWriter.write_format_controls`. `write_format_controls` uses `dedup` to preserve any ordering of the underlying iterable, but there is no underlying order here. If you agree with this change, I can submit a quick PR.

#### Environment Versions

1. OS Type ubuntu
1. Python version: `$ python -V`: `Python 3.5.9`
1. pip version:  `$ pip --version`: `pip 18.1`
1. pip-tools version: `$ pip-compile --version`: `pip-compile, version 4.5.1`

#### Steps to replicate

1. 
```
# reqs.in
--no-binary six
--no-binary requests
--no-binary urllib3

six
requests
urllib3
```
2. `$ pip-compile reqs.in`
```
--no-binary six
--no-binary requests
--no-binary urllib3

certifi==2019.11.28       # via requests
chardet==3.0.4            # via requests
idna==2.9                 # via requests
requests==2.23.0          # via -r temp.in
six==1.14.0               # via -r temp.in
urllib3==1.25.8           # via -r temp.in, requests
```

3. `$ pip-compile reqs.in` again
```
--no-binary requests
--no-binary six
--no-binary urllib3

certifi==2019.11.28       # via requests
chardet==3.0.4            # via requests
idna==2.9                 # via requests
requests==2.23.0          # via -r temp.in
six==1.14.0               # via -r temp.in
urllib3==1.25.8           # via -r temp.in, requests
```

#### Expected result
```
--no-binary requests
--no-binary six
--no-binary urllib3

certifi==2019.11.28       # via requests
chardet==3.0.4            # via requests
idna==2.9                 # via requests
requests==2.23.0          # via -r temp.in
six==1.14.0               # via -r temp.in
urllib3==1.25.8           # via -r temp.in, requests
```

^ An example using a sorted order

**Comment by atugushev** [comment]
@richafrank thanks for the good catch!
