### ISSUE TITLE
The `pip-compile` doesn't mask credentials in --extra-index-url from pip.conf file

### ISSUE THREAD

**Issue by aorumbayev** [jazzband/pip-tools#1099]
#### Environment Versions

1. macOS Catalina 10.15.4
1. Python version: 3.6.10
1. pip version: 20.0.2
1. pip-tools version: 4.5.1

#### Steps to replicate

1. Write an extra-index-url that contains username/password in global pip.conf file. Due to pip limitations those has to be passed along in url (for example for cases when there is a private registry in Artifactory) 
```
[global]
timeout = 60
extra-index-url = https://{username}:{password}@private_pypi_registry_url
```
2. run pip-compile on absolutely any .in file
3. Observe the header lines containing full url without encoded credentials. In contrast while doing pip install, pip at least masks the password part automatically.

#### Expected result

Any extra flag or argument that dev can specify to mask both username and password.

#### Actual result

Raw unmasked credentials that can be accidentally committed into git history.

**Comment by atugushev** [comment]
Hello @aorumbayev,

Thanks for the issue. In that case `--no-index` option might help.

**Comment by aorumbayev** [comment]
Sorry @atugushev wasn't aware of this flag. This solves the issue! Thanks for fast reply!

**Comment by shaleh** [comment]
For those hitting this from a web search, the option as of 6.6 is now `--no-emit-index-url`.

**Comment by jeffwright13** [comment]
I'm surprised `--no-emit-index-url` isn't the default behavior. All too easy to commit your credentials to a public repo with this.
