### ISSUE TITLE
pip-compile --generate-hashes including bdist_egg hashes

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#1121]
Due to https://github.com/jazzband/pip-tools/pull/1109 pip-compile now includes bdist_egg hashes when previously it did not

This isn't strictly a bug as the hashes are useless eggs that pip does not install

#### Environment Versions

1. OS Type N/A
1. Python version: `$ python -V` N/A
1. pip version:  `$ pip --version` N/A
1. pip-tools version: `$ pip-compile --version` 5.1.0

#### Steps to replicate

```diff
 toml==0.10.0 \
     --hash=sha256:229f81c57791a41d65e399fc06bf0848bab550a9dfd5ed66df18ce5f05e73d5c \
     --hash=sha256:235682dd292d5899d361a811df37e04a8828a5b1da3115886b73cf81ebc9100e \
+    --hash=sha256:f1db651f9657708513243e61e6cc67d101a39bad662eaa9b5546f789338e07a3 \
```

**Comment by atugushev** [comment]
Please review #1122.
