### ISSUE TITLE
pip-compile does not seem to support pip "--python-version" arg

### ISSUE THREAD

**Issue by David-Guillot** [jazzband/pip-tools#1124]
Hi there,

Our use-case is described in [this Dependabot issue](https://github.com/dependabot/feedback/issues/794) (I thought it was Dependabot-related but it seems not), here is a quick summary:

- Our project targets Python 3.6
- The environment running `pip-compile -P whatever_package` or `pip-compile -U` is Python 3.8 (it's Dependabot)
- Some of our packages require, only for Python <3.8, `importlib-metadata`
- When running `pip-compile -U`, package `importlib-metadata` is removed from the existing output file ; this is normal behavior since the environment running `pip-compile` is Python 3.8.

After some research we found argument `--pip-args` that allows to pass `--python-version` to `pip`, which should do what we want. The expected behavior of this is to have the same result as we have by running `pip-compile` with Python 3.6, no? But when running `pip-compile -U --pip-args '--python-version=3.6'`, package `importlib-metadata` is also removed from output file :thinking: 

#### Environment Versions

1. GNU/Linux
1. Python version: 3.8.0
1. pip version:  20.1
1. pip-tools version: 5.1.0

#### Steps to replicate

1. Have a `requirements.in` file with `kombu==4.6.*`
2. Run `pip-compile --pip-args='--python-version=3.6'`

#### Expected result

Among the output, `importlib-metadata` should appear.

#### Actual result

It does not.

#### :warning: Warning :warning:

It is possible that I misunderstood the role of `pip`'s `--python-version` argument, so if you have another way to achieve compiling for Python 3.6 using Python 3.8, I'm listening ;)

Thanks,

**Comment by atugushev** [comment]
Hello @David-Guillot,

Thanks for the issue! `pip-tools` doesn't guarantee that all `pip install` options would work. I believe we should point out that in the docs/help (what do you think @AndydeCleyre?).

As for `--python-version=3.6` workaround, have you tried `python3.8 -m pip install kombu --python-version=3.6` and get `importlib-metadata` installed as a dependency?

Also, you may find useful [a note](https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile) about cross-environment usage of `pip-tools`.

**Comment by atugushev** [comment]
@David-Guillot 

> It is possible that I misunderstood the role of `pip`'s `--python-version` argument, so if you have another way to achieve compiling for Python 3.6 using Python 3.8, I'm listening ;)

I should note that `pip-tools` doesn't encourage compiling python3.X using python3.Y.

**Comment by AndydeCleyre** [comment]
Hello! A few notes:

1. `--python-version` is an option of `pip install`, not a general `pip` option.

`pip-compile --pip-args '--python-version=3'` will pass that on to `pip`, which will ignore it, AFAIK.

In contrast, `pip-sync --pip-args` will pass options to `pip install`.

This is documented in the cli help outputs and in the readme, but let me know if you think it should be made clearer somehow.

2. I'm not sure this `pip` option relates to the env markers anyway. The [description](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-python-version) is:

> The Python interpreter version to use for wheel and “Requires-Python” compatibility checks.

:man_shrugging: I really don't know what the `wheel` behavior is with that.

3. Yeah, while there are some interesting possibilities now for compiling to multiple targets and combining the results, this project does not currently offer ways to compile for one target from another.

4. IMO, dependabot *should* support specifying which version of python to use.

5. To workaround the problem (hopefully just until dependabot gets version-spec support), maybe you could keep a separate `txt` file with `importlib-metadata ; python_version < '3.8'`, and include (`-r`) that along with your primary compiled `txt` in a new non-compiled "master" `txt`.

**Comment by David-Guillot** [comment]
Hi there,

@atugushev I did not understand that `--python-version` is a `pip install` option. When running `pip install kombu --python-version=3.6`, pip fails with message
> ERROR: When restricting platform and interpreter constraints using --python-version, --platform, --abi, or --implementation, either --no-deps must be set, or --only-binary=:all: must be set and --no-binary must not be set (or must be set to :none:).

I now understand what you @AndydeCleyre say about this pip option description: it just does not apply to env markers. I'll setup the workaround you're suggesting and ask Dependabot guys if they can implement choosing Python version on their side.

Thank you both for your quick, clear and complementary answers :+1: . Closing the issue.

**Comment by David-Guillot** [comment]
Just a successful demo of @AndydeCleyre workaround suggestion:

### Without workaround

`requirements.in`
```
kombu===4.6.*
```
`pip-compile` result:
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
amqp==2.5.2               # via kombu
kombu==4.6.8              # via -r requirements.in
vine==1.3.0               # via amqp
```


### Workaround

`requirements.in`
```
-r requirements-py36.txt
kombu===4.6.*
```
`requirements-py36.txt`
```
importlib-metadata==1.6.*
```
`pip-compile` result:
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
amqp==2.5.2               # via kombu
importlib-metadata==1.6.0  # via -r requirements-py36.txt
kombu==4.6.8              # via -r requirements.in
vine==1.3.0               # via amqp
zipp==3.1.0               # via importlib-metadata
```

It's perfect!
