### ISSUE TITLE
Pin VCS links (pin github etc. links to git hashes)

### ISSUE THREAD

**Issue by jjlee** [jazzband/pip-tools#1128]
#### What's the problem this feature will solve?

Quite often I have a bunch of github / gitlab repositories that I want to pin to their current revision.

* Often these repositories are ones I maintain myself, in which case it would be great if pip-compile could pin to a git hash for me.
* Sometimes I'm pulling in some bugfix from somebody else's repo before a release has been done, in which case automatic pinning using pip-compile is less useful, because probably I should manually pin to a github link with a hash in requirements.in, and then the next time I update, manually replace that github link with a PyPI name so that I get a release instead of a random github revision.
* Other times, though, even with other people's repositories, I do want to pin to a github link: little repositories won't always bother to upload to PyPI at all, and sometimes I do want to track development -- but updating at a time of my choosing -- so pinning to a github link is exactly what is needed.

Is it possible to use pip-compile to do that?

#### Describe the solution you'd like

For example, I'd like pip-compile to be able to turn something like this in requirements.in:

git+https://github.com/some/project.git#egg=someproject

into something like this:

git+https://github.com/some/project.git@abcdef123#egg=someproject

I imagine it would default to branch master if no branch was specified in the link in requirements.in, but would allow a link like this, specifying a different branch name:

git+https://github.com/some/project.git@develop#egg=someproject

Note: I'm not up to date with all the current variations of how to spell this in requirements.txt and their subtleties (-e link#egg=project, link, project@link, link#egg=project, etc.) so I just illustrated with the plain "link" format above.  I'm sure others know better than me how to deal best with all those variants.

#### Alternative Solutions

I can do the pinning by hand by specifying a git hash in the VCS link in requirements.in.  But almost every time I do that, I'm really just looking to pin to the latest commit on master, and then later to update again to the latest master commit.

Conceivably it would be even better if you could *also* say "pin this github branch, and then when a PyPI release is done that contains that commit, use the release instead of the github link on the next pip-compile", but then we're very definitely far enough into bonus points that I'd see that as a different feature request, and I imagine it would be tricky to connect releases with git hashes with useful reliability without somebody putting in a big effort on adding metadata to PyPI.  Also, I'd like to stress that in many situations (own github repo, or tracking upstream development), this behaviour is not actually the needed one.

**Comment by atugushev** [comment]
Hello @jjlee,

Thank you for the detailed issue! It duplicates #161.
