### ISSUE TITLE
Adopt flake8-pytest-style

### ISSUE THREAD

**Issue by webknjaz** [jazzband/pip-tools#1133]
#### What's the problem this feature will solve?

Tests style consistency.

#### Describe the solution you'd like

Adopt https://github.com/m-burst/flake8-pytest-style.

#### Alternative Solutions

N/A

#### Additional context

N/A

**Comment by atugushev** [comment]
Nice plugin! Looking forward to adopting it 👍

**Comment by webknjaz** [comment]
FTR here's how I configure it:
```ini
# flake8-pytest-style
# PT001:
pytest-fixture-no-parentheses = true
# PT006:
pytest-parametrize-names-type = tuple
# PT007:
pytest-parametrize-values-type = tuple
pytest-parametrize-values-row-type = tuple
```

**Comment by atugushev** [comment]
Personally, I prefer `pytest-parametrize-names-type = csv`, but I prefer consistency more, so nevermind :)

**Comment by atugushev** [comment]
@webknjaz 

It would be nice to have a check to use `pytest.param()` for non-simple parametrizations. Have you seen one?

**Comment by webknjaz** [comment]
I don't like csv because it's one huge visually unparsable string and a data structure with separate strings is preferable here.

You can open an issue to request a new rule in their repo.
