### ISSUE TITLE
Clear-text password leaked via index URL

### ISSUE THREAD

**Issue by nolar** [jazzband/pip-tools#1137]
Clear-text username and password from index URL are directly put to the generated `requirements.txt` files, not hidden in any way as `pip` does, and ignoring the `--no-index-url`/`--no-trusted-host` options.

#### Environment Versions

1. OS Type: Linux
1. Python version: 3.6
1. pip version:  20.1
1. pip-tools version: 5.1.1

#### Steps to replicate

1. Set env var `PIP_INDEX_URL` to `https://username:password@hostname/...`
2. Set env var `PIP_TRUSTED_HOST` to `hostname`
2. Run `pip-compile --no-index --no-emit-trusted-host`

#### Expected result

No index URL is added due to `--no-index`.

OR: No credentials included.

OR: Credentials are hidden.

#### Actual result

Index URL with credentials is added to the requirements.txt file:

```
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --index-url=https://username:password@hostname/... --no-emit-trusted-host --no-index --output-file=requirements.txt --trusted-host=hostname requirements.in
#
………
```

...

**Comment by nolar** [comment]
Related with a similar issue: #1028

**Comment by nolar** [comment]
And also, when clear-text username and password are used, `pip-compile` still leaks them on stdout/stderr (not into `requirements.txt` as above); stdout/stderr are often sent to remote logging systems, so they should not contain sensitive data (same is true for user terminals).

```
$ cat ~/.pip/pip.conf
[global]
index-url = http://user1:passw1@localhost:8888/
```

```
$ pip-compile --no-emit-trusted-host --no-index requirements.in --upgrade
Could not find a version that matches kopf (from -r requirements.in (line 1))
No versions found
Was http://user1:passw1@localhost:8888/ reachable?
```

This code is also in pip-tools: https://github.com/jazzband/pip-tools/blob/b37b91d251f7c7e590047f902e6f51e9a49d276c/piptools/exceptions.py#L45-L47

**Comment by atugushev** [comment]
Hello @nolar 

Thanks for the issue. Here is the fix #1146. Please test/review, any feedback is welcomed!

**Comment by nolar** [comment]
@atugushev Yes, it fixes the password leaking problem:

In stdout/stderr, the output now is:

```
Was http://user1:****@localhostBAD:8888/repository/pypi/simple reachable?
```

In requirements.txt:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --index-url='http://user1:****@localhost:8888/repository/pypi/simple' --no-emit-trusted-host --no-index --output-file=requirements.txt --trusted-host=localhost requirements.in
#
………
```

The `--index-url` and `--trusted-host` should not have been added to the header at all, but this is a separate issue #1028 (this PR is mentioned there, but the CLI arg is not removed). The password leaking problem is stopped though.

**Comment by nolar** [comment]
@atugushev Can you please give a rough estimation when will this be released as a PyPI-hosted package?

**Comment by atugushev** [comment]
@nolar 

Thanks for pinging. I'll start working on a release as soon as we fix our CI issues (#1151).

**Comment by atugushev** [comment]
`pip-tools v5.2.0` is released 🚀

**Comment by nolar** [comment]
@atugushev Nope. The password still leaks. Now, yet another way — with `--no-header`, but with no `--no-index`, as it is declared deprecated:

```
$ cat ~/.pip/pip.conf

[global]
index-url = http://user1:pass1@localhost:8888/repository/pypi/simple
```

```
$ pip freeze --all | grep pip
pip==20.1
pip-tools==5.2.0
```


```
$ pip-compile --no-header requirements.in 
--index-url http://user1:pass1@localhost:8888/repository/pypi/simple

aiohttp==3.6.2            # via aiojobs, kopf
………
```

The same with the header:

```
$ pip-compile requirements.in 
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.in
#
--index-url http://user1:pass1@localhost:8888/repository/pypi/simple

aiohttp==3.6.2            # via aiojobs, kopf
```

It does NOT leak via the header as originally reported — as expected. I only tried this mode because `--no-index` caused warnings.

**Comment by atugushev** [comment]
@nolar 

`--no-emit-index-url` should be used if you have a sensitive data in `--index-url`.

**Comment by nolar** [comment]
@atugushev It works! Thank you for your fast reaction to this issue!

**Comment by atugushev** [comment]
@nolar 

Glad to help! Don't hesitate to reach out if you have any questions.
