### ISSUE TITLE
Xfail test_realistic_complex_sub_dependencies on pypy windows

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1148]
>           # TODO: fix test_realistic_complex_sub_dependencies test on Windows

this could be an xfailing test

_Originally posted by @webknjaz in https://github.com/jazzband/pip-tools/pull/1147#issuecomment-629831688_

**Comment by DiddiLeija** [comment]
Hi @atugushev. Is this issue resolved? If not, I can work on it. Just tell me where to go.

**Comment by atugushev** [comment]
Hello @DiddiLeija,

It's not yet resolved. This test should be marked as `xfail` for the Windows platform so that we can uncomment the Windows platform on CI.

**Comment by DiddiLeija** [comment]
Ok. I'll be opening a PR the next week.

**Comment by DiddiLeija** [comment]
I created #1489 to fix this issue.
