### ISSUE TITLE
UnpicklingError on pip-compile on Windows

### ISSUE THREAD

**Issue by marfire** [jazzband/pip-tools#115]
Running `pip-compile` (with either the exe or the python script) fails with the following `UnpicklingException` on Python 3.4.1 (64-bit) on Windows 7.

> Traceback (most recent call last):
>   File "pip-compile-script.py", line 9, in <module>
>     load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
>   File "C:\Program Other\Python341\lib\site-packages\click\core.py", line 610, in
> **call**
>     return self.main(_args, *_kwargs)
>   File "C:\Program Other\Python341\lib\site-packages\click\core.py", line 590, in
> main
>     rv = self.invoke(ctx)
>   File "C:\Program Other\Python341\lib\site-packages\click\core.py", line 782, in
> invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "C:\Program Other\Python341\lib\site-packages\click\core.py", line 416, in
> invoke
>     return callback(_args, **kwargs)
>   File "C:\Program Other\Python341\lib\site-packages\piptools\scripts\compile.py", line 174, in cli
>     compile_specs(src_files, include_sources=include_sources, dry_run=dry_run)
>   File "C:\Program Other\Python341\lib\site-packages\piptools\scripts\compile.py", line 106, in compile_specs
>     pinned_spec_set = resolver.resolve()
>   File "C:\Program Other\Python341\lib\site-packages\piptools\resolver.py", line 44, in resolve
>     if not self.resolve_one_round():
>   File "C:\Program Other\Python341\lib\site-packages\piptools\resolver.py", line 28, in resolve_one_round
>     new_deps = self.find_new_dependencies()
>   File "C:\Program Other\Python341\lib\site-packages\piptools\resolver.py", line 91, in find_new_dependencies
>     all_deps = self.find_all_dependencies()
>   File "C:\Program Other\Python341\lib\site-packages\piptools\resolver.py", line 74, in find_all_dependencies
>     pkg_deps = pkgmgr.get_dependencies(spec.pin(version))
>   File "C:\Program Other\Python341\lib\site-packages\piptools\package_manager.py", line 337, in get_dependencies
>     deps = self._dep_cache.get((name, version))
>   File "C:\Program Other\Python341\lib\site-packages\piptools\package_manager.py", line 200, in get
>     return self[key]
>   File "C:\Program Other\Python341\lib\site-packages\piptools\package_manager.py", line 192, in __getitem__
>     return self.cache[key]
>   File "C:\Program Other\Python341\lib\site-packages\piptools\package_manager.py", line 169, in cache
>     self.read_cache()
>   File "C:\Program Other\Python341\lib\site-packages\piptools\package_manager.py", line 176, in read_cache
>     self._cache = pickle.load(f)
> _pickle.UnpicklingError: the STRING opcode argument must be quoted

[This message](http://lists.open-bio.org/pipermail/biopython-dev/2014-April/011292.html) suggests that it might have something to do with DOS versus UNIX line endings.

**Comment by davidovich** [comment]
This issue was opened at a time where there was a package_manager.py file in pip-tools. I will now close. If you think that this is still a problem, feel free to reopen.
