### ISSUE TITLE
Varying "extras" outcomes with the same input requirements

### ISSUE THREAD

**Issue by nolar** [jazzband/pip-tools#1153]
The compiled extras appear and disappear on sequential runs of `pip-compile` with the same input.

#### Environment Versions

1. OS Type: Mac OS
1. Python version: `$ python -V`: Python 3.7.4
1. pip version:  `$ pip --version`: pip 20.1
1. pip-tools version: `$ pip-compile --version`: 5.2.0

#### Steps to replicate

1. Create files as following:

```
# requirements.in (NOT NEEDED, just for a complete picture)
connexion
```

```
# requirements.txt
connexion==2.7.0
```

```
# requirements-dev.in
-c requirements.txt
connexion[swagger-ui]
```

2. Run 

```
pip-compile --no-emit-trusted-host --no-emit-index-url --upgrade --output-file=requirements-dev.txt requirements-dev.in
```

3. Observe: `connexion==2.7.0` OR `connexion[swagger-ui]==2.7.0` is added to `requirements-dev.txt` depending on luck (repeat 3-4 times), when `[swagger-ui]` extra is expected to be there always.

4. Repeat 3-4 times.

#### Expected result

The outcome is consistent over time: multiple runs generate the same result (always with the extra).

```
connexion[swagger-ui]==2.7.0  # via -c requirements.txt, -r requirements-dev.in
```

#### Actual result

The outcome varies between multiple runs.

One of:

```
connexion[swagger-ui]==2.7.0  # via -c requirements.txt, -r requirements-dev.in
```

OR

```
connexion==2.7.0          # via -c requirements.txt, -r requirements-dev.in
```

Randomly on each attempt.

---
**PS:** My initial assumption was that it is flipping forth-and-back on each run. But, after a few experiments, I've got cases when it was consistent for 2-3 attempts in a row, but again varying on the 4th attempt. So, looks like random.

**Comment by atugushev** [comment]
Duplicates to #852

**Comment by atugushev** [comment]
@nolar 

Thanks for the reproducer!

**Comment by atugushev** [comment]
Let's track it in #852. Thanks for the issue!
