### ISSUE TITLE
`pip-compile` only primary requirements defined in `requirements.in`

### ISSUE THREAD

**Issue by cabhishek** [jazzband/pip-tools#1156]
#### What's the problem this feature will solve?

We have a requirement where our project only really needs to pin the primary requirements defined in the `requirements. in` file. And right now, there is no way to do this explicitly. So we have to generate the `requirements.txt` file and strip out all non-primary dependencies, which is quite hacky. 
 
#### Describe the solution you'd like

`pip-compile --primary-requirements-only --output-file requirements.txt --upgrade requirements.in`. 

#### Alternative Solutions

None available today in `pip-compile.` But maybe use `pip.` 

#### Additional context

None

**Comment by atugushev** [comment]
Hello @cabhishek,

Thanks for the issue! IMO, this case is too specific and could be solved by:

```console
$ pip-compile -qo- | grep "via -r requirements.in"
```

But, I'd be happy to hear other opinions.

**Comment by cabhishek** [comment]
@atugushev Thanks for the suggestion, and we are doing something similar. But I guess our use case is specific since we don't even need the annotations  `# "via -r requirements.in..."`. So we cannot use `--no-annotate` flag if we are relying on annotation for primary dependency filtering.  

But overall I think its quite a simple use case, just pin dependencies from `requirement.in` but not recursively.

**Comment by AndydeCleyre** [comment]
A few extra notes:

- You can add a comment-stripping step in the pipeline to @atugushev's example:
```console
$ pip-compile -qUo- requirements.in | grep "via -r requirements.in" | grep -o '.*  ' > requirements.txt
```
- You can do it with one fewer pipe with a fancy tool like `pcregrep`, `pcre2grep`, or `rg` (ripgrep):
```console
$ pip-compile -qUo- requirements.in | pcregrep -o1 '(.*) # via -r requirements.in' > requirements.txt
$ pip-compile -qUo- requirements.in | pcre2grep -o1 '(.*) # via -r requirements.in' > requirements.txt
$ pip-compile -qUo- requirements.in | rg -r '$1' '(.*) # via -r requirements.in' > requirements.txt
```
- **Be warned** that in this project's current state, running `pip-sync` without options against such a resulting `requirements.txt` will behave inconsistently. Let's say we've got two primary requirements, `click` and `boto3`:
```console
$ pip-sync -q requirements.txt
$ pip freeze | wc -l
10
$ pip-sync -q requirements.txt
$ pip freeze | wc -l
4
$ pip-sync -q requirements.txt
$ pip freeze | wc -l
4
$ pip-sync -q /dev/null
$ pip-sync -q requirements.txt
$ pip freeze | wc -l
10
```
You can consistently install only the primary requirements without any of their dependencies (a broken installation), with:
```console
$ pip-sync --pip-args --no-deps requirements.txt
```
But I doubt that's what you want. I would be very interested to hear if it *is* what you want; I have a PR to, IMO, *fix* the above inconsistency by always installing those unpinned dependencies, but it's been met with concerns about breaking workflows, though no one has yet provided an actual workflow which would be broken by it. For details, see #907 and #896.

**Comment by AndydeCleyre** [comment]
Looks like the new annotation format that puts them on separate lines breaks these workarounds. You can instead get the explicit reqs by either parsing the reqsin files or fancier parsing of the annotated txts.

I'll try to post such a workaround soon.

**Comment by cabhishek** [comment]
@AndydeCleyre Thanks, and yes, this change breaks our build pipeline. Our unit test caught this change, and now regex parsing is harder. TBH, I don't understand the value add of the new annotation format.

**Comment by AndydeCleyre** [comment]
@cabhishek 

While I hope and believe we'll get the compact annotations back soon, I have written a new workaround that doesn't parse the annotation strings, as a zsh function:

```zsh
#!/bin/zsh
.pcpicky_pkgspec2name () {  # <pkgspec>
  emulate -L zsh
  unset REPLY
  [[ $1 ]] || return

  REPLY=${${(j: :)${${(s: :)${1##*\#egg=}:l}:#-*}}%%[ \[<>=#~;@&]*}
}

pcpicky () {  # [<reqs.in>]
  emulate -L zsh

  local reqsin pipc_args=()
  reqsin=${1:-requirements.in}

  local targets=()
  for 1 ( ${(f)"$(<$reqsin)"} ) {
    .pcpicky_pkgspec2name $1
    targets+=($REPLY)
  }

  local pins=()
  for 1 ( ${(f)"$(pip-compile -qUo- $reqsin)"} ) {
    .pcpicky_pkgspec2name $1
    if (( targets[(I)$REPLY] )) pins+=($1)
  }

  <<<${(F)pins} >${reqsin:r}.txt
}

pcpicky $@

```

**Comment by AndydeCleyre** [comment]
Just noting here that `--annotation-style=line` can help with parsing, in newer versions.

**Comment by cabhishek** [comment]
`--annotation-style=line` works as expected and creates comments on the same line as the requirements.  Thanks.
