### ISSUE TITLE
Question: Are there risks when hashes couldn't be gotten from PyPI?

### ISSUE THREAD

**Issue by khink** [jazzband/pip-tools#1170]
Just out of curiosity:

I just ran pip-compile and it said "Couldn't get hashes from PyPI, fallback to hashing files". This appears to come from https://github.com/jazzband/pip-tools/blob/008865ac7607476c0be20b2a3c5fd1bcf3d39c70/piptools/repositories/pypi.py#L340

When i run `pip-compile -v`, i get:
```
    Missing release files on PyPI
    Couldn't get hashes from PyPI, fallback to hashing files
    Hashing Unidecode-0.04.21.tar.gz
    Hashing Unidecode-0.04.21-py2.py3-none-any.whl
```

This is the first time i get this message, although we've been using pip-tools in this project for about 6 months, and we have been using this Unidecode version for a long time as well. According to https://pypi.org/project/Unidecode/0.04.1/#history, this version is 3 years old.

Question 1: How come this message appears now? Could the hash have been removed on PyPI? 

The resulting requirements file has no changes for Unidecode, so `pip-sync`ing the resulting requirements.txt is no problem. 

Question 2: If there was an update for a package for which no hash could be found on PyPI, could it be a problem?

**Comment by graingert** [comment]
Getting the requirements from pypi is a relatively new optimization, and if they are missing it's not a problem per-se.

It could mean the network dropped out, or there was some other outage, or you are using an index that doesn't support the pypi JSON api

**Comment by graingert** [comment]
if you run with --debug mode it should give you more info:

@khink https://github.com/jazzband/pip-tools/blob/008865ac7607476c0be20b2a3c5fd1bcf3d39c70/piptools/repositories/pypi.py#L267-L286

**Comment by khink** [comment]
@graingert I can't reproduce it right now, but i'll keep the `--debug` in mind when i see this again. 

Closing this now, question answered, thanks!

**Comment by graingert** [comment]
actually there is no such `--debug` option!

**Comment by atugushev** [comment]
I'm glad the fallback mechanism works as expected! :)
