### ISSUE TITLE
Can't compile certain dependencies (cartopy, pyhdf)

### ISSUE THREAD

**Issue by ingwinlu** [jazzband/pip-tools#1185]
It is quite common (and sometimes necessary) for some libraries to depend on other dependencies in their setup.py. Currently pip-compile can't handle those cases as those imports fail.

relevant upstream issues:
https://github.com/SciTools/cartopy/issues/1552

#### Environment Versions

1. all (tested on linux)
1. Python version: python 3.8.3
1. pip version:  pip 20.1.1
1. pip-tools version: 5.2.1

#### Steps to replicate

1. requirements.in with either cartopy or pyhdf in it, other lines optional)
2. run pip-compile

#### Expected result
success and requirements.txt is produced
#### Actual result
pip-compile exception due to exceptions raised in the dependencies package files

**Comment by atugushev** [comment]
Hello @ingwinlu,

Thanks for the issue! Looks like there is no clear solution at the moment. Science libs (e.g., `cartopy`) require `NumPy` (and many more) at the setup time, so you have to satisfy those requirements before pip-compile being run.

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
