### ISSUE TITLE
The index URL should not expose the password

### ISSUE THREAD

**Issue by aflaisler** [jazzband/pip-tools#1193]
By default `pip-compile` will add any custom pip repository URL along with the login details if they are in the URL. 

#### Steps to replicate

1. Run `pip-compile`

#### Expected result

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
--index-url https://user:****@private.pip.repo.c4cloud.net/repository/pypi-all/simple
```

#### Actual result

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
--index-url https://user:password@private.pip.repo.c4cloud.net/repository/pypi-all/simple
```

**Comment by atugushev** [comment]
Hello @aflaisler 

Thanks for the report! That's a deliberate decision. You can hide sensitive data with `--no-emit-index-url` option.

**Comment by aflaisler** [comment]
Ah ok thanks!
