### ISSUE TITLE
Avoid exposing secrets on requirements.txt for --[extra-]index-url with credentials

### ISSUE THREAD

**Issue by jorgecarleitao** [jazzband/pip-tools#1198]
When running

```
pip-compile requirements.in --extra-index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@gitlab.com/api/v4/projects/.../packages/pypi/simple
```

the resulting requirements is

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --extra-index-url='https://[USERNAME]:****@gitlab.com/api/v4/projects/.../packages/pypi/simple' requirements_test.in
#
--extra-index-url https://[USERNAME]:[PASSWORD]@gitlab.com/api/v4/projects/.../packages/pypi/simple

...==0.2.7  # via -r requirements.in
numpy==1.19.1             # via ...
scipy==1.5.2              # via ...
```

where both `[USERNAME]` and `[PASSWORD]` are __shown in plain text__. Since the `requirements.txt` shall end in version control, specially with post-commit hooks, this exfiltrates secrets to the git repository.

#### Environment Versions

1. OS Type: Mac
1. Python version: `Python 3.7.3`
1. pip version:  `pip 20.2.1`
1. pip-tools version: `pip-compile, version 5.3.1`

#### Steps to replicate

See above.

#### Expected result

The secrets should not be outputted to the compiled `requirements.txt`. Instead, they should keep their original names, [as pip accepts](https://pip.pypa.io/en/latest/reference/pip_install/#using-environment-variables).

In the example above, IMO we should only output

```
--extra-index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@gitlab.com/api/v4/projects/.../packages/pypi/simple
```
both on the header and on the actual requirements. It is the responsibility of the deployment team to ensure that they have the credentials to download dependencies from a pypi server.

#### Actual result

The secrets are outputted to `requirements.txt`.

**Comment by jorgecarleitao** [comment]
This also happens with

```
PIP_EXTRA_INDEX_URL=https://${PYPI_USERNAME}:${PYPI_PASSWORD}@gitlab.com/api/v4/projects/.../packages/pypi/simple pip-compile requirements.in
```

**Comment by jorgecarleitao** [comment]
This also happens when

```
--extra-index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@${PYPI_REPOSITORY}/simple
```

is added on `requirements.in`. This is likely the correct place place it, as we have the opportunity to not expand the variables here. All other options above, `PIP_EXTRA_INDEX_URL` and `--extra-index-url` give us no opportunity to not have the expanded variables, as they are already expanded by bash when we receive them.

**Comment by jorgecarleitao** [comment]
@atugushev, together with git-hooks this easily causes password exfiltrations, which is considered a security vulnerability. Is there any timeline or acknowledgement of the validity of the issue?

**Comment by atugushev** [comment]
Hello @jorgecarleitao,

Thanks for the issue! There is `--no-emit-index-url` option for the case when you have sensitive data in index URLs.

> This also happens when
> 
> ```
> --extra-index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@${PYPI_REPOSITORY}/simple
> ```
> 
> is added on `requirements.in`. This is likely the correct place to place it, as we have the opportunity to not expand the variables here. 

Keeping unexpanded variables in `requirements.txt` sounds a good idea, see relative issue #966.

**Comment by jorgecarleitao** [comment]
closing in favor of #966 .

**Comment by ericbn** [comment]
The issue here is that the shell is expanding the environment variables, so pip-compile will get the `--extra-index-url` parameter value with the environment variables already expanded. A solution is to use single quotes, to prevent the shell from expanding them, like:
```
pip-compile requirements.in --extra-index-url 'https://${PYPI_USERNAME}:${PYPI_PASSWORD}@gitlab.com/api/v4/projects/.../packages/pypi/simple'
```
But that only works partially. See #1367.
