### ISSUE TITLE
Environment markers not processed correctly for package "keyring"

### ISSUE THREAD

**Issue by khink** [jazzband/pip-tools#1199]
After reading https://github.com/jazzband/pip-tools/issues/206, i understood that OS-dependent requirements should be processed correctly by pip-compile and pip-sync now.

However, for the keyring package, which requires jeepney and SecretStorage on Linux (https://github.com/jaraco/keyring/blob/master/setup.cfg#L26), i don't see these environment markers in the generated requirements file, and they are therefore unpinned. As a result, the requirements file that i generated (with hash-checking mode) on MacOS does not work on my colleague's Linux machine.  

#### Environment Versions

1. MacOs
1. Python 3.6.8
1. pip 20.1 (and 20.2.1)
1. pip-tools 5.1.2 (and 5.3.1)

#### Steps to replicate

1. `echo "keyring" >> keyring.in`
2. `pip-compile keyring.in`
This gives:
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile keyring.in
#
importlib-metadata==1.7.0  # via keyring
keyring==21.3.0           # via -r keyring.in
zipp==3.1.0               # via importlib-metadata
```

#### Expected result

I'd expect to see the `jeepney` and `SecretStorage` dependencies in the generated requirements, followed by `; sys_platform=="linux"`

#### Actual result

I don't see the `jeepney` and `SecretStorage` dependencies in the generated requirements.

**Comment by atugushev** [comment]
Hello @khink,

Thanks for the issue! If you os-dependant packages, yous should compile them to separate requirement files, e.g. `linux-requirements.txt` and `macos-requirements.txt`. You can read more details in [README](https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile).

**Comment by khink** [comment]
@atugushev Thanks for pointing that out.

**Comment by atugushev** [comment]
@khink  Sorry for taking so long to answer your question.

Yes, you're right, `requirements.txt` may have markers for different OS'es.

To compile dependencies on a certain OS, you must run `pip-compile` on that particular OS to evaluate markers. It's impossible to run `pip-compile` on macOS and get dependencies for Linux, hence the article on README to split requirements.txt to OS (or python) dependant requirement files.

Currently, `pip-tools` does not support multi-environment (multi-OS or multi-python) dependencies compilation.

**Comment by khink** [comment]
Thanks for clearing that up!

**Comment by webknjaz** [comment]
> To compile dependencies on a certain OS, you must run `pip-compile` on that particular OS to evaluate markers. It's impossible to run `pip-compile` on macOS and get dependencies for Linux, hence the article on [README](https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile) suggesting to split requirements.txt to OS (or python) dependant requirement files.

I'm curious if this could be achieved with pip's `--platform`.

**Comment by AnandInguva** [comment]
Does pip-compile plan to support pip's platform tag? 

I am trying to compile the list of dependencies on MacOS for the package `google-python-cloud-debugger` which has only wheels compatible on Linux. 

Use case: We download the PyPI package and its sub-dependencies on windows/Linux/MacOS by pip download <package> --platform <linux> for offline installations on Linux systems.

It would be great if pip-tools can have this feature.

**Comment by ppawiggers** [comment]
This would be great - I would like to generate a hashed requirements file on MacOS, including the hashes for Linux-only packages.
