### ISSUE TITLE
pip-dump rewrites requirements from git

### ISSUE THREAD

**Issue by utapyngo** [jazzband/pip-tools#120]
In my requirements.txt I have some requirements from git, like this one:

```
git+git://github.com/pivotal-energy-solutions/django-datatable-view.git@e8fb942f5b39da63a252803d6d052305a04ab311#egg=django-datatable-view
```

pip-dump overwrites this line with django-datatable-view==0.8.0

I would prefer if it left these lines as they were.

**Comment by davidovich** [comment]
pip-dump is no longer present in latest releases. If you feel that this needs to be addressed, please feel free to reopen.
