### ISSUE TITLE
Preserve directory when deriving output path from input path

### ISSUE THREAD

**Issue by gsganden** [jazzband/pip-tools#1200]
#### What's the problem this feature will solve?

When `pip-compile` derives an output path from an input path, it does not preserve the input path directory. As a result, for instance, compiling requirements for a standalone module within a repository from the top-level directory in that repository without an explicit output directory causes the output to be placed in the top-level directory rather than alongside the input file within its module.

#### Describe the solution you'd like

Preserve the input directory when deriving an output path from an input path.

#### Alternative Solutions

Another option is to provide an explicit output path when running pip-compile on a file outside the working directory. However, the solution proposed here is more convenient. More importantly, it is less surprising and thus will lead to fewer mistakes.

#### Additional context

This change is easy to make, and I would be happy to implement it.

**Comment by atugushev** [comment]
Hello @gsganden,

Thanks for the issue! Could you please provide some examples to clarify the issue to make sure that we're on the same page?

**Comment by gsganden** [comment]
My team has a repository for "performance reports" for various machine learning models. It contains a directory called "reports" with subdirectories for different models, e.g. "taxonomy" and "category_propensity." The code to generate the taxonomy reports has different requirements from the code to generate the category_propensity reports, so "reports/taxonomy" and "reports/category_propensity" each have their own requirements.in and requirements.txt files, for instance.

I'd like to be able to run e.g. `pip-compile reports/taxonomy/requirements.in` from the repo root to generate reports/taxonomy/requirements.txt, but that command actually generates ./requirements.txt from reports/taxonomy/requirements.in. My biggest concern is not that having to run `pip-compile reports/taxonomy/requirements.in -o reports/taxonomy/requirements.txt` instead is a minor convenience, but that it is easy to miss the fact that `pip-compile reports/taxonomy/requirements.in` overwrote ./requirements.txt and mess up your requirements files because the default behavior of `pip-compile reports/taxonomy/requirements.in` is surprising.

**Comment by gsganden** [comment]
It looks like you are right and I made a mistake. Sorry to bother you!
