### ISSUE TITLE
Guideline on how to install new package

### ISSUE THREAD

**Issue by robinaly** [jazzband/pip-tools#1201]
Dear pip-tools authors,

I think I understand the intention behind these tools and would like to start using them.

What is unclear to me is how a new dependency is introduced. Suppose you have two packages A and B in requirements.in that received versions AV and BV respectively from pip-compile. If you now want to install package C, I understand I should add it to requirements.in and run pip-compile? But what happens if A has now a newer version then at the time of original install? I will get that version in requirements.txt, correct? That might not be wanted in several use cases. Can you comment on the intended workflow in this regard?

Thanks & Kind regards
Robin

**Comment by atugushev** [comment]
Hello @robinaly,

Thanks for the issue!

> But what happens if A has now a newer version then at the time of original install? I will get that version in requirements.txt, correct?

`pip-compile` would preserve the pinned version of `A` package. If you need to upgrade versions, you should run `pip-compile --upgrade` to [upgrade](https://github.com/jazzband/pip-tools#updating-requirements) all packages or `pip-compile--upgrade-package {package-name}` to upgrade a specific package.

**Comment by AndydeCleyre** [comment]
@robinaly 

I think your question has been answered. Please write again if something's unclear; otherwise, we'll go ahead and close this issue soon. Thanks!
