### ISSUE TITLE
pip-sync --keep-existing

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#1206]
https://github.com/jazzband/pip-tools/issues/1166
https://github.com/pypa/pip/issues/53

#### What's the problem this feature will solve?
I've enabled https://github.com/jazzband/pip-tools/issues/1166 which works great to remind people to upgrade their packages - but some people add additional local packages but don't add them to the requirements.txt

#### Describe the solution you'd like
a `pip-sync --keep-existing` flag that worked with `pip-sync --keep-existing --dry-run` to behave in the same way as the proposed https://github.com/pypa/pip/issues/53

#### Alternative Solutions
* a `requirements-dev-specific.txt` in .gitignore for additional deps?
* I could just wait for them to do it in `pip` directly

#### Additional context
`pip-sync --keep-existing` is kind-of odd without `--dry-run` as it's exactly the same as `pip install -r requirements.txt`

**Comment by AndydeCleyre** [comment]
Can you please state more specifically what `pip-sync --keep-existing` and `pip-sync --keep-existing --dry-run` are expected to do, and what the initial problem is?

Is the behavior you're after the same as currently achieved with `pip-sync --dry-run <shared.txt> <personal.txt>`?

**Comment by graingert** [comment]
> Is the behavior you're after the same as currently achieved with pip-sync --dry-run <shared.txt> <personal.txt>?

Ooh I think so - is there a way to ignore the `<personal.txt>` file if it's missing?

**Comment by AndydeCleyre** [comment]
That's probably easiest (best?) handled by shell globbing/scripting, and a file naming convention. What do you think?

**Comment by graingert** [comment]
Yeah that's probably better
