### ISSUE TITLE
Expected a pinned InstallRequirement, got unknown

### ISSUE THREAD

**Issue by portedison** [jazzband/pip-tools#1219]
#### Environment Versions

1. OS Type
1. Python version: 3.6.0 (via pyenv)
1. pip version:  20.2.4
1. pip-tools version: 5.3.1

#### Steps to replicate

1. create requirements.in with WeasyPrint (50 or 52)
2. run pip-compile --output-file=requirements.txt requirements.in

#### Actual result
```WARNING: Generating metadata for package cairocffi produced metadata for project name unknown. Fix your #egg=cairocffi fragments....```

``` ... /.pyenv/versions/3.6.0/lib/python3.6/site-packages/piptools/utils.py", line 141, in as_tuple raise TypeError("Expected a pinned InstallRequirement, got {}".format(ireq))
TypeError: Expected a pinned InstallRequirement, got unknown from https://files.pythonhosted.org/packages/84/ca/0bffed5116d21251469df200448667e90acaa5131edea869b44a3fbc73d0/cairocffi-1.2.0.tar.gz#sha256=9a979b500c64c8179fec286f337e8fe644eca2f2cd05860ce0b62d25f22ea140 (from WeasyPrint==52->-r requirements.in (line 2))```

**Comment by AndydeCleyre** [comment]
Closing in favor of #1218
