### ISSUE TITLE
piptools is broken with pip 20.3b1

### ISSUE THREAD

**Issue by mayli** [jazzband/pip-tools#1227]
pip has [dropped](https://github.com/pypa/pip/commit/6887b0795b3567ac2a85578e5509dd8cfcc2b284) the `wheel_download_dir` in 20.3b1

https://github.com/pypa/pip/commit/6887b0795b3567ac2a85578e5509dd8cfcc2b284#diff-c17e0a1f79c2e7ffff850bdb0c3f9593b7f5ffd56b094a9fdb53b9ce5212c34bL203-L209

Not sure why I am getting pre-release pip installed, but FYI this interface change break piptools.

**Comment by atugushev** [comment]
Thanks @mayli for the issue! It duplicates #1228.
