### ISSUE TITLE
Remove AppVeyor use?

### ISSUE THREAD

**Issue by jezdez** [jazzband/pip-tools#1230]
#1229 has removed the use of Travis-CI in favor of the GitHub Actions setup, which also supports Windows.

I've already removed the pull request merge requirement for AppVeyor following the discussion there.

Should we remove AppVeyor completely?

Refs: https://github.com/jazzband-roadies/help/issues/74

**Comment by atugushev** [comment]
I'm in. See also #1223.

**Comment by davidovich** [comment]
I'm for it in theory. Github actions model is very nice, and having only one ci provider is simpler.

**Comment by vphilippon** [comment]
Agreed on my side too. If we have our needs covered (which I think we do), then 👍 .
