### ISSUE TITLE
Annotations sometimes losing internal packages

### ISSUE THREAD

**Issue by enkidulan** [jazzband/pip-tools#1248]
When I run `pip-compile` some of the internal packages may not appear in annotations, but the next day they may appear again.  

The internal package structure looks like this:
```
# package: dependencies 
my_pkg_1:
my_pkg_2:
my_pkg_3: libhoney, my_pkg_2
my_pkg_4: my_pkg_3
my_pkg_5: my_pkg_3 my_pkg_4, my_pkg_2
my_pkg_6: libhoney, my_pkg_2, my_pkg_2, my_pkg_3, my_pkg_4
my_pkg_7: my_pkg_1, my_pkg_6, my_pkg_4, my_pkg_5
```

I'm having hard times trying to pin-point the way to reproduce the issue, but the issue seems constant. I was getting a package appearing and dispersing from annotations in 3 successive days constantly. 

Any hints on what can cause the issue or how to debug it is very appreciated.

#### Environment Versions

1. Linux
1. Python version: `2.7.18`
1. pip version:  `19.0.3`
1. pip-tools version: `4.5.1`

#### Steps to replicate

1. run `pip-compile`

#### Expected result

No changes to `.txt` files

#### Actual result

`my_pkg_4` is lost from `libhoney` annotation

```
-libhoney==1.9.0           # via -c my_pkg_7/requirements.txt, -r my_pkg_7/requirements.txt, my_pkg_4, honeycomb-beeline, my_pkg_5, my_pkg_3
+libhoney==1.9.0           # via -c my_pkg_7/requirements.txt, -r my_pkg_7/requirements.txt, honeycomb-beeline, my_pkg_5, my_pkg_3
```

**Comment by atugushev** [comment]
Hello @enkidulan,

Thanks for the detailed report! Could you reproduce the issue with the latest `pip-tools` version?

**Comment by atugushev** [comment]
It's been some time so I will close this issue now, but please don't hesitate to reach out again if you have any other issues. Thanks!
