### ISSUE TITLE
Combining setup.py with requirements.in

### ISSUE THREAD

**Issue by IRDonch** [jazzband/pip-tools#1256]
#### What's the problem this feature will solve?
I'd like to build a `requirements.txt` based on a combination of inputs that includes both `requirements.in` files and project `setup.py` files.

#### Describe the solution you'd like
It would be nice if `pip-compile` could support arbitrary combinations of `requirements.in` files and `setup.py` files as input. Perhaps it could look something like this:

```
$ pip-compile /path/to/requirements1.in /path/to/some-project-dir /path/to/requirements2.in
```

#### Alternative Solutions
I've tried to create a `requirements.in` file that contained a line with the path to the project directory and to pass _that_ as an input to `pip-compile`, however that doesn't work quite right. The resulting `requirements.txt` file contains that path too, as well as the project's dependencies; whereas I'm looking for a way to include the project's dependencies, but not the project itself.

**Comment by atugushev** [comment]
Hello @IRDonch,

Have you tried this?

```bash
pip-compile requirements.in  setup.py --output-file requirements.txt
```

**Comment by IRDonch** [comment]
Oh! Didn't think that was possible. That solves it, thanks. :-)
