### ISSUE TITLE
Combining efforts with the new pip resolver utilization

### ISSUE THREAD

**Issue by fridex** [jazzband/pip-tools#1298]
Hi there!

I'm not sure if I'm using the right medium to reach out to the pip-tools people with this question, but I hope so. I would like to ask if there are any plans to use the new pip resolver (pip>=20.3) in pip-tools. There was an idea to use pip's resolver in [micropipenv](https://github.com/thoth-station/micropipenv) (https://github.com/thoth-station/micropipenv/issues/151#issuecomment-754624873) and I'm wondering how much our efforts eventually overlap.

Thanks for your reply!

**Comment by webknjaz** [comment]
Hey @fridex!
I suggested it here https://github.com/jazzband/pip-tools/issues/1190#issuecomment-740094471 as I have experience integrating it already, and also somebody mentioned resolvelib in https://github.com/jazzband/pip-tools/issues/693 earlier. But nobody seemed to explicitly agree that this should be done.
Personally, I think it's a good idea to use it. FWIW it shouldn't be too hard to implement.

**Comment by fridex** [comment]
Thanks, @webknjaz for the reply! I'm not familiar with the pip resolver interface so I cannot judge complexity. I'll try to monitor pip-tools efforts and learn if something suitable for micropipenv would occur in that case. Thanks!

**Comment by atugushev** [comment]
#1539 adds for pip's 2020 dependency resolver support!

**Comment by atugushev** [comment]
The resolver is released as part of pip-tools `v6.8.0`. Use `pip-compile --resolver backtracking`.
