### ISSUE TITLE
add exclusions (prevent pip-sync from uninstalling unreferenced dependencies)

### ISSUE THREAD

**Issue by maquino1985** [jazzband/pip-tools#1305]
#### What's the problem this feature will solve?

I'm running pip-sync inside a docker image (tiangolo/meinheld-gunicorn:python-3.8) which contains meinheld and gunicorn pre-installed and are only used for deployment.  if i do not have them added to the requirements.txt they are removed. however i'm worried setting them in the requirements.txt file will create version conflicts in the future and would rather just exclude them from being installed, like what the docs say pip install --user SomePackage does.  (pip-sync requirements.txt --pip-args '--user' doesn't do this)

#### Describe the solution you'd like

a way to prevent pre-existing dependencies from being uninstalled

I think my problem includes the real-world use case.

#### Alternative Solutions

I tried running pip-sync inside a virtual environment in my Dockerfile but that didn't work. The only thing that has worked is adding the dependencies to my project requirements as well, but the issue is that I'm afraid we will get out of sync (as I'm not running pip-compile unless my dependencies change and pip-compile without a version still contains the current latest version in the output requirements.txt file)

**Comment by AndydeCleyre** [comment]
It sounds like you want 

```console
$ pip install -r requirements.txt
```

**Comment by AndydeCleyre** [comment]
@maquino1985 

I believe your case is solved by using `pip install` rather than `pip-sync`, as above.

As it's been a month since your last message and my proposed solution, I'm going to close this for now. Please come back and we'll re-open if this turns out not to be a solution for you. Thanks!
