### ISSUE TITLE
Request: Compact annotations

### ISSUE THREAD

**Issue by AndydeCleyre** [jazzband/pip-tools#1306]
#### What's the problem this feature will solve?
**Primary:**

I would like to see a lot more information on my screen without having scroll up and down, when viewing annotated `pip-compile` output. At least as much as was the case before annotations became split into many lines.

**Secondary:**

I would like to use simple line-oriented shell tools to casually inspect properties of the `pip-compile` output, without resorting to multi-line regular expressions.

#### Describe the solution you'd like
I would like the ability, through a flag or any other means, to have `pip-compile`'s annotated output place annotations for a pinned requirement on the same line as said requirement.

My screen is wide and short, as is common for computers. It's a more efficient use of this space to use more width and less height.

Example of the different use of space, for the `magic-wormhole` package from PyPI:

![Example](https://user-images.githubusercontent.com/1787385/103960545-629a1300-5120-11eb-9a6b-7bbf41292d64.png)

#### Alternative Solutions
- I could skip annotations, but then I'd lose a lot of valuable information.
- I could add a post-processor to re-write the `pip-compile` output every time I compile.
- I could revert #1237 and poorly maintain a fork of this project, but that would make me sad.

#### Additional context
- #1297
- #1237
- #1377

**Comment by atugushev** [comment]
Based on feedback it looks like we should have introduced one-per-line annotations via an option. Well, better to do it late than never. I don't mind adding an option for the old-style annotations.

**Comment by ulope** [comment]
Just to give some feedback in the other direction: I'm very happy with the new separate line mode. The old format often caused really annoying merge conflicts that more than once lead developers in our team to just "blow away" the generated requirements.txt and compile a new one (with the obvious drawbacks of uncontrolled version changes)...

**Comment by AndydeCleyre** [comment]
@jdufresne 

Would you like to tackle this one?

**Comment by jdufresne** [comment]
As this is an issue for enough users, please go ahead with adding an option. While I will personally not use it, clearly enough people will so might as well try to make this useful for as many people as possible.

**Comment by cjerdonek** [comment]
It occurs to me that this, as well as a number of other issues in `pip-tools`'s tracker that want to alter and customize `pip-tools`'s output in various ways, could perhaps be enabled generally if `pip-compile` provided the option of outputting the information it has in a structured format like json. Then it would be a lot easier for people to create `requirements.txt` files in the format (and content) they want if not explicitly supported by `pip-compile`. Currently, trying to alter `pip-compile`'s output by parsing is fragile because the output format can change from release to release.

**Comment by pohmelie** [comment]
@cjerdonek 
If I got you right, then I disagree. I think `--format` with some argument is classic solution and enough for this case.

**Comment by ushuz** [comment]
I think https://github.com/jazzband/pip-tools/pull/1297#issuecomment-758588222 is the way to go, future proof.

**Comment by cjerdonek** [comment]
> It occurs to me that this, as well as a number of other issues in pip-tools's tracker that want to alter and customize pip-tools's output in various ways, could perhaps be enabled generally if pip-compile provided the option of outputting the information it has in a structured format like json. 

FYI, I just created issue #1377 expanding on my suggestion above.

> If I got you right, then I disagree. I think --format with some argument is classic solution and enough for this case.

@pohmelie I don't disagree with you. `pip-tools` can still implement feature requests like this. I was merely pointing out a way that `pip-tools` could make it easier for users to work-around issues in cases where `pip-tools` hasn't yet implemented the feature in `pip-tools` itself.

**Comment by pohmelie** [comment]
@cjerdonek, that sounds nice.

**Comment by merwok** [comment]
JSON output seems potentially useful but orthogonal to the issue at hand, which is about a simple option to restore previous output format.  It’s been a few months, people are either stuck with older pip-tools and can’t accept dependabot PRs anymore, or have to accept a PR with 100% diff.  As time passes and newer pip gets incompatible with older pip-tools, this won’t be tenable.

**Comment by BarnabasSzabolcs** [comment]
It looks like the developers of pip-tools are against maintaining any parameters that would keep the requirements.txt look consistent to older pip-tools generated versions. 

The pip-tools version that generates compact requirements.txt annotations is `5.4.0`.

**Comment by AndydeCleyre** [comment]
@jdufresne 

Could you please at least weigh in on some of the proposed fixes? These include a structured output option, and two specific format options. I am *guessing* you would not support making the old style the default. I want to reduce wasted/undone work by getting input from the new-style "camp" written out here.

**Comment by jdufresne** [comment]
@AndydeCleyre sorry for the late response.

I like @cjerdonek's idea of adding a structured intermediate format that can then be manipulated further (outlined in #1377). pip-tools could ship with two formatters one with the multi-line annotations and one with the compact annotations. The project could choose one or the other as the default output. I personally like the multi-line as the default, but recognize others may prefer the compact.

I won't have the time to implement this, so it would be a welcome contribution from other maintainers or contributors. Thanks all for the feedback.

**Comment by AndydeCleyre** [comment]
I have a basic working `--annotation-style long|split` implementation at https://github.com/AndydeCleyre/pip-tools/tree/bugfix/1306 -- [compare to master](https://github.com/jazzband/pip-tools/compare/master...AndydeCleyre:bugfix/1306).

It does not have tests, and it may be ugly and otherwise yet unsuitable. I will try to get back to this soon, but anyone is welcome to take that and build it up to PR standards in the meantime. Or just yell feedback this way. Thanks.

**Comment by AndydeCleyre** [comment]
I invite all interested parties to provide feedback for #1477, which adds `--annotation-style`.

**Comment by atugushev** [comment]
Old annotation style is released in `pip-tools v6.3.0` 🚀

**Comment by BarnabasSzabolcs** [comment]
pip-tools v6.3.0+ does not have `--annotation-style` as an option anymore :(

`Error: no such option: --annotation-style`
