### ISSUE TITLE
README diagram does not display well on dark mode

### ISSUE THREAD

**Issue by johnthagen** [jazzband/pip-tools#1313]
1. Enable GitHub Dark Mode: https://github.com/settings/appearance
2. Open the `pip-tools` GitHub page

<img width="962" alt="Screen Shot 2021-02-01 at 7 28 07 AM" src="https://user-images.githubusercontent.com/10340167/106459081-54a98a80-645f-11eb-9926-9ef78c60163c.png">

Perhaps if the black text had a white outline it would help?

**Comment by atugushev** [comment]
Hello @johnthagen,

Nice catch! Yes, indeed. White outlined labels would look better on a dark mode.

**Comment by fhightower** [comment]
I'd like to address this issue. @atugushev: Do you mind assigning the issue to me?

**Comment by webknjaz** [comment]
@fhightower feel free to send a PR, I've marked you as an assignee.

**Comment by webknjaz** [comment]
FTR now that there's Sphinx docs including README, we need to also check https://pip-tools.rtfd.io (there's a dark mode toggle at the top-right corner).

**Comment by fhightower** [comment]
Ah, ok - thanks for the feedback @webknjaz .
