### ISSUE TITLE
Document how to check multiple requirements with pre-commit hooks

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1335]
> Thanks for the issue! You should use a separate hook for each input requirement file, for example:
> 
> ```yaml
> repos:
> -   repo: https://github.com/jazzband/pip-tools
>     rev: 5.3.1
>     hooks:
>       - id: pip-compile
>         name: pip-compile setup.py
>         files: ^setup\.py$
>       - id: pip-compile
>         name: pip-compile requirements-dev.in
>         args: [requirements-dev.in]
>         files: ^requirements-dev\.(in|txt)$
>       - id: pip-compile
>         name: pip-compile requirements-lint.in
>         args: [requirements-lint.in]
>         files: ^requirements-lint\.(in|txt)$
> ```

Would it be possible to add this somewhere in the documentation? I wasn't familiar at all with how pre-commit really worked so it took some digging until I realized that even if the pattern matches for `files` we would still need to feed the names in individually for each requirements file for it to work as intended.

_Originally posted by @seanytak in https://github.com/jazzband/pip-tools/issues/1208#issuecomment-784675891_

**Comment by microcat49** [comment]
Hey @atugushev, 

Do you mind if I take this one?

**Comment by atugushev** [comment]
Hello @microcat49,

Please, feel free to 👍🏻

**Comment by microcat49** [comment]
Pull request https://github.com/jazzband/pip-tools/pull/1387
