### ISSUE TITLE
--extra-index-url option is ignored in v5.5.0

### ISSUE THREAD

**Issue by gwerbin** [jazzband/pip-tools#1348]
#### Environment Versions

1. OS Type: Mac
1. Python version: 3.8.6
1. pip version: 21.0.1
1. pip-tools version: 5.5.0

#### Steps to replicate

Install `pip-tools` from PyPI.

Create the file `req.in` containing:
```
--index-url https://example.net/pypi/simple/
--extra-index-url https://pypi.org/simple/
numpy
```

Run `pip-compile`.

#### Expected result

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile req.in
#
--index-url https://example.net/pypi/simple/
--extra-index-url https://pypi.org/simple/

numpy==1.20.1
    # via -r req.in
```

#### Actual result

The `--extra-index-url` option provided in `req.in` does not appear in the generated `req.txt`:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile req.in
#
--index-url https://example.net/pypi/simple/

numpy==1.20.1
    # via -r req.in
```

I even tried specifically running `pip-compile --extra-index-url https://pypi.org/simple req.in`, but it still produced the output above.

**Comment by atugushev** [comment]
Hello @gwerbin,

Thanks for the report! This has been fixed in #1325.

**Comment by gwerbin** [comment]
> Hello @gwerbin,
> 
> Thanks for the report! This has been fixed in #1325.

Thanks!

I was going to start using Pip-Tools in a new project, but right now I'm working around the issue with Sed. Out of curiosity (if only for my planning purposes), is there a general timeline on when this fix will be released on PyPI?

**Comment by atugushev** [comment]
@gwerbin 

It's pretty soon. I would say — by the end of the week.

**Comment by atugushev** [comment]
pip-tools `v6.0.0` is released 🚀
