### ISSUE TITLE
Why does pip-sync --dry-run return an exit code of 1 instead of 0?

### ISSUE THREAD

**Issue by pmi123** [jazzband/pip-tools#1373]
Why does `pip-sync --dry-run requirements.txt`  return an exit code of 1 instead of 0 when the dry run is successful? 

As a comparison, `rsync --dry-run ...`  returns an exit code of 0 as long as the dry run is successful. 

Thanks for the clarification!

Mark

**Comment by atugushev** [comment]
Hello @pmi123,

Thanks for the question! See #1166.

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
