### ISSUE TITLE
[RFC] Support pinning PEP 517 build deps in `pyproject.toml`

### ISSUE THREAD

**Issue by webknjaz** [jazzband/pip-tools#1396]
#### What's the problem this feature will solve?

PEP 518 [defines a `[build-system]` section with a `required = []` field](https://www.python.org/dev/peps/pep-0518/#build-system-table). But there is no way to tell PEP 517 build front-ends to apply constraints to those build requirements while provisioning an env for them. This makes it hard to go perform predictable builds.

#### Describe the solution you'd like

I was thinking that pip-tools could facilitate this by either learning to manage that setting in `pyproject.toml` or by sourcing the requirements from that field to produce a constraints file. The former could allow to keep the builds predictable with any build front-end like pip while the latter would be helpful mostly for more flexible build front-ends like pypa/build that allow the users to provision the envs by themselves.

WDYT folks? 

#### Alternative Solutions

N/A

#### Additional context

N/A

**Comment by Hattshire** [comment]
I think it would be great if `pip-compile` could take the `build-system.requires = []` and `tool.<name>.metadata.requires = []` fields from the _**pyproject.toml**_ and generate a _**requirements.txt**_ file from that, as it does for _**setup.py**_ and _**requirements.in**_

**Comment by AndydeCleyre** [comment]
> But there is no way to tell PEP 517 build front-ends to apply constraints to those build requirements while provisioning an env for them.

Can you please clarify?

You mean the `requires` field, right?

When I create a package using `flit`, I'll have something like:

```toml
[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"
```

[PEP 518 specifies](https://www.python.org/dev/peps/pep-0518/#id27) that `requires` is a list of PEP 508 deps, [which may look like](https://www.python.org/dev/peps/pep-0508/#id17):

```python
requests [security,tests] >= 2.8.1, == 2.8.* ; python_version < "2.7"
```
or
```python
pip @ https://github.com/pypa/pip/archive/1.3.1.zip#sha1=da9234ee9982d4bbb3c72346a6de940a148ea686
```
What kind of constraints application are you talking about that is not demonstrated in these examples?

**Comment by webknjaz** [comment]
@AndydeCleyre in `requires`, the requirements listed are usually direct deps having wide ranges of versions. I want an additional lock file. As in `pip install -r direct-requires.txt -c comprehensive-pins.txt`

**Comment by webknjaz** [comment]
I've recently clarified that doing `PIP_CONSTRAINT=build-constrains.txt python -m build` is able to apply constraints to the deps that are listed in `[build-system]requires` and returned from the dynamic hooks in the chosen PEP 517 backend (`setuptools`' backend adds a dependency on `wheel` under the hood, for example).
Done this manually for now: https://github.com/cherrypy/cheroot/commit/5c1ac088c595ec91b9bda2dc818e491a23132a2c.

**Comment by gokuatkai** [comment]
supporting `[build-system.requires]` and `[project.optional-dependencies]` and all the various other dependencies keys would be really great!

**Comment by apljungquist** [comment]
I too would like to gather requirements from `[build-system.requires]`.

I also want to gather requirements from the `deps` sections in `tox.ini`. And gather constraints from openembedded. Support for plugging in _gatherers_ might be neat.

Side note about using constraints files with pip; you may want to prefer `PIP_CONSTRAINT` over `-c` because [generated pip commands do not respect constraints files in outer install command](https://github.com/pypa/pip/issues/8439) (yes, I am still annoyed by this  :sweat_smile:).

**Comment by apljungquist** [comment]
Not sure if this would be a good way to do it but looks ok to me. Thoughts?
