### ISSUE TITLE
tox tests are failing due to new pip release

### ISSUE THREAD

**Issue by nicoa** [jazzband/pip-tools#1403]
There is a deprecation leading to failing CI since a few days, namely the one discussed in https://github.com/pypa/pip/issues/7555:
```
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
```

I'm not sure about the options here - i.e. if this should be filtered out or tested as suggested by pip maintainers in that message and where / how to do this in the tests when the cli is invoked.

Further, a second problem are the pip deprecation warnings for the "previous" pip test setup.

So, the obvious solution would be to do the following on each pip-call: use feature flag in recent pip (as suggested in the warning above) and suppress version warnings in previous pip (`export PIP_DISABLE_PIP_VERSION_CHECK=1`).

Unfortunately I'm not sure how to proceed here or how to move the warnings from the pytest error section to the pytest warnings section.

If the solution is easy to implement and one could guide me to the proper place and has a bigger vision of what should happen and has the time for this, I'd be happy to get some guidance to file a PR.

### Links
* latest successful: https://github.com/jazzband/pip-tools/actions/runs/870122483
* first failing: https://github.com/jazzband/pip-tools/actions/runs/873544759

**Comment by webknjaz** [comment]
Regarding pytest, this can be suppressed with the `filterwarnings` option. But of course, it's best to test pip in different modes, especially since the default is going to get flipped at some point.

**Comment by nicoa** [comment]
Seems that it is not only related to the above issues, but as well to now the `fake-with-deps` package gets output for wheel built, opposed to before. Not sure if this is related to the latest updates to setuptools (there was a new release recently).
