### ISSUE TITLE
Order of packages in requirements.txt -- pip-compile vs. pip freeze

### ISSUE THREAD

**Issue by adamsol** [jazzband/pip-tools#1414]
The issue regards packages with names containing `-` character or a digit. This may cause an unexpected order of packages in the output file, different than with `pip freeze`. It seems that the output file is sorted by the whole lines, together with `==` and version name, instead of just by the package names.

#### Environment Versions

1. Windows 10
2. Python version: 3.7.6
3. pip version: 21.1.2
4. pip-tools version: 6.1.0

#### Steps to replicate

`pip-compile` with `requirements.in` file:

```
django
django-redis
django-sendfile
django-sendfile2
djangorestframework
```

#### Expected result

(without comments and additional libraries, for clarity)

```
django==3.2.4
django-redis==5.0.0
django-sendfile==0.3.11
django-sendfile2==0.6.0
djangorestframework==3.12.4
```

#### Actual result

```
django-redis==5.0.0
django-sendfile2==0.6.0
django-sendfile==0.3.11
django==3.2.4
djangorestframework==3.12.4
```

**Comment by ssbarnea** [comment]
I am not sure we really need a fix for this, it would add extra complexity for a very minor benefit.

**Comment by adamsol** [comment]
It's certainly not a big issue, but it causes some inconveniences:
* When migrating from `pip freeze`, the shuffle of the packages creates a bigger diff than necessary, and thus makes it harder to review the changes introduced by `pip-compile`.
* When reading the generated list of packages, it's harder to find the one we're looking for, since we know how lexicographic order should work.

It's a bit surprising to read that fixing this would add extra complexity. I've looked at the code and it seems like the issue is here:

https://github.com/jazzband/pip-tools/blob/f953ceb8840b5b653ef94d7b9bc172192413e0a8/piptools/writer.py#L91-L92

I've tried changing locally `str(ireq.req).lower()` to `ireq.req.name.lower()` and it works like expected.

**Comment by atugushev** [comment]
Yeah, this would make sense to sync packages ordering with `pip freeze`, which is [a case-insensitive sorted order](https://pip.pypa.io/en/stable/cli/pip_freeze/).

> I've tried changing locally `str(ireq.req).lower()` to `ireq.req.name.lower()` and it works like expected.

Try also `key_from_ireq(ireq))`.

@adamsol feel free to open a PR 👍🏻
