### ISSUE TITLE
[TODO] Add an initial Sphinx docs skeleton

### ISSUE THREAD

**Issue by webknjaz** [jazzband/pip-tools#1427]
#### What's the problem this feature will solve?

The only doc currently is the project README. It's grown over time and now it may be a good idea to split that information into pieces.

#### Describe the solution you'd like

I'd like a simple docs skeleton to be added to the project with an index page simply including the README, as the first step. Plus this needs to be hooked up to RTD.

Steps to implement:
1. Create a `docs/` dir.
2. Generate a docs project skeleton via `sphinx-quickstart` and make sure that the RST documents are moved right into `docs/` — we don't really need subfolders.
3. Drop any makefile mentions — the project uses tox so it should become the entry point for building the docs locally.
4. Add a tox env for building docs. Take https://github.com/ansible/pylibssh/blob/b87a6ad/tox.ini#L264-L309 as an example.
5. Edit `index.rst` to include the current README.
6. Edit `docs/conf.py` to enable nitpicky mode and make sure to add `-W --keep-going` to the Sphinx invocations in tox.
7. Integrate MyST extension.
8. Integrate Furo theme.
9. Specify all the deps in `docs/requirements.txt`
10. Add a separate sphinx invocation with `-b linkcheck`.
11. Add those tox envs to GitHub Actions CI/CD workflows.
12. Add `.readthedocs.yml` to configure Read The Docs. Make sure to set `htmldir` builder and fail on warnings.
13. (probably needs to be done by a separate person with access) Enable Read The Docs and building PRs.

#### Alternative Solutions

N/A

#### Additional context

@jezdez also mentioned that this needs to be done on Libera.

**Comment by webknjaz** [comment]
This is an issue for @l1storez who wanted to help with this task.

**Comment by l1storez** [comment]
Oh, wow. Assign me, please

**Comment by webknjaz** [comment]
@jezdez while you're on it, could you plz edit the project meta and fill out the URL on the repo front page to point at `https://pip-tools.rtfd.io/`?
