### ISSUE TITLE
--extra=foo,bar does not work as expected

### ISSUE THREAD

**Issue by ssbarnea** [jazzband/pip-tools#1430]
Apparently using `--extra` with a list of strings does not enable any extras. If the extra string contains commas it needs to be split and and used as a list of extras, which is not happening now. Same option works correctly with pip.

#### Environment Versions

1. pip-tools version: `5.2.0`

**Comment by atugushev** [comment]
[Click](https://click.palletsprojects.com/en/8.0.x/options/#multiple-options) provides only `pip-compile --extra foo --extra bar` syntax.

**Comment by AndydeCleyre** [comment]
What's the main advantage/use-case of `--extra EXTRANAME` over specifying `req[EXTRANAME]` in the input? Oh, for when you don't want to use an `.in` input file at all, just the project's own `setup.py`.

Yes I think you're right that we need to fix something here. Either:

- do comma-splitting ourselves
- improve/correct help output, which is currently misleading

Current help text:

```
--extra TEXT                    Names of extras_require to install
```

Actually we've got the same problem there for `-P`/`--upgrade-package`, at least.

**Comment by AndydeCleyre** [comment]
Taking a look at all the `multiple=True` args across the project, just 2 of 8 use plural language:
```
piptools/scripts/compile.py-    "--extra",
piptools/scripts/compile.py-    "extras",
piptools/scripts/compile.py:    multiple=True,
piptools/scripts/compile.py-    help="Names of extras_require to install",

piptools/scripts/compile.py-    "-f",
piptools/scripts/compile.py-    "--find-links",
piptools/scripts/compile.py:    multiple=True,
piptools/scripts/compile.py-    help="Look for archives in this directory or on this HTML page",

piptools/scripts/compile.py:    "--extra-index-url", multiple=True, help="Add additional index URL to search"

piptools/scripts/compile.py-    "--trusted-host",
piptools/scripts/compile.py:    multiple=True,
piptools/scripts/compile.py-    help="Mark this host as trusted, even though it does not have "
piptools/scripts/compile.py-    "valid or any HTTPS.",

piptools/scripts/compile.py-    "--upgrade-package",
piptools/scripts/compile.py-    "upgrade_packages",
piptools/scripts/compile.py-    nargs=1,
piptools/scripts/compile.py:    multiple=True,
piptools/scripts/compile.py-    help="Specify particular packages to upgrade.",

piptools/scripts/sync.py-    "-f",
piptools/scripts/sync.py-    "--find-links",
piptools/scripts/sync.py:    multiple=True,
piptools/scripts/sync.py-    help="Look for archives in this directory or on this HTML page",

piptools/scripts/sync.py:    "--extra-index-url", multiple=True, help="Add additional index URL to search"

piptools/scripts/sync.py-    "--trusted-host",
piptools/scripts/sync.py:    multiple=True,
piptools/scripts/sync.py-    help="Mark this host as trusted, even though it does not have valid or any HTTPS.",
```

So I think we should change those two to use singular language, and consider explicitly stating it can be used multiple times (unless `click` has an option to do that automatically; `plumbum` displays this info by default).

**Comment by ssbarnea** [comment]
I approved the PR but I see a newly introduced bot/integration that is broken. The PR is useful but ideally we should also allow commas. I was affected by this bug myself, I cannot blame anyone trying to use commas.

**Comment by AndydeCleyre** [comment]
Thanks @ssbarnea!

The broken integration was probably because I worked on an outdated master, but have now rebased.

The comma notation is indeed natural, since that's how these extras are specified in req files. I will submit a separate PR for that, but I don't know if it ought to be an advertised feature.
