### ISSUE TITLE
[pip-tools@1.8.0] Pin the library click version in the `setup.py`

### ISSUE THREAD

**Issue by YashGadle** [jazzband/pip-tools#1433]
#### What's the problem this feature will solve?
This feature will pin the dependencies of `pip-tools@1.8.0` so that the developer can avoid unexpected interpreter errors while building dependencies.

Currently if we check the dependencies of `pip-tools@1.8.0`, they are not pinned which causes an issue that if its dependencies gets updated then it will automatically fetch the latest version. This might seem safe but what if that dependency has some vulnerabilities. Or let's say `pip-tools@1.8.0` which supports python2 but its dependencies `click@8.0.1` does not. This will break some code bases that are still relying on python2.

#### Describe the solution you'd like
We would like that the dependencies (in `setup.py`) should not be specified as `>=X.0.0`, instead `<X.0.0`

We want to make the dependencies of `pip-tools@1.8.0` to be pinned as `click<8.0`.

We have a legacy codebase that uses `pip-tools@1.8.0` & `python2` virtual env, and it started to break as the library `click@8.0.1` started using syntax that is not supported in python2. 
(We understand `python2` is deprecated and should not be relied on, but can we make sure that old versions of `pip-tools` should have pinned dependencies so that the latest python syntax does not break the existing code  base. For example `click>7.0` started adding data types like so `def _fast exit(code: int)`.

#### Additional context
We know that v1.8.0 is old and we should use the latest version only, but we have circumstances and env where we have to use python2 (there is no alternate). So if we can pin these libraries `click, six and first` that would be very helpful.

**Comment by webknjaz** [comment]
I'm afraid you'll have to constraint this in your constraints file. There's no process for doing ancient post-releases.

**Comment by YashGadle** [comment]
got it. closing this then.
