### ISSUE TITLE
multiple values for --extra-index-url aren't supported

### ISSUE THREAD

**Issue by foozmeat** [jazzband/pip-tools#1440]
As of v21.1.3 pip properly handles multiple values for `--extra-index-url` with credentials. This is needed when you have private package repos. `pip-compile` doesn't seem to work for multiple extra indexes however.

pip issue: https://github.com/pypa/pip/issues/3931

#### Environment Versions

1. OS Type: macos
1. Python version: 3.9.1
1. pip version: 21.1.3
1. pip-tools version: 6.2.0

#### Steps to replicate

1. and an `--extra-index-url` line to requirements.in with multiple values like:

```
--extra-index-url 'https://gitlab+deploy-token-17:xxx@gitlab.yyy.com/api/v4/projects/323/packages/pypi/simple,https://gitlab+deploy-token-18:xxx@gitlab.yyy.com/api/v4/projects/631/packages/pypi/simple,https://gitlab+deploy-token-19:xxx@gitlab.yyy.com/api/v4/projects/550/packages/pypi/simple'
```

2. run `pip-compile`

#### Expected result

The specified indexes are searched for packages

#### Actual result

```
Could not find a version that matches my-packages (from -r requirements.in (line 44))
No versions found
Were https://pypi.org/simple or https://gitlab%2Bdeploy-token-17:****@gitlab.yyy.com/api/v4/projects/323/packages/pypi/simple,https://gitlab+deploy-token-18:xxx@gitlab.yyy.com/api/v4/projects/631/packages/pypi/simple,https://gitlab+deploy-token-19:xxx@gitlab.yyy.com/api/v4/projects/550/packages/pypi/simple reachable?
```

It appears that the URLs aren't being split on the `,` as it only masked the password of the first URL.

**Comment by atugushev** [comment]
Hello @foozmeat,

Thanks for the issue!  Use a separate option for each URL, that's how click's [@option(multiple=True)](https://click.palletsprojects.com/en/8.0.x/options/#multiple-options) works:


```
echo | pip-compile - -qo- \
    --extra-index-url 'https://gitlab+deploy-token-17:xxx@gitlab.yyy.com/api/v4/projects/323/packages/pypi/simple' \
    --extra-index-url 'https://gitlab+deploy-token-18:xxx@gitlab.yyy.com/api/v4/projects/631/packages/pypi/simple' \
    --extra-index-url 'https://gitlab+deploy-token-19:xxx@gitlab.yyy.com/api/v4/projects/550/packages/pypi/simple'
```

**Comment by foozmeat** [comment]
Specifying separate `--extra-index-url ` entries at the top of `requirements.in` also worked fine. Thanks!
