### ISSUE TITLE
How to install from private repository without leaking credentials

### ISSUE THREAD

**Issue by rossgray** [jazzband/pip-tools#1447]
I have been looking through the docs and existing issues but have not been able to find any documentation on the following problem:

I need to install a package from a private GitHub repository, therefore I have something like the following in my `requirements.in`, where I am using an environment variable `GITHUB_AUTH_TOKEN` as an auth token.

```
git+https://${GITHUB_AUTH_TOKEN}@github.com/username/my-package@somehash#egg=my-package
```

The problem with this is that the auth token is evaluated and exposed in the output `requirements.txt` file.

Does `pip-compile` support this, and if so what is the recommended solution?

Thanks in advance!

**Comment by atugushev** [comment]
Hello @rossgray,

Thanks for the issue! Currently, `pip-tools` does not support environment variables in URL parts and always expands them in compiled packages list. The tracking issue for the feature is here: https://github.com/jazzband/pip-tools/issues/966.
