### ISSUE TITLE
Autogenerated command string in requirements.txt missing --upgrade flag

### ISSUE THREAD

**Issue by tomjhunt13** [jazzband/pip-tools#1461]
Running the command `pip-compile --no-emit-index-url --no-emit-trusted-host --upgrade --output-file=requirements.txt requirements.in` creates the `requirements.txt` file, but the command that is printed at the top is  missing the --upgrade flag. Ideally it would copy all the input parameters so that the whole string can be copied and pasted at a later date without needing to recall each parameter.

#### Environment Versions

1. OS Type: Windows
1. Python version: `$ python -V`: 3.7
1. pip version: `$ pip --version`: 21.1.3
1. pip-tools version: `$ pip-compile --version`:  6.2.0

#### Steps to replicate

1. Create a requirements.in file with some arbitrary requirements.
2. Run `pip-compile --no-emit-index-url --no-emit-trusted-host --upgrade --output-file=requirements.txt requirements.in`

#### Expected result
1. A `requirements.txt` file is generated with the command  that was run printed in full at the top

#### Actual result
1. A `requirements.txt` file with `pip-compile --no-emit-index-url --no-emit-trusted-host --output-file=requirements.txt requirements.in` (missing --upgrade) printed at the top

**Comment by atugushev** [comment]
It's a deliberate decision to skip `--upgrade` option in the pip-compile header. Pip-tools considers it as a one-off option.

**Comment by tomjhunt13** [comment]
I see, thanks for the fast reply. Can I ask why it's considered one-off? Maybe I have an unusual use case, but I only run `pip-compile` with the `--upgrade` option. The reason I use `pip-compile` is to either to add additional dependencies from an updated `requirements.in` file or (more commonly) to upgrade direct and indirect dependencies in response to a vulnerability  indicated by tools such as Snyk.

**Comment by atugushev** [comment]
I guess it's to make `requirement.txt` less noisy in VCS when you upgrade dependencies occasionally. For example, `--upgrade-pakage="django==3.2.3"` option is not expected in the header after `pip-compile` run, since it's a [one-off operation](https://github.com/jazzband/pip-tools/issues/788#issuecomment-486657890). The same principle applied to  `--upgrade` option for most cases.

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!

**Comment by Nao83** [comment]
I have the same issue. My company requires to keep our dependencies to the latest possible version, so we always run pip-compile with --upgrade

Developers normally copy the command from the requirements.txt to guarantee consistency, but this doesn't lead to the expected behaviour.

**Comment by atugushev** [comment]
> Developers normally copy the command from the requirements.txt to guarantee consistency, but this doesn't lead to the expected behaviour.

@Nao83 you might find useful env [COMPILE_COMMAND](https://github.com/jazzband/pip-tools#configuration) to control this.

**Comment by Nao83** [comment]
Thanks, that's nice
