### ISSUE TITLE
support PEP 665 -- Specifying Installation Requirements for Python Projects

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#1463]
there's a new PEP about lockfiles https://www.python.org/dev/peps/pep-0665/

pip-tools should support it if the PEP is approved

**Comment by Ayushparikh-code** [comment]
yeah PEP 665 proposes a standardized lock-file (c. 2021)

**Comment by webknjaz** [comment]
Should we close this in favor of #1526?

**Comment by webknjaz** [comment]
There are more comments in the other issue so I'm closing this one.
