### ISSUE TITLE
--check-unchanged flag for pip-compile

### ISSUE THREAD

**Issue by ovangle** [jazzband/pip-tools#1476]
#### What's the problem this feature will solve?

In brief, I want a behaviour for pip-compile similar to the behavior of `npm ci`.

When attempting to generate a `Dockerfile` for a package with both `requirements.txt` and `requirements.in`, currently there are two options for pip-compile:

**Option 1:** Only copy `requirements.txt`, only run `pip install` in container

This will not regenerate `requirements.txt` if a change is made to `requirements.in`, thus a developer needs to both change `requirements.in` _and_ run `pip-compile` on the host in order to generate a new build.

In addition, if running `pip-compile` is forgotten before rebuilding, the build will continue to install dependencies, even though `requirements.txt` is out of sync with the host.

**Option 2:** Run `pip-compile` in dockerfile, overwriting existing `requirements.txt`, then run `pip install` in container

If pip-compile is run in the Dockerfile, then it will overwrite the existing `requirements.txt` with a new version, but leaves the file untouched on the host machine. Since the file remains unchanged on the host machine, the changes will not be picked up by `git` or other tooling.

#### Describe the solution you'd like

Add an option `--check-unchanged` to `pip-compile`, which would generate a temporary `requirements-check.txt`, then compare it to the existing `requirements.txt` and error the build if the two mismatch (similar to how `npm ci` errors when `package-lock.json` is out of sync.
  
    pip-compile --output-file="requirements-check.txt" &> /dev/null
    diff <(sed '/^#/d' requirements.txt) <(sed '/^#/d' requirements-check.txt)
    if [ $? -ne 0 ]; then
         echo "requirements.txt is stale and needs to be regenerated"
         exit 1;
    fi
    rm requirements-check.txt
    pip install -r requirements.txt

This fails the build at the earliest possible time for `pip-compile` to be re-run in the host environment.

#### Alternative Solutions

There is a workaround script I'm using (see above). However, running `pip-compile --generate-hashes` can be quite slow, and incorporating the flag into `pip-compile` would allow checks to be performed much earlier in the process, resulting in improved build times. 

#### Additional context

[Behaviour of `npm ci`](https://docs.npmjs.com/cli/v7/commands/npm-ci)

edit: Couldn't work out why this was failing for me. Ended up being the fact that the comments at the header of the file are dependent on the directory the file was generated from :). Updated the script to refect this.

**Comment by atugushev** [comment]
MIght be related to #882

**Comment by ovangle** [comment]
Yeah, that's the same one and the git-diff one liner is also appropriate for my use case. Thanks!
