### ISSUE TITLE
Running pip-compile with a dev-requirements.in that adds an extra to a library has inconsistent output

### ISSUE THREAD

**Issue by arthurio** [jazzband/pip-tools#1478]
When you define a `requirements.in` file that has a library with no `[extra]` and use the `requirement.txt` output as input for a `dev-requirements.in` file that adds an `[extra]`, the output `dev-requirements.txt` will inconsistently have either the `[extra]` at the end of the library or not...

#### Environment Versions

1. MacOS 11.5.2 (but also happens on linux)
1. Python version: 3.7.11, 3.8.7, 3.9.1
1. pip version: 21.2.4
1. pip-tools version: 6.2.0

#### Steps to replicate

I have created a reproducible demo:
1. Minimal library repo: https://github.com/arthurio/pip-tools-bug-lib
2. Bug repro repo: https://github.com/arthurio/pip-tools-bug-extra-repro

In the bug repro repo, I have a script called `pip-compile.sh`. If you remove the `.txt` files and run the script twice, you'll see that the first time `dev-requirements.txt` contains `git+https://git@github.com/arthurio/pip-tools-bug-lib#egg=my-lib[test]`
but the second time it contains `git+https://git@github.com/arthurio/pip-tools-bug-lib#egg=my-lib`.

You can see that from the 2 consecutive commits:
1. https://github.com/arthurio/pip-tools-bug-extra-repro/commit/63cefceeb4f0c9938943d038cef2ef1a763d14ad#diff-43470c4f399e798afc682f0bf6c690eef5f47ee25445904a066e4c3314f3a787R11
2. https://github.com/arthurio/pip-tools-bug-extra-repro/commit/33f8d6f8af827aa8b58cf4490ab798d21e8331b2#diff-43470c4f399e798afc682f0bf6c690eef5f47ee25445904a066e4c3314f3a787R11

#### Expected result

I would expect `pip-compile` to always keep the `[extra]` flag.

#### Actual result

`pip-compile` strips out the `[extra]` flag the second time it's ran.

**Comment by arthurio** [comment]
Also, the same happens with just a library name (not using a git url)

**Comment by AndydeCleyre** [comment]
This might be a dupe of #1451

**Comment by arthurio** [comment]
@AndydeCleyre You are right, sorry about that!

**Comment by AndydeCleyre** [comment]
No worries! Thanks for the issue; your documented case helps describe the problem.
