### ISSUE TITLE
Output for requirement-lock.txt file locally is different from the output for requirements-lock.txt file on Github CI

### ISSUE THREAD

**Issue by MNabeelHassan** [jazzband/pip-tools#1479]
Output for requirement-lock.txt file locally is different from the output for requirements-lock.txt file on Github CI
 
#### Environment Versions

1. OS Type: Windows
1. Python version: `3.9.5`
1. pip version: `21.2.4`
1. pip-tools version: `6.2.0`

#### Steps to replicate

1. The output for requirements-lock.txt is different when pip-compile is run locally and on Github CI 
2. My requirements.txt 
```
-r prod/requirements.txt

coverage==5.5
gitlint==0.15.1
sh==1.14.1
```
3. requirements-lock.txt
```
#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile --output-file=requirements-lock.txt requirements.txt
#
arrow==1.0.3
    # via gitlint
asgiref==3.4.1
    # via django
click==7.1.2
    # via gitlint
coverage==5.5
    # via -r requirements.txt
dj-database-url==0.5.0
    # via environs
dj-email-url==1.0.2
    # via environs
django==3.2.4
    # via
    #   -r prod/requirements.txt
    #   django-debug-toolbar
    #   djangorestframework
django-cache-url==3.2.3
    # via environs
django-debug-toolbar==3.2.2
    # via -r prod/requirements.txt
djangorestframework==3.12.4
    # via -r prod/requirements.txt
environs[django]==9.3.3
    # via -r prod/requirements.txt
faker==8.12.1
    # via -r prod/requirements.txt
gitlint==0.15.1
    # via -r requirements.txt
gunicorn==20.1.0
    # via -r prod/requirements.txt
marshmallow==3.13.0
    # via environs
psycopg2==2.9.1
    # via -r prod/requirements.txt
pycountry==20.7.3
    # via -r prod/requirements.txt
python-dateutil==2.8.2
    # via
    #   arrow
    #   faker
python-dotenv==0.19.0
    # via environs
pytz==2021.1
    # via django
pyyaml==5.4.1
    # via -r prod/requirements.txt
sh==1.14.1
    # via -r requirements.txt
six==1.16.0
    # via python-dateutil
sqlparse==0.4.1
    # via
    #   django
    #   django-debug-toolbar
text-unidecode==1.3
    # via faker
uritemplate==3.0.1
    # via -r prod/requirements.txt

# The following packages are considered to be unsafe in a requirements file:
# setuptools

```

#### Expected result
```
pyyaml==5.4.1
    # via -r prod/requirements.txt
sh==1.14.1
    # via -r requirements.txt
```
#### Actual result

```
@@ -52,7 +52,9 @@ pytz==2021.1
 pyyaml==5.4.1
     # via -r prod/requirements.txt
 sh==1.14.1
-    # via -r requirements.txt
+    # via
+    #   -r requirements.txt
+    #   gitlint
```

**Comment by AndydeCleyre** [comment]
Taking a look at [`gitlint`'s requirements](https://github.com/jorisroovers/gitlint/blob/main/requirements.txt#L4):

```ini
sh==1.14.2; sys_platform != 'win32' # sh is not supported on windows
```

So when the dependencies are determined on Windows, `sh` is only a top-level requirement for you, but on anything else it's additionally required by `gitlint`.

**Comment by MNabeelHassan** [comment]
> Taking a look at [`gitlint`'s requirements](https://github.com/jorisroovers/gitlint/blob/main/requirements.txt#L4):
> 
> ```ini
> sh==1.14.2; sys_platform != 'win32' # sh is not supported on windows
> ```
> 
> So when the dependencies are determined on Windows (or whatever matches `win32`), `sh` is only a top-level requirement for you, but on anything else it's additionally required by `gitlint`.

@AndydeCleyre that makes sense, thank you for helping out!  :slightly_smiling_face:
