### ISSUE TITLE
Cannot add . or -e . to setup.py/setup.cfg install_requires/extras_require

### ISSUE THREAD

**Issue by adamcunnington-gdt** [jazzband/pip-tools#1482]
I can't reference `.` or `-e .` in install_requires/extras_require in setup.py/setup.cfg. I get the following error:
subprocess.CalledProcessError: Command '['.venv/bin/python3.9', '.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmptqvo2r5o']' returned non-zero exit status 1.

I believe my workflow is not that unorthodox:
* I list all of my direct, unpinned dependencies in setup.cfg - I put regular requirements in install_requires and dev requirements in extras_require/dev
* I then run `pip-compile` and `pip-compile --extra dev --output-file dev-requirements.txt` which freezes requirements.
* I need to install setup.py as well as I have console scripts defined in there. If I was using requirements.in or dev-requirements.in, I would just add `.` and `-e .` respectively. I figured I should be able to do the same from install_requires/extras_require but I cannot.

I'm not sure if this is a bug or feature request.

**Comment by AndydeCleyre** [comment]
Wouldn't that be defining a package as dependent on itself? Without using pip-tools, does pip install a package defined like that?

Yeah I would, in addition to your setup files, have `*.in` files with `.` and `-e .[dev]`.

**Comment by RonnyPfannschmidt** [comment]
using `.` or `-e .` in `install_requires/extras_require` is

* intentionally not supported by setuptools
* not at all a part of pip-tools - the error you see is from setuptools itself as the local package cant be built

as feature request it could perhaps be sensible to include a way to add a extra requirement as the feature was added in #1363
the feature should have a extra flag to ensure a editable/install action is added to the requirement itself
