### ISSUE TITLE
Added-value of `pip-sync` over `pip install` 

### ISSUE THREAD

**Issue by azk** [jazzband/pip-tools#1494]
Hello,

I think I have a good understanding of `pip-compile`'s (incredibly useful) functionality, but I'm having a hard time understanding the benefit of using `pip-sync` over simply running `pip install -r` with the `requirements.txt` file generated by `pip-compile`.
The README provides an in-depth explanation of what `pip-compile` does but is pretty brief regarding `pip-sync`

Thank you!

**Comment by AndydeCleyre** [comment]
The main thing is that in addition to installing everything listed in the txt, it uninstalls everything **not** in the txt (excepting pip-tools itself and its few dependencies).

**Comment by azk** [comment]
Thank you for clarifying @AndydeCleyre !
