### ISSUE TITLE
pip-sync fails to run on pip >= 21.3

### ISSUE THREAD

**Issue by SethMMorton** [jazzband/pip-tools#1503]
It seems that pip 21.3 has removed `get_installed_distributions` from `_internal.utils.misc`. `pip-sync` is importing this, and that is causing a catastrophic error on startup.

#### Environment Versions

1. Linux
1. Python: 3.8.6
1. pip version: 21.3
1. pip-tools version: 6.3.1

#### Steps to replicate

1. Create a virtual environment and activate it
2. `pip install -U pip`
3. `pip install pip-tools`
4. `pip-sync -h`

#### Expected result

Help

#### Actual result

```
Traceback (most recent call last):
  File "/home/smmorton/playground/demo/bin/pip-sync", line 5, in <module>
    from piptools.scripts.sync import cli
  File "/home/smmorton/playground/demo/lib/python3.8/site-packages/piptools/scripts/sync.py", line 12, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/home/smmorton/playground/demo/lib/python3.8/site-packages/pip/_internal/utils/misc.py)
```

**Comment by pradyunsg** [comment]
@atugushev Is there someone I should mention when the release issue is created, to give y'all a heads up?
