### ISSUE TITLE
Support pyproject.toml and setup.cfg

### ISSUE THREAD

**Issue by laoshaw** [jazzband/pip-tools#1510]
#### What's the problem this feature will solve?

pyproject.toml and setup.cfg are on the way to replace requirements.txt and setup.py, can pip-tools support them?

**Comment by atugushev** [comment]
pip-tools supports `pyproject.toml` and `setup.cfg` since [6.1.0](https://github.com/jazzband/pip-tools/releases/tag/6.1.0). Try:
```
$ pip-compile pyproject.toml
# or
$ pip-compile setup.cfg
```

**Comment by laoshaw** [comment]
Thanks!! new to pip-tools.
