### ISSUE TITLE
VCS tests failing from github's git:// protocol brownout

### ISSUE THREAD

**Issue by richafrank** [jazzband/pip-tools#1522]
I'm seeing VCS-related tests failing (locally on master) to `git clone` when the url is `git+git://github.com/...`:
```
FAILED tests/test_cli_compile.py::test_url_package[generate_hashes0-VCS URL] - assert 1 == 0
FAILED tests/test_cli_compile.py::test_url_package[generate_hashes1-VCS URL] - assert 1 == 0
FAILED tests/test_cli_compile.py::test_url_package[generate_hashes1-VCS with direct reference and egg] - assert 1 == 0
FAILED tests/test_cli_compile.py::test_url_package[generate_hashes0-VCS with direct reference and egg] - assert 1 == 0
```
Running the clone command myself, I get:
```bash
$ git clone -q git://github.com/jazzband/pip-tools newdir
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Highlights from https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git :
> We’ll be disabling support for this protocol

> November 2, 2021 | First brownout

Swapping out `git://` for `https://` works, as recommended. I can put up a PR, if that sounds right.

#### Environment Versions

1. OS Type: MacOS
1. Python version: Python 3.8.12
1. pip version: pip 21.2.4
1. pip-tools version: pip-compile, version 6.4.1.dev2+gdc80b95.d20211102

#### Steps to replicate

1. `tox -e py38-pipmain -- -k test_url_package`

#### Expected result

All tests pass.

#### Actual result

```
4 failed, 4 passed, 720 warnings in 3.32s
```
(see above)

**Comment by mrazvanalex** [comment]
https://github.blog/2021-09-01-improving-git-protocol-security-github/

I suspect this is the issue you are facing.
![image](https://user-images.githubusercontent.com/6265028/139857089-a3b2d473-4ff7-4e84-8171-3c71d6c71a55.png)

**Comment by muellefa** [comment]
Had the same issue when doing npm install on docker build.
Was able to solve it by including a git-token.

First i created a token:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

And then I included it in my Dockerfile:
`ENV GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

**Comment by richafrank** [comment]
A [quick search](https://github.com/search?q=git+protocol&type=issues) of github looks to me like most others are updating their repos according to `git://` -> `https://`, which I think matches [github's recommendation](https://github.blog/2021-09-01-improving-git-protocol-security-github/#git-protocol-troubleshooting) and means less work for devs to run the tests, but I could be convinced that's not right here.

I put up https://github.com/jazzband/pip-tools/pull/1525 that follows that.
