### ISSUE TITLE
Interest in supporting PEP 665?

### ISSUE THREAD

**Issue by brettcannon** [jazzband/pip-tools#1526]
#### What's the problem this feature will solve?

PEP 665 tries to come up with a standard file format to replace pinned requirements files.

#### Describe the solution you'd like

https://discuss.python.org/t/pep-665-take-2-a-file-format-to-list-python-dependencies-for-reproducibility-of-an-application/11736

#### Alternative Solutions

Status quo.

#### Additional context

I'm basically after a quote or something from the project staying that they would support PEP 665's acceptance. If your answer is "we will if pip will", then https://github.com/pypa/pip/issues/10636 is my request for such support from pip.

**Comment by RonnyPfannschmidt** [comment]
#1463 is a previous request for the feature,
while i'm currently not deeply involved with the development of pip-tools,
i believe the primary inhibitions are that unless pip supports it as well, its not a valuable feature
and the fact that it needs someone to actually write the support code

**Comment by webknjaz** [comment]
There are other non-txt formats consumable by other tools. I would imagine that this could be useful if there's at least one tool actually capable of working with this format. I'd say it's reasonable to wait or to see at least one effort/commitment from any installer to support this soon.

**Comment by brettcannon** [comment]
Thanks for the feedback, everyone! I listed that pip-tools might not be needed for this PEP if pip implemented what they are discussing on their issue tracker.

**Comment by webknjaz** [comment]
@brettcannon I think this might be worth reopening in the context of your new/future PEP. Even if pip implements said features, pip-tools would probably still be useful since it works with some inputs that pip doesn't support (like Poetry).

**Comment by webknjaz** [comment]
xref #2124
