### ISSUE TITLE
requirements resolution does not respect include-system-site-packages = true and break base installation

### ISSUE THREAD

**Issue by garu57** [jazzband/pip-tools#1529]
#### Environment Versions

1. Windows 10 enterprise last update
1. Python version: 3.9.5
1. pip version: 21.3.1
1. pip-tools version: 6.4.0

I'm using [Winpython](http://winpython.github.io/) a scientific distribution (more than 560 packages for almost 7Gb) as a base installation. It's an accurately crafted distribution that guarantees compatibility among all the installed packages. I'm using that precisely because i don't want to go hunting for incompatibilities between the last versions of packages like jupyter, ipython, ipykernel, numpy, pandas, pytorch, tensorflow, etc and the tenth of packages that go around them.
Another thing i don't  want is that each venv for each project ends up containing the very same packages already present in the base installation using then Gb and Gb of useless space and that's the reason why i use `include-system-site-packages = true` in my venv's.

I've always managed all with base commands like `python -m venv` and `pip install` but i wanted to automatize a bit the thing so i gave in sequence a try to [pipenv](https://github.com/pypa/pipenv) and [poetry](https://python-poetry.org/), but i had to quit due to the same problem i found here in [pip-tools](https://github.com/jazzband/pip-tools).

#### Steps to replicate
As an example, if i try to install a very simple thing like `blackcellmagic` in a bare venv with `pip` i get installed only the 4 requirement packages missing in the base installation, because the rest 60 packages of requirements chain are already satisfied by the base installation, (remember the `include-system-site-packages = true`).
If i try `pip-compile` with the same requirement i get 66 (sixty-six) packages because the whole requirements chain is always updated to the last version ignoring the fact that it really it is already satisfied, so breaking the compatibility (both at `pip` requisite level and at execution level) with a lot of other packages in the base installation and making the venv a useless disk space filler.

I tried both `--no-build-isolation` and `--no-upgrade` options, but evidently either i didn't understand their meaning or I'm i missing something, and i didn't find any other way to get `pip-compile`  resolver to honor `include-system-site-packages = true` like `pip` does.

I'm expecting there is a way to force `pip-compile` to accept the already installed satisfied requirements, like `pip`, instead of unconditionally always forcefully updating them to the last version so breaking compatibility with base installation.

I'm not interested to pursue this with [pipenv](https://github.com/pypa/pipenv) and [poetry](https://python-poetry.org/) because i discovered they are both a sort of overkill for my needs, while  [pip-tools](https://github.com/jazzband/pip-tools), if i get this problem solved, would completely satisfy my needs to streamline a lot of hand management.

**Comment by AndydeCleyre** [comment]
The compile command doesn't force updates, but it also doesn't care what's installed, only what may already be listed in the output file.

I think what you want is to first populate your output file with the output of `pip freeze`, then run `pip-compile`.

**Comment by garu57** [comment]
Besides the trick you suggested, I think it's not correct that a dependency manager always operates like it was in a clean room, blindly ignoring what is already installed in the system. Would you accept a request for feature for an option to verify the requirements chain against the installed packages?

**Comment by garu57** [comment]
I just verified what you suggested and it doesn't work.
It fails with the following error:
`
 ERROR: Could not find a version that satisfies the requirement argon2-cffi==20.2.0.dev0 (from notebook==6.4.0->jupyter==1.0.0->blackcellmagic==0.0.3->-r requirements.in (line 1)) (from versions: 15.0.0b5, 15.0.0, 15.0.1, 16.0.0, 16.1.0, 16.2.0, 16.3.0, 18.1.0, 18.2.0, 18.3.0, 19.1.0, 19.2.0, 20.1.0, 21.1.0)
`
I've no idea why, since pip installs without complains and the jupyer env works correctly.

**Comment by AndydeCleyre** [comment]
Can you provide your `requirements.in` and/or whichever input file you're using here?

Looking at https://pypi.org/project/argon2-cffi/#history , I see that `20.2.0.dev0` is not present.

But I don't see that `notebook` is really requiring that specific release.

Does it succeed if you first remove the unavailable `argon2-cffi` release from the output file?

**Comment by AndydeCleyre** [comment]
> Besides the trick you suggested, I think it's not correct that a dependency manager always operates like it was in a clean room, blindly ignoring what is already installed in the system. Would you accept a request for feature for an option to verify the requirements chain against the installed packages?

Well you'd have to lay out clearly what the intended interaction would become between the inputs, the outputs, and the currently-installed set, but this sounds like a way to complicate things and reduce predictability.

**Comment by AndydeCleyre** [comment]
I think the failure is due to a release version in the output that is not on PyPI. But I don't see why that should result in a hard failure like this, rather than being discarded. I'll have a look for existing issues about that.

**Comment by AndydeCleyre** [comment]
OK, you may be interested to try with the changes from PR #1531

**Comment by garu57** [comment]
First of all thanks for your attention.
I stripped down things to the bare minimum to reproduce the issue.
Here's the `requirements.in`
`
blackcellmagic
`

Here's the `pip freeze > requirements.txt` taken from within the venv used for the experiment:
[requirements.txt](https://github.com/jazzband/pip-tools/files/7512714/requirements.txt)

Here is the `pip-compile -v -n --no-upgrade >piptools.log 2>&1` output:
[piptools.log](https://github.com/jazzband/pip-tools/files/7512750/piptools.log)

Here is the `pip list --local` before installing `blackcellmagic`:
 pep517     0.12.0  
 pip        21.3.1
 pip-tools  6.4.0
 setuptools 58.5.3
 tomli      1.2.2

Here is the `pip install -r requirements.in --log pip-install.log` output:
[pip-install.log](https://github.com/jazzband/pip-tools/files/7512758/pip-install.log)

Here is the `pip list --local` after installing `blackcellmagic`:
black          21.10b0
blackcellmagic 0.0.3
pathspec       0.9.0
pep517         0.12.0
pip            21.3.1
pip-tools      6.4.0
setuptools     58.5.3
tomli          1.2.2

**Comment by AndydeCleyre** [comment]
Thank you! I believe that #1530 can be resolved by #1531.

**Comment by garu57** [comment]
If it can be helpful, if i remove `argon2-cffi==20.2.0.dev0` from `requirements.txt` the error changes:

`
  ERROR: Could not find a version that satisfies the requirement jupyter-core==4.8.0.dev0 (from notebook==6.4.0->jupyter==1.0.0->blackcellmagic==0.0.3->-r requirements.in (line 1)) (from versions: 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 4.4.0, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.7.0rc0, 4.7.0, 4.7.1, 4.8.0b0, 4.8.0rc0, 4.8.0rc1, 4.8.0, 4.8.1, 4.8.2, 4.9.0rc0, 4.9.0, 4.9.1rc0, 4.9.1)
`

When they craft the release of Winpython, if it's the only way to fix some issue, they use also dev versions, but in many years since I'm using it i never had a glitch installing things with pip.

I also installed [branch 1530](https://github.com/AndydeCleyre/pip-tools/tree/bugfix/1530) and gave it a try but if fails at runtime with missing modules:
`
ModuleNotFoundError: No module named 'pip._internal.download'
...
ModuleNotFoundError: No module named 'pip.download'
`

What i would expect is an option to allow to match the requirements chain against what is already installed and, if satisfied, install only what is installed by `pip`.
Thanks.

**Comment by AndydeCleyre** [comment]
The current design of this tool does not have `pip-compile` manage the environment's installed packages, instead leaving that to `pip-sync` or `pip` or whatever. 

`pip-compile` only manages the dependency lists, which may inform each other, but are not informed by the environment's installed packages.

**Comment by AndydeCleyre** [comment]
It's been a few weeks, so I am going to close this, but please feel free to open a new issue detailing a feature request, if you think it might be a fit with pip-tools' design. Thanks!

**Comment by m-novikov** [comment]
I have same problem. I want to create virtual env with included system site packages containing only missing dependencies.  
But when I compile requirements it's includes all transitive dependencies that are already available in the system.
Subsequent call to pip-sync installs these requirements breaking the installation.

**Comment by AndydeCleyre** [comment]
@m-novikov Can you formulate your issue into very specific expectations, either here, or as a new feature request?
