### ISSUE TITLE
pip-compile with --index-url option delivers packages that are not on package index

### ISSUE THREAD

**Issue by ckaldemeyer** [jazzband/pip-tools#1546]
#### Environment Versions

1. OS Type: Windows 10 and Linux
1. Python version: 3.7 and 3.8
1. pip version: 21.3.1
1. pip-tools version: 6.4.0

#### Steps to replicate

1. pip-compile --index-url https://user:password@gitlab.my.tld/api/v4/projects/5/packages/pypi/simple
2. creates a `requirements.txt` with pinned versions

#### Expected result

All pinned versions in `requirements.txt` should be available on package index. Otherwise an error is returned.

#### Actual result

The `requirements.txt` contains package versions that are not on the private package index.

I thought that `pip-compile` uses only packages on the index because this allows to use `pip-tools` in combination with a private index.

Can anyone help and clarify the behaviour?

**Comment by ckaldemeyer** [comment]
I have also asked this on SO: https://stackoverflow.com/questions/70438495/pip-compile-with-index-url-option-delivers-pinned-package-versions-that-are-no

**Comment by richafrank** [comment]
@ckaldemeyer I'm going to close this. Looks like you got the answer on SO! Feel free to re-open if not.
```
GitLab pypi registry proxies requests to upstream pypi when package doesn't exist in GitLab registry. Perhaps this is the issue?  – Satya Mishra Dec 31 '21 at 12:20

You are right. This seems to be the issue!  – Cord Kaldemeyer Jan 5 at 15:07
```

**Comment by ckaldemeyer** [comment]
Ye, thanks!
