### ISSUE TITLE
Conditional requirements markers are evaluated instead of being copied

### ISSUE THREAD

**Issue by juledwar** [jazzband/pip-tools#1553]
If my requirements.in file contains something like:
```
importlib_resources==5.4.0 #; python_version < '3.9'
```
When I run pip-compile to generate the requirements.txt file on Python 3.9, the importlib_resources entry is missing completely.
It appears that the conditional is being evaluated to determine the output, rather than just copying it.

#### Environment Versions

1. Linux
1. Python 3.9.9
1. pip 21.3.1
1. pip-tools version: 6.4.0

#### Steps to replicate
```
echo "importlib_resources==5.4.0; python_version < '3.9'" >> requirements.in
pip-compile --generate-hashes --output-file requirements.txt requirements.in
```

#### Expected result

The requirements.txt file should contain:
```
importlib_resources==5.4.0; python_version < '3.9' --hash=sha256:xxxxblah
```

#### Actual result
No entry for importlib_resources
...

**Comment by AndydeCleyre** [comment]
The output file is suitable just for the environment type in which `pip-compile` was run.

Might this discussion fit the existing issue #1326?

**Comment by juledwar** [comment]
I guess that's what it's trying to do yeah, but it seems less useful than copying the filter markers. Also looking at #1326 this is probably a dupe.

**Comment by AndydeCleyre** [comment]
Alright, I'm going to close this in favor of continuing at #1326.
