### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by pauloxnet** [jazzband/pip-tools#1562]
#### What's the problem this feature will solve?

Python 3.6 is EOL since December 2021

#### Describe the solution you'd like

Drop Python 3.6 support in pip-tools

#### Additional context

There's already a related PR #1560

**Comment by gopackgo90** [comment]
There would need to be more changes than just what's in that PR, like updating `python_requires` in setup.cfg.

**Comment by pauloxnet** [comment]
Yes, I know, in fact I wrote that there is a PR related to the issue and not a final PR.

**Comment by hugovk** [comment]
Please see PR #1564 for the other changes.

**Comment by pauloxnet** [comment]
I commented there, but there are still some test failures there.

**Comment by hugovk** [comment]
Thanks, it's been included in the consolidated https://github.com/jazzband/pip-tools/pull/1567 where tests now pass.
