### ISSUE TITLE
CI failing due to normalization of dashes to underscores in tests

### ISSUE THREAD

**Issue by nicoa** [jazzband/pip-tools#1566]
There are some issues currently raised regarding CI failing:
* newest pip version (22.0) using rich for logging instead of  - #1558 
* python 3.6 deprecation in pip - #1564 
* tests failing due to none of the above two cases - registered while working on first point in #1565 

The py36 deprecation was the first to let tests in CI regularly fail in the last few month (around 3 months back). Before the main branch of pip then some time ago introduced the first issue (rich logging) now popping up with lots of attraction, there was this CI failure: https://github.com/jazzband/pip-tools/runs/4419708428?check_suite_focus=true . Fixing issue #1558 still leaves this a problem due to which the CI will fail (see PR #1565 for this).

It seems to be caused by wrong / missing normalization of dashes to underscores - which I would've expected with 21.2 to happen due to https://pip.pypa.io/en/stable/news/#id76 and not to be introduced in 22.0, but maybe I misunderstand the point `Process` there?

In case stuff is unclear here I'm happy to provide details whenever I find time.

**Comment by hugovk** [comment]
Please see https://github.com/jazzband/pip-tools/pull/1567 for a fix.
