### ISSUE TITLE
Don't write pip-compile output to file by default

### ISSUE THREAD

**Issue by scott2b** [jazzband/pip-tools#1586]
#### What's the problem this feature will solve?

pip-compile CLI behavior is unexpected. Simply typing `pip-compile` with the expectation of getting usage is unexpectedly destructive, resulting in an overwrite of requirements.txt. The `-o` option seems unnecessary, where the standard idiom would be to output to stdout and to allow the user to direct the output as desired. This is further complicated by the fact that the output is both printed and written to file by default. At the very least, the file-write should be an option, not the default.

#### Describe the solution you'd like

`pip-compile` with no options or parameters should return a usage message

`pip-compile requirements.in` should send it's output to stdout for redirection and piping and should not be destructive unless options are provided that indicate an expectation of destructive behavior.

**Comment by deifactor** [comment]
One difficulty is that `pip-compile requirements.in > requirements.txt` will *always* truncate the requirements.txt before pip-compile gets a chance to open it, just due to how shell redirection works.

```
❯ echo "some requirements" > requirements.txt
❯ cat requirements.txt > requirements.txt
❯ cat requirements.txt

❯
```

**Comment by scott2b** [comment]
The framing of --dry-run as the default behavior makes sense to me. Alternatively, requiring the user to specify the name of the output file. The problem is that the default behavior of destroying the user's requirements file is unexpected. If I had to specify the name of the output file, then I'd think that yeah this is probably going to do something to that file.

**Comment by AndydeCleyre** [comment]
> The problem is that the default behavior of destroying the user's requirements file is unexpected.

Do you have an example of a lockfile generator which **doesn't** write to a file, even when the output file is not explicitly specified?

Here are the examples I could think of in the same class as `pip-compile`:

Language  |  Lockfile Generator  |  Writes Lockfile by Default?
---  |  ---  |  ---
Rust  |  `cargo generate-lockfile` or `cargo update`  |  YES
NodeJS  |  `npm install`  |  YES
NodeJS  |  `yarn install`  |  YES
Ruby  |  `bundle install` or `bundle update`  |  YES
Python  |  `poetry update`  |  YES
Python  |  `pipenv lock`  |  YES
Python  |  `pip-compile`  |  YES

I may misunderstand about any of those, though, as I don't regularly use them.

**Comment by scott2b** [comment]
Calling a requirements.txt file a "lock" file is a bit of a stretch. I have yet to work on a project where requirements.txt was not written by hand. This is my first experience with a tool that manages requirements.txt for me. The examples you site mostly seem to have actual .lock files which are not hand-edited.

**Comment by deifactor** [comment]
If you're using `pip-compile`, then you shouldn't be hand-editing requirements.txt (most of the time).
