### ISSUE TITLE
[help] How can `# via <pacakge_name> (setup.py)` removed automatically from requirements.txt

### ISSUE THREAD

**Issue by avatar-lavventura** [jazzband/pip-tools#1587]
#### Environment Versions

1. OS Type: `Ubuntu 20.04.3 LTS`
1. `Python 3.8.10`
1. `pip 22.0.3 from /home/alper/venv/lib/python3.8/site-packages/pip (python 3.8)`
1.  `pip-compile, version 6.5.1`

---------

#### Steps to replicate

Let's assume my repo's name is `work`. When I apply `pip-compile`, `requirement.txt` updated as  after each package name there is `# work (setup.py)` line. I can remove them using `sed -i '/work (setup.py)/d' requirements.txt`.  Could it be removed automatically by `pip-compile`?

```
sphinxcontrib-serializinghtml==1.1.5
    # via
    #   work (setup.py)
    #   sphinx
ssh-import-id==5.10
    # via work (setup.py)
sshtunnel==0.1.4
    # via
    #   work (setup.py)
```

**Comment by AndydeCleyre** [comment]
Do you mean to disable all annotations, or just some of them?

**Comment by avatar-lavventura** [comment]
I want to disable all notations that has following pattern:

```#   <my_repo_name> (setup.py)```

**Comment by AndydeCleyre** [comment]
Can you please elaborate on the use case for hiding those?

**Comment by AndydeCleyre** [comment]
OK, so you want to hide annotations which indicate the top level, so that also ones coming from `requirements.in` or any other input file will also be hidden?

**Comment by avatar-lavventura** [comment]
@AndydeCleyre Yes sir.  I want to hide top level annotation (`#   <package_name> (setup.py)`) in everything.

**Comment by atugushev** [comment]
There is no such functionality. I'd suggest to use `sed` or something similar.

**Comment by avatar-lavventura** [comment]
@atugushev ok
