### ISSUE TITLE
future: cache editables in memory during the current run

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#159]
I've noticed that editable VCS dependencies get fetched multiple times during the same run, but they could and should be cached during the current run.

Apart from improving performance, this makes also sure that they do not change during the run.

IIRC I've changed that in the former future branch, before the rewrite.

I could imagine adding a `MemoryDependencyCache`, which behaves like `DependencyCache`, but would not read/write anything.

What do you think?

**Comment by blueyed** [comment]
While this change is probably good anyway, I'd really like to cache the editables also for a certain period, e.g. 5 minutes.
When building the requirements for my project, I call pip-compile for multiple requirements.in files (dev, testing, production), and they should all use the cached result from the first run.

**Comment by davidovich** [comment]
This was implemented in PR #476 to fix a new bug introduced in 1.8.1. Closing.
