### ISSUE TITLE
test_direct_reference_with_extras fails

### ISSUE THREAD

**Issue by pgajdos** [jazzband/pip-tools#1590]
#### Environment Versions

1. OS Type Linux
2. Python version: `$ python -V` 3.9.10
3. pip version: `$ pip --version` 20.2.4
4. pip-tools version: `$ pip-compile --version` 

#### Steps to replicate

[    6s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-pip-tools-6.5.1-0.x86_64/usr/lib/python3.9/site-packages
[    6s] + PYTHONDONTWRITEBYTECODE=1
[    6s] + pytest-3.9 --ignore=_build.python39 --ignore=_build.python310 --ignore=_build.python38 -v -k 'not network or test_direct_reference_with_extras'
[    8s] ============================= test session starts ==============================
[    8s] platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3.9
[    8s] cachedir: .pytest_cache
[    8s] rootdir: /home/abuild/rpmbuild/BUILD/pip-tools-6.5.1, configfile: setup.cfg, testpaths: tests, piptools
[    8s] plugins: forked-1.3.0, xdist-2.5.0
...
[   68s] =================================== FAILURES ===================================
[   68s] ______________________ test_direct_reference_with_extras _______________________
[   68s] [gw7] linux -- Python 3.9.10 /usr/bin/python3.9
[   68s]
[   68s] runner = <click.testing.CliRunner object at 0x7f1e4bd8ff40>
[   68s]
[   68s]     def test_direct_reference_with_extras(runner):
[   68s]         with open("requirements.in", "w") as req_in:
[   68s]             req_in.write(
[   68s]                 "piptools[testing,coverage] @ git+https://github.com/jazzband/pip-tools@6.2.0"
[   68s]             )
[   68s]         out = runner.invoke(cli, ["-n", "--rebuild"])
[   68s] >       assert out.exit_code == 0
[   68s] E       assert 1 == 0
[   68s] E         +1
[   68s] E         -0
[   68s]
[   68s] /home/abuild/rpmbuild/BUILD/pip-tools-6.5.1/tests/test_cli_compile.py:661: AssertionError

#### Expected result

success

#### Actual result

failure

**Comment by AndydeCleyre** [comment]
It looks like this is using an unsupported pairing of pip-tools and pip versions. According to the bottom of the README, pip-tools `>=6.5.0` requires pip `>=21.2`.

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
