### ISSUE TITLE
[6.5.x] Packages containing dots are renamed to use dashes

### ISSUE THREAD

**Issue by Jorricks** [jazzband/pip-tools#1599]
#### Environment Versions
1. OS Type: MacOs
1. Python version: `Python 3.8.11`
1. pip version: `pip 22.0.3`
1. pip-tools version: `pip-compile, version 6.5.1`

#### Steps to replicate
1. Create a file requirements file containing `zope.event`
2. pip-compile
4. Output contains `zope-event`

#### Expected result
The compiled file should contain `zope.event` as `zope-event` does not exist.

#### Actual result
It contains `zope.event`

#### Why is this an issue?
When you have a `setup.py` pointing to your compiled requirements file, you can not use console_scripts anymore.
Because when you try to run my entry_point console_scripts, you will get an error similar to:
```
pkg_resources.DistributionNotFound: The 'zope-event==4.5.0' distribution was not found and is required by my_package
```

**Comment by AndydeCleyre** [comment]
I'd like to close this in favor of centralizing this discussion at #1576

See also: pypa/setuptools#3157

**Comment by Jorricks** [comment]
I completely missed that one. Thank you
