### ISSUE TITLE
Package does not include the `py.typed` file?

### ISSUE THREAD

**Issue by AustinScola** [jazzband/pip-tools#1610]
While the repo has a `py.typed` file and uses annotations, I don't think the `py.typed` file is being packaged which causes the following error when type checking code which imports `piptools`:
```
error: Skipping analyzing "piptools": module is installed, but missing library stubs or py.typed marker  [import]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

I think the solution is to just include `package_data = ["py.typed"]` in `setup.cfg`.

As a bonus the classifier `Typing :: Typed` could also be added.

**Comment by FlorentJeannot** [comment]
Hello @AustinScola,

FYI, I made a PR to fix this. Just out of curiosity, why do you need to import `piptools` in your code?

**Comment by AustinScola** [comment]
> Just out of curiosity, why do you need to import `piptools` in your code?

I have a wrapper script around `piptools` that adds functionality.

**Comment by FlorentJeannot** [comment]
Interesting, is this something we could integrate into pip-tools?

**Comment by AustinScola** [comment]
Maybe? It lets me use a config file to give names to specifications of requirements files and to freeze multiple specifications at once
