### ISSUE TITLE
No versions found for climage.

### ISSUE THREAD

**Issue by madpin** [jazzband/pip-tools#1611]
#### Environment Versions

1. OS Type MacOS
1. Python version: `$ python -V`
1. pip version: `$ pip --version` Python 3.8.8
1. pip-tools version: `$ pip-compile --version` pip-compile, version 5.5.0

#### Steps to replicate

1. create a requirements.in with `climage`
2. pip-compile --upgrade --output-file=requirements.frozen requirements.in

#### Expected result

Everything installed
...

#### Actual result

Could not find a version that matches climage (from -r requirements.in (line 11))
No versions found
Were https://pypi.org/simple or https://pypi.org/simple  reachable?

...

**Comment by AndydeCleyre** [comment]
Thanks!

I can't reproduce here, but I don't have MacOS to test with.

- Might it have been a temporary network disruption?
- What's the `pip` version? 
- Can you try with a current `pip-tools` release?
- Can you reproduce when `climage` is the only top level dep?
- `pip-compile` should not be expected to install these packages into your environment, only to generate the `requirements.txt` lockfile.

**Comment by richafrank** [comment]
FWIW I just ran the following on MacOS using pip-tools 6.6.0 (via git):

```
$ python -V
Python 3.8.12

$ pip --version
pip 22.0.4 ...

$ echo "climage" | pip-compile - -qo- 
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --output-file=- -
#
climage==0.1.3
    # via -r -
kdtree==0.16
    # via climage
pillow==9.1.0
    # via climage
```
