### ISSUE TITLE
Error importing BAR_TYPES with new pip 22.1 release

### ISSUE THREAD

**Issue by kabirkhan** [jazzband/pip-tools#1617]
pip-tools breaks with the new version of pip "22.1". Error:

```
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py)
```

#### Environment Versions

OS: Ubuntu 20.04
Python version: 3.9
pip version: 22.1
pip-tools version: 6.6.0

#### Steps to replicate

1. pip install -U pip pip-tools
2. pip-compile requirements.in

#### Expected result

Compilation is successful

#### Actual result

Full traceback from my CI job.
```
Traceback (most recent call last):
  File "/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/lib/python3.9/site-packages/piptools/scripts/compile.py", line 21, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/lib/python3.9/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/lib/python3.9/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 23, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/tmp/tmpxfal9pqx/6297f3abdc8a9aff/test-env/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py)
```

**Comment by jason-nance** [comment]
Looks like `BAR_TYPES` was removed in [this commit](https://github.com/pypa/pip/commit/728e4fe7c4168f62b8f47721aa56576cce5e46fb).

**Comment by AndydeCleyre** [comment]
There's a fix for this in the new resolver PR, and we either need pull that bit out for a more immediate release, or finalize and merge that PR, which still has at least one problem.

**Comment by klimburg** [comment]
Just hit this in our CI

**Comment by pradyunsg** [comment]
Pulling that out into a more immediate release seems reasonable to me. :)

**Comment by lafolle** [comment]
For now i am just pinning `pip` to 22.0.4. Looking forward to the fix!

**Comment by AndydeCleyre** [comment]
I can't be at a computer for a little while, @atugushev want to do a small release soon?

**Comment by deifactor** [comment]
IIRC this isn't the first time a new pip release has broken pip-tools. Would it be a good idea to have upper bounds in its dependency?

**Comment by wizpig64** [comment]
That commit has been in the pip main branch for a month, ideally this repo should be testing against that regularly to catch for this kind of thing early, rather than needing to add a version cap that would just get in the way later.

oh dear, it *does* regularly check for this: https://github.com/jazzband/pip-tools/runs/6267937837?check_suite_focus=true

**Comment by hynek** [comment]
1. pip is not following semantic versioning
2. even if it did, removing a symbol from an internal module is not a breaking change

Please stop suggesting upper bounds pins, they would make everything much, much worse.

**Comment by atugushev** [comment]
Fix released as part of `pip-tools v6.6.1`.

**Comment by kabirkhan** [comment]
Thanks for getting this done so quickly :)

**Comment by hugo2121-trip** [comment]
what was the fix there? 
I got same issue with 
```
pip version 22.1.2 (also tried 22.0.4)
pip-tools version 6.8.0

```

**Comment by hugovk** [comment]
Sorry I clicked the wrong button!

**Comment by hugo2121-trip** [comment]
> @hugo2121-trip
> 
> Can you provide a reproducible procedure?

thanks for replying. I fixed the issue. My team is using `tox` to run some command, and seems tox using `pip 22.1.2` under the hood. 

I made some dependencies change to force using some version: 

```
pip == 22.0.4
pip-tools==5.4.0
```

and fixed the issue.

**Comment by thehackermonkey** [comment]
For me it worked after doing:

1. `pip install pip==22.0.4`
2. `pip install --upgrade pip-tools`


Thanks to @lafolle for pointing the latest working version.

**Comment by kijewskimateusz** [comment]
I can see this issue existing too when executing `pip-compile` command using Pre-Commit. As far as I've found, pre-commit installed by brew uses latest python@3.10 package and every pre-commit action is executed inside pre-commit venv I can't access.

**Comment by matheusft** [comment]
> For me it worked after doing:
> 
> 1. `pip install pip==22.0.4`
> 2. `pip install --upgrade pip-tools`
> 
> Thanks to @lafolle for pointing the latest working version.

That worked fine for me. Thanks =)
