### ISSUE TITLE
[documentation] Use double quotes instead of single when running `piptools` with `--pip-args` flag

### ISSUE THREAD

**Issue by amenasria** [jazzband/pip-tools#1621]
Running `piptools` with `--pip-args` flag using single quotes is working for Linux but failing for Windows.

#### Environment Versions

1. OS Type: Windows
1. Python version: `2.X` and `3.X`
1. pip version: `pip 22.0.4`
1. pip-tools version: `$ pip-compile --version` latest

#### Steps to replicate

Following the documentation:
1. Creating a `requirements.in` file:
```
django
```
2. Running `piptools` with `--pip-args` flag:
```
python -m piptools compile requirements.in --pip-args '--retries 20 --timeout 20'
```
3. Get the following result:
```
Error: No such option: --timeout
```

**But running the command with double quotes work**

#### Expected changes

The documentation for `--pip-args` should be using double quotes by default.

**Comment by AndydeCleyre** [comment]
Thanks!

What is the shell being used here?

**Comment by amenasria** [comment]
My bad, I forgot !

Apparently, single quotes are working on Windows PowerShell but not on Command Prompt (cmd.exe).

I discovered the issue in a Gitlab CI pipeline's job using [Shell executor](https://docs.gitlab.com/runner/executors/shell.html) though.

**Comment by amenasria** [comment]
Ok thanks ! Yes maybe it's the best solution at the end of the day, but this fix build suits me well for now aha :smiling_face_with_tear:

Yup for the PR, I also modified the `--pip-args` in the pip-syncs command (I tested it and the same problem occurred).

Here it is: #1622
