### ISSUE TITLE
I would like the output of help to be written in READEME.

### ISSUE THREAD

**Issue by 29rou** [jazzband/pip-tools#1633]
#### What's the problem this feature will solve?

This is so that those who are wondering whether to use this tool can understand how to use it at a glance. I also believe that this will encourage more people to use this tool.

#### Describe the solution you'd like

Describe the output of help in READEME.

#### Alternative Solutions

Add a man page to the documentation.

#1634

**Comment by atugushev** [comment]
@29rou FYI, there is a PR (#1934) where CLI reference has been included in the pip-tools' documentation.
