### ISSUE TITLE
The banner in the generated requirements.txt is confusing

### ISSUE THREAD

**Issue by jceresini** [jazzband/pip-tools#1636]
When I use pip-compile to generate a requirements.txt file, it includes this banner at the top:

```
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --no-emit-index-url
```

However, without the `--upgrade` argument, that command won't generate a new requirements.txt file, unless the setup.py changes. It sounds like it's the distinction between _updating_ the file vs _upgrading_ the packages pinned in the file. As a new user, I found that confusing when subsequent runs of pip-compile weren't picking up upgraded packages.

Ref: https://github.com/jazzband/pip-tools/blob/master/README.rst?plain=1#L64-L68

**Comment by atugushev** [comment]
Agreed. Perhaps, there should be mentioned that a file is autogenerated by the command.
