### ISSUE TITLE
Add --dry-run

### ISSUE THREAD

**Issue by nbecker** [jazzband/pip-tools#1638]
#### What's the problem this feature will solve?

Like to see what install --upgrade might do without actually proceeding with install

#### Describe the solution you'd like

Easiest option is add --dry-run, which would print what actions would be taken, but not actually perform any filesystem modifications.

As an example, I have a system with tensorflow-2.8.  I can't update to 2.9 because I'm working with sionna, which doesn't support tf-2.9.  I'm wondering if I could update tensorboard?  It would be nice if I could do
pip install --upgrade tensorboard --dry-run
And see what it thinks.

**Comment by AndydeCleyre** [comment]
```console
$ pip-compile --help | grep dry -A 1
  -n, --dry-run                   Only show what would happen, don't change
                                  anything
```
```console
$ pip-sync --help | grep dry
  -n, --dry-run             Only show what would happen, don't change anything
```

> It would be nice if I could do
> `pip install --upgrade tensorboard --dry-run`

The `pip` command isn't part of this project, but over at https://github.com/pypa/pip

**Comment by nbecker** [comment]
Sorry about that
