### ISSUE TITLE
Pip-tools should not canonicalize package names when writing to requirements file

### ISSUE THREAD

**Issue by ZianVW** [jazzband/pip-tools#1641]
Piptools canonicalizes package names according to PEP 503 when writing to the `requirements.txt` file.  

This can cause problems for tools like PyCharm that compare the contents of the `requirements.txt` file to the list of packages that are actually installed, leading to false "Package not installed" warnings that won't go away.

It is legitimate for package names to contain periods, for example: https://pypi.org/project/zope.interface/

I do not believe that canonicalizing the package name when writing to `requirements.txt` is correct, because PEP 503 relates to the _**API**_ for a package repository, which is really a different thing from the requirements file. Pip will automatically canonicalize the package name when using the requirements file to access the package repository, so it will find and install the package regardless of whether it was canonicalized in the file or not.

#### Environment Versions

1. OS Type : Mac OS
1. Python version: `$ python -V` : Python 3.10.4
1. pip version: `$ pip --version` : pip 21.3.1
1. pip-tools version: `$ pip-compile --version` : pip-compile, version 6.6.2
#### Steps to replicate

1. Setup contents of `requirements.in`:
```
datetime
```
2. Run `pip-compile -U`

Resulting `requirements.txt`:
```
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile
#
datetime==4.4
    # via -r requirements.in
pytz==2022.1
    # via datetime
zope-interface==5.4.0.             <== Notice the "-" in the package name
    # via datetime

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

Output of `pip freeze` after running `pip install -r requirements.txt`:
```
click==8.1.3
pep517==0.12.0
pip-tools==6.6.2
tomli==2.0.1
zope.interface==5.4.0               <== Notice the "." in the package name
```

#### Expected result

I expect the following in `requirements.txt`:
```
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile
#
datetime==4.4
    # via -r requirements.in
pytz==2022.1
    # via datetime
zope.interface==5.4.0.             <==
    # via datetime

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

#### Actual result

Resulting `requirements.txt`:
```
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile
#
datetime==4.4
    # via -r requirements.in
pytz==2022.1
    # via datetime
zope-interface==5.4.0.             <== Notice the "-" in the package name
    # via datetime

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

**Comment by AndydeCleyre** [comment]
I'm going to close this, but feel to continue the discussion at #1576.

If the only problem you're experiencing is with PyCharm, note that the project has known issues in its ability to match up modules with PyPI packages; see: 

- https://youtrack.jetbrains.com/issue/PY-49425 (and all the issues marked as duplicates of that one)
- https://youtrack.jetbrains.com/issue/PY-22114
- https://youtrack.jetbrains.com/issue/PY-24636
