### ISSUE TITLE
Compile just does nothing if library spacy is in requirements.in file

### ISSUE THREAD

**Issue by Schwankenson** [jazzband/pip-tools#1665]
I have this requirements.in file and try to compile it with pip-compile

    django==3.2
    ptvsd==4.3.2
    spacy==3.4.1

`pip-compile requirements.in` just does nothing: I have to stop with Ctrl + C. No output. Waited 10 minutes. If I remove spacy from requirements.in, everything works fine and requirements.txt file is generated within seconds. I tried to not specify version and to use `git+https://github.com/explosion/spaCy@v3.4.1` instead. Always the same outcome.

What could be wrong?

**Comment by atugushev** [comment]
Have you tried `pip-compile -v` or `pip-compile -vvv`

**Comment by Schwankenson** [comment]
Thank you for that quick answer. I tried `-vvv` now. It stops at: `spacy==3.4.1 not in cache, need to check index` -

**Comment by atugushev** [comment]
Can you install `spacy` using pip `python -m pip install spacy==3.4.1`?

**Comment by Schwankenson** [comment]
It starts installing but "Installing build dependencies ... /" takes a looong time...I write again if it has finished...

**Comment by Schwankenson** [comment]
Installing spacy finished after some time without a problem - Does pip-compile check system requirements of the package?

**Comment by atugushev** [comment]
Yeah, pip-compile invokes pip's download/install command to get metadata.

**Comment by atugushev** [comment]
@Schwankenson FYI https://github.com/explosion/spaCy/discussions/11240
