### ISSUE TITLE
pip-compile --upgrade not propagating to the header

### ISSUE THREAD

**Issue by jamesbraza** [jazzband/pip-tools#1675]
#### Environment Versions

1. OS Type: macOS Big Sur v11.5.1
1. Python version: `$ python -V`: 3.10.3
1. pip version: `$ pip --version`: 22.2.2
1. pip-tools version: `$ pip-compile --version`: 6.8.0

#### Steps to replicate

I use the included header command to reproduce the command run.  I would like `--upgrade` to be propagated to the header.

Trying it out:

```bash
pip-compile --upgrade
```

#### Expected result

I expect `--upgrade` to propagate to the header.

```txt
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile --upgrade
#
...
```

#### Actual result

It did not propagate to the header.

```txt
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile
#
...
```

**Comment by atugushev** [comment]
That's a deliberate decision, because `--update` is a one-off option.

**Comment by jamesbraza** [comment]
In my workflow, I like having the header match the command used to produce the file for traceability.  In other words, if `--upgrade` was part of the `pip-compile` invoked to produce the `requirements.txt`, then imo it should be reflected in the header.

To take a different perspective, I see the header silently filtering out parts of the `pip-compile` command as unexpected behavior.

I like `pip-compile` so I reported this issue, and I leave it up to you what you decide to do!

**Comment by atugushev** [comment]
You can override the header with [COMPILE_COMMAND](https://github.com/jazzband/pip-tools#configuration) env.

**Comment by AndydeCleyre** [comment]
See also: #1461

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
