### ISSUE TITLE
pip-compile not propagating platform_system

### ISSUE THREAD

**Issue by jamesbraza** [jazzband/pip-tools#1676]
#### Environment Versions

1. OS Type: macOS Big Sur v11.5.1
1. Python version: `$ python -V`: 3.10.3
1. pip version: `$ pip --version`: 22.2.2
1. pip-tools version: `$ pip-compile --version`: 6.8.0

#### Steps to replicate

I have a [PEP 508 dependency specification](https://peps.python.org/pep-0508/) present `platform_system`:

`requirements.in`

```txt
windows-curses ; platform_system=="Windows"
```

Then running:

```bash
pip-compile --upgrade --annotation-style=line --no-emit-index-url --no-header
```

#### Expected result

```txt
windows-curses==2.3.0 ; platform_system=="Windows"  # via -r requirements.in
```

#### Actual result

(the `windows-curses` field is not propagated)

How can I get it to be propagated?

**Comment by AndydeCleyre** [comment]
> (the `windows-curses` field is not propagated)

You mean the `platform_system` environment marker?

**Comment by AndydeCleyre** [comment]
Oh I see. Yes, when you run `pip-compile` on a platform for which an environment marker evaluates as false, the corresponding requirement is not part of the resulting locked dependency tree, and this is currently expected behavior.

You may be interested in the discussion at #1326.

**Comment by AndydeCleyre** [comment]
Does it work for you to close this, to funnel relevant ideas into #1326?

**Comment by jamesbraza** [comment]
Sure, I am down to redirect ideas into #1326!  I don't have any ideas of a solution, just more raising the feature request.

It may be helpful for other users searching through issues to notice this is open, and close it out when #1326 is implemented.  However, if you want to close this out now, please feel free 🙂

**Comment by AndydeCleyre** [comment]
Oh, #826 is more directly relevant, but I also wonder about merging that issue into #1326. It's not obvious how to move forward on these issues, so it's not about to get implemented. We need to establish a clear and sane strategy.
