### ISSUE TITLE
pip-compile doesn't identify version of unpinned package that is compatible with a pinned dependency

### ISSUE THREAD

**Issue by tsh56** [jazzband/pip-tools#1688]
I tried to `pip-compile` a set of dependency which leads to resolution issues. When I `pip install` the set of requirements below, pip is able to identify a compatible set of packages. It does this by probing prior versions of boto3 to look for compatibility. The problem arises from the fact that boto3 has strict dependencies on botocore. When another package pins botocore to a specific version, you must find the version of boto3 which is compatible with the pinned version of botocore.

Example:
```
s3fs==2022.8.2
boto3
```

#### Environment Versions

1. OS Type: Linux
1. Python version: `$ Python 3.10.4`
1. pip version: `$ pip 22.0.4 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`
1. pip-tools version: `$ pip-compile, version 6.8.0`

#### Steps to replicate

1. Place example requirements into a requirements.txt file
2. `pip-compile requirements.txt`

#### Expected result

I believe the compile should succeed with all dependencies properly resolved.

#### Actual result

```
There are incompatible versions in the resolved dependencies:
  botocore<1.28.0,>=1.27.84 (from boto3==1.24.84->-r test.txt (line 2))
  botocore<2.0a.0,>=1.12.36 (from s3transfer==0.6.0->boto3==1.24.84->-r test.txt (line 2))
  botocore<1.27.60,>=1.27.59 (from aiobotocore==2.4.0->s3fs==2022.8.2->-r test.txt (line 1))
```

**Comment by atugushev** [comment]
`pip-compile --resolver backtracking` might help.

**Comment by tsh56** [comment]
This works. Thanks for the suggestion.
