### ISSUE TITLE
[advice] fasten `pip-compile --help`

### ISSUE THREAD

**Issue by Freed-Wu** [jazzband/pip-tools#1703]
Now pip-tools' cli is

```python
from piptools.scripts.compile import cli
```

However, import the full `piptools/scripts/compile.py` is too slow, if user just want to take a look at the usage of cli, that is `pip-compile --help`, it still need to import this file. why not divide the argument parse part to a `piptools/scripts/compile.py/__main__.py` to fasten `pip-compile --help`? Same reason for `pip-sync`. Thanks.

**Comment by atugushev** [comment]
`piptools/scripts/compile.py` imports pip internals which is slow. Moving slow imports inside `cli()` should improve the speed. PRs are welcomed!

**Comment by q0w** [comment]
Its 4 times faster without pip imports, but I dont know how to properly dynamically add click.option without a custom function like:
```python
def get_options(f):
    if "--help" not in sys.argv[1:]:
        click.option(
            "-i",
            "--index-url",
            help="Change index URL (defaults to {index_url})".format(
                index_url=redact_auth_from_url(_get_default_option("index_url"))
            ),
        )(f)
		...
    return f
 ```
 
 > Moving slow imports inside cli()

 It does not work, since click.option already imports pip internals for its args (like help above)
