### ISSUE TITLE
about virtual  env install

### ISSUE THREAD

**Issue by dyhyao6** [jazzband/pip-tools#1704]
My environment is:
Python3 --version: python3.7
conda: miniconda
Now I need to manage the python3 virtual environment:
1. There are more than 500 python packages to be installed, but there are many dependencies in the python packages. As a result, the installation of requirements.txt cannot be successful every time the virtual environment is installed，have a good idea ？ @jezdez

**Comment by AndydeCleyre** [comment]
Thanks! Can you provide reproducible steps, input files, and any error messages?

**Comment by dyhyao6** [comment]
> Thanks! Can you provide reproducible steps, input files, and any error messages?

1、create a venv :  conda create --name py379 python=3.7
2、pip install -r requirements.txt
but there are many problems like:
![image](https://user-images.githubusercontent.com/49445844/196072439-5eceff69-38ac-456c-b6f7-8b64c92ad70c.png)
can you import my requirements.txt to creaete a vens ，here is my import file: 

[requirements.txt](https://github.com/jazzband/pip-tools/files/9796304/requirements.txt)
