### ISSUE TITLE
pip-tools is raising dependency conflicts when it shouldn't for apache_beam[gcp]

### ISSUE THREAD

**Issue by AnandInguva** [jazzband/pip-tools#1709]
When we use `google-cloud-pubsub==2.13.10` and `protobuf==3.20.3` as part of apache_beam[gcp] in the req.in, we get errors about dependency conflicts since google-cloud-pubsub depends on grpcio-status. pip-tools fails emitting this in the error log ` protobuf>=4.21.6 (from grpcio-status==1.50.0->google-cloud-pubsub==2.13.10->-r req.txt`  but when we include `grpcio-status==1.48.2` in the req.in, pip-tools work and produces a list of dependencies. The expectation here is pip-tools should be able to deduct the version of grpcio-status on its own, isn't it?

#### Environment Versions

1. OS Type: Linux
1. Python version: `38`
1. pip version: `22.1.2`
1. pip-tools version: `6.9.0`

#### Steps to replicate

1.  Create a req.in and place apache_beam[gcp] in it.
2. Run pip tools. It will generate the error

#### Expected result

No dependency conflict since pip was able to install apache_beam[gcp] without any dependency conflicts but pip-tools fails due to the above description

**Comment by AndydeCleyre** [comment]
Can you try with `--resolver=backtracking` ?

**Comment by AnandInguva** [comment]
It worked. Thanks. 

After going through the change log, I got one question. Shouldn't backtracking be the default value for `--resolver`?

**Comment by AndydeCleyre** [comment]
The plan is to make it default very soon.

**Comment by atugushev** [comment]
I'll close this based on the above. Thanks!
