### ISSUE TITLE
Question: Correct way to include requirement/installation of self via pip-compile/pip-sync

### ISSUE THREAD

**Issue by adamcunnington-mlg** [jazzband/pip-tools#1746]
I am wondering what the correct way to specify "self" for installation alongside dependencies, when using pip tools.

I am using `[project.dependencies]` in `pyproject.toml` to specify my main dependencies and I am using `[project.optional-dependencies]` to specify various groups of dev/extra dependencies.

I also want to install my current package - potentially in editable mode if alongside dev dependencies.

Currently, I do something like this:
```bash
pip-compile pyproject.toml --extra=dev --output-file=extras/dev-requirements.txt
pip-sync extras/dev-requirements.txt
pip install -e .
```

When not installing dev dependencies, I'd do the same as the above except no `--extra` and just `pip install .`

The problem is that the next time I do `pip-sync`, my current package is uninstalled and I had to re-run `pip install -e .`
Maybe this is fine but I noted that there's zero mention of installing the current package or editable packages, in general, in the docs.

The broader context here is I'm creating my own cookiecutter template and whenever I instantiate my template, I am running certain tasks (such as setting up virtual env, freezing unversioned requirements and then installing them).

**Comment by adamcunnington-mlg** [comment]
One option I can think of it is to create:
`self.txt`
```
.
```

and `self-editable.txt`
```
-e .
```

and then when I run pip-sync to include the relevant file alongside my `requirements.txt` or `extras/dev-requirements.txt` files. E.g. `pip-sync requirements.txt self.txt`

**Comment by AndydeCleyre** [comment]
I think you're right, that you should avoid self-referencing in `pyproject.toml`, and that your answer will be some form of another requirements file. Within that, there are a lot of variations that may or may not suit your workflows.

For my own projects, I like to populate the `pyproject.toml` dependencies programmatically from the contents of `requirements.in` files, but I think that detail doesn't address your question.

So in a [recent project](https://github.com/AndydeCleyre/nestedtextto/blob/develop/local-requirements.txt), in addition to the locked `txt` files, I have a `local-requirements.txt`:

```ini
-e .[dev,toml]
-c dev-requirements.txt
-c nt2/requirements.txt
-c nt2/toml-requirements.txt
```

It requires the current project, in editable mode, with relevant extra groups, and is constrained by all the locked `txt`s.

**Comment by adamcunnington-mlg** [comment]
Nice pattern, thanks for sharing. I'll draw some inspiration from this.

Closing issue, thanks.
