### ISSUE TITLE
Is 22.0 possible?

### ISSUE THREAD

**Issue by daveisfera** [jazzband/pip-tools#1750]
The minimum version of `pip` was increased to 22.2, but is 22.0 possible? I ask because the [official image for Python 3.9 is using 22.0](https://github.com/docker-library/python/blob/7a895a185a2bc5ff7730ddf9804600c55ad691b9/3.9/slim-buster/Dockerfile#L121) and that prevents upgrading.

**Comment by atugushev** [comment]
See [versions and compatibility](https://github.com/jazzband/pip-tools#versions-and-compatibility).

**Comment by daveisfera** [comment]
Yes, I saw the version increase, but I'm asking if it's a hard requirement. I only see [1 case that mentioned 22.1](https://github.com/jazzband/pip-tools/pull/1729/files#diff-4b833620e477ab6401e3b2c03d4ca7e34202a151a3e709dc31f6e7c885bda25fL187) and could that one case be kept or something changed to allow support of 22.0?

**Comment by atugushev** [comment]
It's not hard to support pip-22.0 version per se. However, conventionally pip-tools supports only the last two major pip versions to reduce maintenance burden and CI time. We occasionally bump the minimum version of pip using this convention. If someone needs older pip versions they should use a [compatible](https://github.com/jazzband/pip-tools#versions-and-compatibility) pip-tools version.

**Comment by daveisfera** [comment]
I'm grateful for `pip-tools` and definitely understand that and if it's the way it has to be, then I'm ok with that, but if the supported versions of `pip` could align with the [life cycle of Python itself](https://devguide.python.org/versions/), then that would be great

**Comment by atugushev** [comment]
I'll close this based on the [above](https://github.com/jazzband/pip-tools/issues/1750#issuecomment-1334582716). Thanks for the understanding.
