### ISSUE TITLE
pip-compile shows the files were autogenerated with the wrong python version

### ISSUE THREAD

**Issue by mmerickel** [jazzband/pip-tools#1757]
#### Environment Versions

1. OS Type `macos 13.0.1`
1. Python version: `3.9.7`
1. pip version: `22.3.1`
1. pip-tools version: `6.11.0`

#### Steps to replicate

1. `$(pyenv --prefix 3.9.7)/bin/python3 -m venv env`
2. `source env/bin/activate`
3. `pip --install -U pip pip-tools`
4. `echo pyramid > foo.in`
5. `pip-compile foo.in`

#### Expected result

```
#
# This file is autogenerated by pip-compile with Python 3.9.7
# by the following command:
<snip>
```

#### Actual result

```
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
<snip>
```

**Comment by atugushev** [comment]
Not reproducible. Could you provide the following output on your local machine?
- `python -m pip --version`
- `python -m piptools compile`

**Comment by mmerickel** [comment]
well this is a fun situation:

```
(env) ❯ which pip
XXX/env/bin/pip
(env) ❯ pip --version
pip 22.3.1 from XXX/env/lib/python3.10/site-packages/pip (python 3.10)
(env) ❯ python -m pip --version
pip 22.3.1 from XXX/env/lib/python3.9/site-packages/pip (python 3.9)
```

I need to investigate further what's going on there.

Anyway I'm closing this for now until I unpack my environment. :-)
