### ISSUE TITLE
--Upgrade does not work if using a existing requirements.txt

### ISSUE THREAD

**Issue by NielsKorschinsky** [jazzband/pip-tools#1760]
Hello,

I am trying to upgrade my existing `requirements.txt` without using a `requirements.in` file.

My initial requirements file only had `requests` in it.
Then, a few weeks a go I run: 
`pip-compile -r --header --upgrade --allow-unsafe --resolver=backtracking --annotation-style line --no-emit-index-url ./requirements.txt`

When I re-run this command, including the `--upgrade` flag yesterday, I've had the issue that `certifi` is not upgraded to the latest version, even though I am using the upgrade flag.

Execute: `pip-compile -r --header --upgrade --allow-unsafe --resolver=backtracking --annotation-style line --no-emit-index-url ./requirements.txt`
```requirements.txt
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile --allow-unsafe --annotation-style=line --no-emit-index-url --resolver=backtracking ./requirements.txt
#
certifi==2022.9.24        # via -r ./requirements.txt, requests
charset-normalizer==2.1.1  # via -r ./requirements.txt, requests
idna==3.4                 # via -r ./requirements.txt, requests
requests==2.28.1          # via -r ./requirements.txt
urllib3==1.26.13          # via -r ./requirements.txt, requests
```

Then, I use a regex to remove the duplicate -r requirements notation and to softlock the requirements:
`sed -i '' "s/==/~=/" "./requirements.txt" && sed -i '' 's/ # via -r .\/requirements.txt, / # via /' "./requirements.txt"`

```requirements.txt
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile --allow-unsafe --annotation-style=line --no-emit-index-url --resolver=backtracking ./requirements.txt
#
certifi~=2022.9.24        # via requests
charset-normalizer~=2.1.1  # via requests
idna~=3.4                 # via requests
requests~=2.28.1          #  via -r ./requirements.txt
urllib3~=1.26.13          # via  requests

```

As you can see, certifi is still on the old version.

We do not want to include the requirements.in file as it is another overhead file and I see no sense in it if I already have the requirements.txt file.

#### Environment Versions

1. OS Type: Mac
1. Python version: Python 3.10.8
1. pip version: pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
1. pip-tools version: pip-compile, version 6.10.0

#### Steps to replicate

1. create a requirements.txt with pip-compile, having an outdated version
2. upgrade this requirements: `pip-compile -U --annotation-style line ./requirements.txt` 
3. The versions wont be upgraded

#### Expected result

The version lock is ignored due to the upgrade flag and the requirements are brought to the latest version

#### Actual result

The versions remain at the beginning version

**Comment by NielsKorschinsky** [comment]
or is this intended behavior?

**Comment by atugushev** [comment]
Pip-tools would not work properly with `requirements.txt` as input and output file at the same time. You'll end up with frozen requirements forever. Instead, put `requests` in `requirements.in` as a primary requirement and let `pip-compile` to resolve its dependencies into `requirements.txt` file, for example:

This is the input file `requirements.in`:
```
requests
```

This produces an output file `requirements.txt` (aka lock file):

```
$ pip-compile --header --upgrade --allow-unsafe --resolver=backtracking --annotation-style line --no-emit-index-url
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --allow-unsafe --annotation-style=line --no-emit-index-url --resolver=backtracking
#
certifi==2022.12.7        # via requests
charset-normalizer==2.1.1  # via requests
idna==3.4                 # via requests
requests==2.28.1          # via -r requirements.in
urllib3==1.26.13          # via requests
```

**Comment by atugushev** [comment]
Reported in #1762.
