### ISSUE TITLE
`pip-compile requirements.txt` compiles dependencies to the same input file

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1762]
It looks like pip-tools has a bug, when `reqs.txt` is passed as an input file then `pip-compile reqs.txt ` would resolve dependencies to the same input file. I remember we had a guard against this scenario, but apparently, we lost it somewhere in between new features.

_Originally posted by @atugushev in https://github.com/jazzband/pip-tools/issues/1760#issuecomment-1345420673_

#### Environment Versions

1. OS Type macOS
1. Python version: `3.11`
1. pip version: `22.3`
1. pip-tools version: `6.11.0`

#### Steps to replicate

1. `echo six > requirements.txt`
2. `pip-compile requirements.txt`
3. `ls requirements.*` 

#### Expected result

I would expect an error that `requirements.txt` is using as input and output file.

#### Actual result

```
$ ls requirements.*
requirements.txt
```

**Comment by AndydeCleyre** [comment]
In #1650 (rejected), in the case where the input file was the same as the derived output file, I added another `.txt` extension. The change is in [this commit](https://github.com/jazzband/pip-tools/pull/1650/commits/996f21c0f97cd69e8a5fd2d099c6d83fae1a6802), which also addresses the current dangerous behavior when the input file has no extension and a parent folder has a `.`.

```console
$ echo six > requirements.txt
$ pip-compile requirements.txt
$ ls requirements.*
```
```
requirements.txt  requirements.txt.txt
```

**Comment by AndydeCleyre** [comment]
It didn't seem useful to me to raise an exception. I often use pip-tools locally on projects that don't use it, so I like the ability to easily compile from a regular requirements.txt without bothering to specify an output name.

**Comment by AndydeCleyre** [comment]
Now that I read the source issue for this, and see how pip-tools was attempted to be applied, I am not necessarily opposed to requiring an output file be specified explicitly in this case, to protect users.
