### ISSUE TITLE
pip-compile generates empty requirements.txt

### ISSUE THREAD

**Issue by Burtannia** [jazzband/pip-tools#1796]
I'm trying to use `pip-compile` to generate `requirements.txt` from `pyproject.toml` but for some reason the output from `pip-compile` doesn't actually contain any dependencies.

#### Environment Versions

1. OS: macOS Ventura 13.1
1. Python version: 3.11.1
1. pip version: 22.3.1
1. pip-tools version: 6.12.1

#### Steps to replicate

1. Create a `pyproject.toml` file containing the following:
```
[build-system]
requires = ["setuptools<61"]

[project]
name = "python_101"
version = "1.0.0"
description = "Demo Python app"
dependencies = ["pydantic"]
```

Note that without the `setuptools` restriction I get the following error when running `pip-compile -v ...`:
```
Creating venv isolated environment...
Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
Getting build dependencies for wheel...
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse /Users/jburton/Projects/python_101/pyproject.toml
```

2. Run the following command:
`python -m piptools compile --resolver=backtracking --generate-hashes -o requirements.txt pyproject.toml`

#### Expected result

`requirements.txt` to be populated with dependencies.

#### Actual result

`requirements.txt` only contains:
```
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --generate-hashes --output-file=requirements.txt --resolver=backtracking pyproject.toml
#
```

**Comment by q0w** [comment]
Build produces metadata without Requires-Dist

**Comment by q0w** [comment]
Its because pep621 is supported for setuptools>61
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

**Comment by Burtannia** [comment]
@q0w Thanks for the quick response! As mentioned in "step 1", if I use `setuptools>61` or remove the restriction and allow the default to be used then I get the following error:
```
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse /Users/jburton/Projects/python_101/pyproject.toml
```

**Comment by q0w** [comment]
@Burtannia oh I see... Could you apply this patch https://github.com/jazzband/pip-tools/issues/1711#issuecomment-1328301486 and show the error

**Comment by Burtannia** [comment]
@q0w Aha! It seemed to be getting confused when finding the package directory. I had a top level directory called `proto` containing only a `.proto` file which seemed to be enough for it to not find the actual package directory. Upon adding the following to my `pyproject.toml` everything worked:
```
[tool.setuptools]
packages = ["python_101"]
```

I've made a PR to add some debugging tips and a note about `setuptools` to the README https://github.com/jazzband/pip-tools/pull/1797

Thanks for the help!
