### ISSUE TITLE
pip-compile does not pin git commit, pip freeze does

### ISSUE THREAD

**Issue by lorey** [jazzband/pip-tools#1801]
I'm installing a dependency directly from a git repo.
While `pip freeze` uses the used git commit's hash as expected and thus pins the dependency, `pip-compile` does not.

#### Environment Versions

1. OS Type: ubuntu (docker image python:3.11, python:3.11-slim)
1. Python version: 3.11.1
1. pip version: 22.3.1
1. pip-tools version: 6.12.1

#### Steps to replicate

Create a requirements.in file that contains
```
git+https://github.com/startupradar/transformers.git#egg=startupradar_transformers
# or
-e git+https://github.com/startupradar/transformers.git#egg=startupradar_transformers
```

#### Expected result
Pinned version by using the git commit of the installed repo.
Which is also the behavior of `pip freeze`:
```
startupradar-transformers @ git+https://github.com/startupradar/transformers.git@c00dc1925cdfc3bd64c7f8ecb3733b9b4bdbebc6
```

#### Actual result
After running `pip compile`, requirements.txt contains
```
startupradar_transformers @ git+https://github.com/startupradar/transformers.git
    # via -r requirements.in
# or 
-e git+https://github.com/startupradar/transformers.git#egg=startupradar_transformers
    # via -r requirements.in
```

Thanks for your great work everyone. Really appreciate the workflow that pip-compile enables. Any hint in the right direction would be highly appreciated.

**Comment by atugushev** [comment]
Duplicates #161.
