### ISSUE TITLE
Authentication details for private repo in requirements exposed by generated requirements file

### ISSUE THREAD

**Issue by marksweb** [jazzband/pip-tools#1812]
What I'm trying to do is migrate a project to use `pip-tools` but one of the packages in `requirements.txt` is in a private github repo so needs to include authentication. Currently this is done using environment variables to keep detail private.

This is similar to #966 however it's not a case of an environment variable for a path so there's no solution there.

For example;

```
django-redis==5.2.0
git+https://${PIP_AUTH_USER}:${PIP_AUTH_PASS}@github.com/my-org/django-package.git@v1.0#egg=django_package
djangorestframework==3.14.0
```

With this now part of `requirements.in`, the generated `requirements.txt` contains the actual values for the two environment variables.

I don't think there's a solution for this, but if anybody has any thoughts on something that might work, I'd love to hear them.

**Comment by atugushev** [comment]
-e ${MY_PROJECT_DIR}/myapp
-e git+https://${USER}:${PASSWD}@gitserver/myapp.git

**Comment by marksweb** [comment]
Ok, thanks @atugushev - I missed that.
