### ISSUE TITLE
[Question] Should `requirements.txt` be committed to a shared repository?

### ISSUE THREAD

**Issue by davidleejy** [jazzband/pip-tools#1838]
My understanding of `requirements.txt` is that it can vary from machine to machine despite the codebase having a single `requirements.in` due to differences in OS, hardware, drivers, etc. As such, would it be ok to, or even recommended to ignore `requirements.txt` in commits? 

I suppose for people using git, `requirements.txt` would be an entry in `.gitignore`?

So whenever a python environment is being set up on a machine, the user will run `pip-compile` followed by `pip-sync` instead of just `pip-sync` alone.

Thanks for reading and have a great day. 🙂

**Comment by webknjaz** [comment]
If you have multiple envs, generate the constraints in each and commit all of those files. Also, make sure to read the readme to the bottom.
