### ISSUE TITLE
Failed to parse pyproject.toml when I change its location

### ISSUE THREAD

**Issue by mpizenberg** [jazzband/pip-tools#1840]
`pip-compile` fails to parse my `pyproject.toml` when I change its location. The following `pyproject.toml` works fine with `pip-compile` when I’m in the `..../ids-peak-python/` directory, but when I create a new project at `..../controllable-leds/client/`, and I copy that same `pyproject.toml` there, `pip-compile` does not work anymore.

It’s really mysterious and I was hoping someone has a clue on what’s going on.

```
[project]
name = "ids-peak-python"
version = "0.1.0"
description = 'Example IDS camera usage in python'
readme = "README.md"
requires-python = "==3.10.*"

dependencies = [
  "wincertstore ; platform_system == 'Windows'"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

#### Environment Versions

1. OS Type: Windows
1. Python version: `$ python -V`: 3.10.10
1. pip version: `$ pip --version`: 23.0.1
1. pip-tools version: `$ pip-compile --version`: 6.12.3

#### Steps to replicate

1. copy the pyproject.toml in a new folder
2. run `pip-compile` in the folder

#### Expected result

It should resolve and generate the requirements file

#### Actual result

```
Installing packages in isolated environment... (hatchling)
Getting dependencies for wheel...
Getting metadata for wheel...
Backend subproccess exited when trying to invoke prepare_metadata_for_build_wheel
Failed to parse C:\Users\MatthieuPIZENBERG\git\controllable-leds\client\pyproject.toml
```

**Comment by AndydeCleyre** [comment]
Is there a `README.md` in the new folder as well?

**Comment by mpizenberg** [comment]
> Is there a README.md in the new folder as well?

That was it 🤦 

Thanks @AndydeCleyre ! I guess the error message could be improved

**Comment by AndydeCleyre** [comment]
Yes, definitely can be improved. I think we're waiting on new releases from other projects so that we can preserve clearer error messages. Some more info in #1711
