### ISSUE TITLE
The latest and the stable documentation may have been built using the development version

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1846]
Shouldn't be [there](https://pip-tools.readthedocs.io/) the latest released version?

<img width="788" alt="Screenshot 2023-04-07 at 01 17 17" src="https://user-images.githubusercontent.com/7377671/230510654-fd15e934-4243-4ee3-85c6-bb8d55e656d4.png">

**Comment by chrysle** [comment]
It is only the name that points to the development version.

See the [overview](https://readthedocs.org/projects/pip-tools/versions/):

A change that has been made in #1847 for example is contained in the `latest` version, but not `stable`. That still points to commit [f3fd37ba](https://github.com/jazzband/pip-tools/commit/f3fd37ba9b3123aa2215238004a8454173d2a362).

Trying to investigate why that is the case.

**Comment by webknjaz** [comment]
> Shouldn't be there the latest released version?

No, it should be the current commit. For the release, the URL should be stable. Also, there's specific tag URLs.
