### ISSUE TITLE
Preview docs?

### ISSUE THREAD

**Issue by chrysle** [jazzband/pip-tools#1869]
Is it possible to build and preview the docs using `tox` or another tool?

**Comment by webknjaz** [comment]
It should be. Try `tox -av` to see what are the envs there.. Ideally, building Sphinx docs should run in CI, so you could check out the invocations there...

**Comment by chrysle** [comment]
Thanks, `tox run -e build-docs` does the trick.

However, I'm missing a preview env with continuous docs build [like implemented](https://github.com/pypa/packaging.python.org/blob/main/noxfile.py#L63) in the python packaging guide.

They are using `nox`, but this should also be possible to do using `tox`?

**Comment by webknjaz** [comment]
I never implemented that, feel free to try adding it yourself.
