### ISSUE TITLE
Accepting version hints for pip compile.

### ISSUE THREAD

**Issue by shayanhoshyari** [jazzband/pip-tools#1878]
#### What's the problem this feature will solve?

I have various envs in my project

```
prod_env1.in.txt
prod_env2.in.txt
prod_env3.in.txt
...
dev.in.txt
```

The dev.in.txt has all my dependencies and used for development. Each `prod_...` env, however, has only a subset of dependencies; and is used in a deployed service. For fast deployment of service we want the env to be as minimal as possible, so each service only has the deps it needs.

For some of the dependencies, we want to force the same version across all the compiled envs. Imagine some of the envs (e.g. prod_env2.in.txt and prod_env3.in.txt) indirectly depend on `opencv-python`. To ensure that they install version `3.0.0` we have to put `opencv-python=3.0.0` in those files. Yet, we must not put it in other files as we don't want them to have opencv-python.

This is very error prone, because we don't know a-priori which envs might need `opencv-python` (it might be indirect dependency). 
  - If we add it to an env by mistake, we  have a problem. We get an unwanted package in env.
  - If we don't add it to env by mitake, we have a problem. We might get an unwanted version.

#### Describe the solution you'd like

The requested feature is to allow piptools  to read a set of version hints. E.g. 
```
pip-compile prod_env2.in.txt --hint opencv-python==3.2.0
```
or support reading a file with all the hints
```
pip-compile prod_env2.in.txt --hints hints.txt

# hints.txt:
opencv-python==3.2.0
```

This says that `if you encountered opencv-python in prod_env2.in.txt use version 3.2.0`. Then we can pass `--hints hints.txt` when compiling each requirement file, and it ensures they all have opencv version 3.2.0 iff they need opencv.

#### Alternative Solutions

N/A

#### Additional context

Mentioned in problem description.

**Comment by AndydeCleyre** [comment]
If I understand the needs here, you can currently either 

- put all your version hints in a text file, and in each requirements file add `-c hints.txt`; or
- pass each version hint on the command line with `-P`

**Comment by shayanhoshyari** [comment]
I cannot believe I did not know about `-c`. Thanks, that will do the job!
