### ISSUE TITLE
`pip-args` not supported when defined in `pyproject.toml`

### ISSUE THREAD

**Issue by brettcannon** [jazzband/pip-tools#1914]
Specifying `pip-args` in `[tool.pip-tools]` in `pyproject.toml` doesn't seem to cause it to be used by (at least) `pip-compile`.

Another way to solve this could be to document all the supported keys for `pyproject.toml` at https://pip-tools.readthedocs.io/en/latest/#configuration .

#### Environment Versions

1. OS Type
1. Python version: 3.8.17
1. pip version: 23.1.2
1. pip-tools version: 7.0.0

#### Steps to replicate

1. Add something for `pip-args` in `pyproject.toml`, e.g. `pip-args = "--only-binary :all:"`
2. Run `pip-compile`

#### Expected result

`--only-binary :all:` to end up in the `requirements.txt` file.

#### Actual result

Line doesn't end up in the resulting `requirements.txt` file.

**Comment by atugushev** [comment]
This is fixed in #1910.

**Comment by brettcannon** [comment]
Great! Did you want me to close this issue or did you want to leave it open?

**Comment by atugushev** [comment]
The fix release as part of pip-tools v7.1.0. Nonetheless, thanks for the issue!
