### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ikreb7** [jazzband/pip-tools#1923]
#### What's the problem this feature will solve?

In our company we have to use a proxy. So pip-compile doesn't get connection to pypi.org. ``pip`` has also the parameter ``--proxy``.

#### Describe the solution you'd like

Please add the parameter ``--proxy``, use the environment proxy variables or read the ``pip.conf``.

**Comment by atugushev** [comment]
Pip-compile has `--pip-args` option where you can pass additional parameters to pip, for example:

```console
$ pip-compile --pip-args "--proxy=..."
```

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!

**Comment by ikreb7** [comment]
Thank you very much!
