### ISSUE TITLE
pip-tools crashing while installing

### ISSUE THREAD

**Issue by iamMohamed** [jazzband/pip-tools#1925]
#### Environment Versions

1. python:3.9.13-alpine3.15

#### Steps to replicate

1. pip install "pip-tools<7.0"
3. ...
4. ...

#### Expected result
Successful installation

#### Actual result
Traceback (most recent call last):
40.35   File "/usr/local/bin/pip-sync", line 5, in <module>
40.35     from piptools.scripts.sync import cli
40.35   File "/usr/local/lib/python3.9/site-packages/piptools/scripts/sync.py", line 17, in <module>
40.35     from .. import sync
40.35   File "/usr/local/lib/python3.9/site-packages/piptools/sync.py", line 11, in <module>
40.35     from pip._internal.commands.freeze import DEV_PKGS
40.35 ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze' (/usr/local/lib/python3.9/site-packages/pip/_internal/commands/freeze.py)
------

**Comment by atugushev** [comment]
This has been fixed in pip-tools v7.0.0.
