### ISSUE TITLE
Non-unique heading anchors on pip-tools' changelog documentation

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1935]
#### What's the problem this feature will solve?

Currently, pip-tools generates non-unique anchors for links in the documentation, as seen for example here: https://pip-tools.readthedocs.io/en/latest/changelog/#id1. This will led to confusion with links for future versions deployed on RTD.

#### Describe the solution you'd like

Generate unique anchors, for example https://pip-tools.readthedocs.io/en/latest/changelog/#710-2023-07-18

#### Alternative Solutions

N/A

#### Additional context

- Example on GitHub: https://github.com/jazzband/pip-tools/blob/main/CHANGELOG.md#700-2023-07-14
- https://myst-parser.readthedocs.io/en/stable/syntax/optional.html#anchor-slug-structure

**Comment by chrysle** [comment]
Related: sphinx-doc/sphinx#4814

**Comment by atugushev** [comment]
Fixed in #1942 using [sphinx.transform](https://www.sphinx-doc.org/en/master/_modules/sphinx/transforms.html).
