### ISSUE TITLE
pip-compile doesn't pin editables

### ISSUE THREAD

**Issue by gavinwahl** [jazzband/pip-tools#194]
I want to use requirements like this in my requirements.in:

```
-e git+git@github.com:fusionbox/django-widgy@master#egg=django-widgy
```

And expect `master` to get replaced with the actual latest commit in master:

```
-e git+git@github.com:fusionbox/django-widgy@23dbde9746#egg=django-widgy
```

Otherwise requirements.txt isn't actually reproducible.

**Comment by blueyed** [comment]
Should work in https://github.com/nvie/pip-tools/pull/169 IIRC.

**Comment by ariscn** [comment]
Bump, would love to see this functionality.

**Comment by blueyed** [comment]
pip-sync != pip-compile.

Apart from that, https://github.com/nvie/pip-tools/pull/169 has been closed without being merged (at least for now).

**Comment by danni** [comment]
This feature would be super useful when building with Docker also because if the commit hash doesn't change then the Python requirements cached layer won't invalidate.

**Comment by vphilippon** [comment]
See #161
