### ISSUE TITLE
Installation of the dependencies from pre-generated wheels

### ISSUE THREAD

**Issue by sla-te** [jazzband/pip-tools#1965]
Using the following code I am trying to achieve the following:

1. Download all my projects dependencies as `.whl` files via `mkdir wheelhouse && python -m pip download -r requirements.txt -d wheelhouse` 
2. On the target server, download the previously generated `.whl` files via `python -m pip install --no-index --find-links=wheelhouse -r requirements.txt`

Result:
`ERROR: Could not find a version that satisfies the requirement somepackage==1.2.3 (from versions: none)`

Im not sure  what is going wrong here but I could imagine using this approach might require some different handling when using a pip-compile generated requirements.txt?

Note: I am deploying a REST API backend and the idea is to have a GHA build the package, including its dependencies and make the artifacts available for the production server to install them. - I take it you guys must be experts when it comes to best-practises for deployment in such a scenario, so I am open to any alternative approaches you might want to suggest.

Thanks in advance for any input!

**Comment by webknjaz** [comment]
AFAIK, `pip download` only gets wheels. If there's any packages that only ship sdists, it won't get them. You could try `--prefer-binary` but if it works, it may get older versions of stuff.
