### ISSUE TITLE
Expose option to use relative paths when converting -e modules from .in to .txt

### ISSUE THREAD

**Issue by theahura** [jazzband/pip-tools#1968]
#### What's the problem this feature will solve?

My requirements.in file has an editable install, `-e ../../foo/bar`. When this gets converted to requirements.txt with piptools, it turns into `-e file:///home/theahura/path/to/foo/bar`. 

The issue is that if anyone else on my team wants to use this requirements.txt, it will break; and if they recompile, the requirements.txt gets an unnecessary update.

#### Describe the solution you'd like

Turns out that relative path editable installs work just fine in a requirements.txt. It's possible to just have `-e ../../foo/bar` in the requirements.txt AND the requirements.in. So one option would be:

`pip-compile requirements.in --relative_editable_installs=true`

which would output the relative path to `requirements.txt` instead of the absolute one.

#### Alternative Solutions

Currently I hardcode any relative editable paths in my requirements.txt, which works fine from a pip-install perspective. Unfortunately, pip-tools will then go and update it _back_ to the absolute path whenever a recompile occurs

**Comment by atugushev** [comment]
Does `-e file:../../foo/bar` work for you?

**Comment by theahura** [comment]
fantastic! that works great, thank you for the quick turnaround!
