### ISSUE TITLE
Specifying source files in pyproject.toml leads to only pyproject.toml being used

### ISSUE THREAD

**Issue by csalerno-asml** [jazzband/pip-tools#2006]
Hi,
I am using `pip-compile==7.3.0`, and trying to specify multiple source files within the `pyproject.toml` file with the keyword `src-files`.

My desired outcome would be to specify `pyproject.toml` and `requirements.hotfix.txt`, so that the list of dependencies can be used together.
However, I noticed that it's like these files - and the whole input in general - are ignored, because then the tool only use the dependencies specified in `pyproject.toml`.

I also tried to do something like these (see picture), but I ended up with again `pyproject.toml` being used.
![image](https://github.com/jazzband/pip-tools/assets/119511125/70ff88e3-5327-49b9-8aa6-ea14b0b98a0d)

I know that the tool is reading the config, since the other options are used, and if I specify a non-existing file I get an error message
![image](https://github.com/jazzband/pip-tools/assets/119511125/04248abe-62f5-48d4-9182-57954ab56f77)

Is this a known bug? Should I change something on my end?

#### Environment Versions

1. OS Type: RHEL7
1. Python version: 3.10.5
1. pip version: 23.3
1. pip-tools version: 7.3.0

#### Steps to replicate

1. specify dependencies in `pyproject.toml` and `file.txt`
2. specify `tools.pip-tools` / `src_files = ["pyproject.toml", "file.txt"`
3. check if dependencies specified in `file.txt` are picked up and translated in requirements.txt

#### Expected result

Dependencies specified in both files are translated in `requirements.txt`

#### Actual result

Only dependencies specified in `pyproject.toml` are picked up

**Comment by csalerno-asml** [comment]
To add on this, if I run `pip-compile pyproject.toml file.txt`, I get the expected result

**Comment by webknjaz** [comment]
A full repro would be helpful.

**Comment by csalerno-asml** [comment]
To add on this, the `src-files` option in `pyproject.toml` is used, and all the paths specified there are checked, i.e., an error will raise if you put a `non-existing-file` inside.

My concern is, then: maybe the code is missing the logic to handle `src-files` when specified from a config, rather than CLI usage?

**Comment by atugushev** [comment]
I believe we should first incorporate this PR https://github.com/jazzband/pip-tools/pull/1966 which will allow us to separately specify inputs and outputs for the `compile` and `sync` commands.

**Comment by chrysle** [comment]
Actually, I found out what exactly causes this: According to pallets/click#390, default values won't work on arguments with unlimited length. So I think the proposed fix is the only solution.
