### ISSUE TITLE
Transitive dependency defined with ~= won't generate the latest dependency 

### ISSUE THREAD

**Issue by jonathan-s** [jazzband/pip-tools#2016]
If you have a dependency that has it's own dependency and that child dependency is defined with `~=` pip-compile won't pick the latest allowable version when you compile the requirements.txt.  

#### Environment Versions

1. MacOS
2. 3.8.16
3. 7.3.0

#### Steps to replicate
Your project defines dependency A. 

Depedency A defines Dependency B like this. 

```
dependency-b~=0.0.1
```

dependency-b has a later version 0.0.23, using `~=` it should install 0.0.23 as that is allowed, thus I would expect pip-compile to generate `dependency-b==0.0.23` in the output. 

#### Expected result
See above

#### Actual result
See above

**Comment by webknjaz** [comment]
There may be other constraints that lead to this in your deptree. Without a reproducer, there's nothing to discuss, really.
We can only tell fortune 🔮 by reading logs and STR 🤷‍♂️

**Comment by webknjaz** [comment]
A PR with a regression test is welcome — that would clearly document the expectations.

**Comment by jonathan-s** [comment]
@webknjaz May I ask where at what test suite I should start looking at? Is it `test_resolver.py`, or somewhere else?

**Comment by chrysle** [comment]
> Is it `test_resolver.py`

Yes, you can take https://github.com/jazzband/pip-tools/blob/f20d6ae0af45cfeb54e69d7ead9a9d09449b8d5c/tests/test_resolver.py#L448 as a reference.

**Comment by jonathan-s** [comment]
Thanks for your help. I'm unable to replicate this in tests (it appears everything is working correctly even with Pypi repository). So I'm closing this issue.
