### ISSUE TITLE
Bug: presence of `PIP_EXTRA_INDEX_URL` breaks tens of tests

### ISSUE THREAD

**Issue by jamesbraza** [jazzband/pip-tools#2023]
#### Environment Versions

1. OS Type: macOS Ventura v13.5.2
1. Python version: `$ python -V` 3.8.16
1. pip version: `$ pip --version` 23.3.1
1. pip-tools version: `$ pip-compile --version` https://github.com/jazzband/pip-tools/tree/f20d6ae0af45cfeb54e69d7ead9a9d09449b8d5c

#### Steps to replicate

```bash
export PIP_EXTRA_INDEX_URL=https://user:123@pypi.fury.io/name/
pytest
```

#### Expected result

Tests to pass, regardless of `PIP_EXTRA_INDEX_URL` being set (in my `~/.zshrc`) or not

#### Actual result

Many tests fail due to the extra index URL being set

**Comment by WhyNotHugo** [comment]
Running with `tox` should prevent exactly this.

I don't think that it is realistic to support running tests with any mix of environment variables.

**Comment by jamesbraza** [comment]
Oh I see the `tox.ini` here, I didn't observe that earlier. Yeah `tox` is a viable solution, so feel free to close this out.

> I don't think that it is realistic to support running tests with any mix of environment variables.

Fwiw, I was not posing _any_ mix, really it's just one: `PIP_EXTRA_INDEX_URL`. But I know what you mean.

An alternate solution could be:

- Designing tests to account for possibility of `PIP_EXTRA_INDEX_URL` already in env
- Using something like `pytest-env` to globally set this environment variable 
    - I guess `tox` is doing something similar

**Comment by chrysle** [comment]
I agree with @WhyNotHugo.
