### ISSUE TITLE
Pip-tools optimizer for lib versions

### ISSUE THREAD

**Issue by ManPython** [jazzband/pip-tools#2030]
#### What's the problem this feature will solve?

Find right libs version to create right requirements.txt from conditions < > =< => etc

#### Describe the solution you'd like
Something like this: (https://github.com/pypa/pip/issues/12427) Update optimizer for lib versions and backuper for optimal and last working requirements

#### Alternative Solutions

Cooperate with PIP around optimal versions for requirements.txt 

#### Additional context

[](https://github.com/jupyter/notebook/issues/7177)

**Comment by webknjaz** [comment]
It's already possible with Pip's constraint files periodically regenerated by pip-tools and updated via PR where it's visible that the tests pass.

**Comment by webknjaz** [comment]
> Soo.. what I should do when I broken whole jupyter after update?

You can't do anything unless you have a constraint file with the exact pins upfront.

You have to set up and maintain a constraints file, only updating it with testing. Once you have it, you can recreate your env from scratch.

- https://pip.pypa.io/en/stable/user_guide/#constraints-files
- https://pip-tools.rtfd.io/en/latest/#pip-tools-pip-compile-pip-sync

You can either combine these two or opt to use an entirely separate set of tools that manage venvs.

I made a note the other day, regarding some conceptions I wish people understood better: https://github.com/jazzband/pip-tools/issues/1326#issuecomment-1834517252.

**Comment by webknjaz** [comment]
I think the currently talked through proposal to standardize lockfiles on discuss.python.org will solve your concerns but there's nothing to be done in pip-tools.

**Comment by ManPython** [comment]
Can you refer right discuss link? This?
https://discuss.python.org/t/lock-files-again-but-this-time-w-sdists/46593/9
https://discuss.python.org/t/lockfile-implementation-in-the-standard-library-ipc-lockfile-not-packaging/44896

**Comment by webknjaz** [comment]
Yes
