### ISSUE TITLE
Add `--proxy` flag to `pip-sync` command to support the same functionality as `pip install --proxy`

### ISSUE THREAD

**Issue by tomdaley92** [jazzband/pip-tools#2033]
#### What's the problem this feature will solve?

Use a on-prem pypi cache/proxy with pip-sync command

#### Describe the solution you'd like

Add the flag `--proxy` to the `pip-sync` command to behave the exact same way as  `pip install --proxy https://some-proxy`. I figured since pip-sync let's you add trusted hosts etc. etc. it would be in this step, rather than the `pip-compile` step. Thoughts?

#### Alternative Solutions

Use the native way of installed to venv via pip. e.g. `pip install --proxy https://some-pypi-cache --requirement requirements.txt`.

Not sure if behaviour is the same of not but you could also just use the flag `--index-url` with `pip-sync` instead?

#### Additional context

Is this out of scope for intended functionality of  the `pip-tools` project?  It would be nice if `pip-sync` just wrapped (fell back to) most of the common functionality of pip if it does not need to be implemented any differently.

**Comment by AndydeCleyre** [comment]
Just checking:

Can this not be done with `--pip-args` already?

**Comment by tomdaley92** [comment]
@AndydeCleyre It probably can.. Thank you ☺️ . I guess I didn't read through the help text carefully enough.

**Comment by webknjaz** [comment]
Closing per above.
