### ISSUE TITLE
Readthedocs website should point to "stable" release by default

### ISSUE THREAD

**Issue by not7cd** [jazzband/pip-tools#2049]
As of now, https://pip-tools.readthedocs.io or https://pip-tools.rtfd.io redirects to documentation for v7.3.1.dev85, which is the latest release.
It might be confusing at first. The default should be changed to "stable".

**Comment by chrysle** [comment]
Thanks, I agree setting that as the default version would be helpful.

I'm not a maintainer on RTD, so @webknjaz could you take a look? This should be configurable under the [advanced settings](https://docs.readthedocs.io/en/stable/tutorial/index.html#creating-a-new-version). Thank you!
