### ISSUE TITLE
Allowing pre-release for only one package

### ISSUE THREAD

**Issue by AntoineD** [jazzband/pip-tools#2059]
Consider a package A that depends on package B, I want the develop branch of the package A to be tested against the develop branch of the package B.
Following #1920, the workaround I found to create a lock file is to host the development version of package B on a dedicated package index then pass this extra index and the flag `--pre` to `pip-compile`.

But this allows pre-release versions for any packages instead of only allowing it for package B.

How could this be achieved?

**Comment by chrysle** [comment]
Have you also considered pinning the pre-release version of package B in `requirements.in`? Apart from that, pre-release settings are only considered globally by `pip` in lockfiles.

**Comment by AntoineD** [comment]
It works fine, thank you all.
