### ISSUE TITLE
flag in COMPILE_EXCLUDE_OPTIONS showing up in header

### ISSUE THREAD

**Issue by mjsir911** [jazzband/pip-tools#2065]
#### Environment Versions

1. OS Type
  Windows mingw
1. Python version: `$ python -V`
  Python 3.11.8
1. pip version: `$ pip --version`
  pip 24.0
1. pip-tools version: `$ pip-compile --version`
  pip-compile, version 7.4.1.dev14 (`main` as of 03/04/2024)

#### Steps to replicate

1. `pip-compile --no-reuse-hashes -o requirements.txt`

#### Expected result

`--no-reuse-hashes` doesn't show up in the generated header comment.

#### Actual result

```
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --generate-hashes --index-url=.. --no-reuse-hashes --output-file=requirements.txt --strip-extras --trusted-host=..
#
```

**Comment by chrysle** [comment]
I think we should allow users to customise `COMPILE_EXCLUDE_OPTIONS` by exposing it as an environment variable. Could I have your opinion on that, @webknjaz?
