### ISSUE TITLE
[TODO][CI][pip upstream changes] Fix failing nightlies running against `pip`'s `main` branch

### ISSUE THREAD

**Issue by webknjaz** [jazzband/pip-tools#2078]
Failure example: https://github.com/jazzband/pip-tools/actions/runs/8794562108/job/24134206791

**Comment by hugovk** [comment]
A new pip 24.1 release is due out any day now. 

https://github.com/pypa/pip/issues/12613

**Comment by hugovk** [comment]
Last pass: https://github.com/jazzband/pip-tools/actions/runs/8716054525 Wed, 17 Apr 2024 03:54:40 GMT

First fail: https://github.com/jazzband/pip-tools/actions/runs/8732146094 Thu 18 Apr 2024 03:55:04 GMT

https://github.com/pypa/pip/commit/4d09e3c004857b3ba766cb93cdea8e1fc3c3c677 (https://github.com/pypa/pip/pull/12571) looks the most likely from a quick check of the commits from this window.

**Comment by webknjaz** [comment]
Thanks for taking time to look into this!

**Comment by chrysle** [comment]
This seems to be the faulty line:

https://github.com/jazzband/pip-tools/blob/b692edb31c548e2cc23d19ae3bf3732d729df089/piptools/exceptions.py#L30

We already had a similar case in #570.
