### ISSUE TITLE
Typo error on readme

### ISSUE THREAD

**Issue by Saifeddine75** [jazzband/pip-tools#2120]
There is likely a typing error in readme file. 

This seems like a typing error:
`pip-compile - --output-file=- < requirements.in > requirements.txt`

Im not sure but maybe It should be:
`pip-compile --output-file= requirements.in > requirements.txt`

**Comment by chrysle** [comment]
No, this seems correct; the first `-` instructs `pip-compile` to read from standard input, and the `<` redirects the contents of `requirements.in` to standard input, while per the second dash the results are being written to the standard output, which in turn is redirected to `requirements.txt` (via the `>`).

**Comment by WhyNotHugo** [comment]
@Saifeddine75 `-` is commonly used by applications as an alias for `stdin`

**Comment by Saifeddine75** [comment]
Oh okay thank you very much, was just getting error with this command in powershell but I guess it is not compatible with windows shells.
