### ISSUE TITLE
broken precommit ci builds.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [jazzband/pip-tools#2133]
While working on the PR #2132 , I've noticed precommit is broken as it can't able to build.

#### Environment Versions

1. OS Type
1. Python version: `$ python -V`
1. pip version: `$ pip --version`
1. pip-tools version: `$ pip-compile --version`

#### Steps to replicate

1. ... Open a PR.
2. ... Wait for pre-commit ci to run
3. ... Analyze the logs

#### Expected result

Pre-commit ci to Run.

#### Actual result

https://results.pre-commit.ci/run/github/5746963/1730664892.Ada_O1p_QdCVeGicV9Y4lQ

...

**Comment by webknjaz** [comment]
The CI is green now.
