### ISSUE TITLE
Recommend using `.txt` and `.lock` instead of `.in` and `.txt`

### ISSUE THREAD

**Issue by daveisfera** [jazzband/pip-tools#2136]
#### What's the problem this feature will solve?

The current recommendation of using `.in` as the input and then `.txt` as the output, means that the file that all of the existing tools view is the full list of installed packages with specific versions (and potentially hashes), so it's hard to review/audit and is a long detailed list that may contain a lot of packages that the developers aren't aware of because they aren't using them directly.

#### Describe the solution you'd like

Recommend that `.txt` is the input and `.lock` is the output, so the existing uses of `requirements.txt` can be maintained as a short list that's easy to review/audit.

(this is creating a use case like `package.json` and `yarn.lock` or `package-lock.json` in the `node` ecosystem)

#### Alternative Solutions

N/A

#### Additional context

[PyCharm and the IntelliJ IDEs can't handle the files generated by `pip-compile`](https://youtrack.jetbrains.com/issue/PY-27874) so this solution also has the benefit of working around this bug and any others that may crop up from `requirements.txt` being more detailed/specific than may be expected.

**Comment by WhyNotHugo** [comment]
> the file that all of the existing tools view is the full list of installed packages with specific versions (and potentially hashes)

That's the whole point: tools which prepare or analyse an environment should use the long list with the exact versions.

If they used `requirements.in`, the environment that they produce would not be deterministic and will quite frequently have the wrong dependency versions.

> [PyCharm and the IntelliJ IDEs can't handle the files generated by pip-compile](https://youtrack.jetbrains.com/issue/PY-27874) so this solution also has the benefit of working around this bug and any others that may crop up from requirements.txt being more detailed/specific than may be expected.

This would just replace one problem with another. If you supply the input file to PyCharm, then the environment which it creates won't have the right dependency versions.

Keep in mind that failing to parse requirement files with hashes is a security issue. Checking the hashes is what guarantees that you're fetching the exact same package as intended. If you are forced to remove hashes, then there's no way to ensure that you ve downloaded the right packages.

**Comment by daveisfera** [comment]
Definitely understand that. I'll follow up on the PyCharm/IntelliJ bug so it can be used in accordance with this.

**Comment by webknjaz** [comment]
> The current recommendation of using .in as the input and then .txt as the output, means that the file that all of the existing tools view is the full list of installed packages with specific versions

I'd also like to add that the existing tools (like Dependabot) specifically recognize pip-tools maintained file pairs using this convention that's in place. So changing that would actually be breaking the ecosystem.
