### ISSUE TITLE
What method is used for dependency resolution?

### ISSUE THREAD

**Issue by piotr-dobrogost** [jazzband/pip-tools#218]
I couldn't find any information on what method is used for dependency resolution. I'm interested in this to know if pip-tools could be used to workaround lack of dependency resolution in pip – https://github.com/pypa/pip/issues/988

**Comment by vphilippon** [comment]
This is from a long time ago, but still. I recently made a comment covering an issue in pipenv.
That comment a some information how the dependency resolution is done.

https://github.com/kennethreitz/pipenv/issues/875#issuecomment-337717817

**Comment by atugushev** [comment]
It's been some time, so I'll close this issue now. I hope the above helped.
