### ISSUE TITLE
Error in test_cli.py: "Click will abort further execution..."

### ISSUE THREAD

**Issue by paulkernfeld** [jazzband/pip-tools#219]
I'm seeing the following error:

```
RuntimeError: Click will abort further execution because Python 3 was
  configured to use ASCII as encoding for the environment. Either switch
  to Python 2 or consult http://click.pocoo.org/python3/ for
  mitigation steps.
```

More info on this error is [here](http://click.pocoo.org/5/python3/#python-3-surrogate-handling) on the Click site.

I believe that this error may be related to tox 2.x (I'm using 2.1.1), which does not automatically pass environment variables through into virtualenvs. I'm on OSX Yosemite. This problem occurs with both Python 3.4 and Python 3.5 (Python 2 seems fine).

I had thought that this would be fixable by setting LC_ALL and LANG (as suggested in the link above) and passing them through, but I still saw the same error. Possibly I was just passing them through wrong.

**Comment by davidovich** [comment]
Is this still happening ?

**Comment by paulkernfeld** [comment]
I don't have access to the machine that I used when I originally reported this issue, but when I run `tox` on my new machine I no longer see this error.

**Comment by davidovich** [comment]
Thank you, I will now close, don't hesitate to open if it happens again!
