### ISSUE TITLE
via not shown for packages installed from VCS

### ISSUE THREAD

**Issue by cancan101** [jazzband/pip-tools#293]
my `requirements.in` file has:

```
-e git+https://github.com/scikit-image/scikit-image.git@33646e0#egg=scikit-image==0.12.git
```

but the `.txt` just shows:

```
dask[array]==0.7.6
```

without showing the `via`. This even though I gave the package a name with the `egg=`.

**Comment by vphilippon** [comment]
FTR, I stumble on the cause of this in the code: The editable dependencies are never added to the dependency cache (which is ok, editable packages requirements are likely to change for a same version), and the OutputWriter uses the reversed dependency cache to generate the "via" comments.

**Comment by suutari-ai** [comment]
This probably isn't directly usable in pip-tools, but if it's any help here's how I implemented this feature on Prequ: https://github.com/suutari/prequ/commit/634ef5c5daae3eb1911da2b482a766667d8d6364

**Comment by richafrank** [comment]
@vphilippon I'd love to see this enhancement. If I submit a PR using the design from [above](https://github.com/suutari/prequ/commit/634ef5c5daae3eb1911da2b482a766667d8d6364), would that be welcome, i.e. filtering out editable dependencies at persistence time? Another idea is to maintain a separate in-memory-only cache for editables.
