### ISSUE TITLE
subprocess.CalledProcessError: Cannot uninstall requirement argparse, not installed

### ISSUE THREAD

**Issue by peramsathyam** [jazzband/pip-tools#308]
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', 'argparse', 'astroid', 'autopep8', 'flake8', 'lazy-object-proxy', 'logilab-common', 'mccabe', 'mercurial', 'pbr', 'pep257', 'pep8', 'pyflakes', 'pylama', 'pylama-pylint', 'pylint', 'python', 'stevedore', 'virtualenv', 'virtualenv-clone', 'virtualenvwrapper', 'wrapt', 'wsgiref']' returned non-zero exit status 1

**Comment by nvie** [comment]
What happens if you manually run this command?

**Comment by peramsathyam** [comment]
@nvie : https://github.com/nvie/pip-tools/blob/f7b5f0183c6aeacf119cec172fe9ad6cbad26512/piptools/sync.py#L131
May be here you have to check :) 

Running `pip uninstall -y argparse` result in 
`Cannot uninstall requirement argparse, not installed`

**Comment by alexwforsythe** [comment]
How did you cause the error? Do you get it when calling `pip-sync` inside of a virtualenv?

**Comment by nvie** [comment]
Can you specify the contents of your *.in file here?

**Comment by piotr-dobrogost** [comment]
I don't know what method pip-tools uses to find out what's installed but in case it uses pip you may be interested to know that `argparse` (and a few others libs) are special cased in pip. See https://github.com/pypa/pip/issues/1570 and https://github.com/pypa/pip/issues/3132

**Comment by allanlewis** [comment]
I think this might be related to #328.

**Comment by davidovich** [comment]
Is this still happening with newer pip-tools?

**Comment by vphilippon** [comment]
Closing this, a lot has changed. Comment if this is still an issue.
