### ISSUE TITLE
--process-dependency-links is not respected in in-files

### ISSUE THREAD

**Issue by cancan101** [jazzband/pip-tools#310]
If I specify a dependency in the requirements.in file with `--process-dependency-links`, pip-compile does not respect the flag yielding:

```
Could not find a version that matches ...
```

if the `dependency-links` is needed.

**Comment by cancan101** [comment]
Further `--process-dependency-links` does not get passed through from the in file to the txt file.

**Comment by nvie** [comment]
I'm not sure if I follow. Can you explain what you expect and what the actual result is?

**Comment by cancan101** [comment]
pip 8 allows specifying `--process-dependency-links` in the requirements file which then means that pip will use the `dependency-links` section in `setup.py` to satisfy requirements. pip-tools does not consider the `dependency-links` section even tho I have set  `--process-dependency-links` in my requirements.in file.

**Comment by Daenyth** [comment]
This applies to setup.py files as well - I have dependency links in my setup.py and pip-compile is saying it can't find a package.

**Comment by ivan-latka-exponea** [comment]
Any progress or alternative solution?

**Comment by atugushev** [comment]
I'll close this since `--process-dependency-links` option has been removed from `pip==19.0`.
