### ISSUE TITLE
Running without --update duplicates --extra-index-url lines

### ISSUE THREAD

**Issue by Chronial** [jazzband/pip-tools#316]
If there is an --extra-index-url line at the beginning of the `requirements.in`, it will be duplicated in the `requirements.txt` on each run of `pip-compile` without the `--update` switch.

**Comment by jbbarth** [comment]
Confirmed here. It was not the case in pip-tools 1.4.4, but I see this now with pip-tools 1.6. In my case the "--extra-index" option sits in `~/.pip/pip.conf` for what is worth, so not specific to the `requirements.in` parsing.

For what is worth everything still works normally despite of this bug, so not a blocker.

**Comment by nvie** [comment]
Can you give an example *.in file that does not have the problem and one that does? Thanks!

**Comment by Chronial** [comment]
It's as simple as it sounds: 
**Good**

```
chardet
```

**Bad**
```
--extra-index-url https://pypi.python.org
chardet
```

**Comment by hugoboos** [comment]
Same here, with version 1.6

I have one `--extra-index-url <url>` line at the top of my `requirements.in`. On every run of `pip-compile` the same `--extra-index-url <url>` is added to `requirements.txt`.

**Comment by yakky** [comment]
Confirmed here
Maybe just extract index_urls from finder beyond this point https://github.com/nvie/pip-tools/blob/master/piptools/scripts/compile.py#L132 ?
Tested with pip >= 7
@nvie I can work a on PR if a solution is agreed

**Comment by mchristopher** [comment]
@yakky @nvie any update on this? I'm running into this problem as well.

**Comment by anthrotype** [comment]
I have the same issue with --extra-index-url occurring multiple times, when I include a pip-compile-generated requirements.txt inside my requirements.in file, e.g. by adding `-r some_requirements.txt` at the top of it.

**Comment by davidovich** [comment]
Closed by #468
