### ISSUE TITLE
Pass additional arguments to pip

### ISSUE THREAD

**Issue by 31z4** [jazzband/pip-tools#321]
It would be nice to have an ability to pass some non harmful additional arguments to `pip` during `pip-sync`. E. g. `--no-cache-dir` or `--cache-dir <dir>`.

**Comment by estan** [comment]
I would like to be able to pass `--upgrade` to `pip` when doing `pip-sync`, the reason is I'm unfortunately required to use `--system-site-packages` on my virtualenv, to get access to the distro installed PyQt (which is not on PyPI yet, so not in `requirements.txt`), but I still want `pip-sync` to install as much as possible into the virtualenv (and not skip stuff that is already satisfied by the system-wide `site-packages`).

**Comment by estan** [comment]
Just want to check, is there still no way to do this?

**Comment by tkwon** [comment]
+1 on adding options like --no-cache-dir

**Comment by merwok** [comment]
A nice interface for this could be the command-line end marker: `pip-sync requirements.txt -- --pip-option-1 --pip-option-2=no`

**Comment by atugushev** [comment]
That's a great idea! How to handle `--` using click API? I skimmed docs and code and didn't find the solution.

**Comment by aorumbayev** [comment]
@atugushev any updates on this issue ?

**Comment by atugushev** [comment]
Hello @aorumbayev,

Unfortunately, there are no updates. It's still not clear how to pass the additional arguments.

**Comment by atugushev** [comment]
@merwok 

> A nice interface for this could be the command-line end marker: `pip-sync requirements.txt -- --pip-option-1 --pip-option-2=no`

What if we need to process files containing double-dash? For example:

```console
$ touch -- --requirements--.in
$ pip-compile -- --requirements--.in
```

**Comment by merwok** [comment]
@atugushev Not sure I get your question.  Recognizing a single token with the exact value of `--` shouldn’t interfere with other params containing two dashes.

**Comment by atugushev** [comment]
@merwok 

> Not sure I get your question. Recognizing a single token with the exact value of `--` shouldn’t interfere with other params containing two dashes.

I mean how to distinguish filenames and options after `--`? For instance:

```console
$ pip-compile -- --requirements--.in --no-cache-dir
```

**Comment by merwok** [comment]
That wouldn’t be valid.  `--` means «end of processing, so all parameters for pip-compile mist appear before it:

```
$ pip-compile --some-opt file1.in --more-opt file2--weird.in -- --pip-option1 --pip-option2 arg --pip-option3
```

**Comment by atugushev** [comment]
@tkwon 

> That wouldn’t be valid. `--` means «end of processing, so all parameters for pip-compile mist appear before it:

AFAIK, the `--` marks that all further parameters are accepted as arguments. This is how it currently works:
```console
$ echo six > --requirements.in

$ ls 
--requirements.in

$ pip-compile -- --requirements.in
six==1.13.0

$ ls
--requirements.in  --requirements.txt
```

**Comment by merwok** [comment]
Yes, this would involve changing the meaning of the token.
Are there really many people who decide to use filenames starting with two dashes?  That’s asking for trouble IMO.  But even so, there is still a way to disambiguate: `./--filename` is a path!

**Comment by atugushev** [comment]
@merwok 

> Are there really many people who decide to use filenames starting with two dashes? 

I think it's close to zero. Anyways, I'm in favor to change the meaning of the marker, but, honestly, have no idea how to do it using click API.

**Comment by merwok** [comment]
Seems like click automatically accepts `--`: https://click.palletsprojects.com/en/7.x/arguments/#option-like-arguments

I’ve also found this which may be of interest: https://click.palletsprojects.com/en/7.x/advanced/#forwarding-unknown-options

**Comment by AndydeCleyre** [comment]
Another thought on the interpretation of `--`.

I'm a big fan of [plumbum](https://github.com/tomerfiliba/plumbum), so checked what happens there, and it's this:

- first occurrence of an island `--` is removed and the following args are args, not options.
- subsequent island `--`s are args themselves

I haven't looked closely at click to compare.

`dashes.py`:
```python
#!/usr/bin/env python3
from plumbum import cli


class Dashes(cli.Application):

    nopanic = cli.Flag('--no-panic')

    def main(self, *args):
        if self.nopanic:
            print("Don't Panic")
        print('args:', args)


if __name__ == '__main__':
    Dashes()
```

```console
$ ./dashes.py
args: ()
$ ./dashes.py --no-panic
Don't Panic
args: ()
$ ./dashes.py --no-panic --
Don't Panic
args: ()
$ ./dashes.py -- --no-panic
args: ('--no-panic',)
$ ./dashes.py --uglyfile
Error: Unknown switch --uglyfile
$ ./dashes.py -- --uglyfile
args: ('--uglyfile',)
$ ./dashes.py -- --uglyfile --no-panic
args: ('--uglyfile', '--no-panic')
$ ./dashes.py --no-panic -- --uglyfile -- --elsewhere-bound
Don't Panic
args: ('--uglyfile', '--', '--elsewhere-bound')
$ ./dashes.py -- --for-here
args: ('--for-here',)
$ ./dashes.py -- -- --elsewhere-bound
args: ('--', '--elsewhere-bound')
```

**Comment by AndydeCleyre** [comment]
So [here's a simple way](https://github.com/jazzband/pip-tools/compare/master...AndydeCleyre:bugfix/321) to get this working.

Notes:

- args/flags to `pip install` must follow a second ` -- ` (not necessarily consecutive)
```console
$ pip-sync <pip-sync arg/flag>... -- -- <pip install arg/flag>...
$ pip-sync <pip-sync arg/flag>... -- --awfully-named-reqs.txt -- <pip install arg/flag>...
```
- click's existing-path check was removed from the decorator, as `src_files` gets processed manually to split true `src_files` from pip install args (and the `--` itself)
- black and flake8 do not agree about acceptable whitespace formatting:
```python
install_flags = list(src_files[fwd_args_idx + 1 :])  # black style
install_flags = list(src_files[fwd_args_idx + 1:])   # flake8 style
```

**Comment by atugushev** [comment]
@AndydeCleyre I like the idea!

**Comment by AndydeCleyre** [comment]
@atugushev black style vs flake8 style preference?

**Comment by atugushev** [comment]
@AndydeCleyre 

> black style vs flake8 style preference?

I'd prefer black style. See https://github.com/psf/black#slices.

**Comment by AndydeCleyre** [comment]
Hi, just inviting those interested to have a look and comment on #1080 -- please see my latest comment there.

**Comment by AndydeCleyre** [comment]
Please note that I'm holding off on any continued work on #1080 until we can get feedback on @atugushev's [suggestion](https://github.com/jazzband/pip-tools/pull/1080#issuecomment-601016980) of using

```console
$ pip-compile --pip-args="--no-cache-dir --no-deps --force-reinstall"
```

rather than the PR's current state of using

```console
$ pip-compile -- -- --no-cache-dir --no-deps --force-reinstall
```

Pinging most recent participants here, @merwok @tim-mitchell @aorumbayev and OP @31z4 

Thanks for any feedback!

**Comment by 31z4** [comment]
I like the `--pip-args` version. Maybe there will be a little bit of inconvenience when args must be quoted, though.

**Comment by merwok** [comment]
Quoted args with `--pip-args` seem cleaner to me than the double `--`.  Go for it!

**Comment by AndydeCleyre** [comment]
Thanks for the feedback everyone, I'll start re-implementing soon.

**Comment by AndydeCleyre** [comment]
Alright, I've pushed the `--pip-args` implementation to #1080 -- *please* go ahead and test it!
