### ISSUE TITLE
pip-compile gives misleading error message if no internet

### ISSUE THREAD

**Issue by cjerdonek** [jazzband/pip-tools#352]
If there is no internet access, `pip-compile` will fail with a misleading message. This is with pip-compile 1.6.1, pip 8.1.1, and Python 3.5.1.
##### Steps to replicate
1. Create a `requirements.in` file with a single project name.
2. Disable internet access (e.g. by disabling wi-fi).
3. Run `pip-compile --verbose requirements.in`.
##### Expected result

The command should fail with an error message relating to the fact that there is no internet connection.
##### Actual result

Instead, the output looks something like this:

```
Using indexes:
  https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  MyPackage

Finding the best candidates:
Could not find a version that matches MyPackage
Tried: (no version found at all)
```

**Comment by nvie** [comment]
Wow, that's pretty bad. Thanks for reporting, this obviously needs to be fixed.

**Comment by cjerdonek** [comment]
Note that it's possible this is due in part to a similar bug / behavior in pip itself. If I run the following with no internet:

    $ pip install --retries 0 MyPackage > temp.txt

then pip's stderr output looks like this--

      Could not find a version that satisfies the requirement MyPackage (from versions: )
    No matching distribution found for MyPackage

Without the retries argument, you will at least see connection errors prior to this. As with this report, it would be better if pip's final error message says something about the inability to connect.

**Comment by cjerdonek** [comment]
FYI, I filed the analogous issue for pip here: https://github.com/pypa/pip/issues/3642

It's possible that if pip fixes that issue the right way, then this bug will also go away (at least for the versions of pip where that issue is fixed).
