### ISSUE TITLE
pip-compile logs to stdout

### ISSUE THREAD

**Issue by cjerdonek** [jazzband/pip-tools#353]
`pip-compile` logs its verbose output to stdout instead of stderr.
##### Steps to replicate
1. Create a test `requirements.in` file.
2. Run `pip-compile --verbose requirements.in > temp.txt`
##### Expected result

You should see verbose logging in the console.
##### Actual result

No output is visible in the console.

**Comment by nvie** [comment]
This is a bug. Thanks for reporting!

**Comment by atugushev** [comment]
Fixed in #834
