### ISSUE TITLE
Add support for non-editable vcs requirements

### ISSUE THREAD

**Issue by voidlily** [jazzband/pip-tools#355]
Previous attempt at #169

**Comment by simon-weber** [comment]
I'm interested in taking a stab at this.

@blueyed is it correct that your original changes don't require https://github.com/pypa/pip/pull/2913 if vcs requirements.in are of the form ` git+https` or `git+ssh`? I'll be more hesitant if this would also involve pushing things through pip 😁

**Comment by jmbowman** [comment]
Should this be closed now that https://github.com/jazzband/pip-tools/pull/807 has been merged?  The resolution of https://github.com/jazzband/pip-tools/pull/372 implies that it should.

**Comment by blueyed** [comment]
Yeah, thanks @jmbowman.
