### ISSUE TITLE
pip-compile --output-file test.txt also writes to stdout

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#360]
With `pip-compile --output-file test.txt test.in` the output should only be written to the file, and not to stdout additionally.
This happens through `log.info` (https://github.com/nvie/pip-tools/blob/a5ef99f320e1eb3841a8571131e1cfc8aa6ed4e4/piptools/writer.py#L96).

I think it should write to stdout only when `-` is used for `--output-file` (which would be a new feature also).

Related: #353.

Support for stdin/stdout was initially requested/discussed in https://github.com/nvie/pip-tools/issues/104.

**Comment by cjerdonek** [comment]
Issue #275 is also related.

**Comment by atugushev** [comment]
It writes to stderr since 4.0.0. Can be suppressed by `--quiet` flag.

**Comment by blueyed** [comment]
@atugushev Thanks!
