### ISSUE TITLE
Failure to install compiled .txt when version has alphanumeric version number?

### ISSUE THREAD

**Issue by danwiesenthal** [jazzband/pip-tools#363]
pip install fails with the generated/compiled .txt file, I think because nose-cprof has a version number that is not purely numeric.  (nose-cprof==0.1.post1)  I have run into this issue in the past before moving to pip-tools and manually edited the .txt file to a non-alphanumeric version number for nose-cprof (nose-cprof>=0.1), but having to manually edit the compiled .txt seems to break the nice abstraction pip-tools provides.
##### Steps to replicate
1. add nose-cprof to requirements.in, without specifying a version
2. pip-compile requirements.in
3. verify requirements.txt has this line:  nose-cprof==0.1.post1
4. pip install -r requirements.txt
##### Expected result

Successful install of all packages in requirements.txt
##### Actual result

Failure to find package (note that compile succeeded and pinned the package):

Downloading/unpacking nose-cprof==0.1.post1 (from -r requirements/dev.txt (line 40))
  Could not find a version that satisfies the requirement nose-cprof==0.1.post1 (from -r requirements/dev.txt (line 40)) (from versions: 0.1-0, 0.1-1)

**Comment by deviousgeek** [comment]
I am having the same issue~!

**Comment by davidovich** [comment]
Closing as non reproducible. Reopen if you think this is closed by error.
