### ISSUE TITLE
--index/--no-index flag means different things in pip-compile and pip-sync

### ISSUE THREAD

**Issue by Sharadh** [jazzband/pip-tools#373]
`--no-index` is an existing `pip` internal flag. It does the same thing on `pip-sync` (ignore default pypi url), and something different on `pip-compile` (don't annotate index url into `requirements.txt`).

**Proposal: Change `--index/--no-index` in `pip-compile` to `--annotate-index/--no-annotate-index`.**

Achieves:
- Consistency (between `pip-sync` and `pip-compile`)
- Consistency (with `pip --no-index`)
- Consistency (with other flag `--annotate/--no-annotate`)

**Comment by vphilippon** [comment]
My initial thought on this was to make the change if we were to make a major release.
While I would also prefer it to be consistent, I feel it isn't worth it to make an additional breaking change for aesthetic reasons.

If others feels like this is really irritating and should really be changed, speak up. I just don't want to make this change if there's no one else that want it changed.

@davidovich @jdufresne @suutari / @suutari-ai If you would like to chime-in as common contributors

**Comment by jdufresne** [comment]
`--index` & `--no-index` could continue to exist as aliases that also issue a warning when used. That way, existing code won't break. The hope is people will notice a need to change before an eventual backwards compatibility breakage.

**Comment by suutari-ai** [comment]
Yeah, I agree with @jdufresne. Introducing the new options and deprecating the old ones would be the nicest first step.

**Comment by vphilippon** [comment]
Good idea, thanks for the input!

**Comment by atugushev** [comment]
I'd prefer `--emit-index / --no-emit-index` to be consistent with `--emit-trusted-host / --no-emit-trusted-host`.

**Comment by atugushev** [comment]
There is a PR #1130 which resolves the issue, any feedback is appreciated!

**Comment by atugushev** [comment]
`pip-tools v5.2.0` is released 🚀
