### ISSUE TITLE
Add parameter `--no-trusted-host`: Don't add trusted host to generated file

### ISSUE THREAD

**Issue by mckelvin** [jazzband/pip-tools#382]
Describe the issue briefly here.
##### Steps to replicate
1. Prepare `~/.pip/pip.conf`

``` ini
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
extra-index-url = http://devpi.arpanet/private/dev/+simple
trusted-host = devpi.arpanet

[search]
index = http://devpi.arpanet/private/dev/
```

Then
2. `pip-compile --no-index --upgrade --output-file requirements.txt requirements.in`
##### Expected result

`--trusted-host devpi.arpanet` should not existed in `requirements.txt`
##### Actual result

I wish there's a option in `pip-sync` like `--no-index` which won't write `--trusted-host devpi.arpanet` into the generated `requirements.txt`.

**Comment by bepetersn** [comment]
+1 this is kind of awkward. My .pypirc or pip config or whatever it's reading from has a trusted host that I use for development on a specific project, but the host is being included in every project.
