### ISSUE TITLE
Include comments from input files in output file

### ISSUE THREAD

**Issue by allanlewis** [jazzband/pip-tools#391]
Sometimes it's useful to have comments in input files where versions have been restricted, e.g.: `pytest<3  # Don't upgrade to Pytest 3.x because <foobar>`.
##### Steps to replicate
1. Add an inline comment to a line in an input file.
2. Run `pip-compile`.
##### Expected result

The comment should be preserved in the output file against the same line.
##### Actual result

The comment doesn't appear in the output file.
##### Specific use case

My actual use case here is compatibility with [Pyup](https://pyup.io/)'s [dependency filter](https://pyup.io/docs/filter/) functionality, which uses comments in requirements files like:

```
foo==1.2.3  # pyup: != 1.2.4  # disable 1.2.4, breaks tests
bar  # pyup: ignore
```

Currently, the best solution I can think of is to extend my `Makefile` to add these comments after running `pip-compile`.

**Comment by willhardy** [comment]
This is the standalone script I used to make this happen, in effect wrapping `pip-compile`. It'd be nice to just add an argument to `pip-compile`, but I couldn't wait and didn't want to maintain a fork, so wrote this quickly: https://gist.github.com/willhardy/8086aa8fcbd5df4986986cf4a66a440c

**Comment by vphilippon** [comment]
This sounds like a sensible feature to me. PRs are welcomed!

**Comment by allanlewis** [comment]
Closing as stale.
