### ISSUE TITLE
pip-compile with "setuptools" dependency fail

### ISSUE THREAD

**Issue by Lucas-C** [jazzband/pip-tools#396]
`pip-compile` fails unexpectedly on requirements that depend on `setuptools`.
##### Steps to replicate

```
echo setuptools > requirements.txt
pip-compile requirements.txt
```

Alternatively:

```
echo luigi==1.2.1 > requirements.txt
pip-compile requirements.txt
```
##### Expected result

NOT a failure
##### Actual result

Error code **2** and output:

```
Could not find a version that matches None
Tried: (no version found at all)
```
##### Additionnal notes

We have this issue with [luigi](https://pypi.python.org/pypi/luigi), that depends on [python-daemon<3.0](https://pypi.python.org/pypi/python-daemon) that [depends on `setuptools`](https://alioth.debian.org/scm/browser.php?group_id=100328).

**Comment by Lucas-C** [comment]
Note: it works fine if you specify an explicit version of `setuptools`:
````
echo setuptools==28.2.0 > requirements.txt
```

**Comment by vphilippon** [comment]
I tried to reproduce and the error seems to be fixed.
I tried using:
```
pip-tools: 1.8.2
pip: 8.1.1 and 9.0.1
```
Can you check on your side to see if it's fixed? Thanks!

**Comment by Lucas-C** [comment]
Looks ok with the latest pip-tools version
