### ISSUE TITLE
Show whether the "latest" pip version is supported

### ISSUE THREAD

**Issue by AndreasBackx** [jazzband/pip-tools#443]
Ever since I started using it, I've been a bit cautious about updating pip because I'd rather not break pip-tools. I don't really know how they version pip (I would assume semver) so I'm wondering when changes cause pip-tools to "break". Could a command in pip-tools or could the README be updated to display what the latest version of pip is that pip-tools supports? A command would be great so I don't have to keep checking the repository and just update pip-tools and check it then.

Would love to hear what you have to say too of course.

**Comment by davidovich** [comment]
@AndreasBackx There is a kind of check at startup, but for the moment it is a lower bound at pip 8.0. Unfortunately, pip does not provide a programmatic API, but pip-tools depends on it to do it's work, so it theoretically break at a future pip version. 

see assert_compatible_pip_version() in utils.py (https://github.com/jazzband/pip-tools/blob/master/piptools/utils.py#L27)

**Comment by vphilippon** [comment]
For the record, the lastest  version of pip is tested for every change.
(https://github.com/jazzband/pip-tools/blob/master/tox.ini#L6)
so the latest version is pretty safe.
A nice idea though would be to add a test with the master branch of pip (but configure it as an "allowed to fail" configuration) to see if the upcomming pip release is going to break pip-tools, and prepare accordingly.

**Comment by davidovich** [comment]
Closing. We will make sure to support latest pip.
