### ISSUE TITLE
Project Status Update?

### ISSUE THREAD

**Issue by AndydeCleyre** [jazzband/pip-tools#447]
Hello!

I love this project. I hope to continue using it. The only pain points for me are the lack of support for git url requirements and lack of confidence in the project's development status. It looks like it's been a few months since the last commit.

Can @nvie check in and either assure us that this project will continue being developed, or give us the bad news?

**Comment by mhluongo** [comment]
@nvie if you need help maintaining, I'd be happy to put some time in.

**Comment by davidovich** [comment]
@nvie Hi, you must be very solicited, but I would like to add my voice to this request. Knowing what is the way forward will influence how and if we use pip-tools in the future. 

We use pip-tools as a dependency validator to ensure user serviced venv creation is kosher. It is a central part of our validation process.

At my knowlegde, pip-tools is the only standalone dependency validator available right now (this is excluding conda in which you have to buy-in). Until pip grows one (which is a long standing [pip issue](https://github.com/pypa/pip/issues/988)), I beleive pip-tools remains a viable and very useful solution to sane python package management.

That being said, I would be very sad to see it go out of maintenance. I would also like to thank you for starting and steering the project.

**Comment by bdeeney** [comment]
@nvie I also find pip-tools very valuable and would be willing to help maintain it.

**Comment by jezdez** [comment]
Good news everyone! @nvie has moved the pip-tools project into the [Jazzband](https://jazzband.co/) GitHub organization. That means that pip-tools is now a lot easier to contribute to.

To be able to review PRs and merge code, go to [jazzband.co](https://jazzband.co) and login there to join. You're then given access to this repo [and others](https://jazzband.co/projects). Please make sure you've read the [Jazzband Code Of Conduct](https://jazzband.co/about/conduct) and [contribution guidelines](https://jazzband.co/about/guidelines) before you dive in though.

Some more info can be [found here](https://jazzband.co/news/2015/12/17/launching-jazzband). And of course in the [documentation](https://jazzband.co/about).

**Comment by davidovich** [comment]
I have reached out and had a very warm contact with @nvie by mail and he has transferred ownership to jazzband, where we it is possible to share maintainership of the project. https://jazzband.co/ is a really nice initiative. 

@jezdez beat me to the point! 

I am really eager to see how this turns out for a so popular project!

**Comment by davidovich** [comment]
Seems this is working out, closing.
