### ISSUE TITLE
pip-sync doesn't get ipython dependencies

### ISSUE THREAD

**Issue by dimaqq** [jazzband/pip-tools#454]
Describe the issue briefly here.

##### Environment Versions

1. OS Type
1. Python version: `$ python -V: Python 3.6.0`
1. pip version:  `$ pip --version: pip 9.0.1`
1. pip-tools version: `$ pip-compile --version: pip-compile, version 1.8.0`

##### 
* add `ipython` to `requirements-dev.txt`
* run `pip install -r requirements-dev.txt`
* run `pip-sync requirements.txt requirements-dev.txt`

pip-sync ends up removing ipython's dependencies...

Perhaps I misunderstood how the tools works? Or the intention behind the tool? I don't want to pin every single dependency a complex package has, do I?

**Comment by davidovich** [comment]
pip-sync works in tandem with pip-compile which creates a pinned version of your dependencies and their sub-dependencies.

You need to run pip-compile first on a requirements.in file. In your example, you would have `ipython` in your requirements.in, then run pip-compile.

pip-sync is used to update an existing virtualenv to match what would have appeared in a previous pip-compile invocation.

Closing. Do not hesitate to reopen if you still need info.
