### ISSUE TITLE
freature request: version range shorthand

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#465]
It would be neato to support semver shorthand version ranges:

`pkg ^x.y.z` -> `pkg >= x.y.z <x+1.0.0`
`pkg ~x.y.z` -> `pkg >= x.y.z <x.y+1.0`

**Comment by davidovich** [comment]
I'm afraid this differs too much from pep440 and adds a parallel system (albeit semver) that needs to be maintained. There is some notation available to attain the same functionality. Please see https://www.python.org/dev/peps/pep-0440/#version-specifiers.
