### ISSUE TITLE
Providing a source file which does not have an extension writes to a .txt file in current dir

### ISSUE THREAD

**Issue by davidovich** [jazzband/pip-tools#470]
If you happen to use an extensionless filename as a source of requirements in, pip-compile will deduce the wrong output filename and generate a ".txt" file (relative file, thus at current working dir).

##### Environment Versions

1. OS Type Should be cross platform, but observed on Windows
1. Python version: `$ python -V` 2.7.8
1. pip version:  `$ pip --version` 9.0.1
1. pip-tools version: `$ pip-compile --version` 1.8.1rc2

##### Steps to replicate

1. echo "request" > no_extension
2. pip-compile no_extension

##### Expected result

We should error out because it is difficult to deduce a new name if there is no extension to remove.

##### Actual result

a .txt file is generated at the current directory.

**Comment by vphilippon** [comment]
Giving an error is an option, but how about simply adding ".txt" for the output filename , as it's already the used extension for the output file.
Ex:
pip-compile no_extension
Result: no_extension.txt is created, containing the pip-compile output.

That way, if anyone happens to be using files without extension as input, it won't break them, while not outputing to exact same file for every filename without extension, which is the case right now.

**Comment by davidovich** [comment]
@vphilippon yes, you are right, appending .txt to a filename missing extension is the simple solution.
