### ISSUE TITLE
pip-tools 1.8.1 doesn't detect api-hour requirements with a specific Git commit

### ISSUE THREAD

**Issue by GMLudo** [jazzband/pip-tools#474]
With pip-tools 1.8.0, I have the correct requirements.txt for api-hour dependencies.

##### Environment Versions

1. OS Type: Linux
1. Python version: 3.5.2
1. pip version:  9.0.1
1. pip-tools version: 1.8.1

##### Steps to replicate

1. Create a **requirements.in** file with:

`-e git+https://github.com/Eyepea/API-Hour.git@10420b21230112ba95753c4d85839be44ae7b875#egg=api_hour
`
2. launch: **pip-compile --output-file requirements.txt requirements.in**

##### Expected result

requirements.txt with:

```
gunicorn==19.7.1          # via api-hour
pyyaml==3.12              # via api-hour
setproctitle==1.1.10      # via api-hour
```

##### Actual result

No dependencies.

Thank for your help.

**Comment by GMLudo** [comment]
Gentle ping :-)

**Comment by davidovich** [comment]
I believe this is a duplicate of #466, which is fixed by upcoming merge of #476.

**Comment by davidovich** [comment]
Can you check if this is still happening on 1.8.2 ? Thanks.

**Comment by GMLudo** [comment]
Hi,

I confirm that you fix the bug.
BTW, I've noticed that for requirements libraries from editable eggs, you don't put the egg name as a comment like you do for a regular egg.

Anyway, thank you a lot jazzband group for the maintenance of pip-tools, it's awesome ;-)

Have a nice week.
