### ISSUE TITLE
support wheel build tag regexes

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#475]
eg:

```
echo 'numpy==1.11.0' > requirements.txt
pip-compile --generate-hashes --expression="cpy35.*-macosx.*x86_64"
```

will include
- `numpy-1.11.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl`
- `numpy-1.11.0.tar.gz`

See https://github.com/peterbe/hashin/issues/19 and https://github.com/jazzband/pip-tools/issues/414

**Comment by jdufresne** [comment]
Since #414 has landed and been released, I don't think this feature is required any longer. That adds _all_ hashes for all platforms. Is there still a use case not covered? I suggest we close.

**Comment by graingert** [comment]
Yeah I think this is not needed anymore

**Comment by jdufresne** [comment]
Thanks.
