### ISSUE TITLE
1.8.1 Doesn't read dependencies from local package

### ISSUE THREAD

**Issue by ryanhiebert** [jazzband/pip-tools#480]
In 1.8.0, I have a requirements.in file that has only the contents `-e .`, and pip-tools will generate a requirements.txt based on the requirements in my setup.py, as well as including the absolute path to the local package (#204 is the bug tracking translating a relative path to absolute). Even in 1.8.0, this only works if there is not a current `requirements.txt`, otherwise it fails with the bug described in #416 and #421.

In 1.8.1, with the same requirements.in, it will only generate with the absolute path to the local package, and not freeze the local package's dependencies.

##### Environment Versions

1. OS Type: macOS and Ubuntu (confirmed on both)
1. Python version: CPython 2.7.13 and 3.6.1 installed by pythonz
1. pip version:  9.0.1
1. pip-tools version: 1.8.1

##### Steps to replicate

Run this shell script:

```sh
pip install 'pip-tools==1.8.1' > /dev/null  # Adjust version to test
echo "import setuptools; setuptools.setup(install_requires=['Django', 'six'])" > setup.py
echo "-e ." > requirements.in
rm requirements.txt 2&>1 > /dev/null
pip-compile
```

##### Expected result

To get the following output from pip-compile ,and written to requirements.txt:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
-e file:///home/ryan/Code/python/pip-tools-bug
Django==1.10.6
six==1.10.0
```

##### Actual result

Got this instead. The Django and six dependencies aren't recorded.

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
-e file:///home/ryan/Code/python/pip-tools-bug
```

**Comment by si14** [comment]
If I understand the issue correctly, I have the same problem with git deps.

**Comment by davidovich** [comment]
I believe this is a duplicate from #466. Let's continue there.
