### ISSUE TITLE
Misleading error message: pip-sync claims ">=X" is "incompatible" with "==X" in second reqs.txt file

### ISSUE THREAD

**Issue by mkoistinen** [jazzband/pip-tools#505]
When syncing requirements.txt alongside another requirements file (in my case, there's runtime requirements and develop-time requirements), pip-sync forgets its math skills.

##### Environment Versions

1. OS Version: MacOS Sierra 10.12.4
1. Python version:  3.5.1
1. pip version:  9.0.1
1. pip-tools version: 1.9.0

##### Steps to replicate

Use pip-compile
Use pip-sync like so: `pip-sync requirements.txt dev_requirements.txt`

##### Expected result
Sync'ed up virtual env, ready to go.

##### Actual result
```
Incompatible requirements found: invoke>=0.15.0 (from -r requirements/dev.txt (line 12)) and invoke==0.15.0 (from -r requirements.txt (line 57))
```

Unclear why this is incompatible.

**Comment by vphilippon** [comment]
I looked in the cound and found this comment:
https://github.com/jazzband/pip-tools/blob/master/piptools/sync.py#L81

`pip-sync` was designed to be used with the output of pip-compile only. This means that both files should only have pinned requirements.
If one of the files has unpinned requirements (like `invoke>=0.15.0 (from -r requirements/dev.txt (line 12))`), then that file is certainly not the output of a pip-compile.

So here's why it's considered incompatible. pip-sync didn't take the math class, that's pip-compile thing. I hope that helps you out @mkoistinen.

The error message could definitely be improved though, it's quite misleading.

**Comment by mkoistinen** [comment]
lol. OK. Thanks for the explanation.

**Comment by vphilippon** [comment]
Doc updated by #609, closing.
