### ISSUE TITLE
Packages previously pinned to an older version do not return to latest version 

### ISSUE THREAD

**Issue by ned2** [jazzband/pip-tools#510]
When a package in a `requirements.in` file was previously pinned to an older version (and pip-compiled) but then was unpinned, running  `pip-compile` results in a `requirements.txt` that has still has the older version rather than the latest.

Seems to only happen when reusing the same name for the `.in` file. When I rename `requirements.in` to `foo.in`, I get the latest package again. Seeing as this seems to be some kind of caching issue, I tried deleting both the pip and pip-tools cache in `~/.cache`, but did not fix it. 

A workaround for the problem is to pass the `-U` flag to `pip-compile` to force the upgrade: 
```
pip-compile -U requirements.in
```
##### Environment Versions

- Ubuntu 17.04
- Python version: 3.6.1
- pip version:  9.0.1
- pip-tools version: 1.9.0

##### Steps to replicate

1. Pin a package to an older version than the current and pip-compile
```
# requirements.in
ipython==5.3.0
```
```
$ pip-compile requirements.in
```

2. Unpin the package then pip-compile
```
# requirements.in
ipython
```
```
$ pip-compile requirements.in
```
##### Expected result
Ipython 6.0.0 (the latest) should be in `requirements.txt`

##### Actual result
Ipython 5.3.0 is in `requirements.txt`

...

**Comment by davidovich** [comment]
@ned2 this is by design since [version 1.6](https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#16).

As you say in the issue, if you want to explicitly upgrade, use the -U option. This is not a workaround.

**Comment by ned2** [comment]
Ah, somehow I missed that. This of course makes plenty of sense as the default behaviour. Thanks!
