### ISSUE TITLE
pip-sync fails if /usr/bin/pip does not exist

### ISSUE THREAD

**Issue by jmfederico** [jazzband/pip-tools#519]
Describe the issue briefly here.

##### Environment Versions

1. Alpine Linux 3.6
1. Python version: 3.6.1
1. pip version:  9.0.1
1. pip-tools version: 1.9.0

##### Steps to replicate

1. Install python3 on a clean alpine install
2. install pip-tools
3. Copy a requirements.txt file
4. run `pip-sync` or `python3 -m piptools sync`

##### Expected result

For pip-sync to install all packages.

##### Actual result

pip-sync fails complaining that `/usr/bin/pip` does not exists.
On new alpine installs, pip is by default pip3, and no pip exists.

**Comment by rpkilby** [comment]
It looks like you're trying to `pip-sync` your system python, which I would strongly discourage. It's likely that there are python packages installed that Alpine depends on, and pip-sync would remove those if they were not present in the requirements file. 

It's generally recommended that users install packages within a [virtual environment](https://docs.python.org/3/library/venv.html). When operating inside an active virtualenv, there should be `python`/`pip` executables on your path that `pip-sync` can call. Steps should look like...

1. Install python3 on a clean alpine install
2. Change to working directory (`cd /path/to/my/project`)
3. Create a virtual environment in a `venv` or similiarly named directory (`python3 -m venv ./venv`)
4. Activate the virtual environment (`source ./venv/bin/activate`)
5. Install pip-tools
6. Copy a requirements.txt file
7. Run pip-sync or python3 -m piptools sync

**Comment by jmfederico** [comment]
Hi, yes, completely aware of the virtual environment workflow. That I use for pretty much everything, except for when working with Docker.

This is a project I'm developing in a Docker image, NOT based on the official Python image, but from a clean alpine image, and Python3 installed with apk package manager.

I am thinking of using a virtualenv for the Docker image, but still thought I should report this.

**Comment by vphilippon** [comment]
Given the time that has passed, I will close this.

If, with the increasing usage of docker, there's a higher demand to address this usage, we could come back to this.

Thanks for the report by the way, at least this is now known 👍 .
