### ISSUE TITLE
pip-compile with generate hashes is very slow

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#521]
Could probably do with a progress bar

##### Environment Versions

1. OS Type Ubuntu
1. Python version: `$ python -V` 3.6
1. pip version:  `$ pip --version` n/a
1. pip-tools version: `$ pip-compile --version` master

##### Steps to replicate

use geenrate-hashes with a fairly big package graph

##### Expected result

generated hashes turn up in requirements.txt and pip-compile does not appear to hang
##### Actual result

generated hashes turn up in requirements.txt but pip-compile appears to hang

**Comment by proinsias** [comment]
I agree that a progress bar would be useful for normal operations. I would also suggest verbose output similar to the verbose output of `hashin` when `-v` is enabled.

**Comment by vphilippon** [comment]
The situation seems to have improved to a reasonable level with #557.
In `--verbose` mode, we could use some output during the hashing though.

**Comment by kaeptmblaubaer1000** [comment]
A progress bar would still be nice.

**Comment by atugushev** [comment]
Hello @kaeptmblaubaer1000,

I've added a PR #743 for that feature. I hope it'll be merged.

**Comment by RonRothman** [comment]
Question: Is there currently a way to see the progress _without_ turning on verbose output (which contains a lot of details beyond what's needed to indicate progress).

**Comment by atugushev** [comment]
Hello @RonRothman,

Unfortunately there is no way to see the progress without --verbose flag.

**Comment by graingert** [comment]
Would it be possible to add in-between verbosity levels?

**Comment by graingert** [comment]
@RonRothman do you have an example verbose output with what you want to see Vs what you don't want to see?
