### ISSUE TITLE
Using pip-compile --upgrade does not upgrade rPy2 to latest available version in requirements.txt

### ISSUE THREAD

**Issue by edesz** [jazzband/pip-tools#525]
I am trying to upgrade the `rPy2` package from my current version (2.8.5) to the [next version available](https://pypi.python.org/pypi/rpy2) - 2.8.6.

Here are the contents of my `requirements.in`
```
# requirements.in
Pandas
Jupyter
Dask
Seaborn
rpy2
matplotlib
```

When I run `pip-compile requirements.in`, here is a snippet of the resulting `requirements.txt` file produced:
```
.
.
.
pyzmq==16.0.2             # via jupyter-client
qtconsole==4.3.0          # via jupyter
rpy2==2.8.6
seaborn==0.7.1
simplegeneric==0.8.1      # via ipython
.
.
.
```

Now, I use this `requirements.txt` to upgrade all packages. Only `rPy2` is out of date - all the others are already up-to-date. When I run `pip-compile --upgrade` and then `pip freeze`, I find that the `rPy2` package has not been upgraded. It still remains at version 2.8.5.

I have also tried `pip-compile --upgrade-package rpy2` and `pip-compile --output-file requirements.txt requirements.in` but `rpy2` is still not upgraded.

The steps to reproduce are below. How can I achieve this upgrade of `rPy2` using `pip-compile`?

##### Environment Versions

1. OS Type - Windows 8 64-bit
1. Python version: `$ python -V` - 3.6.1
1. pip version:  `$ pip --version` - 9.0.1
1. pip-tools version: `$ pip-compile --version` - 1.9.0

##### Steps to replicate

1. Install [Python](https://www.python.org/downloads/release/python-361/) - I got [this](https://www.python.org/ftp/python/3.6.1/python-3.6.1.exe) file
2. Install [R](https://cran.rstudio.com/bin/windows/base/) - I got [this](https://cran.rstudio.com/bin/windows/base/R-3.4.0-win.exe) file
3. Install `rPy2` version 2.8.5 using a pre-compiled binary, for Windows, from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#rpy2)
4. Set [rPy2 environment variables](https://stackoverflow.com/a/25479841/4057186)
   - R_USER C:\Users\<user_name>\AppData\Local\Programs\Python\Python36\Lib\site-packages\rpy2
   - R_HOME C:\program files\R\R-3.4.0
5. At the [`git-bash`](https://git-scm.com/downloads) console or Windows command prompt:
   1. pip-compile requirements.in
   2. pip-compile --upgrade (or pip-compile --upgrade-package rpy2 or pip-compile --output-file requirements.txt requirements.in)
   3. pip freeze

##### Expected result

`rPy2` would be upgraded to version 2.8.6, after running `pip freeze` in last step above.

##### Actual result

`rPy2` remains at its current version of 2.8.5, after running `pip freeze`.

**EDIT**
`rPy2` does not list any Python dependencies. My version of `R` - 3.4.0 and Python meet the  `rPy2`[requirements](http://rpy2.readthedocs.io/en/version_2.8.x/overview.html#requirements).

**EDIT 2**
I think this is a question, and not an issue.

**Comment by edesz** [comment]
Digging a bit into this:

The package `six` is bizzarely listed as a dependency in `requirements.txt`. Also in `requirements.txt`, `six` is at version 1.10.0 which is the [latest version](https://pypi.python.org/pypi/six).

Maybe `rPy2` cannot be updated since its apparent dependency `six` is already at the latest version? Could this be the cause of the problem?

**Comment by vphilippon** [comment]
Just to double check: I noted that the example of requirement.txt you've given actually contains `rPy2 2.8.6`, I assume that yours contains `2.8.5`, right?

Also, you said that you performed a `pip-compile`, and then a `pip freeze`, and the package `r2py` was not updated, but I'll also assume that you did `pip install -r requirements.txt` in between to actually update your venv with the new `requirements.txt`, right?

If those 2 things above are true, could you give me your full `requirements.txt` before and after trying to upgrade, as well as the verbose output of each of your `pip compile` command?

I'll try to get the time to setup R and try to reproduce, but in the meantime, maybe I'll be able to help with that additional info.

**Comment by edesz** [comment]
Hi,

I think you might have already resolved the problem.

Here's the info about the questions:
1. My `pip freeze` currently gives `2.8.5` - this is the version I have installed. After running `pip-compile requirements.in`, the produced requirements.txt file **does** list `2.8.6`.
2. Apologies since I am new to `pip-tools` - I was following the instructions [here](https://github.com/jazzband/pip-tools#updating-requirements) which indicated:
```
pip-compile requirements.in    #generates requirements.txt
pip-compile --upgrade          #to periodically upgrade all packages
```
I assumed the second command would have performed the upgrade. So, after `pip-compile --upgrade`, I did not actually run `pip install -r requirements.txt`. This might be the problem - I think I followed the **Updating requirements** section of the README.md too literally. Is this necessary to perform the upgrade with `pip install -r .....`, or does `pip-compile --upgrade` perform this upgrade automatically?

**Comment by vphilippon** [comment]
`pip-compile` makes no change to the installed packages, so yes, you have to do `pip install -r .....`.

The `--upgrade` flag is actually to upgrade the version in the resulting `requirements.txt`.
Now, you might ask:

"Wait, you mean re-runing pip-compile without `--upgrade` does not update the requirements.txt`? Why? Why would a run `pip-compile` then?"

And thats a good question. The thing is that when re-running `pip-compile`, the tool will make sure that the `requirements.txt` still respects what's in the `requirements.in`. Much like if you do `pip install resquests>=2.13.0`, and `requests 2.14.0` is already installed, it won't upgrade it to the latest (say `2.17.3`). For `pip install` to update `requests` to the latest, you must use `--upgrade`. It's the same thing for `pip-compile`: For the version in the `requirements.txt` to be updated after it was first generated, you use `--upgrade`.

I hope that makes sense. Tell me if not, that can be confusing.

**Comment by edesz** [comment]
Many thanks! Yes, all makes sense. Thanks for the details.
