### ISSUE TITLE
pip-sync installs non-listed dependencies

### ISSUE THREAD

**Issue by jtiai** [jazzband/pip-tools#529]
When running pip-sync with editable dependecies it install also dependencies from setup.py.

##### Environment Versions

1. Ubuntu 16.04
1. Python version: 2.7.12
1. pip version:  9.0.1
1. pip-tools version:  1.9.1.dev28+gc0cd04d

##### Steps to replicate

1. Create editable package with contradicting package
2. Add newer package in requirements.txt
3. run pip-sync

##### Expected result

Package from requirements.txt would be installed

##### Actual result

Either version might end up installed (in my environment version was alternating between two versions when pip-sync was run). 

Note: didn't observed same issue with normal packages.

When installing packages --no-deps flag should be used to avoid installation of dependencies from packages.

**Comment by vphilippon** [comment]
Could you give an example `setup.py`, `requirements.txt` and `pip freeze` output?
I'm not sure to exactly understand what is happening on your end.

**Comment by rpkilby** [comment]
It might also be worth providing the `pip freeze` output for both before and after calling `pip-sync`.

**Comment by jtiai** [comment]
requirements.txt:
```
flake8==3.3.0
-e hg+https://hg.repo.example/samplerepo/@1.0#egg=sample-app
```

`pip install --no-deps -r requiremens.txt`

Expected result happens - only pinned versions without dependencies are installed.

`pip-sync requirements.txt`

Unexpected result happens - flake8 is installed as pinned version without dependencies but editable version is installed with dependencies.

sample-app/setup.py:
```python
from setuptools import setup
setup(
    name='sample-app',
    install_requires=[
        'Django>=1.8,<1.9',
    ],
)

```

**Comment by jtiai** [comment]
I added sample repository to demonstrate the issue:
https://github.com/jtiai/pipsync-issue

**Comment by vphilippon** [comment]
Ah! Here's a thing: `pip-sync` is designed to be used **only with a `requirements.txt` generated with a `pip-compile`**!
And I can tell the `requirements.txt` is not: Django is not in the `requirements.txt`, so you end-up with what we could call an undefined behaviour.

Although, I noted that the same happens even if I have only "normal" packages in the `requirements.txt`: the dependencies also get installed.

Result: the `requirements.txt` is not the product of a `pip-compile`, it's not "fully pinned" (meaning, including subdependencies), and that use case is not supported, hence the weird behaviour.

Now, that begin said, @jtiai, is this just an inconsistency you noted, or is it a behaviour you actually need?
If I had to guess, I think I can see what you're trying to accomplish: You want to be able to do something like `pip-compile --no-deps` and/or `pip-sync --no-deps`, am I right?
That's not yet possible AFAIK, but that might be a feature to add, if you actually need it.

**Comment by jtiai** [comment]
Oh, then this is just merely a documentation issue since nothing is indicating that pip-sync is not meant to work with any requirements.txt, but specially ones created by pip-compile.

If I need the feature I'll do PR.

**Comment by vphilippon** [comment]
I'd go for some documentation first, that won't hurt.

For the feature, I'd skip it for now. If it comes up again as an actual need, we'll take a look at it (and I'll try to remember to poke you back on your offer :) )
