### ISSUE TITLE
Add option to pip-compile to not write sub-dependencies

### ISSUE THREAD

**Issue by kennell** [jazzband/pip-tools#534]
Would it be possible to add a flag/option to instruct pip-compile to not output the sub-dependencies.

E.g. in requirements.in i have 

````
babel
````

pip-compile will generate:

```
babel==2.4.0
pytz==2017.2              # via babel
```

A option where the sub-dependencies (in this case, "pytz") is not written to the .txt file would be useful.

**Comment by syurchenko** [comment]
The core function of pip-tools is to pin requirements with it`s dependencies. You can pip versions of first level dependencies in your requirements.txt without pip-tools

**Comment by atugushev** [comment]
Refs #560
