### ISSUE TITLE
pip-compile does not evaluate environment markers in setup.py file

### ISSUE THREAD

**Issue by kennell** [jazzband/pip-tools#535]
I have a Python 3.x application/environment that uses the [jsonschema](https://github.com/Julian/jsonschema) library. Therefore, in my requirements.in i have:

```
jsonschema
````

Running pip-compile will output the following: 

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file req.txt req.in
#
functools32==3.2.3.post2  # via jsonschema
jsonschema==2.6.0
````

However, the functools32 dependency should only by installed for Python 2.7 apps, [as specified by the environment marker in its setup.py file](https://github.com/Julian/jsonschema/blob/master/setup.py#L25).

Therefore, when i run ```pip install -r requirements.txt```, the installation will fail because functools32 is not compatible with Python 3.x.

**Comment by adamchainz** [comment]
I think you're using a python 2 installation of pip-tools, try reinstalling it with Python 3 and recompiling

**Comment by kennell** [comment]
You are right, that was the issue. Closing this issue - thank you.
