### ISSUE TITLE
setuptools==18.2 cannot be pip-compiled

### ISSUE THREAD

**Issue by Lucas-C** [jazzband/pip-tools#541]
Executing `pip-compile` on a `requirements.txt` file containing the `setuptools` package fails.

I've seen issues mentioning `setuptools` being an "unsafe" package, but if `pip-compile` does not support this, the error message should be a little bit more helpful. Maybe explaining that is is an "unsafe" package and what that means.

##### Environment Versions

1. OS Type: Windows with Cygwin
1. Python version: `$ python -V`
`Python 3.4.3`
1. pip version:  `$ pip --version`
`pip 8.1.1`
1. pip-tools version: `$ pip-compile --version`
`pip-compile, version 1.9.0` (in a virtualenv)

##### Steps to replicate

1. `echo setuptools==18.2 > requirements.txt`
2. `pip-compile requirements.txt`

##### Expected result

No error

##### Actual result

```
Could not find a version that matches None
Tried: (no version found at all)
```

**Comment by vphilippon** [comment]
This looks a lot like a the previous bug you reported on the matter: #396
I get a failure with `pip 8.1.1`, but it's `AttributeError: Requirement instance has no attribute 'name'` instead.
I tried with python 2.7 though, and `setuptools 28.8.0`.

I tried with `pip 8.1.2`  and `pip 9.0.1`, and it works fine.

Could you try updating `pip` to `8.1.2` and see if it fixes the issue?
If not, try updating your setuptools version in the virtualenv (not in the requirements.txt, this one is not the issue).

I've seen a lot of issues with outdated `pip` and `setuptools`.

**Comment by Lucas-C** [comment]
Thanks for your help.
I'll try that tomorrow

**Comment by Lucas-C** [comment]
First off, I resinstalled pip-tools: `pip install pip-tools==1.9.0`
Then I did the them steps and got the following error:
```
$ python -V
Python 3.4.3
$ pip --version
pip 8.1.1
$ pip-compile --version
pip-compile, version 1.9.0
$ echo setuptools==18.2 > requirements.txt
$ pip-compile requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.txt
#

# The following packages are considered to be unsafe in a requirements file:
  File "/home/lucas_cimon/.local/share/virtualenvs/nexus_uploader/lib/python3.4/site-packages/piptools/writer.py", line 107, in _iter_lines
    marker=markers.get(ireq.req.name),
AttributeError: 'Requirement' object has no attribute 'name'
```

Then I realized I previously applied this :
https://github.com/jazzband/pip-tools/pull/540

I applied it, and this time got no issue :P

I guess once #540 is merged this ticket can be closed.

**Comment by jonafato** [comment]
It looks like #540 has been merged. Is this issue now solved?

**Comment by Lucas-C** [comment]
Yes, I could not reproduce the original issue, this can be close
Thanks
