### ISSUE TITLE
use sha256 hashes from warehouse

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#543]
Generating hashes is too slow, use the hashes from warehouse.

eg: click the SHA256 buttons: https://pypi.org/project/gitchart/#files

**Comment by vphilippon** [comment]
@graingert Is this still needed/relevent with #557 merged?

**Comment by graingert** [comment]
Yes. Means you don't have to download the package to get the hash

**Comment by Mogost** [comment]
That is really good idea to get hashes from warehouse.
It speeds up a lot

**Comment by graingert** [comment]
@atugushev does this still need the https://github.com/jazzband/pip-tools/labels/needs%20discussion

**Comment by atugushev** [comment]
@graingert I think so. Is there an API where we could get hashes from warehouse?

**Comment by graingert** [comment]
@atugushev https://warehouse.readthedocs.io/api-reference/json/

**Comment by atugushev** [comment]
@graingert cool, thanks!

**Comment by graingert** [comment]
@atugushev it also includes package dependency information which would save downloading any packages at all

**Comment by atugushev** [comment]
I made a PR #1109, please test/review. Thanks!
