### ISSUE TITLE
Example or documentation on --index-url

### ISSUE THREAD

**Issue by sethalicious** [jazzband/pip-tools#545]
Describe the issue briefly here.
I didn't see any examples or documentation on using --index-url for a private PyPi. Experimenting, I found that adding --index-url <PyPiUrl> in the requirements.in file did the correct thing and mirrored that in the requirements.txt.

Is there additional docs needed here for different pip options? Or you can still do anything in a requirements.txt file in the .in file and have it be preserved?

##### Environment Versions

1. OS Type
1. Python version: `$ python -V`
1. pip version:  `$ pip --version`
1. pip-tools version: `$ pip-compile --version`

##### Steps to replicate

1. ...
2. ...
3. ...

##### Expected result

...

##### Actual result

...

**Comment by atugushev** [comment]
Currently, the following options in `requirements.in` are preserved in `requirements.txt`:

- `--index-url`
- `--no-index`
- `--extra-index-url`
- `--only-binary/--no-binary `
- `--trusted-host`
- `--find-links`

And yes, it's a lack of documentation for this topic. PRs are welcomed :)

**Comment by atugushev** [comment]
Note, that below options in `requirements.txt` are not supported in `pip-sync`. Supported only cli options. There is a PR #824 wich fixes that.

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
