### ISSUE TITLE
Support updating setup.py through a pip freeze

### ISSUE THREAD

**Issue by ravindranathakila** [jazzband/pip-tools#548]
I am looking for a tool which can do a pip freeze > setup.py since this might be very common when building something inside a Virtual Environment

**Comment by franekp** [comment]
+1 This would be very useful for packaging complete "end products" (e.g. web applications) with pinned dependencies. A dot in `requirements.txt` refers to a package from current directory. Maybe pip-compile could check whether `requirements.txt` contains one line with a dot and nothing else, and if it does, assume that this is an "end product" and write pinned dependencies to `install_requires` in `setup.py`?

**Comment by vphilippon** [comment]
I think this is not in the scope of `pip-tools`.  `pip-tools` takes care of dealing with `requirements.in`/`requirements.txt` to keep the set of concrete dependencies fresh and sane, and be able to reproduce a given virtualenv.

I'm not ready (as an active contributor to `pip-tools`) to endorse and then maintain such a feature.
Thank you for your suggestion!
