### ISSUE TITLE
On python 3.6, `pip-compile` adds a python 2.7 dep

### ISSUE THREAD

**Issue by Gastove** [jazzband/pip-tools#552]
`pip-compile` keeps adding `functools32==3.2.3.post2` to my output requirements.txt; this causes `pip install` to fail:

```
Collecting functools32==3.2.3.post2
  Downloading functools32-3.2.3-2.zip
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.7 only.
```
`functools32==3.2.3.post2` comes from `jsonschema==2.6.0`, which comes from `nbformat==4.4.0`, which comes from `notebook`. 

##### Environment Versions

1. macOS 10.12.6
1. Python version: 3.62
1. pip version:  9.0.1
1. pip-tools version: 1.9.0

##### Steps to replicate

1. Create a `requirements.in` with one line: `ipython[notebook]`
2. `pip-compile requirements.in`
3. `pip-install requirements.txt`

##### Expected result

The generated `requirements.txt` should be valid.

##### Actual result

It is not, and install fails.

**Comment by vphilippon** [comment]
I tried to reproduce with python 3.6.2, and I can't. `functools32` is not collected.

requirements.in:
```
ipython[notebook]
```
requirements.txt:
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
bleach==2.0.0             # via nbconvert
decorator==4.1.2          # via ipython, traitlets
entrypoints==0.2.3        # via nbconvert
html5lib==0.999999999     # via bleach
ipykernel==4.6.1          # via ipywidgets, notebook
ipython-genutils==0.2.0   # via nbformat, notebook, traitlets
ipython[notebook]==6.1.0
ipywidgets==7.0.0         # via ipython
jedi==0.10.2              # via ipython
jinja2==2.9.6             # via nbconvert, notebook
jsonschema==2.6.0         # via nbformat
jupyter-client==5.1.0     # via ipykernel, notebook
jupyter-core==4.3.0       # via jupyter-client, nbconvert, nbformat, notebook
markupsafe==1.0           # via jinja2
mistune==0.7.4            # via nbconvert
nbconvert==5.2.1          # via notebook
nbformat==4.4.0           # via ipywidgets, nbconvert, notebook
notebook==5.0.0           # via ipython, widgetsnbextension
pandocfilters==1.4.2      # via nbconvert
pexpect==4.2.1            # via ipython
pickleshare==0.7.4        # via ipython
prompt-toolkit==1.0.15    # via ipython
ptyprocess==0.5.2         # via pexpect, terminado
pygments==2.2.0           # via ipython, nbconvert
python-dateutil==2.6.1    # via jupyter-client
pyzmq==16.0.2             # via jupyter-client
simplegeneric==0.8.1      # via ipython
six==1.10.0               # via bleach, html5lib, prompt-toolkit, python-dateutil, traitlets
terminado==0.6            # via notebook
testpath==0.3.1           # via nbconvert
tornado==4.5.1            # via ipykernel, notebook, terminado
traitlets==4.3.2          # via ipykernel, ipython, ipywidgets, jupyter-client, jupyter-core, nbconvert, nbformat, notebook
wcwidth==0.1.7            # via prompt-toolkit
webencodings==0.5.1       # via html5lib
widgetsnbextension==3.0.1  # via ipywidgets
```

The only difference I can think of is that I used a Dokcer container (not macOS), and our `setuptool` version could be different.

From the top of my head, I'd say:
- Try doing `pip install jsonschema` and confirm it works.
- Check/update your `setuptools` version
- Triple-check that you're really using `pip-tools 1.9.0`.

If all else fails, send the verbose (`-v`) output of your `pip-compile`.

**Comment by Gastove** [comment]
Oh boy. Thanks for looking! I'll dig a little more on my end and report back.

**Comment by vphilippon** [comment]
As I mentioned in #554, make sure to delete your requirement.txt and try to `pip-compile` with `--rebuild` to clear your cache. Tell me if it works out.

**Comment by Gastove** [comment]
Alas: I'm still getting the same result, with the same bad dep, every time: https://pastebin.com/uC1WgxT9

**Comment by Gastove** [comment]
Ah right -- here's the `pip-compile -v --rebuild` output: https://pastebin.com/8dQS7Y26

**Comment by vphilippon** [comment]
Something is not right. My `pip-compile` on a python 3.6 system will give me `ipython` 6.1.0, while you get 5.4.1. And the version 5.4.1 is the one offering a py2 wheel, while 6.1.0 offers a py3 wheel.

Somehow, your system act as if is was running in python 2.7. That goes beyond requirements parsing: AFAIK, `pip-tools` takes no part in the checking the wheel's python version compatibility: that's all handled by `pip`.

In the same venv, could you give me:
- Give me your setuptools version (you can also try updating it)
- Try doing `pip install ipython[notebook]` and give me the output, as well as a `pip freeze --all` output.

**Comment by Gastove** [comment]
Um. Well. This is all.... perfectly alarming. I will... see if I can't... dig in to this a little further on my end. _Something_ seems to have gone completely sideways, and it's smelling increasingly like it's something subtly borked on my end. 

Thanks for your time! I'll report back.

**Comment by Gastove** [comment]
So. A pretty significant part of this seems to be some tooling we use here at my work, which has turned out to be... uh, let's say "bad." Something is... deeply wrong system python. I do not understand what yet -- or, honestly, why it hasn't exploded much more dramatically much earlier. *But*, I seem to have tooling that is actually using python2.7 pip (and claiming it's python 3 pip), which is probably what's cramming garbage in to the cache. 

So. If I meticulously create a new venv with absolutely for-sure only python3 and skip the pip cache for pip-tools installation, everything works great for me. 

Beyond "oh god oh god," I'm not... confident yet about what is going on. I'm.... well. I very much appreciate the help digging in to this, and I apologize for any wasted time. It certainly seems like this is something deeply screwed up in my python installation. 

In light of this, I'm going to go try and purge/re-install basically everything fresh.

**Comment by Gastove** [comment]
Okay, I have: 

1. Completely scrubbed global pip packages, including blowing away the cache entirely
2. Fresh venv install
3. Fresh installation of pip-tools

Everything now seems groovy and consistent. 

Thanks for an awesome tool and for the digging!
