### ISSUE TITLE
pip-compile incorrectly adds functools32 as matplotlib dependency on Python 3.5

### ISSUE THREAD

**Issue by nirvana-msu** [jazzband/pip-tools#554]
When compiling requirements for `matplotlib` under python 3.5, one of the generated dependencies is `functools32==3.2.3.post2  # via matplotlib`. This package, however, is only uses to backport functionality to python 2.7 and pip fails when it tries to install it on python 3. Looks like for some reason `pip-compile` fails to recognize that `functools32` is not required with python 3. When you simply run `pip install matplotlib` pip correctly understands that `functools32` is not required and does not attempt installing it.

##### Environment Versions

1. OS Type: Windows 7 x64
1. Python version: Python 3.5.3 :: Continuum Analytics, Inc.
1. pip version:  pip 9.0.1 from <...> (python 3.5)
1. pip-tools version: pip-compile, version 1.9.0

##### Steps to replicate

1. Install python 3.5.3, pip-tools 9.0.1
2. .Create `requirements.in` with just one line:
```
matplotlib
```
3. Run `pip-compile`
4. Run `pip-sync`

##### Expected result

`functools32` should not be in the generated package list.

##### Actual result
Results of `pip-compile`:
```
cycler==0.10.0            # via matplotlib
functools32==3.2.3.post2  # via matplotlib
matplotlib==2.0.2
numpy==1.13.1             # via matplotlib
pyparsing==2.2.0          # via matplotlib
python-dateutil==2.6.1    # via matplotlib
pytz==2017.2              # via matplotlib
six==1.10.0               # via cycler, matplotlib, python-dateutil
```
When you run `pip-sync`, it fails with the error:
```
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.7 only.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\<username>\AppData\Local\Temp\pip-build-vbzf_gya\functools32\
```

Is there a workaround for this? Is it possible to blacklist a package, maybe?

**Comment by vphilippon** [comment]
This is extremely similar to #552. I've tried with a docker container, to no effect.

But, I've tried with python 2.7, and `functools32` did not appear in the requirements.txt. But it did get installed with `pip install`, which *really* confused me.

So I tried another `pip-compile`, deleting the requirements.txt and clearing the cache with `--rebuild`, and *then* `functools32` got listed (with python 2.7).
I then retried with `--rebuild` on python 3.5, and it did not get listed.

So I'm not sure how/why, but I got feeling your `pip-tools` cache has old or bad stuff. Please try again with `--rebuild`, and tell me if it fixes the issue.

If it does work, I'll ask right away: do you use both python 2.7 and python 3.X? I'd like to figure out what is wrong with the `pip-tools` cache.

**Comment by nirvana-msu** [comment]
hmm, it didn't help. To give you some background, I used to work with python 2.7 in a conda environment (and pip-tools correctly resolved `functools32` dependency). Now I'm trying to upgrade to 3.5.3 and face this issue.

I tried with `--rebuild` (and deleting the `.txt` file) but it did not change anything.  `functools32` still got listed.

At that point I still had `functools32` package installed in my conda environment because I just upgraded python from 2.7 to 3.5.3 with conda (so the package just persisted from the previous state of my conda environment).

I then uninstalled it manually via pip (`pip uninstall functools32`) and tried with `--rebuild` again. This time it failed, apparently while trying to install `functools32` (error listed below). Now I seem stuck as I always get this error no matter what I try to do...

```
(<envname>) C:\<path>>pip-compile --rebuild requirements.in
Traceback (most recent call last):
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\runpy
.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\runpy
.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\AppData\Local\Continuum\Anaconda2\envs\<envname>\Scripts\p
ip-compile.exe\__main__.py", line 9, in <module>
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\piptools\scripts\compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\piptools\resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\piptools\resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\piptools\resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\piptools\repositories\pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\<username>\appdata\local\continuum\anaconda2\envs\<envname>\lib\site-
packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with
 error code 1 in C:\Users\<username>\AppData\Local\Temp\tmpbcec3wc5build\functools
32\
```

**Comment by nirvana-msu** [comment]
I also have a global python installed, which is 2.7. It almost looks like some part of pip-tools gets confused and thinks that I'm using python 2.7...

**Comment by nirvana-msu** [comment]
I think the problem originates here. This is what I get if I simply try to resolve dependencies of `matplotlib==2.0.2` from PyPI:

```python
Python 3.5.3 |Continuum Analytics, Inc.| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)] on win32
In[2]: import os
from pip.req import InstallRequirement
from piptools.scripts.compile import get_pip_command
from piptools.repositories.pypi import PyPIRepository

pip_command = get_pip_command()
pip_options, _ = pip_command.parse_args([])
session = pip_command._build_session(pip_options)
repository = PyPIRepository(pip_options, session)

ireq = InstallRequirement.from_line('matplotlib==2.0.2')
repository.get_dependencies(ireq)
Out[2]: 
{<InstallRequirement object: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib==2.0.2) editable=False>,
 <InstallRequirement object: cycler>=0.10 (from matplotlib==2.0.2) editable=False>,
 <InstallRequirement object: numpy>=1.7.1 (from matplotlib==2.0.2) editable=False>,
 <InstallRequirement object: pytz (from matplotlib==2.0.2) editable=False>,
 <InstallRequirement object: functools32 (from matplotlib==2.0.2) editable=False>,
 <InstallRequirement object: python-dateutil (from matplotlib==2.0.2) editable=False>,
 <InstallRequirement object: six>=1.10 (from matplotlib==2.0.2) editable=False>}
```

I am not too familiar with how pip works, unfortunately.. but shouldn't it *not* list `functools32` as a dependency given I am on python 3.5.3?

**Comment by nirvana-msu** [comment]
Hm, I got this resolved now, though I'm not exactly certain what the root cause was. I think it had something to do with either conda or pip caching incompatible version on `matplotlib` distribution.

Here's what I did. I tried debugging the following script:
```python
from pip.req import InstallRequirement
from piptools.scripts.compile import get_pip_command
from piptools.repositories.pypi import PyPIRepository

pip_command = get_pip_command()
pip_options, _ = pip_command.parse_args([])
session = pip_command._build_session(pip_options)
repository = PyPIRepository(pip_options, session)

ireq = InstallRequirement.from_line('matplotlib==2.0.2')
```

I then placed a breakpoint on [this line](https://github.com/pypa/pip/blob/9.0.1/pip/req/req_set.py#L485), and changed `self.ignore_installed` to `True`, and continued. From that point onwards everything worked fine.. I am not exactly sure which cache I ended up clearing with this..

**Comment by vphilippon** [comment]
Most likely the wheels cache yes. I'll close this issue, if it occurs again, ping.
I'll pray this one was only a cache issue.
