### ISSUE TITLE
"Could not find a version that matches django-prices<0.5a0,>=0.4.11,>=0.6.1"

### ISSUE THREAD

**Issue by damianarechar** [jazzband/pip-tools#559]
I can't use the "pip-compile requirements.in" sucessfully.

##### Environment Versions

1. OSX
1. Python version: `$ python -V
    python 2.7.10`
1. pip version:  `$ pip --version 
    pip 9.0.1`
1. pip-tools version: `$ pip-compile --version
    pip-compile, version 1.9.0`

##### Steps to replicate

1. Create a requirements.in file with the following content:
```     
Babel>=1.3
BabelDjango>=0.2
boto3
Django>=1.8,!=1.8.6
dj_database_url>=0.3.0
dj_email_url>=0.0.4
django-bootstrap3>=8.2.1
django-cache-url>=1.0.0
django-countries>=4.1
django-emailit>=0.2.2
django-materializecss-form>=0.1
django-mptt>=0.7.1
django-payments>=0.11.0,<0.12a0
django-prices>=0.4.11,<0.5a0
django-prices-openexchangerates>=0.1.12,<0.2a0
django-redis>=4.0.0
djangorestframework>=3.1
django-storages>=1.4.1
django-versatileimagefield>=1.0.1
django-webpack-loader>=0.3.0
elasticsearch>=2.0.0,<3.0.0
faker>=0.7.7
google-measurement-protocol>=0.1.2,<0.2a0
google-i18n-address>=2.0.1
graphene-django==1.2.0
jsonfield>=1.0.3
Markdown>=2.4
maxminddb>=1.2.0,<1.3
maxminddb-geolite2==2015.708 
mock>=1.3.0
prices>=0.5.7,<0.6a0
psycopg2>=2.6
purl>=0.4.1
pytest>=2.8.0
pytest-django
requests>=1.2.0
satchless>=1.1.2,<1.2a0
social-auth-app-django>=1.1.0
text-unidecode
uwsgi>=2.0.0 
```

2. pip-compile requirements.in

##### Expected result

`The system creates a requirements.txt document.`

##### Actual result

```
Could not find a version that matches django-prices<0.5a0,>=0.4.11,>=0.6.1
Tried: 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.6.1, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.5.0, 0.6.0, 0.6.1, 0.6.2

```

**Comment by vphilippon** [comment]
This means you have a dependency conflict in your requirements. It's not a bug.
You specified `django-prices>=0.4.11,<0.5a0`.
One of the other package (or one of its dependencies) requires `django-prices>=0.6.1`, which conflicts with the `<0.5a0` you specified.

You can:
A) remove your `<0.5a0` requirement if it's not needed.
B) Look at the verbose output of `pip-compile -v` and find which packages requires `django-prices>=0.6.1`. You can use `grep` or a similar search tool to help you out.

**Comment by damianarechar** [comment]
thank you @vphilippon 😄
