### ISSUE TITLE
Simply merging multiple input files without pinning versions

### ISSUE THREAD

**Issue by bendikro** [jazzband/pip-tools#560]
It would be useful to be able to merge multiple requirement files to discard duplicate entries without adding more information than found in the requirement files. This is due to pip's inability to handle the same dependency give more than once in the input requirements.

Also relevant is #534 which suggests an option to not include sub-dependencies in the output.

### Example
```
$ cat requirements1.in
requests
pytz==2017.2
nose

$ cat requirements2.in
requests==2.11.1
pytz>=2017.2

$ pip-compile --no-pin-versions --no-write-deps -o requirements.txt requirements1.in requirements2.in
cat requirements.txt
requests==2.11.1
pytz==2017.2
nose
```

`--no-write-deps` would only prevent including the dependencies in the output, but it could still ensure there are no version conflicts for all libraries including dependencies.

**Comment by vphilippon** [comment]
I currently see no real value for this in `pip-tools`.
Do you have a concrete example as to why you would need to merge multiples requirements.in like that?

**Comment by bendikro** [comment]
I don't understand your question. Did you look at the example?

As written in the OP, pip does not handle multiple requirement files that have the same dependency multiple times with different version requirements.

So currently, it's necessary to run `pip install -r requirements1.in` and `pip install -r requirements2.in` to install successfully, as `pip install -r requirements1.in -r requirements2.in` will fail.

**Comment by vphilippon** [comment]
Alright, allow me to rephrase that: Why do you have multiple requirements.in file with duplicates that need? What is your workflow?

My current stance on this is "that's not in the scope of pip-tools", but I wanted to take the time to consider your situation, in case I missed something that would make this part of "pip-tools' job" before saying yes or no.

**Comment by bendikro** [comment]
We have a common set of makefiles for different types of functionality, where each makefile has a corresponding requirement.in file. When including a certain makefile, it adds a requirement.in file to a list of pip requirement files.
So depending on what functionality is needed, a project may end up with a set of requirement.in files with some overlapping dependencies.

Pinning exact versions for all dependencies is only useful for the an end project, i.e. a project that is not used by other projects.

We have a python library used by other projects, that includes includes multiple makefiles and therefore relies on multiple requirement.in files. We do not want to pin the versions for all the dependencies of this library (as pip-tools currently does). However, we have to pin some library versions as not doing so may lead to version conflicts in end projects, depending on the order the libraries are installed. Right now we cannot use pip-tools to generate a requirement file for this python library (built from multiple input requirement files) as it pins all library versions. We therefore do this manually.

pip-tools is what we need as it does proper dependency handling to ensure there are no version conflicts. But we want to use this for a python library that should not be pinning all library versions.

Does this answer your questions?

**Comment by vphilippon** [comment]
Thank you for the detailed explanation, that did clarify the need a lot.

This is a pretty specific need, and I don't think this should be done and maintained in `pip-tools`. I understand that `pip-tools` has a part of the logic that could be used to do this, but the proper feature doesn't fit in `pip-tools`.

I think this is a job for a separate tool, or even a feature request in `pip` itself, like supporting/merging duplicate requirements from the input files.

Thank you for your time and using `pip-tools`.
