### ISSUE TITLE
Could not find a version that matches celery<4,<4.0,==3.*,>=2.5,>=3.1.0,>=3.1.15,>=4.0

### ISSUE THREAD

**Issue by oppianmatt** [jazzband/pip-tools#565]
We have our celery version pinned to 3.* but pip-tools fails with the above error. 

##### Environment Versions

1. OS Type: Debian Jessie Docker
1. Python version: `Python 2.7.14`
1. pip version: `pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)`
1. pip-tools version: `pip-compile, version 1.9.0`

##### Steps to replicate

1. Pin celery like so in requirements.in
`celery==3.*`
2. Run `pip-tools --upgrade`

##### Expected result

Celery pinned to 3.x version

##### Actual result

```
Could not find a version that matches celery<4,<4.0,==3.*,>=2.5,>=3.1.0,>=3.1.15,>=4.0
Tried: 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.2.0, 0.3.0, 0.3.7, 0.3.20, 0.4.0, 0.4.1, 0.6.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.0, 2.2.0, 2.2.1, 2.2.1, 2.2.1, 2.2.2, 2.2.2, 2.2.2, 2.2.3, 2.2.3, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.5, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.20, 3.0.21, 3.0.22, 3.0.23, 3.0.24, 3.0.25, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.3, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.9, 3.1.10, 3.1.10, 3.1.11, 3.1.11, 3.1.12, 3.1.12, 3.1.13, 3.1.13, 3.1.14, 3.1.14, 3.1.15, 3.1.15, 3.1.16, 3.1.16, 3.1.17, 3.1.17, 3.1.18, 3.1.18, 3.1.19, 3.1.19, 3.1.20, 3.1.20, 3.1.21, 3.1.21, 3.1.22, 3.1.22, 3.1.23, 3.1.23, 3.1.24, 3.1.24, 3.1.25, 3.1.25, 4.0.0rc3, 4.0.0rc3, 4.0.0rc4, 4.0.0rc4, 4.0.0rc5, 4.0.0rc5, 4.0.0rc6, 4.0.0rc6, 4.0.0rc7, 4.0.0rc7, 4.0.0, 4.0.0, 4.0.1, 4.0.1, 4.0.2, 4.0.2, 4.1.0, 4.1.0
```

Judging from the output it looks like it would have a hard time finding something >= 4.0 and also less than < 4.0

**Comment by oppianmatt** [comment]
found it was the package django-celery-email being upgraded from 1.x to 2 requiring celery 4
but my django-celery-email line is unpined
so to satisfy requirements why didn't it pick the 1.x instead of trying to go to 2 since that is incompat?

**Comment by vphilippon** [comment]
`pip-compile` will act like `pip`: If no constraints are given, it will fetch the latest version of a package.

>  why didn't it pick the 1.x instead of trying to go to 2 since that is incompat?

Because `pip-compile` does not try to "backtrack" to find a matching version.
It's a shame, but it's not a trivial thing to do. See #397 for a bit more info.
In your specific case, I'd say downpinning `django-celery-email <2.0` in your requirements.in would be your solution.

Hope this helps!

**Comment by oppianmatt** [comment]
yep down pinned worked

instead of backtracking then, since it's hard
couldn't it display which package(s) are causing a conflict
or even just display which packages had any version specifications when it fails to find a package
so I could see which ones are probably the culprit

turned on verbose and had to grep the output of a big list (lots of requirements)

**Comment by vphilippon** [comment]
There's an issue on that: #473. It does gets asked a lot, and I agree it would really help.
I had started some work on this, but had no time to work on it for a while.

The general idea would probably to populate the `InstallRequirements.comes_from` property and to display it on failure, although it gets messy. `grep` is indeed your best friend right now.

I'll admit I'm waiting to #531 to be resolved before putting more energy in new features right now.

Contributions are still welcomed though!

**Comment by vphilippon** [comment]
Closing, keeping #473
