### ISSUE TITLE
pip-compile sets wrong dependencies for social-auth-core under python3

### ISSUE THREAD

**Issue by mhozza** [jazzband/pip-tools#575]
Describe the issue briefly here.
_social-auth-core_ has different set of dependencies for python 2 and 3.
with python 2 it requires `python-openid`, whereas with python 3 it requires `python3-openid`.
When I install _social-auth-core_ via pip, it installs the correct dependency.
When I generate a requirements.txt file, it adds a dependency for:
`python-openid==2.2.5      # via social-auth-core`, which is incopatible with python3.

##### Environment Versions

1. Linux
1. Python version: 3.6.2
1. pip version:  9.0.1 
1. pip-tools version: 1.10.1

##### Steps to replicate

1. create a `requirements.in` with `social-auth-core`
2. run `pip-compile requirements.in` under python3

##### Expected result

python-openid dependency is:
python3-openid==3.0.10

##### Actual result
python-openid dependency is:
python-openid==2.2.5

**Comment by mhozza** [comment]
Hmm, this seems to be caching problem - seems like it reuses a cache generated from python2. 
adding -r fixes the problem, but it would be nice to have separate cache for each python version or virtal env.

**Comment by mhozza** [comment]
Hmm, sorry, it does not fix it (it changed behaviour when I installed social-auth-core via pip - after that it put the right dependency).

**Comment by suutari-ai** [comment]
This sounds like the same issue as fixed in PR #571. Can you try if it works with master?

**Comment by vphilippon** [comment]
I fixed the exact same issue (with the same package) in `pipenv` by updating its patched-and-vendored version of `pip-tools` to use the latest fix in `pip-tools` master branch. I'm pretty sure it should be fixed.

When trying with the master branch, be sure to clear you cache too.

**Comment by vphilippon** [comment]
Closing, tell us if the issue still occurs on master.

**Comment by vphilippon** [comment]
(Nevermind, reopening to *maybe* avoid duplicated issues, as I have no idea of when an official release will be made.)

**Comment by vphilippon** [comment]
This is now fixed in 1.10.2
**Make sure to clear you dependency cache: `pip-compile --rebuild`**

**Comment by pdehaye** [comment]
that seems to have done it! weird bug...
