### ISSUE TITLE
 Idea: have a tool to check your requirements.in file for outdated dependencies, without installing them.

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#579]
Idea: have a tool to check your requirements.in file for outdated dependencies, without installing them.

Similar to #63 but without installing any packages.

**Comment by jerzyk** [comment]
add an option to check for vulnerabilities... https://pyup.io/safety/

**Comment by rpkilby** [comment]
The suggestion to integrate pyup.io has been discussed and denied in #486. My recommendation would be to create an independent tool that checks requirements files for outdated dependencies, and then use that as part of your workflow. This tool could be used with or without pip-tools. eg, 

Users of pip-tools would have a workflow of:
write requirements.in > check w/ safety > pip-compile

Those who don't use pip-tools would then just do:
write requirements.txt > check w/ safety

**Comment by graingert** [comment]
Let's continue to only use free (freedom) network services, and chastise
those that use promote or create non-free network services.

**Comment by tuukkamustonen** [comment]
Related: `pip list --outdated`, `pip check` (seems undocumented and at early stages, see https://github.com/pypa/pip/issues/4738), [pipenv check](https://docs.pipenv.org/index.html#pipenv-check), [pipenv update](https://docs.pipenv.org/index.html#pipenv-update).

I wonder if the implementation from pipenv could be moved into pip-tools, which pipenv uses internally anyway...(?)

**Comment by vphilippon** [comment]
Without installing the dependencies, right now you can:
- run `pip-compile --upgrade`
- Diff your requirements.txt using your source control (or do a diff of a previously made copy of your requirements.txt)

This is a sensible way to do it IMO that does not require additional work or feature in `pip-tools`.
You can stay fresh and keep an eye out for risky package upgrades.
If anyone thinks that `pip-tools` really needs a new command for this, come have a talk!

Closing, thank you for using pip-tools 👍

**Comment by graingert** [comment]
`pip-compile --upgrade` doesn't unpin deps pinned in requirements.in

**Comment by graingert** [comment]
@vphilippon
