### ISSUE TITLE
Doesn't work in Windows

### ISSUE THREAD

**Issue by cluelesscoder** [jazzband/pip-tools#58]
While I don't mind using Linux, unfortunately it's not an option at work. Using PortablePython-2.7.5. pip works but pip-review does not - note that the ../Scripts folder has pip.exe which is part of the issue (versus pip-review with no .exe), but when I added the .exe to it I just got some weird message (can't copy-paste it - says the NTVDM CPU has encountered an illegal instruction).

**Comment by itavero** [comment]
What's the status of this issue? Still seems to be broken on this end.

**Comment by nvie** [comment]
I'm rewriting the entire pip-tools suite (almost from scratch). I definitely want to support Windows, but I will need some help from others that actually use Windows to report and fix bugs.
The `master` version of pip-tools won't see any updates anymore—all my efforts are focused on the rewrite.

**Comment by jgonggrijp** [comment]
`pip-review` should work under Windows as of [version 0.5](https://pypi.python.org/pypi/pip-review/0.5). Otherwise, please submit a ticket to [my fork](https://github.com/jgonggrijp/pip-review/issues).
