### ISSUE TITLE
pip-compile 1.10+ not finding tornado dependencies

### ISSUE THREAD

**Issue by haylo75** [jazzband/pip-tools#590]
Using pip-compile 1.9.0 with a requirement of tornado==4.5.2, the required dependencies are found and generated.  Starting with 1.10.0, said dependencies are no longer found.  Verbose output from 1.9.0 indicates 3 rounds of dependency checks, but zero rounds with 1.10.0

I checked the [setup.py](https://github.com/tornadoweb/tornado/blob/810c341d2488c11813995dd2beadab7ba00ff44d/setup.py) for [Tornado](https://github.com/tornadoweb/tornado), and here is the relevant section.

    if setuptools is not None:
        # If setuptools is not available, you're on your own for dependencies.
        install_requires = []
        if sys.version_info < (2, 7):
            # Only needed indirectly, for singledispatch.
            install_requires.append('ordereddict')
        if sys.version_info < (2, 7, 9):
            install_requires.append('backports.ssl_match_hostname')
        if sys.version_info < (3, 4):
            install_requires.append('singledispatch')
            # Certifi is also optional on 2.7.9+, although making our dependencies
            # conditional on micro version numbers seems like a bad idea
            # until we have more declarative metadata.
            install_requires.append('certifi')
        if sys.version_info < (3, 5):
            install_requires.append('backports_abc>=0.4')
        kwargs['install_requires'] = install_requires

##### Environment Versions

1. Mac OS X 10.11.6
1. Python version: 2.7.10
1. pip version:  9.1.0
1. pip-tools version: 1.10.0 (and 1.10.1)

##### Steps to replicate

1. Write a requirements.txt file with the following contents:

`echo tornado==4.5.2 > requirements.in`

2. Run pip-compile in verbose mode

`pip-compile requirements.in -v -r`

3. View output

##### Expected result
See attached pip-requirements-1.9.0.txt
[pip-requirements-1.9.0.txt](https://github.com/jazzband/pip-tools/files/1420235/pip-requirements-1.9.0.txt)

##### Actual result
See attached pip-requirements-1.10.0.txt
[pip-requirements-1.10.0.txt](https://github.com/jazzband/pip-tools/files/1420234/pip-requirements-1.10.0.txt)

**Comment by vphilippon** [comment]
This is a known issue fixed in master, and will be part of 1.10.2, when a release will be available (see #531 as of why a bugfix is not out yet).

**Comment by haylo75** [comment]
Thanks for the context.  I checked out master and tornado 4.5.2 and its dependencies compiled just fine.  I'll close this issue since it was already addressed.
