### ISSUE TITLE
Respect --find-links in requirements.in and put it in compiled requirements.txt

### ISSUE THREAD

**Issue by wooyek** [jazzband/pip-tools#591]
I have had `--find-links=requirements` in `requirements.txt`. It point's to a folder containing proprietary libraries, this folder is deployed alongside the application to CI server, to Heroku, etc.

When I switched to `requirements.in` and `pip-tools`, my compiled `requirements.txt` does not contain it anymore. I know I can supply `find-links` switch [in other ways](https://pip.pypa.io/en/stable/user_guide/#configuration) in target environment, but leaving it in the `requirements.txt` file is the most simple and robust solution — no need to configure each and every environment separately.

It would be good to somehow whitelist or otherwise put `--find-links=requirements` in compiled `requirements.txt.

**Comment by suutari** [comment]
This is already implemented in PR #453, but it's still unmerged.

**Comment by wooyek** [comment]
Sweet :)
