### ISSUE TITLE
flake8 fails due to bare except (E772) in _compat/contextlib

### ISSUE THREAD

**Issue by therefromhere** [jazzband/pip-tools#592]
I noticed that recent builds of master have failed due a bare exception here: https://github.com/jazzband/pip-tools/blob/master/piptools/_compat/contextlib.py#L111 (eg https://travis-ci.org/jazzband/pip-tools/jobs/293392462#L691 )

This is due to flake8==3.5.0  (flake8==3.4.1 passes)

I'm not clear if a bare exception is justified in this case, but in any case the code is the same as in contextlib2.  Should piptools add contextlib2 as a conditional dependency for python 2.7 instead of _compat/contextlib?

##### Environment Versions

1. Ubuntu 16.04
1. Python version: 2.7.12
1. pip version:  9.0.1
1. pip-tools version: 1.10.2.dev7+g29ea9a4

##### Steps to replicate

tox -e flake8

##### Expected result

test pass

##### Actual result

```
$ tox -e flake8
GLOB sdist-make: /home/johnc/workspace/pip-tools/setup.py
flake8 create: /home/johnc/workspace/pip-tools/.tox/flake8
flake8 installdeps: flake8
flake8 inst: /home/johnc/workspace/pip-tools/.tox/dist/pip-tools-1.10.2.dev7+g29ea9a4.zip
flake8 installed: click==6.7,configparser==3.5.0,enum34==1.1.6,first==2.0.1,flake8==3.5.0,mccabe==0.6.1,pycodestyle==2.3.1,pyflakes==1.6.0,six==1.11.0
flake8 runtests: PYTHONHASHSEED='1185616339'
flake8 runtests: commands[0] | flake8 piptools tests --max-line-length=120
piptools/_compat/contextlib.py:111:13: E722 do not use bare except'

```

**Comment by vphilippon** [comment]
Hi @therefromhere, thanks for looking into this.

So, you're saying this is just really a vendoring of `contextlib2` (this was done before my time here I think)? If so, yeah, let's go ahead with a condition dependency for py2.7, using those sweet environment markers.

**Comment by bittner** [comment]
>> This is due to flake8==3.5.0 (flake8==3.4.1 passes)
>
> So, you're saying this is just really a vendoring of `contextlib2`

That only means that the checks are more strict now. We shouldn't look into pinning or purposely downgrading, I feel.

What if we catch `Exception` and let errors fall through? See [this SO answer](https://stackoverflow.com/questions/14797375/should-i-always-specify-an-exception-type-in-except-statements/14797393#14797393) for comparison.
