### ISSUE TITLE
README broken on PyPI (must be reStructuredText)

### ISSUE THREAD

**Issue by bittner** [jazzband/pip-tools#594]
The [package description](https://pypi.python.org/pypi/pip-tools/) on PyPI is unreadable since PyPI expects the README in [reStructuredText](http://www.sphinx-doc.org/en/stable/rest.html) file format and we use MarkDown.

Solution A: Convert to reST
---------------------

1. Rename the current `README.md` to `README.rst`
1. Replace the markdown of the badges and the code samples ([example](https://github.com/Organice/djangocms-maps/blob/master/README.rst))
1. Add a `long_description=read_file('README.rst')` line to `setup.py` ([example](https://github.com/Organice/djangocms-maps/blob/master/setup.py#L50))

Solution B: Process before Upload
-------------------

1. Integrate [pypandoc](https://pypi.python.org/pypi/pypandoc) in `setup.py` ([example](https://github.com/jrief/djangocms-cascade/blob/master/setup.py#L7-L14))
1. Add a `long_description=convert('README.md', 'rst')` line to `setup.py` ([example](https://github.com/jrief/djangocms-cascade/blob/master/setup.py#L49))

------------

Both solutions above will render a nicely formatted, HTML-styled package description on PyPI.

Quality Assurance
--------------

Optionally, you may check your README with [checkdocs](https://github.com/Organice/djangocms-maps/blob/master/tox.ini#L13-L19) before uploading the package to PyPI, because sometimes the reST-to-HTML conversion that PyPI uses fails -- and renders a still hard-to-read, broken, unformatted package description.

**Comment by bittner** [comment]
Let me know if you want this to be fixed, and which solution you prefer. I can happily prepare a PR.

**Comment by vphilippon** [comment]
Hi @bittner, thanks for the report and suggestions.

I would suggest to go with A). Mostly because:
> Pypandoc uses pandoc, so it needs an available installation of pandoc. 

and there are no prebuilt wheels for Linux with `pandoc`, so that could be an issue with the BMs for the releases. Let's just keep the release process as simple as possible, especially in the Jazzband context :p. (But thank you for the info, I might use that in my own projects) 

Thanks again, you can submit a PR, that would be really appreciated!

**Comment by vphilippon** [comment]
https://pypi.python.org/pypi/pip-tools/1.10.2rc1
Allright, so this is a lot more readable than it used to be, hurray!
But the rendering seems to fail. I'll reopen for anyone who wants too look into this.

**Comment by vphilippon** [comment]
Todo: try this out: https://github.com/pypa/warehouse/issues/2600#issuecomment-346156317
