### ISSUE TITLE
Add option to preserve range pinning in pip-compile.

### ISSUE THREAD

**Issue by lukeschlather** [jazzband/pip-tools#596]
This is a sort of odd question.

Our organization uses range-pinning for certain classes of packages (build tools for example.) We would like to be able to range-pin something in test_requirements.in or setup.py and have the range pin preserved in the resultant requirements.txt.

Does it seem reasonable to add a --preserve-range-pinning flag to pip-compile?

**Comment by vphilippon** [comment]
Hi @lukeschlather, I see your use case, but I think it's not reasonably feasible.

The main issue is that within a version range for a package, its dependencies can change. This means that you cannot pin those dependencies. It ends up breaking the whole idea of the reproductible environment.

My suggestion would be to keep those in a seperate requirements file and use that file as is.

**Comment by lukeschlather** [comment]
Packages that are range-pinned in this way are designed to be tolerant to older versions of hard-pinned packages, or to have no dependencies.

And so there's a bit of trouble I think for us with having a separate requirements.txt, since we really only want first-party packages to be range-pinned. We want any transitive dependencies to be hard-pinned (and pip-tools lets us do that easily, but it breaks our range-pinning assumption.)

I wrote a patch that I'm pretty sure does exactly what we want though I can see how it might not be worth it on your end: https://github.com/lukeschlather/pip-tools/commit/7e4255901f4e18483d3bca70f217cce262d5e2df

**Comment by vphilippon** [comment]
Hm, I see. I'll admit I'm not sure I see the value in this. If you want a newer version of your top-level packages installed, I would rather run `pip-compile --upgrade-package <package-to-update>` in order to keep the transitive dependencies unchanged.

I feel like this option could do more harm than good to most users.

Still, I'm open and ready to discuss about your usage, either to find another solution for you, or change my vision on this.

**Comment by vphilippon** [comment]
Closing, feel free to comment back, I'm still open to discussion 👍 
Thank you for using pip-tools!
