### ISSUE TITLE
Travis-Ci Issue

### ISSUE THREAD

**Issue by vphilippon** [jazzband/pip-tools#598]
It seems that with the recent change to the test matrix, the python 2.7 jobs get stuck waiting for each other, or something like it. I don't know a lot about tox and travis, so I'm struggling here.

From my understanding, we configured all python 2.7 job to wait for others (using `travis-after`). Now, there are multiple python 2.7 jobs (while before, there was only one). 
**That might be the issue, although I don't understand why this didn't cause issue in the original PR.**

I also have a feeling this is going to be troublesome for the deploy step (if it ever gets activated again) in the future.

Any helping hand is more than welcome here.
/cc @bittner as you likely have more travis/tox knowledge than I do.

**Comment by vphilippon** [comment]
Thought: Is it because the `deploy` step is only executed on the main repo, and every py2.7 job is waiting for the other jobs to finish before doing the `deploy` step itself, causing a deadlock?

The solution would be to select one of the specific job (say, py2.7 PIP=8) to wait and take care of the `deploy`. That's worth trying I guess.

**Comment by bittner** [comment]
I would suggest to remove the `[travis:after]` section.

It [is deprecated](https://tox-travis.readthedocs.io/en/stable/after.html), and Travis build stages should be used instead, as explained in the warning of the related tox-travis documentation.

**Comment by vphilippon** [comment]
🥇
