### ISSUE TITLE
suppress pip-compile console output

### ISSUE THREAD

**Issue by wbolster** [jazzband/pip-tools#601]
even when using an explicit `--output-file`, `pip-compile` insists on printing (coloured) output to the console:

```
pip-compile --output-file requirements.txt requirements.in
```

it seems there is no way to suppress this, which is a bit annoying since the output is rather useless. (especially since requirements.txt is updated, and `git diff` is more useful for it.)

**Comment by nabeel-ms** [comment]
@wbolster Have you tried using the -q/--quiet flag to suppress the output? It worked to fix the issue for me.

**Comment by wbolster** [comment]
thanks!
