### ISSUE TITLE
Link to pipdeptree in docs

### ISSUE THREAD

**Issue by merwok** [jazzband/pip-tools#602]
Hello!  I find myself converting projects with long requirements files to pip-tools.
Git history or coworkers memories are not enough to determine what is a top-level dependency and what was required indirectly.

pipdeptree is a small tool that answers that question.  I’d like to add a link in the readme or docs of pip-tools.

Cheers!

**Comment by vphilippon** [comment]
I also think that `pipdeptree` is worth mentioning, as is can also help out with "debugging" the dependency tree.

It could be added in a "Other useful tools" section.
