### ISSUE TITLE
Bad output

### ISSUE THREAD

**Issue by MichaelHipp** [jazzband/pip-tools#62]
I'm getting this:
(reports) C:\dev\reports>pip-review
)jango==1.6 is available (you have 1.2.1
)istribute==0.7.3 is available (you have 0.7.3
)ip-tools==0.3.4 is available (you have 0.3.4
)sycopg2==2.5.1 is available (you have 2.5.1
)ywin32==214 is available (you have 218
)eportlab==2.7 is available (you have 2.7
)irtualenv==1.10.1 is available (you have 1.10.1
)lwt==0.7.5 is available (you have 0.7.2
- Something is going wrong with character output.
- It seems to think all these are all back versions, even tho most are not

**Comment by jgonggrijp** [comment]
Was fixed in jgonggrijp#16. First release after [pip-review 0.5](https://pypi.python.org/pypi/pip-review/0.5) will include this fix.
