### ISSUE TITLE
Pip-compile always ignores existing pins for pre-releases

### ISSUE THREAD

**Issue by davidjlloyd** [jazzband/pip-tools#624]
You can specify the `--pre` flag to allow pip-compile to upgrade to a pre-release package. However once you do this future package upgrade calls to pip-compile will ignore the existing pin for that package and advance it to the most recent version available. Looks like the `--pre` flag is only considered by the PyPI repository and not the local repository.

##### Environment Versions

1. OS Type (Linux/Ubuntu)
1. Python version: 2.7
1. pip version: 9.0.1
1. pip-tools version: 1.11.0

##### Steps to replicate

1. Create a new package with dependencies `a` and `b`, where latest `b` is a pre-release package
1. Create a requirements.txt from the package using `pip-compile --dev` to pin to the latest versions of each package
1. Release new versions of packages `a` and `b` (or equivalently pin to earlier version of `a` and `b` if you don't have a local PyPI server to test on - `b` must still be pinned to a pre-release package)
1. Attempt to upgrade `a` using `pip-compile --dev --upgrade-package a`

##### Expected result

Package `a` should be upgraded in requirements.txt, package `b` should remain pinned as before.

##### Actual result

Packages `a` and `b` are both upgraded to the latest versions of each.

**Comment by atugushev** [comment]
I've tried the steps to replicate it and couldn't reproduce the bug with the latest version 6.11.0. Feel free to reopen if you feel that the issue is still not fixed. Thanks!
