### ISSUE TITLE
pip compile does not honor dependency_links

### ISSUE THREAD

**Issue by jeremyarr** [jazzband/pip-tools#626]
Reopening #53 

If any package in requirements.txt has dependency_links pip compile will fail, because currently it only polls PyPI for packages.

Is there a way to make pip compile check the dependency links? Or if this is not possible, use a private pypi?

**Comment by vphilippon** [comment]
Hi @jeremyarr 

To use a private pypi, it works that same as pip: configure in `pip.ini`/`pip.conf` or using `--index-url`/`--extra-index-url`.

For the `dependency_link` issue, could you give me an example with an existing package?

**Comment by moggers87** [comment]
@vphilippon Inboxen would like to move to using `setup.py` (and in future be installable from PyPI) and we often find that we want to use unreleased versions of packages. As an open source project, a private PyPI is out of the question.

It is worth noting that `pip` does not honour dependency-links either, unless you specify `--process-dependency-links`. How hard would it be to implement such an option for `pip-compile`?

**Comment by moggers87** [comment]
Having a quick look at the source code, would I be wrong in thinking that `--process-dependency-links` could be conditionally added [here?](https://github.com/jazzband/pip-tools/blob/master/piptools/scripts/compile.py#L108)

**Comment by dizlv** [comment]
Any updates on this? We have some custom libraries, written by our own, that are stored in private git repositories. We would like to put them in setup.py, but seems it's not possible right now?

**Comment by atugushev** [comment]
Dependency links has been [removed](https://pip.pypa.io/en/stable/news/?highlight=--process-dependency-links#id103) since `pip==19.0`.
