### ISSUE TITLE
pip-compile quiet

### ISSUE THREAD

**Issue by nicain** [jazzband/pip-tools#627]
Feature request:

Add -q/--quiet flag to pip-sync command.

**Comment by vphilippon** [comment]
Hello @nicain,

This flags already exists. Is there any extra messages still going through?

**Comment by wizpig64** [comment]
pip-sync has --quiet, pip-compile does not.

**Comment by CapedHero** [comment]
Bump. It would be a truly sweet feature.

**Comment by tonal** [comment]
For empty changes also not empty output:
```
$ pip-sync -q
Everything up-to-date
```
