### ISSUE TITLE
pip-compile accidentally pins release candidates 

### ISSUE THREAD

**Issue by hyperknot** [jazzband/pip-tools#633]
`pip-compile` prefers to set release candidate versions of packages. `pip install` would get the stable version of the same package. 

If you test it right now, `webob` package can replicate this bug.

`pip install webob` -> 1.7.4
`pip-compile` on a file with `webob` -> `webob==1.8.0rc1`

I believe pip-compile should never pin unreleased / release-candidate versions, but should always pin the latest stable, like pip does.

##### Environment Versions

1. OS Type: macOS 10.12.6
1. Python version: `$ python -V`  Python 2.7.14
1. pip version:  `$ pip --version` pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
1. pip-tools version: `$ pip-compile --version` pip-compile, version 1.11.0

**Comment by rpkilby** [comment]
Hi @hyperknot. I can't recreate this myself. Tested this with the latest version of pip & pip-tools, and with python 2.7.13 and 3.6.0.
- Create/activate fresh virtual environment
- `pip install pip-tools`
- `echo webob > requirements.in`
- `pip-compile requirements.in`
- `cat requirements.txt`
    ```
    #
    # This file is autogenerated by pip-compile
    # To update, run:
    #
    #    pip-compile --output-file requirements.txt requirements.in
    #
    webob==1.7.4
    ```

Have you tried recreating this in a fresh virtual environment?

**Comment by hyperknot** [comment]
OK, it only happens when the requirement is `pyramid`.
It requires `WebOb>=1.7.0rc2` which installs 1.8.0rc1 instead of 1.7.4.

But this mirrors the Pip behaviour, which might mean it's a bug in pip?

**Comment by hyperknot** [comment]
Actually the minimal case is as simple as: 
```
pip install 'webob >= 1.7.0rc2'
Collecting webob>=1.7.0rc2
  Using cached WebOb-1.8.0rc1-py2.py3-none-any.whl
```

I think it's a bug in pip.

**Comment by hyperknot** [comment]
Opened pip issue: https://github.com/pypa/pip/issues/4969
