### ISSUE TITLE
Issue with nested editable dependencies prevents arguably satisfiable requirements files from compiling.

### ISSUE THREAD

**Issue by mattgiles** [jazzband/pip-tools#634]
Consider the following `requirements.in`:

```
boto3
botocore<1.8.0
```

Pip-compile will produce something like:

```
$ pip-compile requirements.in
Could not find a version that matches botocore<1.8.0,<1.9.0,>=1.8.29
Tried: 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3,
...,
1.8.29
```

The issue is that boto3's botocore requirement is:

```
-e git://github.com/boto/botocore.git@develop#egg=botocore
```

And, as such, this editable requirement pins to latest.

I initially started drafting an issue to boto3, to say "python dependency conflicts, pypa tooling, pip-tools... please pin your dependencies so my tooling still works." But it's not going to be just boto3, and I wonder if there isn't an option here for pip-tools.

Would it make sense to preserve existing behavior, but allow editable requirements like the one above to be plastic (i.e. can be any version) with a command line flag like `--free-editables` or a command line option like `--unpinned-editable-operator <=` (defaulting, as it does now, to `>=`)?

I believe the behavior would still need to pin editable requirements which *are* pinned:

```
-e git://github.com/boto/botocore.git@1.4.48#egg=botocore
```

Is this a feasible solution?

##### Environment Versions

1. OS Type
`macOS`
1. Python version: `$ python -V`
`Python 2.7.10`
1. pip version:  `$ pip --version`
`pip 9.0.1`
1. pip-tools version: `$ pip-compile --version`
`pip-compile, version 1.10.1`

##### Steps to replicate

See above.

##### Expected result

See above.

##### Actual result

See above.

**Comment by mattgiles** [comment]
Maybe this issue does, in fact, belong on boto3. Going to open an issue there.

**Comment by vphilippon** [comment]
For correctness for anyone reaching this: The cause is that `boto3` actually has a dependency on `botocore>=1.8.29` in this case, effectively conflicting with the explicit requirement of `botocore<1.8.0` given in the requirements.in here.

It isn't related to nested editable dependency (`boto3` has none).
