### ISSUE TITLE
AttributeError: module 'click' has no attribute 'FloatRangeecho'

### ISSUE THREAD

**Issue by chaoflow** [jazzband/pip-tools#636]
Describe the issue briefly here.

##### Environment Versions

1. Linux
1. Python version: 3.6.4
1. pip version:  9.0.1
1. pip-tools version: 1.11.0

##### Steps to replicate

1. python3.6 -m venv venv
2. ./venv/bin/pip install -e git+https://github.com/pallets/click@55682f6f5348f5220a557f89c3a796321a52aebf#egg=click
3. ./venv/bin/pip install pip-tools==1.11.0
4. ./venv/bin/pip-compile --help

##### Expected result

Display help message.

##### Actual result
```
% ./venv/bin/pip-compile --help                                                             
Traceback (most recent call last):
  File "./venv/bin/pip-compile", line 7, in <module>
    from piptools.scripts.compile import cli
  File "/path/to/venv/lib/python3.6/site-packages/piptools/scripts/compile.py", line 13, in <module>
    from .. import click
  File "path/to/venv/lib/python3.6/site-packages/piptools/click.py", line 6, in <module>
    from click import *  # noqa
AttributeError: module 'click' has no attribute 'FloatRangeecho'
```

```
% grep -i FloatRangeecho /path/to/venv/src/click/click -R                
Binary file /path/to/venv/src/click/click/__pycache__/__init__.cpython-36.pyc matches
% grep -i FloatRangeecho /path/to/venv/lib/python3.6/site-packages/piptools -R
%
```

**Comment by vphilippon** [comment]
Hi @chaoflow, thanks for the report.

I was able to reproduce the issue by doing simply this:
1. python3.6 -m venv venv
2. ./venv/bin/pip install -e git+https://github.com/pallets/click@55682f6f5348f5220a557f89c3a796321a52aebf#egg=click
3. ```
    $ python
    >>> from click import *
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'FloatRangeecho'
    ```

I'm not sure what's going on. `FloatRangeecho` isn't even a type defined in `click`. Something seems odd. Doing `from X import *` is generally discouraged, but is still valid.

This can either be raised over to the `click` devs, or assumed to be a quirk of this dev, unreleased version of `click`.

`pip-tools` could be adjusted to only import the necessary `click` modules to avoid this specific issue.

**Comment by suutari** [comment]
The culprit is a missing comma at the end of this line: https://github.com/pallets/click/blob/55682f6f5348f5220a557f89c3a796321a52aebf/click/__init__.py#L69

The line ends with string literal `'FloatRange'` which is then concatenated with the next string literal `'echo'` on line 72, because there is no comma in between.

**Comment by chaoflow** [comment]
thx a lot!
