### ISSUE TITLE
pip-sync ignores options in requirements.txt

### ISSUE THREAD

**Issue by kmontag** [jazzband/pip-tools#638]
Same issue as #367, just re-opening because it seems discussion there isn't getting noticed.

Options like `--index-url` and `--extra-index-url` are honored when passed explicitly to `pip-sync`, but ignored when they're included in `requirements.txt`. So something like this:

```
# requirements.in
--extra-index-url https://my.private.index/
private-package==1.0.0
```

will compile successfully (via `pip-compile requirements.in`) to:

```
# requirements.txt
--extra-index-url https://my.private.index/
private-package==1.0.0
```

but then `pip-sync requirements.txt` will throw `Could not find a version that satisfies the requirement private-package==1.0.0`.

This can obviously be worked around with `pip-sync --extra-index-url https://my.private.index/ requirements.txt`, but `pip-sync` should be able to recognize the option automatically.

**Comment by davidovich** [comment]
Thanks for the issue. We will welcome any PR that can fix this problem that you are having, in the pure open-source fashion :-)

**Comment by desaintmartin** [comment]
Hey, this looks interesting in adding one handy feature of pip into pip-tools. How can we go further with this? I think #674 is a good start.

**Comment by suutari-ai** [comment]
There's also my earlier PR #464 which addresses this same issue, I think.

**Comment by atugushev** [comment]
I've prepared a pull request (#824), which adds support of `--no-binary` and the other options. Any feedback, review/test would be appreciated!
