### ISSUE TITLE
pip-compile with generate hashes is very slow for new requirements.txt generation

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#643]
Could probably do with a progress bar

##### Environment Versions

1. OS Type Ubuntu
1. Python version: `$ python -V` 3.6
1. pip version:  `$ pip --version` n/a
1. pip-tools version: `$ pip-compile --version` master

##### Steps to replicate

use geenrate-hashes with a fairly big package graph

##### Expected result

generated hashes turn up in requirements.txt and pip-compile does not appear to hang
##### Actual result

generated hashes turn up in requirements.txt but pip-compile appears to hang

**Comment by graingert** [comment]
https://github.com/jazzband/pip-tools/issues/521 was closed by https://github.com/jazzband/pip-tools/pull/641 but it doesn't actually help my use-case, where I regularly regenerate my requirements.txt

**Comment by vphilippon** [comment]
Allright, agreed. We'll track this one for the case of the first generation.

**Comment by devxpy** [comment]
Can we please have some sort of progress bar? Quite frustrating to just see it sit there..

**Comment by atugushev** [comment]
Progressbar added in #743. Use `--verbose` mode.
