### ISSUE TITLE
Pip 10.0.0 compatibility.

### ISSUE THREAD

**Issue by kramarz** [jazzband/pip-tools#653]
It is unusable with the newest pip version. I guess is due to 

> Move all of pip's APIs into the pip._internal package, properly reflecting the fact that pip does not currently have any public APIs.

( https://pip.pypa.io/en/stable/news/ )

When I tried to `pip-sync` I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 7, in <module>
    from piptools.scripts.sync import cli
  File "/usr/local/lib/python3.6/site-packages/piptools/scripts/sync.py", line 10, in <module>
    from .. import click, sync
  File "/usr/local/lib/python3.6/site-packages/piptools/sync.py", line 8, in <module>
    from .utils import flat_map, format_requirement, key_from_ireq, key_from_req
  File "/usr/local/lib/python3.6/site-packages/piptools/utils.py", line 10, in <module>
    from pip.req import InstallRequirement
ModuleNotFoundError: No module named 'pip.req'
```

**Comment by vphilippon** [comment]
I cannot reproduce with `pip-tools` v2.0.1.
`pip-tools` v2+ has vendored `pip 9.0.3` internally to keep compatibility with `pip 10.0.0` when installed.

Did you update `pip-tools` to v2.0.1?

**Comment by kramarz** [comment]
I didn't. My bad. I am closing this.

I was using CI script in docker image and there was `pip install pip-tools` command and I assumed the image didn't contain pip-tools but it did. 

I know it is a bad excuse.
