### ISSUE TITLE
format_requirement is lowercasing markers, which violates PEP 508

### ISSUE THREAD

**Issue by jfly** [jazzband/pip-tools#660]
I discovered this issue while using pipenv. See https://github.com/pypa/pipenv/issues/2113. I believe this bug was introduced in
<https://github.com/jazzband/pip-tools/pull/452> as a band-aid fix to <https://github.com/jazzband/pip-tools/issues/431>.

I've never actually used pip-tools myself, so I'm not sure how to reproduce this issue with pip-tools, but it should be pretty clear from the pipenv bug report what's going on here.

I'm working on a fix for this over in https://github.com/pypa/pipenv/pull/2123, but I thought it would be useful to report this upstream ASAP, in case this is already a known issue, or you have a better idea for a fix.

**Comment by AndydeCleyre** [comment]
I can work on this if someone can provide a reproduction process.

**Comment by jfly** [comment]
@AndydeCleyre I still have never actually used pip-tools directly, but you can see a repro in the test I added to pipenv over here: https://github.com/pypa/pipenv/pull/2123/files#diff-ce6487d3c4a96b746d4e7c37ce59de79cd9f46b7aa0d2e9e26443ee135b517e1. Is that enough to go off of?

**Comment by AndydeCleyre** [comment]
Thanks, but I'm not sure yet. `pip-tools` doesn't currently operate on `Pipfile`s, so I need to test with a `requirements.in` file (same syntax as `requirements.txt`).

With this `requirements.in`:

```python
pytz ; platform_python_implementation == 'CPython'
```

And the following command:
```console
$ pip-compile requirements.in
```

The output looks good:
```ini
pytz==2021.1 ; platform_python_implementation == 'CPython'
```

If I use the wrong case in the input file (`platform_python_implementation == 'cpython'`), the marker doesn't match the environment, and the output is blank.

Is that the case we're talking about here? If so, what's the proper thing to do when a user uses the wrong case for the marker value in the input file? Should we try to catch common mistakes?

**Comment by jfly** [comment]
@AndydeCleyre I just spent a little while reading through pip-tools source code, and I see the same code that `pipenv` copied here:

https://github.com/jazzband/pip-tools/blob/afc255b51c3bb78fdef0d967719c0ee614df7898/piptools/utils.py#L121

Note how this code lowercases the entire requirement, which was a problem over in pipenv because it could include markers that shouldn't be lowercased. However, over in pip-tools, it looks like markers get passed around [separately](https://github.com/jazzband/pip-tools/blob/afc255b51c3bb78fdef0d967719c0ee614df7898/piptools/utils.py#L109) and are [tacked onto the formatted requirements string after the lowercasing](https://github.com/jazzband/pip-tools/blob/afc255b51c3bb78fdef0d967719c0ee614df7898/piptools/utils.py#L124).

I was unable to find a codepath in pip-tools that led to this `format_requirement` function getting called with an `InstallRequirement` with a non-null `markers` attribute. Maybe there is a path, but I just don't know pip-tools well enough to find it if it does!

I think it's ok to close this out.
