### ISSUE TITLE
recommended use of pip-tools vs other tools

### ISSUE THREAD

**Issue by cs01** [jazzband/pip-tools#662]
I just came across this tool and it looks interesting. I am trying to understand how it fits in with the rest of the Python packaging ecosystem and saw a link in the README which led me to [this blog post](http://nvie.com/posts/pin-your-packages/) which in the intro pointed me to [this blog post](http://nvie.com/posts/better-package-management/) which says at the top to basically not read the blog post and to use Pipenv:

> Note: While the principles outlined in this blog post still very much apply, your tool of choice these days should be Pipenv. It internally uses the pip-tools principles and logic to resolve the dependencies, but in a much more polished tool. It's also the officially recommended Python packaging tool from Python.org.

It was recently noted in some conversations by the PyPA that the marketing of Pipenv as "the officially recommended Python packaging tool from Python.org." is a little heavy-handed, and that they are not saying it should be the one and only tool used for packaging and dependency management, and even that they're fine with people using tools that aren't "officially recommended".

So I am curious: should I try out pip-tools, or has the project effectively given up and recommending Pipenv?

**Comment by davidovich** [comment]
pip-tools is just a resolver (plus the pip-sync companion). It all depends on your needs, as pip-tools can be seen as the plumbing behind what pipenv offers you. If you just need to manage the result of a resolver, then bare pip-tools might be ok. We use it this way to provide a reproductible deployment of dependencies. If you want all the developper tooling and project oriented virtualenv management (and more), then pipenv would be a better fit.

**Comment by techalchemy** [comment]
(and we rely heavily on, and modify and push changes back to pip-tools itself)

**Comment by cs01** [comment]
Interesting, thanks!
