### ISSUE TITLE
when running with --allow-unsafe it's not added to the 'To update, run' instructions

### ISSUE THREAD

**Issue by rmwthorne** [jazzband/pip-tools#664]
when running with --allow-unsafe it's not added to the 'To update, run' instructions

##### Environment Versions

1. Mac OSX
1. Python version: `$ python -V` Python 3.6.3
1. pip version:  vendored
1. pip-tools version: 2.0.2

##### Steps to replicate

1. pip-compile with --allow-unsafe

##### Expected result

--allow-unsafe is added to the instructions

##### Actual result

--allow-unsafe is not added to the instructions

**Comment by atugushev** [comment]
Closed in #708. Thanks for the issue!
