### ISSUE TITLE
Readme links to an outdated article

### ISSUE THREAD

**Issue by m-aciek** [jazzband/pip-tools#668]
The first paragraph of Readme links to article *Pin Your Packages* from September 26, 2012 on @nvie's  blog. Although first section (*Pin Explicitly*) of this article is completely up-to-date, the second one (*Check for Updates Automatically*) and following are not. pip-review is gone from pip-tools for a long time and one is not able to apply the article content to his own project. IMHO it's a bit confusing. Could you consider replacing link and moving *Pin Your Packages* rationale into Readme?

BTW I think it would be great also to have such as in *Pin Your Packages* but more up-to-date tutorial also in Readme (at the end?).

##### Environment Versions

1. pip-tools version: 2.0.2

##### Steps to replicate

1. Start to read Readme.
2. Click on link "You do pin them, right?".
3. Go to section "pip-review" and try to imitate commands locally with newest pip-tools installed.

##### Expected result
Linked article contains up-to-date content.

##### Actual result
Trying to reproduce example from linked article results with "pip-review: command not found".

**Comment by oleng** [comment]
I second this. 6 years is a really long time ago, especially for a workflow tool.

**Comment by atugushev** [comment]
Refs #883. 

> Could you consider replacing link and moving _Pin Your Packages_ rationale into Readme?
> 
> BTW I think it would be great also to have such as in _Pin Your Packages_ but more up-to-date tutorial also in Readme (at the end?).

I think it's a good idea! PR is welcomed 👍
