### ISSUE TITLE
pip-compile doesn't add "via" for GitHub commit dependencies

### ISSUE THREAD

**Issue by basvdheuvel** [jazzband/pip-tools#675]
I need a package's specific commit. This package has some requirements. Pip-compile doesn't show where these requirements come from.

##### Steps to replicate

1. Add a GitHub commit dependency to `requirements.in`, e.g. `-e git+https://github.com/JelteF/pylatex.git@aa5aa1ea13d548e3a598544f49ceb6fcc80f6b36#egg=PyLaTeX`
2. Run `pip-compile`

##### Expected result

This specific example requires `ordered-set`. The line containing this package in `requirements.txt` should say `  # via PyLaTeX` or something along those lines.

##### Actual result

In actuality, it only shows `ordered-set`, which caused me to search through my entire codebase and Git history searching for usages of this package, without result. I finally discovered the problem when hacking some print statements into piptools' resolver code.

**Comment by atugushev** [comment]
Hello @basvdheuvel, 

Thanks for the issue! It duplicates #293.
