### ISSUE TITLE
You are out of Sync with https://packaging.python.org/tutorials/packaging-projects/#configuring-your-project

### ISSUE THREAD

**Issue by kevindawson** [jazzband/pip-tools#678]
Describe the issue briefly here.
You are out of Sync with https://packaging.python.org/tutorials/packaging-projects/#configuring-your-project:

Sorry but I am a newbie, and your pypi.org instructions are lacking. 

##### Environment Versions

1. `ubuntu 18.04`
1. Python version: `3.6.5`
1. pip version:  `18.0`
1. pip-tools version: `2.0.2`

##### Steps to replicate

1. https://packaging.python.org/tutorials/packaging-projects/#configuring-your-project
2. Creating setup.py
3. copy boiler plate locally and edit

plus install_requires= not in link 

##### Expected result

pip-compile

##### Actual result
```text
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
```

Please: update your documents to work with current Python Packaging User Guide

Many Thanks

**Comment by vphilippon** [comment]
Hello @kevindawson,

I gave a try with the example setup.py, plus an `install_requires`. I do get the same warning, but the `pip-compile` still seems to work. can you check if the `requirements.txt` was properly generated?

**Comment by kevindawson** [comment]
@vphilippon is this of any use to you
```text
kevin@dual:~/git/pylsusb$ pip-compile
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/piptools/scripts/compile.py", line 166, in cli
    dist = run_setup(src_file)
  File "/usr/lib/python3.6/distutils/core.py", line 227, in run_setup
    script_name)
RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script?
```
```
$ pip list |grep click
$ pip3 list |grep click
click                  6.7
```
```    
$ pip list |grep first
$ pip3 list |grep first
first                  2.0.1
```
```      
$ pip list |grep six
six                    1.11.0     
$ pip3 list |grep six
six                    1.11.0
```
```
$ pip list |grep pip-tools
$ pip3 list |grep pip-tools
pip-tools              2.0.2      
```
I normal only use python3.6, but python2.7 install as part of distro ubuntu 18.04

many thanks

**Comment by kevindawson** [comment]
@vphilippon

why do I have to fill out a `install_requires` section

should your app not be doing that for me

if I put my package name in
```python
    install_requires=[
        'my_project',
    ],
```
all I get:
```text
Could not find a version that matches my_project
No versions found
Was https://pypi.python.org/simple reachable?
```

**Comment by vphilippon** [comment]
@kevindawson 
> why do I have to fill out a install_requires section
should your app not be doing that for me

`pip-tools` will not change or update your `install_requires` section, that is not its purpose.

The goal of `pip-tools` is to take a set of requirements (defined in a `requirements.in` file or in your `setup.py` file in the `install_requires`), perform a deep dependency resolution, then output a `requirements.txt` (the "standard" `pip` requirements file) which will contain a set of fully pinned requirements and versions that match those requirements. That file can then be used for reproducible installation of the python environment (typically, in a `virtualenv`).

I suggest that you read the following doc/articles:
- https://packaging.python.org/discussions/install-requires-vs-requirements/
- https://caremad.io/posts/2013/07/setup-vs-requirement/
- https://nvie.com/posts/better-package-management/

As for the specific error you're getting now, `my_projects` was declared as a dependency of you current package, `pip-tools` is looking for is on pypi, and cannot find it. `install_requires` should contain the abstract dependencies of your project (i.e. what libs your project needs to work).

**Comment by kevindawson** [comment]
@vphilippon 

Thanks for the reading list, until I have RTFM :))
later

**Comment by vphilippon** [comment]
I'm glad if that helped you out, have a nice day!
