### ISSUE TITLE
pip-dump: add --dry-run option to pip-dump / dry-run y default

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#69]
I have just tried pip-dump, and it did not work very well (report might follow, probably caused mainly by vcs-style/editable installs).

I would like to have a --dry-run option, which would not rewrite / add to the existing files, but display what it would output.

Maybe "dry-run" should even be the default, and a switch like "-f" would be required to write the files?!

**Comment by nealmcb** [comment]
Why was this closed?  It still seems like it would be good to have a "dry-run" option!
(Also note, it looks like the master branch is once again current....)

Can you re-open this?  Thanks!
