### ISSUE TITLE
pip-tools can't handle setup with functions as kwargs

### ISSUE THREAD

**Issue by Redoubts** [jazzband/pip-tools#696]
I have a setup.py where the `setup` function has a few arguments filled in with outputs from function calls, for example:

```
setup(
    name='MyPackage',
    description='Description',
    version=find_version(),
    ...
```

But when I call `pip-compile` on this project, I get things like `NameError: global name 'os' is not defined`. This error goes away when I comment out these function calls.

It looks like pip-compile is doing something that tries to fill in these values, but doesn't load my imports first (like `import os`), so the execution fails.

##### Environment Versions

1. OS Type: MacOS Latest
1. Python version: Python 2.7.15 :: Anaconda, Inc.
1. pip version:  pip 18.1
1. pip-tools version: pip-compile, version 3.1.0

**Comment by richafrank** [comment]
I believe this stems from pip-compile's use of distutils to run setup.py, which was [broken](https://bugs.python.org/issue23426) in python versions up through 3.5.

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
