### ISSUE TITLE
pip-compile adds private gemfury token to requirements.txt

### ISSUE THREAD

**Issue by thisfred** [jazzband/pip-tools#697]
Describe the issue briefly here.

##### Environment Versions

1. OS Type OSX
1. Python version: 3.7.0
1. pip version:  10.0.1
1. pip-tools version: 3.1.0

##### Steps to replicate

Have pip extra index url set as an environment variable:

export PIP_EXTRA_INDEX_URL="https://pypi.fury.io/$GEMFURY_API_TOKEN/$REPO/"

run pip-compile on any requirements.in file.

##### Expected result

A requirements.txt file that does not leak secrets.

##### Actual result

A requirements.txt file that includes 

--extra-index-url [URL including secret token]

I'm not saying gemfury is doing a great job at security, by including secrets as part of the repo url, but having the --extra-index-url automatically included in the output seems a little too implicit for me. I'd much rather see that be something you explicitly add to the requirements.in source file, or at least something that pip-compile should ask for verification on. (And yes, I already revoked the token I accidentally leaked in this way by pip compiling a public repo.)

**Comment by thisfred** [comment]
I'd be in favor of making `--no-index` the default behaviour. Explicitly passing in the extra index urls when needed seems less likely to cause problems in the long run.

**Comment by vphilippon** [comment]
Hello @thisfred, thanks for the feedback.

I see how this can be a pain point for you, but I would be against changing the default behavior here. Having the information that the requirements.txt was generated using some specific index by default is something that makes sense in most cases (and fits in the idea that the generated requirements.txt is a set of [concrete dependencies](https://caremad.io/posts/2013/07/setup-vs-requirement/#so-why-does-abstract-and-concrete-matter).

I'm sorry this lead to a leaked token though. Using `--no-index` seems to be your best option here.

I'll go ahead and close the issue. If there are strong arguments in favor of changing this, feel free to reply.
Cheers!
