### ISSUE TITLE
How to replace package to other?

### ISSUE THREAD

**Issue by tonal** [jazzband/pip-tools#698]
Package [pillow-simd](https://github.com/uploadcare/pillow-simd) fastest fork from [Pillow](https://github.com/python-pillow/Pillow)

Bat many package have Pillow as depandence.
For example [ImageHash](https://github.com/JohannesBuchner/imagehash)

How can I point out that instead of Pillow you should use pillow-simd?

**Comment by vphilippon** [comment]
If a package has declared a dependency on `pillow`, there's sadly no way to indicate to use `pillow-simd` instead.

**Comment by atugushev** [comment]
I'll close this since it doesn't look like there's any action required regarding pip-tools. Fill free to reach out if you have any questions.
