### ISSUE TITLE
dependency resolver without installing the package

### ISSUE THREAD

**Issue by GreatBahram** [jazzband/pip-tools#701]
HI there, 
I have a problem and for that I need to check python package's dependencies and get a list all of them (then I want to get them to be able create mini repo of pypi). 
I think you have done something like that, right?
do you guys have any idea or piece of code can be a good starting point? I just don't want to reinvent the wheel ...

**Comment by GreatBahram** [comment]
Thank you and wish me luck!

**Comment by atugushev** [comment]
Good luck! Feel free to reopen it if you'll need any further help.
