### ISSUE TITLE
index-url option help misleading

### ISSUE THREAD

**Issue by dinio31** [jazzband/pip-tools#705]
Help message describing pip-compile index-url option does not seem compliant with the expected behavior if I refer to #208: the default could be different of PyPI in that case.

Am I right?

**Comment by atugushev** [comment]
As i can see it works like a charm. 

Here's list index_urls:
https://github.com/jazzband/pip-tools/blob/master/piptools/repositories/pypi.py#L53-L55

Let's assume user did non pass `--index-url`, so first element `pip_options.index_url` would contain a value provided by `pip`. Pip provides a value from `pip.conf` or default `PyPI.simple_url`.

Could you provide a test to demonstrate your assumption?

**Comment by dinio31** [comment]
Thanks for your answer. Probably I was not clear enough: I was speaking of the help message which is misleading when there is a custom pip configuration.
```
>pip-compile --help
Usage: pip-compile [OPTIONS] [SRC_FILES]...

  Compiles requirements.txt from requirements.in specs.

Options:
...
  -i, --index-url TEXT            Change index URL (defaults to PyPI)
```



`(defaults to PyPI)`  is hardcoded:
https://github.com/jazzband/pip-tools/blob/master/piptools/scripts/compile.py#L39

In the case where a `pip.ini` or `pip.conf` file is provided to pip (at the root of a virtualenv for instance), this message is wrong.

This message could be: ` (defaults to PyPI except if you specifid an 'index-url' field in pip configuration)`, or something like that. But it is a bit long.
A better option would be to dynamically provide the true default coming from pip configuration. I have dug into the code but did not find a simple way to do it. Using pip.index.PackageFinder (as done in PyPIRepository class) should certainly do  the job, but I cannot figure out how to call it prior to all the Click stuff.

**Comment by atugushev** [comment]
Got your point. I'm not sure it's worth it. Anyways, it could be rephrased.
