### ISSUE TITLE
celery~=4.2.1 resolved into missing kombu==4.2.2

### ISSUE THREAD

**Issue by wonderbeyond** [jazzband/pip-tools#707]
I have `celery~=4.2.1` in my `requirements.in`.
At **Round 2** resolved into `kombu<5.0,>=4.2.0`.

Below is the latest release history of **kombu**:

![image](https://user-images.githubusercontent.com/228361/51012128-8f99a680-1596-11e9-9c78-db7f1ccd7c1c.png)

But while "Finding secondary dependencies", I saw it's trying to fetch kombu==4.2.2, which is not found in pypi.

> $ pip-compile -v -r
> ...
> kombu==4.2.2 not in cache, need to check index
> Traceback (most recent call last):
> File "/home/wonder/.pyenv/versions/amidala/bin/pip-compile", line 11, in <module>
>   sys.exit(cli())
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/click/core.py", line 764, in __call__
>   return self.main(*args, **kwargs)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/click/core.py", line 717, in main
>   rv = self.invoke(ctx)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/click/core.py", line 956, in invoke
>   return ctx.invoke(self.callback, **ctx.params)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/click/core.py", line 555, in invoke
>   return callback(*args, **kwargs)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/scripts/compile.py", line > 196, in cli
>   results = resolver.resolve(max_rounds=max_rounds)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/resolver.py", line 101, in > resolve
>   has_changed, best_matches = self._resolve_one_round()
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/resolver.py", line 198, in > _resolve_one_round
>   for dep in self._iter_dependencies(best_match):
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/resolver.py", line 284, in > _iter_dependencies
>   dependencies = self.repository.get_dependencies(ireq)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/repositories/local.py", > line 65, in get_dependencies
>   return self.repository.get_dependencies(ireq)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/repositories/pypi.py", line > 217, in get_dependencies
>   self._dependencies_cache[ireq] = self.resolve_reqs(download_dir, ireq, wheel_cache)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/piptools/repositories/pypi.py", line > 183, in resolve_reqs
>   results = resolver._resolve_one(reqset, ireq)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/pip/_internal/resolve.py", line 256, > in _resolve_one
>   abstract_dist = self._get_abstract_dist_for(req_to_install)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/pip/_internal/resolve.py", line 209, > in _get_abstract_dist_for
>   self.require_hashes
> File > "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", > line 218, in prepare_linked_requirement
>   req.populate_link(finder, upgrade_allowed, require_hashes)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/pip/_internal/req/req_install.py", > line 164, in populate_link
>   self.link = finder.find_requirement(self, upgrade)
> File "/home/wonder/.pyenv/versions/2.7.14/envs/amidala/lib/python2.7/site-packages/pip/_internal/index.py", line 621, > in find_requirement
>   'No matching distribution found for %s' % req
> pip._internal.exceptions.DistributionNotFound: No matching distribution found for kombu==4.2.2

##### Environment Versions

1. Ubuntu 18.04.1
1. Python version: 2.7.14
1. pip version:  18.1
1. pip-tools version: 3.2.0

**Comment by thedrow** [comment]
It was released but removed. Please use 4.2.2-post1

**Comment by wonderbeyond** [comment]
@thedrow However, I've got into trap and cannot find way out. `pip-compile` always resolve into `kombu==4.2.2`.

**Comment by atugushev** [comment]
@wonderbeyond 

Try to run: `pip-compile --upgrade-package kombu`. After that you'll be able to run `pip-compile`.

The problem is that in your `requirements.txt` you have `kombu==4.2.2`, and `pip-compile` also tries to parse requirements from `requirements.txt` where you got the exception.

**Comment by wonderbeyond** [comment]
@atugushev Thanks! after remove `requirements.txt` and re-execute `pip-compile`, I got the right `kombu==4.2.2.post1`.
I've no expect that pip-compile would read also `requirements.txt` as input.

**Comment by atugushev** [comment]
Cheers!
