### ISSUE TITLE
pip-sync broken on Windows

### ISSUE THREAD

**Issue by miuliano** [jazzband/pip-tools#722]
Calling pip-sync on Windows returns:
```
Could not open requirements file: [Errno 13] Permission denied: 'c:\\users\\<username>\\appdata\\local\\temp\\tmpe9jswo'
```

This was introduced in 3.3.1 by the change to using `tempfile.NamedTemporaryFile` in [sync.py](https://github.com/jazzband/pip-tools/blob/3.3.1/piptools/sync.py#L167) to create the requirements file before passing it to `pip install` via `subprocess.check_call`. This is caused by Windows requiring reopened temporary files to be opened with the `O_TEMPORARY`  flag. For context see https://stackoverflow.com/a/15235559. 

##### Environment Versions

1. OS Type: Windows 10
1. Python version: Python 2.7.12
1. pip version: pip 9.0.3
1. pip-tools version: pip-compile, version 3.3.1

##### Steps to replicate

1. `pip-sync -r <requirements_file>`

##### Expected result

Command should complete successfully.

##### Actual result

```
Could not open requirements file: [Errno 13] Permission denied: 'c:\\users\\<username>\\appdata\\local\\temp\\tmpe9jswo'
```

**Comment by atugushev** [comment]
Hello @miuliano, thanks for the report, i'll try to fix it ASAP.

Thank you @davidovich for the info! It should have been done the same as in compile.
