### ISSUE TITLE
pip-sync fails to install module inside dependency

### ISSUE THREAD

**Issue by bjmc-globus** [jazzband/pip-tools#724]
For some reason, when I install pyramid_jinja2 using `pip-sync`, with a requirements.txt file generated by `pip-compile`, the `i18n` submodule is missing from `pyramid_jinja2`. See details below.

I'm not 100% sure if this is a `pip-tools` issue or a `pyramid_jinja2` issue, but I'm reporting it here first because the install works as expected with vanilla `pip` but behaves strangely with `pip-sync`.

##### Environment Versions

1. OS Version: Ubuntu 18.04.1
1. Python version: `Python 3.6.7`
1. pip version:  `pip 19.0.1`
1. pip-tools version: `pip-compile, version 3.3.2`

##### Steps to replicate

1. Create a virtual environment: `virtualenv .env --python=python3`
2. Activate the virtualenv `source .env/bin/activate`
3. Install pip-tools: `pip install pip-tools`
4. Use the following minimal `requirements.in`:

```
pyramid-jinja2==1.8
```

5. Generate a requirements.txt `pip-compile --generate-hashes requirements.in`
<details>
  <summary>requirements.txt</summary>
      #
    # This file is autogenerated by pip-compile
    # To update, run:
    #
    #    pip-compile --generate-hashes --output-file requirements.txt requirements.in
    #
    hupper==1.4.2 \
        --hash=sha256:0c0083efcd1b777d7c292e7476e36adaaad187bd0f3cd7b48d8f8ab0abf288a3 \
        --hash=sha256:eb3778398658a011c96e620adcd73175f306f880a6d86b2ebb6d2a15a74b6b9b \
        # via pyramid
    jinja2==2.10 \
        --hash=sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd \
        --hash=sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4 \
        # via pyramid-jinja2
    markupsafe==1.1.0 \
        --hash=sha256:048ef924c1623740e70204aa7143ec592504045ae4429b59c30054cb31e3c432 \
        --hash=sha256:130f844e7f5bdd8e9f3f42e7102ef1d49b2e6fdf0d7526df3f87281a532d8c8b \
        --hash=sha256:19f637c2ac5ae9da8bfd98cef74d64b7e1bb8a63038a3505cd182c3fac5eb4d9 \
        --hash=sha256:1b8a7a87ad1b92bd887568ce54b23565f3fd7018c4180136e1cf412b405a47af \
        --hash=sha256:1c25694ca680b6919de53a4bb3bdd0602beafc63ff001fea2f2fc16ec3a11834 \
        --hash=sha256:1f19ef5d3908110e1e891deefb5586aae1b49a7440db952454b4e281b41620cd \
        --hash=sha256:1fa6058938190ebe8290e5cae6c351e14e7bb44505c4a7624555ce57fbbeba0d \
        --hash=sha256:31cbb1359e8c25f9f48e156e59e2eaad51cd5242c05ed18a8de6dbe85184e4b7 \
        --hash=sha256:3e835d8841ae7863f64e40e19477f7eb398674da6a47f09871673742531e6f4b \
        --hash=sha256:4e97332c9ce444b0c2c38dd22ddc61c743eb208d916e4265a2a3b575bdccb1d3 \
        --hash=sha256:525396ee324ee2da82919f2ee9c9e73b012f23e7640131dd1b53a90206a0f09c \
        --hash=sha256:52b07fbc32032c21ad4ab060fec137b76eb804c4b9a1c7c7dc562549306afad2 \
        --hash=sha256:52ccb45e77a1085ec5461cde794e1aa037df79f473cbc69b974e73940655c8d7 \
        --hash=sha256:5c3fbebd7de20ce93103cb3183b47671f2885307df4a17a0ad56a1dd51273d36 \
        --hash=sha256:5e5851969aea17660e55f6a3be00037a25b96a9b44d2083651812c99d53b14d1 \
        --hash=sha256:5edfa27b2d3eefa2210fb2f5d539fbed81722b49f083b2c6566455eb7422fd7e \
        --hash=sha256:7d263e5770efddf465a9e31b78362d84d015cc894ca2c131901a4445eaa61ee1 \
        --hash=sha256:83381342bfc22b3c8c06f2dd93a505413888694302de25add756254beee8449c \
        --hash=sha256:857eebb2c1dc60e4219ec8e98dfa19553dae33608237e107db9c6078b1167856 \
        --hash=sha256:98e439297f78fca3a6169fd330fbe88d78b3bb72f967ad9961bcac0d7fdd1550 \
        --hash=sha256:bf54103892a83c64db58125b3f2a43df6d2cb2d28889f14c78519394feb41492 \
        --hash=sha256:d9ac82be533394d341b41d78aca7ed0e0f4ba5a2231602e2f05aa87f25c51672 \
        --hash=sha256:e982fe07ede9fada6ff6705af70514a52beb1b2c3d25d4e873e82114cf3c5401 \
        --hash=sha256:edce2ea7f3dfc981c4ddc97add8a61381d9642dc3273737e756517cc03e84dd6 \
        --hash=sha256:efdc45ef1afc238db84cb4963aa689c0408912a0239b0721cb172b4016eb31d6 \
        --hash=sha256:f137c02498f8b935892d5c0172560d7ab54bc45039de8805075e19079c639a9c \
        --hash=sha256:f82e347a72f955b7017a39708a3667f106e6ad4d10b25f237396a7115d8ed5fd \
        --hash=sha256:fb7c206e01ad85ce57feeaaa0bf784b97fa3cad0d4a5737bc5295785f5c613a1 \
        # via jinja2, pyramid-jinja2
    pastedeploy==2.0.1 \
        --hash=sha256:d423fb9d51fdcf853aa4ff43ac7ec469b643ea19590f67488122d6d0d772350a \
        --hash=sha256:fe53697ec2754703096b75d0ba29112b0590b4ce46726fe4f9408fd006e4eefc \
        # via plaster-pastedeploy
    plaster-pastedeploy==0.6 \
        --hash=sha256:71e29b0ab90df8343bca5f0debe4706f0f8147308a78922c8c26e8252809bce4 \
        --hash=sha256:c231130cb86ae414084008fe1d1797db7e61dc5eaafb5e755de21387c27c6fae \
        # via pyramid
    plaster==1.0 \
        --hash=sha256:215c921a438b5349931fd7df9a5a11a3572947f20f4bc6dd622ac08f1c3ba249 \
        --hash=sha256:8351c7c7efdf33084c1de88dd0f422cbe7342534537b553c49b857b12d98c8c3 \
        # via plaster-pastedeploy, pyramid
    pyramid-jinja2==1.8 \
        --hash=sha256:8d542c81f28db2e74af66437007adbca91ebd370935737c3dc53ed6497d42acd
    pyramid==1.10.1 \
        --hash=sha256:37c3e1c9eae72817e0365e2a38143543aee8b75240701fa5cb3a1be86c01a1c0 \
        --hash=sha256:3d5a6165854237b41ac67ced7697d8a884ab2b97625fabfa41b9e53d91187698 \
        # via pyramid-jinja2
    translationstring==1.3 \
        --hash=sha256:4ee44cfa58c52ade8910ea0ebc3d2d84bdcad9fa0422405b1801ec9b9a65b72d \
        --hash=sha256:e26c7bf383413234ed442e0980a2ebe192b95e3745288a8fd2805156d27515b4 \
        # via pyramid
    venusian==1.2.0 \
        --hash=sha256:2f2d077a1eedc3fda40425f65687c8c494da7e83d7c23bc2c4d1a40eb3ca5b6d \
        --hash=sha256:64ec8285b80b110d0ae5db4280e90e31848a59db98db1aba4d7d46f48ce91e3e \
        # via pyramid
    webob==1.8.5 \
        --hash=sha256:05aaab7975e0ee8af2026325d656e5ce14a71f1883c52276181821d6d5bf7086 \
        --hash=sha256:36db8203c67023d68c1b00208a7bf55e3b10de2aa317555740add29c619de12b \
        # via pyramid
    zope.deprecation==4.4.0 \
        --hash=sha256:0d453338f04bacf91bbfba545d8bcdf529aa829e67b705eac8c1a7fdce66e2df \
        --hash=sha256:f1480b74995958b24ce37b0ef04d3663d2683e5d6debc96726eff18acf4ea113 \
        # via pyramid
    zope.interface==4.6.0 \
        --hash=sha256:086707e0f413ff8800d9c4bc26e174f7ee4c9c8b0302fbad68d083071822316c \
        --hash=sha256:1157b1ec2a1f5bf45668421e3955c60c610e31913cc695b407a574efdbae1f7b \
        --hash=sha256:11ebddf765bff3bbe8dbce10c86884d87f90ed66ee410a7e6c392086e2c63d02 \
        --hash=sha256:14b242d53f6f35c2d07aa2c0e13ccb710392bcd203e1b82a1828d216f6f6b11f \
        --hash=sha256:1b3d0dcabc7c90b470e59e38a9acaa361be43b3a6ea644c0063951964717f0e5 \
        --hash=sha256:20a12ab46a7e72b89ce0671e7d7a6c3c1ca2c2766ac98112f78c5bddaa6e4375 \
        --hash=sha256:298f82c0ab1b182bd1f34f347ea97dde0fffb9ecf850ecf7f8904b8442a07487 \
        --hash=sha256:2f6175722da6f23dbfc76c26c241b67b020e1e83ec7fe93c9e5d3dd18667ada2 \
        --hash=sha256:3b877de633a0f6d81b600624ff9137312d8b1d0f517064dfc39999352ab659f0 \
        --hash=sha256:4265681e77f5ac5bac0905812b828c9fe1ce80c6f3e3f8574acfb5643aeabc5b \
        --hash=sha256:550695c4e7313555549aa1cdb978dc9413d61307531f123558e438871a883d63 \
        --hash=sha256:5f4d42baed3a14c290a078e2696c5f565501abde1b2f3f1a1c0a94fbf6fbcc39 \
        --hash=sha256:62dd71dbed8cc6a18379700701d959307823b3b2451bdc018594c48956ace745 \
        --hash=sha256:7040547e5b882349c0a2cc9b50674b1745db551f330746af434aad4f09fba2cc \
        --hash=sha256:7e099fde2cce8b29434684f82977db4e24f0efa8b0508179fce1602d103296a2 \
        --hash=sha256:7e5c9a5012b2b33e87980cee7d1c82412b2ebabcb5862d53413ba1a2cfde23aa \
        --hash=sha256:81295629128f929e73be4ccfdd943a0906e5fe3cdb0d43ff1e5144d16fbb52b1 \
        --hash=sha256:95cc574b0b83b85be9917d37cd2fad0ce5a0d21b024e1a5804d044aabea636fc \
        --hash=sha256:968d5c5702da15c5bf8e4a6e4b67a4d92164e334e9c0b6acf080106678230b98 \
        --hash=sha256:9e998ba87df77a85c7bed53240a7257afe51a07ee6bc3445a0bf841886da0b97 \
        --hash=sha256:a0c39e2535a7e9c195af956610dba5a1073071d2d85e9d2e5d789463f63e52ab \
        --hash=sha256:a15e75d284178afe529a536b0e8b28b7e107ef39626a7809b4ee64ff3abc9127 \
        --hash=sha256:a6a6ff82f5f9b9702478035d8f6fb6903885653bff7ec3a1e011edc9b1a7168d \
        --hash=sha256:b639f72b95389620c1f881d94739c614d385406ab1d6926a9ffe1c8abbea23fe \
        --hash=sha256:bad44274b151d46619a7567010f7cde23a908c6faa84b97598fd2f474a0c6891 \
        --hash=sha256:bbcef00d09a30948756c5968863316c949d9cedbc7aabac5e8f0ffbdb632e5f1 \
        --hash=sha256:d788a3999014ddf416f2dc454efa4a5dbeda657c6aba031cf363741273804c6b \
        --hash=sha256:eed88ae03e1ef3a75a0e96a55a99d7937ed03e53d0cffc2451c208db445a2966 \
        --hash=sha256:f99451f3a579e73b5dd58b1b08d1179791d49084371d9a47baad3b22417f0317 \
        # via pyramid

</details>

6. Install using `pip-sync requirements.txt`

<details>
  <summary>output</summary>
    Collecting hupper==1.4.2 (from -r /tmp/tmpcu_i_bis (line 1))
    Using cached https://files.pythonhosted.org/packages/d8/5f/242706fefee74df5d17d79c027d95c48d751aa5095f56d44d17d5045c224/hupper-1.4.2-py2.py3-none-any.whl
  Collecting jinja2==2.10 (from -r /tmp/tmpcu_i_bis (line 4))
    Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
  Collecting markupsafe==1.1.0 (from -r /tmp/tmpcu_i_bis (line 7))
    Using cached https://files.pythonhosted.org/packages/08/04/f2191b50fb7f0712f03f064b71d8b4605190f2178ba02e975a87f7b89a0d/MarkupSafe-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
  Collecting pastedeploy==2.0.1 (from -r /tmp/tmpcu_i_bis (line 36))
    Using cached https://files.pythonhosted.org/packages/67/0c/faa9971b2e5e048b3b30008d04c72e4d5f63b42f48937c169acce2c5e70a/PasteDeploy-2.0.1-py2.py3-none-any.whl
  Collecting plaster==1.0 (from -r /tmp/tmpcu_i_bis (line 39))
    Using cached https://files.pythonhosted.org/packages/61/29/3ac8a5d03b2d9e6b876385066676472ba4acf93677acfc7360b035503d49/plaster-1.0-py2.py3-none-any.whl
  Collecting plaster-pastedeploy==0.6 (from -r /tmp/tmpcu_i_bis (line 42))
    Using cached https://files.pythonhosted.org/packages/d9/e2/de7cd499923dbf6aacc9b243f262817bfea3ffbbd4dcc5847e1aaec817a7/plaster_pastedeploy-0.6-py2.py3-none-any.whl
  Collecting pyramid==1.10.1 (from -r /tmp/tmpcu_i_bis (line 45))
    Using cached https://files.pythonhosted.org/packages/4c/87/ec5697dec883ac96f2179ec83b31f9ee1b9482d8979ef83cba3b98f39c4e/pyramid-1.10.1-py2.py3-none-any.whl
  Collecting pyramid-jinja2==1.8 (from -r /tmp/tmpcu_i_bis (line 48))
    Using cached https://files.pythonhosted.org/packages/8b/ef/7ed063703d64a356f753825aeed07ba0b987015ef1bfdaeb26a6fb425372/pyramid_jinja2-1.8.zip
  Collecting translationstring==1.3 (from -r /tmp/tmpcu_i_bis (line 50))
    Using cached https://files.pythonhosted.org/packages/26/e7/9dcf5bcd32b3ad16db542845ad129c06927821ded434ae88f458e6190626/translationstring-1.3-py2.py3-none-any.whl
  Collecting venusian==1.2.0 (from -r /tmp/tmpcu_i_bis (line 53))
    Using cached https://files.pythonhosted.org/packages/21/80/8e2ac4aef69e927754277d29636b65eceb4767e9da90a2c3046c4176184a/venusian-1.2.0-py2.py3-none-any.whl
  Collecting webob==1.8.5 (from -r /tmp/tmpcu_i_bis (line 56))
    Using cached https://files.pythonhosted.org/packages/06/e1/4acd2b4327fceb4c6446bdbca515f807ab83188526fd654940c00bcf8cc3/WebOb-1.8.5-py2.py3-none-any.whl
  Collecting zope.deprecation==4.4.0 (from -r /tmp/tmpcu_i_bis (line 59))
    Using cached https://files.pythonhosted.org/packages/f9/26/b935bbf9d27e898b87d80e7873a0200cebf239253d0afe7a59f82fe90fff/zope.deprecation-4.4.0-py2.py3-none-any.whl
  Collecting zope.interface==4.6.0 (from -r /tmp/tmpcu_i_bis (line 62))
    Using cached https://files.pythonhosted.org/packages/19/17/1d198a6aaa9aa4590862fe3d3a2ed7dd808050cab4eebe8a2f2f813c1376/zope.interface-4.6.0-cp36-cp36m-manylinux1_x86_64.whl
  Requirement already satisfied: setuptools in ./.env/lib/python3.6/site-packages (from plaster==1.0->-r /tmp/tmpcu_i_bis (line 39)) (40.7.0)
  Building wheels for collected packages: pyramid-jinja2
    Building wheel for pyramid-jinja2 (setup.py) ... done
    Stored in directory: /home/bjmc/.cache/pip/wheels/c4/55/1c/d2f973f4ed8cc179925e2635e0f13e33408a97bb0ecd56221a
  Successfully built pyramid-jinja2
  Installing collected packages: hupper, markupsafe, jinja2, pastedeploy, plaster, plaster-pastedeploy, venusian, zope.interface, webob, translationstring, zope.deprecation, pyramid, pyramid-jinja2
  Successfully installed hupper-1.4.2 jinja2-2.10 markupsafe-1.1.0 pastedeploy-2.0.1 plaster-1.0 plaster-pastedeploy-0.6 pyramid-1.10.1 pyramid-jinja2-1.8 translationstring-1.3 venusian-1.2.0 webob-1.8.5 zope.deprecation-4.4.0 zope.interface-4.6.0
</details>

##### Expected result

The file `i18n.py` should exist in ./.env/lib/python3.6/site-packages/pyramid_jinja2/

##### Actual result

The file `i18n.py` is missing:

```
$ ls ./.env/lib/python3.6/site-packages/pyramid_jinja2/
compat.py  configure.zcml  demo  filters.py  __init__.py  __pycache__  scaffolds  tests
```

Note that forcing a re-install using vanilla pip will correctly create the file:

`pip install -U pyramid_jinja2`

<details>
  <summary>output</summary>
  Collecting pyramid_jinja2
  Using cached https://files.pythonhosted.org/packages/f4/dd/eb694f397c5c7bf7ce9104c868cdfd4279b78ceea34b832ebdb98af7130f/pyramid_jinja2-2.8-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: MarkupSafe in ./.env/lib/python3.6/site-packages (from pyramid_jinja2) (1.1.0)
Requirement already satisfied, skipping upgrade: zope.deprecation in ./.env/lib/python3.6/site-packages (from pyramid_jinja2) (4.4.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.5.0 in ./.env/lib/python3.6/site-packages (from pyramid_jinja2) (2.10)
Requirement already satisfied, skipping upgrade: pyramid>=1.3.0 in ./.env/lib/python3.6/site-packages (from pyramid_jinja2) (1.10.1)
Requirement already satisfied, skipping upgrade: setuptools in ./.env/lib/python3.6/site-packages (from zope.deprecation->pyramid_jinja2) (40.7.0)
Requirement already satisfied, skipping upgrade: translationstring>=0.4 in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (1.3)
Requirement already satisfied, skipping upgrade: venusian>=1.0 in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (1.2.0)
Requirement already satisfied, skipping upgrade: plaster-pastedeploy in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (0.6)
Requirement already satisfied, skipping upgrade: webob>=1.8.3 in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (1.8.5)
Requirement already satisfied, skipping upgrade: zope.interface>=3.8.0 in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (4.6.0)
Requirement already satisfied, skipping upgrade: plaster in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (1.0)
Requirement already satisfied, skipping upgrade: hupper in ./.env/lib/python3.6/site-packages (from pyramid>=1.3.0->pyramid_jinja2) (1.4.2)
Requirement already satisfied, skipping upgrade: PasteDeploy>=1.5.0 in ./.env/lib/python3.6/site-packages (from plaster-pastedeploy->pyramid>=1.3.0->pyramid_jinja2) (2.0.1)
Installing collected packages: pyramid-jinja2
  Found existing installation: pyramid-jinja2 1.8
    Uninstalling pyramid-jinja2-1.8:
      Successfully uninstalled pyramid-jinja2-1.8
Successfully installed pyramid-jinja2-2.8
</details>

Result:
```
ls ./.env/lib/python3.6/site-packages/pyramid_jinja2/
compat.py  configure.zcml  demo  filters.py  i18n.py  __init__.py  __pycache__  scaffolds  settings.py  tests
```

**Comment by atugushev** [comment]
That's because the release `pyramid_jinja2==1.8` doesn't have i18n.py in a source code. See:
https://github.com/Pylons/pyramid_jinja2/tree/23c6d918514cc89d70ee15c88dc2e097135fe1c9/pyramid_jinja2

**Comment by bjmc-globus** [comment]
Ok, I'll open an issue with them. Thanks.

**Comment by atugushev** [comment]
No problem, happy to help.
