### ISSUE TITLE
pip-compile cannot infer the correct version of dependencies

### ISSUE THREAD

**Issue by tribbloid** [jazzband/pip-tools#725]
Describe the issue briefly here.

##### Environment Versions

1. OS Type: Ubuntu 18.04
1. Python version: Python 3.6.7 :: Anaconda, Inc.
1. pip version:  pip 19.0.1 from /home/shared/anaconda3/lib/python3.6/site-packages/pip (python 3.6)
1. pip-tools version: pip-compile, version 3.3.2

##### Steps to replicate

1. 
create the following requirements.in

```
future >= 0.16.0
dronekit >= 2.9.1
dronekit-sitl >= 3.2.0
pymavlink >= 2.2.8
MAVProxy == 1.6.4
simplejson >= 3.10.0
```

2. run pip-compile under the same dir

##### Expected result

should generate requirements.txt

##### Actual result

```
Could not find a version that matches pymavlink==2.0.6,>=2.2.8
Tried: 2.0.6, 2.0.8, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.17, 2.2.18, 2.2.19, 2.2.20, 2.2.21, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4
There are incompatible versions in the resolved dependencies.
```

**Comment by atugushev** [comment]
Hello @tribbloid, thank you for the report!

It seems `dronekit` has pinned requirement `future==0.15.2` in release `2.9.1`, which conflicts with `requirements.in`. It's already fixed in master, see https://github.com/dronekit/dronekit-python/pull/873, but not released yet.

As a workaround i'd suggest to use in `requirements.in` the latest `dronekit` from git:
```
future >= 0.16.0
-e git+https://github.com/dronekit/dronekit-python.git@ed132c#egg=dronekit
dronekit-sitl >= 3.2.0
pymavlink >= 2.2.8
MAVProxy == 1.6.4
simplejson >= 3.10.0
```

Hope it helps!

**Comment by tribbloid** [comment]
Thanks a lot! yeah you are right, it is indeed displayed after enabling '-v'.

However after switching to the latest github build it triggers another error:

```
$ pip-compile -v
Using indexes:
  https://pypi.org/simple
Traceback (most recent call last):
  File "/home/shared/anaconda3/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/shared/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/piptools/scripts/compile.py", line 173, in cli
    dist = run_setup(src_file)
  File "/home/shared/anaconda3/lib/python3.6/distutils/core.py", line 227, in run_setup
    script_name)
RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script?

```

**Comment by tribbloid** [comment]
sorry, that was a low-level mistake, I accidentally ran a git revert which removed my requirements.in file. Problem solved

**Comment by atugushev** [comment]
No worries, happy to help!
