### ISSUE TITLE
Command in autogenerated requirements.txt can be shortened

### ISSUE THREAD

**Issue by ahmetb** [jazzband/pip-tools#726]
When I run `pip-compile`, my requirements.txt has

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
```

But I think the `--output-file requirements.txt` can just be dropped (for brevity) when the written file itself is named `requirements.txt`.

I'm recommending this because `pip-compile` already goes ahead and modifies `requirements.txt` when no options are specified. Thoughts?

**Comment by atugushev** [comment]
Hello @ahmetb, 

Sounds good to me.
