### ISSUE TITLE
Add option to circumvent the pip issue ''

### ISSUE THREAD

**Issue by tribbloid** [jazzband/pip-tools#728]
This issue:

https://github.com/pypa/pip/issues/562

```
Has prevented -e/--editable option to be used by pip install
```

Unfortunately for URL repo this is the only option, otherwise will trigger:

```
piptools.exceptions.UnsupportedConstraint: pip-compile does not support URLs as packages, unless they are editable. Perhaps add -e option? 
```

##### Environment Versions

OS Type: Ubuntu 18.04
Python version: Python 3.6.7 :: Anaconda, Inc.
pip version: pip 19.0.1 from /home/shared/anaconda3/lib/python3.6/site-packages/pip (python 3.6)
pip-tools version: pip-compile, version 3.3.2

##### Steps to replicate

1. in requirements.in, add the following line

```
-e git+https://github.com/dronekit/dronekit-python.git@ed132c#egg=dronekit
```

2. run pip-compile

##### Expected result

generate a requirements file without -e option

##### Actual result

a requirements file with -e option

**Comment by atugushev** [comment]
Hello @tribbloid,

Thank you for the issue report! Could you please describe what kind of an option do you request?

**Comment by atugushev** [comment]
Closed due to inactivity.
