### ISSUE TITLE
pip-sync uses first pip script on PATH instead of the one from the Python version it is run with

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [jazzband/pip-tools#734]
Describe the issue briefly here.

##### Environment Versions

1. OS Type: Android 8.1 aarch64/Latest Termux
1. Python version: 3.7.2
1. pip version:  `pip 18.1 from /data/data/com.termux/files/usr/lib/python2.7/site-packages/pip (python 2.7)` (pip3.7 --version is `pip 19.0.2 from /data/data/com.termux/files/usr/lib/python3.7/site-packages/pip (python 3.7)
1. pip-tools version: `pip-compile, version 3.3.2`

##### Steps to replicate

1. Get Termux
2. Run `pkg up && pkg install python python2`
3. Install pip on Python 3 (get-pip.py)
4. Install pip on Python 2 (get-pip.py)
5. Install piptools on Python 3
6. Use `pip-sync` with a requirements.txt file and watch it installing to Python 2

##### Expected result

Installs into Python 3 if ran on Python 3 and to Python 2 if ran on Python2

##### Actual result

Installs to whichever Python version `pip` script on `PATH` is from

##### Extra information

If using Python 2 and 3 together, an extra `pip-compile` and `pip-sync` script per Python major and per Python minor version to be able to select Python version to run piptools on would be very useful.

**Comment by atugushev** [comment]
Hello @kaeptmblaubaer1000,

Thank you for the detailed report! The issue probable is here:
https://github.com/jazzband/pip-tools/blob/200bc6bcc4950eb5628c1472638d66bfa7c860a2/piptools/sync.py#L140-L141

Since `pip` uses python2.7 it would install packages to python2. I think pip-sync should use `pip` or `pip3` depending on python version.

**Comment by kaeptmblaubaer1000** [comment]
Or use `console_scripts.pip` entry point and execute it inside the script.

**Comment by Asurasaintking** [comment]
I'm getting an : unable to locate pip
Error message
