### ISSUE TITLE
Readme: "requirements without setup.py" section doesn't warn that it considers existing requirements.txt file

### ISSUE THREAD

**Issue by m-aciek** [jazzband/pip-tools#744]
I just've lost couple of hours trying to figure out why `pip-compile` resolves my `requirements.in` to some old versions of packages. I'd like to propose adding a note to "requirements without setup.py" readme section, that would mention how to migrate from "plain `requirements.txt` workflow" to "`requirements.in` with pip-tools" without confusion.

##### Steps to replicate

1. Have requirements.txt with some package pinned.
2. Follow Readme in Example usage of `pip-compile` -> Without `setup.py`.

##### Expected result

Readme in this section warns the reader that his existing `requirements.txt` might interfere.

##### Actual result

Readme doesn't warn and reader is confused with the result of pip-compile.

**Comment by atugushev** [comment]
Hello @m-aciek,

Thank you for the report! It's a good idea. I think the "[without setup.py](https://github.com/jazzband/pip-tools#without-setuppy)" section could be rephrased something like:
> If you don't use setup.py (it's easy to write one), you can create a requirements.in **(make sure you don't have a requirement.txt file, otherwise... etc)** file to declare the Flask dependency:

@vphilippon WDYT? English native speaker needed here :)

**Comment by hramezani** [comment]
Can I work on this? seems easy :smile:
