### ISSUE TITLE
Wrong command name example in requirements.txt file using pip-compile

### ISSUE THREAD

**Issue by inkhey** [jazzband/pip-tools#755]
##### Environment Versions

1. OS Type: Debian
1. Python version: 3.5.3
1. pip version: 19.0.3
1. pip-tools version: 3.4.0

##### Steps to replicate

1.  use pip-tool 3.4
2. update requirement of a projet using pip-tools (i get this issue on tracim)
3. run  pip-compile --output-file requirements.txt setup.py
3. get wrong command header in requirements.txt .

##### Expected result

Same header as previously (v 3.3.2 work): 
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt setup.py
#
```
##### Actual result
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    setup.py --output-file requirements.txt setup.py
#
```

**Comment by keimlink** [comment]
A workaround is to set `CUSTOM_COMPILE_COMMAND` to the desired value:
```console
CUSTOM_COMPILE_COMMAND="pip-compile --output-file requirements.txt setup.py" pip-compile
```

**Comment by atugushev** [comment]
Hello @inkhey,

Thanks for the report! Unfortunately i can't reproduce it. Could you reproduce it on a fresh debian docker image?

**Comment by jdufresne** [comment]
I'm also unable to reproduce. This issue is getting quite old and has not received the requested followup, so I'm going to close for now. In addition, there have been several releases and improvements since this was reported. If you can still reproduce, please don't hesitate to reopen with additional details.
