### ISSUE TITLE
Updating requirements with extra does not update related package versions

### ISSUE THREAD

**Issue by Behoston** [jazzband/pip-tools#768]
Describe the issue briefly here.

##### Environment Versions

1. OS Type - Linux
1. Python version: 3.7.2
1. pip version: 19.0.3 
1. pip-tools version:  3.4.0

##### Steps to replicate

1. I have compiled requirements.in with:
```
A>=8
B[tool_1,tool_2]>=7
```

(tool_1 requires package A in any version)
and compiled file:

```
A==9.0.3
B[tool_1,tool_2]==7.7.7
...
```
2. I've added `tool_3` to package `B` that require package `A>=10`:
requirements.in
```
A>=8
B[tool_1,tool_2, tool_3]>=8.0.1
```
3. Then I've run `pip-compile` and the result was:
```
A==9.0.3
B[tool_1,tool_2,tool_3]==8.0.1
```

##### Expected result

Package `A` in version `10+` in compiled file.

##### Actual result
I need to remove `A` from the compiled file, compile again and compiled file contains valid version .

**Comment by atugushev** [comment]
Hello @Behoston,

Thank you for the report! Any chance to get a report with real packages? It would help a lot.

**Comment by Behoston** [comment]
No, package B is our private package. But maybe I can do sth similar on test pypi.

**Comment by AndydeCleyre** [comment]
@Behoston 

Can you check if the behavior changes with #1486?

I'm wondering about the relation of this to #1451 and #852.

**Comment by AndydeCleyre** [comment]
@Behoston 

As the suspected related issues and PR are closed and merged, and many releases have gone by, can you still reproduce the problem?

**Comment by atugushev** [comment]
It's been some time so I will close this issue now, but please don't hesitate to reach out if you have any other issues. Thanks!
