### ISSUE TITLE
Flask-OAuthlib has no working dependency setup

### ISSUE THREAD

**Issue by mcbloch** [jazzband/pip-tools#782]
The [Flask-OAuthlib](https://flask-oauthlib.readthedocs.io/en/latest/) library has no working dependency version setup using pip-tools.

It requires 'oauthlib' to be both <3.0.0 and >=3.0.0. I'm not sure if this issue is because of their requirements setup or because of wrong dependency resolution here.

##### Environment Versions

1. OS Type: Arch
1. Python version: `Python 3.7.3`
1. pip version:  `pip 19.0.3`
1. pip-tools version: `pip-compile, version 3.6.0`

##### Steps to replicate

1. `python -m venv venv`
2. `source venv/bin/activate`
3. `pip install pip-tools`
4. `echo "Flask-OAuthlib" > requirements.in`
5. `pip-compile requirements.in`

##### Expected result

Normal compilation.

##### Actual result

`Could not find a version that matches oauthlib!=2.0.3,!=2.0.4,!=2.0.5,<3.0.0,>=1.1.2,>=3.0.0
Tried: 0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0.post1, 1.1.1, 1.1.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.7, 2.1.0, 2.1.0, 3.0.0, 3.0.0, 3.0.1, 3.0.1
There are incompatible versions in the resolved dependencies.`

**Comment by mcbloch** [comment]
Found a related [issue](https://github.com/lepture/flask-oauthlib/issues/390) in their repository, I'm probably in the wrong place posting the above here.

**Comment by atugushev** [comment]
Hello @mcbloch,

Thanks for the report! Yes, that's unresolvable dependencies in `Flask-OAuthlib`. So nice you have already found the issue in their tracker! I'll close this issue then, feel free to reopen it if you need any help.
