### ISSUE TITLE
pip-compile with annotate and generate-hashes looses the annotations

### ISSUE THREAD

**Issue by gforcada** [jazzband/pip-tools#783]
Describe the issue briefly here.

Running ``pip-compile --annotate requirements.in`` returns a correctly annotated file, same if you change the ``--annotate`` for ``--generate-hashes``.

But if you combine them together only the hashes are shown on the final requirements.txt and no annotation is shown :confused: 

##### Environment Versions

1. OS Type **Fedora Linux 29**
1. Python version: `$ python -V` **3.7.2**
1. pip version:  `$ pip --version` **19.0.3**
1. pip-tools version: `$ pip-compile --version` **3.6.0**

##### Steps to replicate

1. Create a minimal requirements.in
2. Install pip-tools
3. Run ``pip-compile --annotate --generate-hashes requirements.in``
4. No annotation is shown on the output

##### Expected result
An output with both annotations as well as generated hashes.

##### Actual result
An output that is exactly the same as if the ``--annotate`` option was not given

**Comment by gforcada** [comment]
:blush: oops, I just noticed that they are indeed shown :sweat_smile: sorry for the noise! :bowing_man:

**Comment by atugushev** [comment]
Hello @gforcada! No worries 😊
