### ISSUE TITLE
pip-sync doesn't work with multiple files when version not specified

### ISSUE THREAD

**Issue by Behoston** [jazzband/pip-tools#786]
I have two files with same package. One of them require version above 0.10.0. Second does not require minimal version. Syncing is failing due to uncompatible version between both files.

##### Environment Versions

1. Python version: `3.7.3`
2. pip-tools version: `3.6.0`

##### Steps to replicate

```bash
mkdir /tmp/inc && cd /tmp/inc
echo "flask_jsonapi>=0.10.0" > a.txt
echo "flask_jsonapi" > b.txt
pip-sync ./*.txt
```

##### Expected result

Sync done with version 0.10.0 or above.

##### Actual result

```bash
Incompatible requirements found: flask_jsonapi (from -r ./b.txt (line 1)) and flask_jsonapi>=0.10.0 (from -r ./a.txt (line 1))
```

**Comment by atugushev** [comment]
Hello @Behoston, 

Thank you for the report! There's a reason. Packages in compiled `requirements.txt` are supposed to be pinned. See comment: https://github.com/jazzband/pip-tools/blob/9d0a91a382748a68f86d58a9e086b46a9b7c74f7/piptools/sync.py#L91-L95

But in any case you can force syncing by `pip-sync --force ./*.txt`.

**Comment by Behoston** [comment]
So, maybe when doing sync on multiple files pip-tools should do same job when `pip-compile` is called. First merge all to one requirements in-memory-file, then sync? It fix both issues - when no version provided and when
a.txt:
```
flask_jsonapi>=0.10.0
```
b.txt:
```
flask_jsonapi>=0.8.0
```

**Comment by atugushev** [comment]
The `flask_jsonapi>=0.10.0` and `flask_jsonapi>=0.8.0` are also not pinned. Pip-compile makes **only** pinned requirements like `flask_jsonapi==0.10.1`. Using `pip-compile` you will never get requirement like `flask_jsonapi>=0.10.0` in `requirements.txt`. See a note in the README:

> Be careful: pip-sync is meant to be used only with a requirements.txt generated by pip-compile.

All i'm saying the situation you described is not possible with `pip-compile&&pip-sync`.

**Comment by atugushev** [comment]
I'm closing this for now. Feel free to reopen it if you need further discussion.

**Comment by martinkozle** [comment]
What is the intended way to install dev dependencies then with this tool?
