### ISSUE TITLE
Describe how to use pip-tools with Flask and setup.py

### ISSUE THREAD

**Issue by slykar** [jazzband/pip-tools#787]
It's not very clear how you should use `pip-compile` when developing a Flask application.

In order to properly package a Flask application you need to create a `setup.py` file.
You then install it using `python setup.py develop` to start working with the code.

How I'm dealing with this:

1. define requirements in `setup.py`
2. Run `pip-compile` to generate `requirements.txt` file
3. Run `pip install -r requirements.txt -e .` to install pinned packages and Flask app in editable mode

It took me some time to figure this out (and stick to it), as I was trying too hard to make this work by just specifying `-r requirements.txt` and placing `-e .` in either `requirements.txt` file by hand or adding this to `requirements.in`.

I think it might be useful to add an example usage like this, since you are using Flask in your examples anyway and it might be hard for newbies to figure this out.

**Comment by atugushev** [comment]
Hello @slykar 

> 3\. Run `pip install -r requirements.txt -e .` to install pinned packages and Flask app in editable mode

Why not `pip-sync && pip install -e .`? 

> I think it might be useful to add an example usage like this, since you are using Flask in your examples anyway and it might be hard for newbies to figure this out.

IMO the `pip-tools` is supposed to work only with app's dependencies. If you want to install dependencies - just `pip-sync`. If you want to instal app in editable mode for a local development, simple use `pip install -e .`.

**Comment by slykar** [comment]
Hi @atugushev 

I completely agree that `pip-tools` should only install app deps. What I wanted to say, is that maybe there should be some sort of a cookbook on how to use `pip-tools` in different setups.

You have an example on homepage which is great, but it's more about showing how `pip-tools` work rather than focusing on any particular setup. I understand that maybe `pip-tools` as a generic tool should not concern itself with the setup it's used in, but providing a set of context specific examples is usually a great way to introduce new people to the tool.

I get questions like "How do I use it with Flask?" or "How do I use it with Django?" from colleagues I show `pip-tools` to. I thought why not describe it at source. A GitHub wiki would work fine.

I think I saw some other issues related to managing dev and prod dependencies on the issue tracker here, so it seems people are having some confusions / ideas / questions about using pip-tools in different scenarios.

---

About my workflow.

I'm usually putting `pip-tools` as a dev dependency in the `setup.py`, so first time install is always `pip install -r requirements.txt -e .[dev]`.

When running in Docker i just run `pip install -r requirements.txt -e .` to install a Flask application.

The `pip-sync` is what I would use during development, but I can't use it alone, because it will wipe my dev dependencies, so I don't use it at all. I know I could pin dev deps too, but I want them to be most recent.

That's not the point tough :)

**Comment by atugushev** [comment]
@slykar,

It's a good idea to have a cookbook for some of scenarios. Contributions are always welcomed :)

**Comment by atugushev** [comment]
Btw, why do you use `setup.py` for Flask app? 

I recommend to read this nice article https://caremad.io/posts/2013/07/setup-vs-requirement/ about when you should use setup.py or requirements.txt. Looks like you should use requirements.txt, not setup.py.

**Comment by slykar** [comment]
I could use `requirements.txt` with `-e .` in it, but `pip-compile` evaluates `-e .` from `requirements.in` file to a full local system path and this would make the generated `requirements.txt` file non transferable between environments.

Without installing your Flask application you won't be able to import it. So you either have to create a `setup.py` file to install your app or fiddle with Python paths like Django does.

**Comment by atugushev** [comment]
@slykar 

> Maybe instead of creating a guideline for other frameworks `pip-compile` should just fix the support for `-e .`

+1 on the fix. I'll link this to the #204 and close the issue then.
