### ISSUE TITLE
Nomalize 'To update, run' advice

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#788]
Currently when you regenerate a requirements.txt, if you run with syntactically different, but semantically identical command line flags the 'To update, run' advice changes.

The 'To update, run' advice should be normalized by:

* expanding short to long,
* removing values that are already default,
* sorting the arguments
* removing arguments that don't change build behaviour like 'verbose'

**Comment by atugushev** [comment]
Hello @graingert,

Thank you for raising this issue. Agree with you. Though it's a challenge since there is no convenient way to implement it via click's API.

**Comment by adamchainz** [comment]
Some arguments are also one-off for example `--upgrade-package django`.

**Comment by atugushev** [comment]
> Some arguments are also one-off for example `--upgrade-package django`.

You are right!

**Comment by atugushev** [comment]
@graingert, @adamchainz

I've prepared PR #800 for this. Please test/review it when you get a chance.
