### ISSUE TITLE
Allow specifying a base directory for relative pathing in pip-compile?

### ISSUE THREAD

**Issue by soapergem** [jazzband/pip-tools#797]
Suppose I have a package structure like this:

    .
    └── hello
        └── world
            ├── api
            │   └── requirements.in
            ├── shared
            │   └── requirements.in
            ├── tools
            │   └── requirements.in
            └── requirements.in

And suppose that these different requirements.in files are not independent. For instance, under hello/world/api/requirements.in, it may include this line:

    -r ../shared/requirements.in

And perhaps hello/world/tools/requirements.in includes these lines:

    -r ../shared/requirements.in
    -r ../requirements.in

What I'm wondering is if there's any way I can do away with the `..`s in the relative paths and instead replace these values with the path *relative to where pip-compile was invoked*? So for instance, if I'm calling pip-compile from the root, specifying each file as an argument, one by one, could I instead use lines like this one - even from further down the folder chain?

    -r hello/world/shared/requirements.in
    -r hello/world/requirements.in

As far as I can tell, currently the answer is "no". The reason I want this is because `..` is messy; I would contend it is harder to manage if one ever needs to restructure a package (many times you can move one folder around freely without any changes if you're able to use the kind of paths I'm describing). And I'm working on a big Makefile to build up all the different subpackages in a given repo, and it would make gathering of targets a lot easier if I didn't have to deal with paths relative to each file but instead was dealing with paths relative to the root of the repo.

I recognize that pip-compile is using pip internals under the hood so I'm not sure if this is even possible. But I thought I'd ask! If it were possible I imagine it would be done by adding some kind of optional parameter to pip-compile to set the basedir, e.g. `pip-compile -d $(pwd) hello/world/requirements.in`

**Comment by atugushev** [comment]
Hello @soapergem,

Thank you for the very detailed report!

> I recognize that pip-compile is using pip internals under the hood so I'm not sure if this is even possible. But I thought I'd ask! If it were possible I imagine it would be done by adding some kind of optional parameter to pip-compile to set the basedir, e.g. `pip-compile -d $(pwd) hello/world/requirements.in`

I'm afraid it's not possible to achieve it without hacks, since the `base dir` for references (`-r` and the other path related options) has been implemented deep down in `pip`.

**Comment by atugushev** [comment]
I'll close it for now. Feel free to reopen this issue if you'll have more questions.
