### ISSUE TITLE
pip-compile replaces password in URL with ****

### ISSUE THREAD

**Issue by jhoelzl** [jazzband/pip-tools#801]
I am using Python 3.6.8, pip-tools 19.1 and setuptools 41.0.1 in an virtual environment.

Since some days, when i compile my requirements.in file which includes a package format with an git repo url like:

```
...
-e git+http://user:password@myhost.com/scm/path/git-repo-name.git#egg=packagename
google-api-python-client
...
```

the password string in the url is replaces with "***":

```
...
-e git+http://user:****@myhost.com/scm/path/git-repo-name.git#egg=packagename
google-api-python-client==1.7.8
...
```

Is there a way to prevent this behaviour?

Regards,
Josef

**Comment by atugushev** [comment]
Hello @jhoelzl,

Thank you for the good catch! It seems the issue has been appeared since `pip>=19.0`, see https://github.com/pypa/pip/pull/5773. With the `pip==18.1` works good.
