### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#802]
When debugging issues pip-tools should be more helpful:

1. print/log executed commands, e.g. https://github.com/pypa/pip/blob/f8732ac06dcb7c6af81dcdc0cc3158196b796baf/src/pip/_internal/utils/misc.py#L721 - pip appears to have some logging for this (see the `--log` option), which could be configured for this
2. keep build directories, so that you can run the setup commands from there.  Currently pip cleans them up.

This could be triggered through `PIPTOOLS_DEBUG` in the environment, `-vv`, or a new `--debug` option.

It might be worth/good to have this with pip itself via an environment already, i.e. `PIP_DEBUG=1` would behave like using `--log=/dev/stderr`.

pip's logging get setup here: https://github.com/pypa/pip/blob/f8732ac06dcb7c6af81dcdc0cc3158196b796baf/src/pip/_internal/cli/base_command.py#L133-L137

**Comment by atugushev** [comment]
Hello @blueyed,

Sounds reasonable!

> 2\. keep build directories, so that you can run the setup commands from there.  Currently pip cleans them up.

Do you know how to force `pip` to keep build directories?

**Comment by atugushev** [comment]
Related to #321

**Comment by atugushev** [comment]
> * print/log executed commands, e.g. https://github.com/pypa/pip/blob/f8732ac06dcb7c6af81dcdc0cc3158196b796baf/src/pip/_internal/utils/misc.py#L721 - pip appears to have some logging for this (see the `--log` option), which could be configured for this
> * keep build directories, so that you can run the setup commands from there.  Currently pip cleans them up.

#1080 introduced `--pip-args`, so now any additional pip's options can be passed , e.g.:

```console
$ pip-compile --pip-args="--no-clean -vv"
```

I'll close this then. Feel free to reopen if it doesn't resolve the issue. Thanks!
