### ISSUE TITLE
pip-compile ignores deps with `--pre` in the input

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#818]
Using `--pre` in a requirements line results in the dependency to be ignored:

```
% echo '--pre channels' | pip-compile -q - -o -
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=- -
#
--index-url http://localhost:3141/root/pypi/+simple/
```

(Noticed this when coming up with #817)
pip-compile, version 3.6.2.dev2+ga3ac5ca

**Comment by atugushev** [comment]
@blueyed 

Do we really need `--pre` options in compiled requirements.txt? Since a package will be pinned with a prerelease version and would be installed on `pip-sync` anyways.

BTW, I've noticed that `--pre` doesn't work in requirements.in at all. See #819.

**Comment by blueyed** [comment]
@atugushev 
It is not needed, but I think it is a bug.
#819 is basically a duplicate of this one here.. :)

**Comment by blueyed** [comment]
But since #819 has more details, I'm closing this one here.
