### ISSUE TITLE
pip-compile generated requirements.txt has different file permissions

### ISSUE THREAD

**Issue by rickydunlop** [jazzband/pip-tools#823]
pip-compile sets different permissions for the requirements.txt file

We keep requirements.txt in git and noticed the permissions were being changed from `-rw-r--r--` to `-rw-------` when we updated some packages and ran `pip-compile`.

It may have been introduced by [this commit](https://github.com/jazzband/pip-tools/commit/964e8e74ce99cfed477b532a843c38a4cdb86d62) as downgrading to pip-tools 3.5 works ok.

##### Environment Versions

1. OS Type MacOS 10.14.5
1. Python version: 3.6.8
1. pip version:  19.1.1
1. pip-tools version: >3.5.0

##### Steps to replicate

1. setup.py
```
from setuptools import setup

setup(
    install_requires=[
        'requests'
    ],
)
```

2. install pip-tools
```
pip install pip-tools
```
3. run pip-compile
```
pip-compile --output-file requirements.txt setup.py
```
4. Check permissions of requirements.txt
```
ls -l requirements.txt
```
5. outputs `-rw-------`

6. delete the requirements.txt
```
rm -f requirements.txt
```
7. install pip-tools 3.5 and downgrade pip to 19.0.3
```
pip install pip-tools==3.5
pip install --upgrade pip==19.0.3
```
8. Run steps 3 - 5 again, output is `-rw-r--r--`

##### Expected result

The permission of the file should stay the same as the original requirements.txt

##### Actual result

The generated file has different permissions `-rw-------`

**Comment by atugushev** [comment]
Hello @rickydunlop,

Thanks for very detailed report and good catch! Right, this bug caused by #727.

**Comment by thanosexcite** [comment]
I would like to also add that an issue that I think is related to this bug is also that it will produce blank *.txt files in my use-case.

I run pip-tools from inside a docker container using docker-compose. My app source directory is mounted as a volume inside the container. Running the following using **pip-tools 3.5.0**:

```

**Comment by andersk** [comment]
I filed pallets/click#1376 for the upstream issue with unexpected permissions from `click.open_file(…, 'w', atomic=True)`.

**Comment by atugushev** [comment]
@andersk great, thanks!

**Comment by atugushev** [comment]
`click==7.1` is [released](https://click.palletsprojects.com/en/7.x/changelog/#version-7-1) with fix. Thanks @rickydunlop  for the issue and thanks @andersk  for the fix! 🙏
