### ISSUE TITLE
log which python version to use/was used

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#827]
eg add this to the header:

```
 # This file is autogenerated by pip-compile on:
 # Python 2.7.15+ (default, Oct  2 2018, 22:12:08) 
 # [GCC 8.2.0] on linux2
 # To update, run:
 #
 #    pip-compile --generate-hashes --output-file=requirements.txt requirements.in
```

**Comment by riordan** [comment]
Would be great to also log the pip version used. Some packages have minimum pip versions (as I'm finding out now), so if you run your pip-compile in an environment with a different pip version from the one you're installing into (e.g. fresh and new and 19.x on your local laptop, but stuck at 9.x on ubuntu in the docker container), it's possible to get installation incompatibility errors.

This'll help users identify that could be an environment difference causing issues.

**Comment by graingert** [comment]
@riordan the pip version is already logged if packages eronously depend on pip

Also you can use `pip install --no-deps --require-hashes -r requirements.txt`

**Comment by atugushev** [comment]
@riordan 

> Some packages have minimum pip versions (as I'm finding out now), so if you run your pip-compile in an environment with a different pip version from the one you're installing into (e.g. fresh and new and 19.x on your local laptop, but stuck at 9.x on ubuntu in the docker container), it's possible to get installation incompatibility errors.

Hello @riordan! You could use `--allow-unsafe` option, which allows you to pin `pip` in `requirements.txt` (by default it's commented-out as an unsafe package).

**Comment by atugushev** [comment]
@graingert 

> Also you can use `pip install --no-deps --require-hashes -r requirements.txt` to avoid pip dependency resolution getting in the way

Yeah, that should also work. Shouldn't we have `--no-deps` and `--require-hashes` in `pip-sync` as well?

**Comment by graingert** [comment]
`--require-hashes` is only useful when passed as a cli directly to the pip
invocation

**Comment by atugushev** [comment]
> `--require-hashes` is only useful when passed as a cli directly to the pip invocation

`pip-sync` invokes `pip install /tmp/file/with/requirements.txt`

**Comment by AndydeCleyre** [comment]
FWIW, zsh wrapper to accomplish this:

```bash
pip-compile-withpyver () {
    CUSTOM_COMPILE_COMMAND=$(
        print -l \
            "pip-compile ${(j: :)@}" \
            '#' \
            "# Last compiled with: ${(j: :)${(f)$(python -V)}}"
    ) pip-compile $@
}
```

```console
$ pip-compile-withpyver --generate-hashes requirements.in
```

```bash
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --generate-hashes requirements.in
#
# Last compiled with: Python 3.6.9 (1608da62bfc71e8ac775121dd0b21bb72e61c6ea, Dec 25 2019, 02:47:23) [PyPy 7.3.0 with GCC 9.2.0]
#
...
```
