### ISSUE TITLE
pip-compile --upgrade-package doesn't apply when requirements.txt doesn't exist

### ISSUE THREAD

**Issue by adamchainz** [jazzband/pip-tools#829]
I have some Django libraries I'm testing. I compile my `requirements.in` to multiple output files in a script, with a `--upgrade-package` (well `-P`) to pin each Django version.

I just discovered that if I remove the `.txt` files and run my script, the latest Django is output in each. If I run the script again, the second invocation of `pip-compile` then obeys the `--upgrade-package` pins.

One PR where I had to fix this: https://github.com/adamchainz/django-perf-rec/pull/198

##### Environment Versions

1. macOS
1. Python version: Pythons 3.5-3.7
1. pip version:  19.1.1
1. pip-tools version: 3.7.0

##### Steps to replicate

```
$ echo django > requirements.in
$ python -m piptools compile --upgrade-package 'django<2.2'
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
django==2.2.1
pytz==2019.1              # via django
sqlparse==0.3.0           # via django
$ python -m piptools compile --upgrade-package 'django<2.2'
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
django==2.1.8
pytz==2019.1              # via django
```

##### Expected result

Django should be pinned even when the output file doesn't exist. Sometimes it can't exist, such as when it's stdout!

##### Actual result

It isn't pinned unless the file exists

**Comment by atugushev** [comment]
Hello @adamchainz,

Thanks for the good catch!

**Comment by adamchainz** [comment]
I am working on a fix!

**Comment by atugushev** [comment]
Move this block outside of the `if not upgrade and os.path.exists(output_file.name)` statement should fix the issue https://github.com/jazzband/pip-tools/blob/4438d98544b396a01efeb37fe25675a0bb9be6ce/piptools/scripts/compile.py#L273-L279

**Comment by adamchainz** [comment]
Yes indeed! #831 🎉
