### ISSUE TITLE
Slow compile

### ISSUE THREAD

**Issue by Rizhiy** [jazzband/pip-tools#832]
Describe the issue briefly here.

##### Environment Versions

1. OS Type: Ubuntu 19.04
1. Python version: Python 3.7.3
1. pip version:  pip 19.0.3
1. pip-tools version: pip-compile, version 3.7.0

##### Steps to replicate
I have a new environment with the following `requirements.in`:
```
Cython
torch
torchvision
```
when I run `pip-compile` it just hangs.
Here is the output of `pip-compile -v`:
```
Using indexes:
  https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  Cython
  torch
  torchvision

Finding the best candidates:
  found candidate cython==0.29.10 (constraint was <any>)
  found candidate torch==1.1.0 (constraint was <any>)
  found candidate torchvision==0.3.0 (constraint was <any>)

Finding secondary dependencies:
  torchvision==0.3.0        requires numpy, pillow>=4.1.1, six, torch>=1.1.0
  torch==1.1.0 not in cache, need to check index
```

##### Expected result
Compiles normally

##### Actual result
Hangs on checking index?

**Comment by atugushev** [comment]
Hello @Rizhiy,

Looks like [torch package](https://pypi.org/project/torch/#files) have large size. Would be nice to see progress-bar though.

**Comment by Rizhiy** [comment]
The thing is, I haven't noticed that problem before, even though I was using torch with pip-compile for more than 6 months.

**Comment by Rizhiy** [comment]
And on my other machine using python3.5 this problem doesn't seem to occur, although it does have faster CPU

**Comment by atugushev** [comment]
> And on my other machine using python3.5 this problem doesn't seem to occur, although it does have faster CPU

Let me guess, was it `macosx`?

**Comment by Rizhiy** [comment]
Nope, both Linux

**Comment by atugushev** [comment]
> Nope, both Linux

Strange, because macox wheel weight 88.9 MB, but linux wheel - 676.9 MB.

**Comment by Rizhiy** [comment]
What does it do when checking the package? Does it download it? Or does it hash the contents?

**Comment by atugushev** [comment]
> What does it do when checking the package? Does it download it? Or does it hash the contents?

It does download it (the same as `pip install torch` and speed checking index and install should be the same). It will hash if you pass `--generate-hashes` to the `pip-compile`.

**Comment by Rizhiy** [comment]
Normally when I run `pip-compile`, I have already installed the package with pip. Is it possible to add functionality, such that pip-compile uses pip cached version of the package instead of downloading it again?

**Comment by atugushev** [comment]
> Is it possible to add functionality, such that pip-compile uses pip cached version of the package instead of downloading it again?

Actually it works this way. The `pip-compile` uses `pip` API to download package (to check dependencies), so it should use cached wheel for a package if it had been installed before. See:

```bash
# clear cache
$ rm -fr ~/Library/Caches/pip*

# make sure torch is not installed
$ pip uninstall torch
WARNING: Skipping torch as it is not installed.

# pip-compile torch
$ echo torch | pip-compile - -qo-

# See that pip uses cached torch
$ pip install torch
Collecting torch
  Using cached https://files.pythonhosted.org/packages/c9/e2/40f7f017437139e5dc076ea5ad4207da61250cc078bceef7d6f333c1d05c/torch-1.1.0-cp37-none-macosx_10_7_x86_64.whl
```

**Comment by Rizhiy** [comment]
TBH, I don't see why it would take so long if it is already downloaded.

**Comment by Rizhiy** [comment]
I don't use virtualenv, I use conda, can that be a problem?

**Comment by atugushev** [comment]
Should work with `conda`.

**Comment by atugushev** [comment]
I'm 99% sure that's the problem when pip-tools downloads large wheels. We need a progress-bar for that process.

**Comment by atugushev** [comment]
@Rizhiy 

Could you try your `requirements.in` with this version of pip-tools (#949)?

```bash
$ pip install git+https://github.com/atugushev/pip-tools.git@downloading-progress-bar#egg=pip-tools

$ pip-compile -v
```
