### ISSUE TITLE
Upgrading flask package loses transitive dependencies

### ISSUE THREAD

**Issue by tuukkamustonen** [jazzband/pip-tools#835]
Upgrading `flask` package removes also transitive dependencies.

##### Environment Versions

1. OS Type: `KDE Neon (Ubuntu 18.04)`
1. Python version: `3.7.2`
1. pip version:  `19.1.1`
1. pip-tools version: `3.8.0`

##### Steps to replicate

```
$ echo "flask==0.12.2" > requirements.in
$ pip-compile --no-header --no-index
click==7.0                # via flask
flask==0.12.2
itsdangerous==1.1.0       # via flask
jinja2==2.10.1            # via flask
markupsafe==1.1.1         # via jinja2
werkzeug==0.15.4          # via flask
$ echo "flask" > requirements.in
$ pip-compile --no-header --no-index -P flask
flask==1.0.3
```

So... upgrading `flask` package removed all transitive dependencies (for that package). `1.0.3` version still depends on `Jinja2` etc so they should be there.

Doesn't happen always, for example:

```
$ echo "pylint==2.0.0" > requirements.in
$ pip-compile --no-header --no-index
astroid==2.2.5            # via pylint
isort==4.3.20             # via pylint
lazy-object-proxy==1.4.1  # via astroid
mccabe==0.6.1             # via pylint
pylint==2.0.0
six==1.12.0               # via astroid
typed-ast==1.4.0          # via astroid
wrapt==1.11.2             # via astroid
$ echo "pylint" > requirements.in
$ pip-compile --no-header --no-index -P pylint
astroid==2.2.5            # via pylint
isort==4.3.20             # via pylint
lazy-object-proxy==1.4.1  # via astroid
mccabe==0.6.1             # via pylint
pylint==2.3.1
six==1.12.0               # via astroid
typed-ast==1.4.0          # via astroid
wrapt==1.11.2             # via astroid
```

Here, `pylint` upgrades and transitive dependencies are kept just fine.

**Comment by tuukkamustonen** [comment]
Actually, looks like `flask>=1.0.0` changed something as transitive dependencies never resolve via `pip-compile`:

```
$ echo "flask==0.12.4" > requirements.in
$ pip-compile --no-header --no-index
click==7.0                # via flask
flask==0.12.4
itsdangerous==1.1.0       # via flask
jinja2==2.10.1            # via flask
markupsafe==1.1.1         # via jinja2
werkzeug==0.15.4          # via flask
$ rm requirements.txt
$ echo "flask==1.0.0" > requirements.in
$ pip-compile --no-header --no-index
flask==1.0.0
```

If you just `pip install flask==1.0.0` it installs transitive dependencies just fine:

```
...
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.4 click-7.0 flask-1.0 itsdangerous-1.1.0
```

**Comment by atugushev** [comment]
Hello @tuukkamustonen,

Thanks for the report! I've tried to repeat the bug with the `flask` locally, but i couldn't confirm it. I'd suggest to try `pip-compile --rebuild` at first. Also would be nice to attach a log from `pip-compile --verbose` command.

**Comment by tuukkamustonen** [comment]
@atugushev `--rebuild` fixed the issue, thanks! Unfortunately, I ran it first, before doing `--verbose`, so the details on the faulty run are now lost :|

Anyway, what does it mean? Corrupted data? How did I end up with such?

**Comment by atugushev** [comment]
@tuukkamustonen 

> Anyway, what does it mean? Corrupted data? How did I end up with such?

Yes that's because the cache was somehow corrupted. Can't tell for sure why was that happened.  Probably by unknown bug.
