### ISSUE TITLE
How to pip-compile multiple requirements.txt in one line?

### ISSUE THREAD

**Issue by OdinTech3** [jazzband/pip-tools#838]
How can you `pip-compile` multiple requirements.txt in one command line. I was hoping that something like this was possible:

```bash
$ pip-compile requirements.in dev-requirements.in 
```
OR

```bash
$ pip-compile requirements/*.in
```
and then it would compile and generate the necessary txt file

**Comment by jakevdp** [comment]
It works how you hope if you specify the name of the output file; e.g.:
```bash
$ echo numpy > requirements_A.in
$ echo requests > requirements_B.in
$ pip-compile --output-file requirements.txt requirements_A.in requirements_B.in
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements_A.in requirements_B.in
#
certifi==2019.6.16        # via requests
chardet==3.0.4            # via requests
idna==2.8                 # via requests
numpy==1.16.4
requests==2.22.0
urllib3==1.25.3           # via requests
```

**Comment by atugushev** [comment]
Looks like @OdinTech3 wants to get `requirements_A.txt` and `requirements_B.txt` from `pip-compile requirements_A.in requirements_B.in`.

Currently it's impossible to do that, since `pip-tools` supports only one output file, so you have to compile each `*.in` file by separate commands.

**Comment by OdinTech3** [comment]
I see. so @atugushev  Is there any interest in supporting supporting this feature? or are there limitations in supporting it.

**Comment by jakevdp** [comment]
One option to do this in one command is to use bash xargs, e.g.
```bash
$ !echo requirements*.in | xargs -n1 pip-compile
```

**Comment by georgek** [comment]
What's the reason for needing this? pip-compile produces one output file. If you want two then you run it twice. Use xargs if you must have it in "one line".

**Comment by atugushev** [comment]
@OdinTech3 

> I see. so @atugushev Is there any interest in supporting supporting this feature? or are there limitations in supporting it.

I would call it deliberate design decision.

**Comment by OdinTech3** [comment]
Alright thank you all for your answers and support.

**Comment by toransahu** [comment]
> What's the reason for needing this? pip-compile produces one output file. If you want two then you run it twice. Use xargs if you must have it in "one line".

Suppose a project has:

```
# requirements.in
Flask
```

```
# dev-requirements.in
-r requirements.in
pytest
```

What I expect is:

```
# requirements.txt
Flask==1.1.1
```

```
# dev-requirements.txt
-r requirements.txt
pytest==2.2.2
```

[Note the `-r` (refer/import a file) here.]


Why?

To make sure that dev-requirements.txt has the same version of dependencies as requirements.txt

But, today, what pip-compile supports/does is: generate a single output file, thus it needs:

`pip-compile requirements.in`, that generates 

```
# requirements.txt

Flask==1.1.1
```

& 

`pip-compile dev-requirements.in`, that generates 

```
# dev-requirements.txt
Flask==1.1.1
pytest==2.2.2
```

However, as both the commands might run at different times, there is a slight chance that dev-requirements.txt could have some version of `Flask` other than the requirements.txt.

To avoid such an out-of-sync issue, I expect it to generate multiple .txt files corresponding to each .in file in one go.

Or, pip-compile should honor the `-r` (refer/import a file) in the files and keep them as they are without expanding/unpacking them.
