### ISSUE TITLE
pip-compile --quiet --upgrade --dry-run --output-file - should produce output

### ISSUE THREAD

**Issue by shipmints** [jazzband/pip-tools#843]
Describe the issue briefly here.

Environment Versions
OS Type
$ uname -v
Darwin Kernel Version 16.7.0: Thu Dec 20 21:53:35 PST 2018; root:xnu-3789.73.31~1/RELEASE_X86_64

Python version: $ python -V
$ python -V
Python 3.7.3

pip version: $ pip --version
$ pip --version
pip 19.0.3[snip]

pip-tools version: $ pip-compile --version
$ pip-compile --version
pip-compile, version 3.8.0

Steps to replicate
Run pip-compile --output-file requirements.pc requirements.in
Run pip-compile --quiet --upgrade --dry-run --output-file - # note the dash as stdout moniker

Note: We use --quiet because we also use --output-file (we don't need/want both). 

Expected result
stdout should have requirements.pc should be left alone if --upgrade is used with --dry-run.

Actual result
stdout produces no output.

Commentary

Please refer to #841

**Comment by atugushev** [comment]
Hello @shipmints,

Thanks for creating this separate issue! Could you explain why do you need these both `--dry-run` and `--output-file=-` options? I'm just curious because it makes no sense to me, since you can't update `stdout`.

**Comment by shipmints** [comment]
Let's chalk this up to my misunderstanding. I will close this issue and start using stdout output without the --dry-run flag to achieve the same effect which is basically to "diff" the existing pip-compile file with what an upgraded one would look like. Using stdout prevents a temporary file from being created which is a bit more convenient as diff can accept a stream on stdin e.g.,
```shell
pip-compile --quiet --upgrade --output-file - | diff -- requirements.pc -
```

To me, it's still a bug that the behavior of the command line should be identical no matter what I set --output-file to point to, a file or a stream.

**Comment by atugushev** [comment]
@shipmints 

The thing is the `--dry-run` flag just turns off writing to the `--output-file`.  But i must admit there is a little mess up with `--dry-run` and `--quiet` options.

**Expected result**

- `--dry-run` should print changes to stdout/stderr
- `--dry-run` should prevent from touching `requirements.txt`
- `--quiet` should suppress _"Dry-run, so nothing updated."_ message 

```bash
$ pip-compile --upgrade --dry-run --quiet
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
six==1.12.0
```

**Actual result**

But currently it behaves the opposite way:

```bash
$ pip-compile --upgrade --dry-run --quiet
Dry-run, so nothing updated.
```

Looks like a bug, isn't it?
