### ISSUE TITLE
Incorrect output on pip-compile upgrade with --dry-run and --quiet flags

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#845]
##### Environment Versions

1. OS Type: any
1. Python version: any
1. pip version:  any
1. pip-tools version: 3.8.0

##### Steps to replicate

1. `echo "six" > requirements.in`
1. `pip-compile`
1. `pip-compile --upgrade --dry-run --quiet`

##### Expected result

- `--dry-run` should print changes to stdout/stderr
- `--quiet` should suppress _"Dry-run, so nothing updated."_ message 

```bash
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
six==1.12.0
```

##### Actual result

But currently it behaves the opposite way:

```
Dry-run, so nothing updated.
```

---

Refs: 

- #843 
- https://github.com/jazzband/pip-tools/issues/841#issuecomment-508454216

**Comment by AndydeCleyre** [comment]
I think the state now is that the dry run message is indeed suppressed by the quiet flag, but so is the output.

Do we want the dry run flag to effectively bypass the log level for the stderr copy of output? Something like

```diff
--- a/piptools/writer.py
+++ b/piptools/writer.py
@@ -245,10 +245,12 @@ class OutputWriter:
     ) -> None:

         for line in self._iter_lines(results, unsafe_requirements, markers, hashes):
-            log.info(line)
             if not self.dry_run:
+                log.info(line)
                 self.dst_file.write(unstyle(line).encode())
                 self.dst_file.write(os.linesep.encode())
+            else:
+                log.log(line)

```

**Comment by AndydeCleyre** [comment]
The above change would break two current tests:

- `test_quiet_option`
- `test_dry_run_quiet_option`

This is because the command

```console
pip-compile --quiet --dry-run
```

would produce the header comment in stderr, instead of an empty stderr.

That doesn't violate what the tests intend to check for exactly, IMO.
