### ISSUE TITLE
New feature:Option to find the latest version for each package

### ISSUE THREAD

**Issue by PhilippSontag** [jazzband/pip-tools#849]
I am currently using pip compile to pin my requirements. But because some packages might be pinned by other packages or some inter dependencies I don't always get the latest available version for every package. I would like an easy way to find the latest version for every package I use and thought that this feature might fit into pip-tools.

Currently I see the following options on how to add this feature to piptools:
1. A new command the finds the latest version for every package and writes them to a file/stdout
2. Add a new option to pip compile to do 1.
3. Add a new option to pip compile that adds the latest version as an annotation.

Do you think this would be a good addition to pip-tools? If yes I would be willing to implement it myself.

**Comment by atugushev** [comment]
Hello @PhilippSontag,

You can simply find the latest version for each package in a file by this bash one-liner:

```bash
$ cat packages.txt
six
pytz
django
flask
uwsgi
django-rest-framework

$ cat packages.txt | while read line; do echo "$line" | pip-compile - -qo- | grep "$line=="; done
six==1.12.0
pytz==2019.1
django==2.2.3
flask==1.1.1
uwsgi==2.0.18
django-rest-framework==0.1.0
```

**Comment by atugushev** [comment]
@PhilippSontag 

I think it's a good idea for a tool outside of `pip-compile`. Seriously. There is no tool that provide you latest version (or a list of recent versions) for a certain package.

**Comment by PhilippSontag** [comment]
Hey @atugushev thank you for your answer.

> I think it's a good idea for a tool outside of pip-compile. Seriously. There is no tool that provides latest version (or a list of recent versions) for a certain package.

With `outside` do you mean outside of `pip-tools`, so a separate package or do you mean a separate script inside the `pip-tools` package?

**Comment by atugushev** [comment]
@PhilippSontag sorry, i mean of `pip-tools`.

**Comment by AndydeCleyre** [comment]
What's desired here that's not provided by

```bash
pip-compile --no-header -U
```
and
```bash
pip list -o
```
?

**Comment by AndydeCleyre** [comment]
@PhilippSontag 

Is the above satisfactory?

**Comment by PhilippSontag** [comment]
Yes, sorry for the late response.

**Comment by Alex3917** [comment]
Just wanted to say that it would also be great if this were built into pip-tools. What I want specifically is a way to list only my outdated requirements that are listed in `requirements.in`.

This script: `cat packages.txt | while read line; do echo "$line" | pip-compile - -qo- | grep "$line=="; done`

Doesn't actually work for that, because it only works for packages that aren't pinned to a specific version. I could obviously figure out how to modify that bash script to do this, but it seems like this is something that would benefit everyone if it were just built into pip-tools.
