### ISSUE TITLE
Release 3.9.0

### ISSUE THREAD

**Issue by kdmccormick** [jazzband/pip-tools#850]
Apologies in advance if you folks already have a release cadence that I'm not aware of, but I've been excitedly waiting to have [constraint provenance](https://github.com/jazzband/pip-tools/pull/837) be available in several repositories that use pip-tools. A 3.9.0 release would be appreciated. Thanks!

**Comment by atugushev** [comment]
Hello @kdmccormick,

Thanks for reminding. I'll prepare a release within 24h.

**Comment by vphilippon** [comment]
@atugushev Thanks for doing the release, I just approved it to get it on PyPi: https://pypi.org/project/pip-tools/

Cheers!

**Comment by atugushev** [comment]
Thanks @vphilippon!

**Comment by kdmccormick** [comment]
Thanks all!

**Comment by georgek** [comment]
This should have been 4.0.0 because of #353. It's a breaking change in behaviour.
