### ISSUE TITLE
There are incompatible versions in the resolved dependencies:

### ISSUE THREAD

**Issue by Srinidhi1994** [jazzband/pip-tools#862]
Describe the issue briefly here.

##### Environment Versions

1. OS Type Mac
1. Python version: Python 2.7.12
1. pip version:  pip 19.2.1 
1. pip-tools version: pip-compile, version 4.0.0

##### Steps to replicate
1. trying 'make upgrade' ... but end up getting the following error
pip-compile --no-emit-trusted-host --no-index --upgrade -o requirements/edx/base.txt requirements/edx/base.in

##### Actual result
Could not find a version that matches edx-opaque-keys<1.0.0,<2.0.0,==1.0.1,>=0.1.2,>=0.2.1,>=0.4,>=0.4.0,>=1.0.0,>=1.0.1 (from -r requirements/edx/paver.txt (line 9))
Tried: 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 1.0.0, 1.0.1
There are incompatible versions in the resolved dependencies:
  edx-opaque-keys (from edx-drf-extensions==2.3.8->-r requirements/edx/base.in (line 73))
  edx-opaque-keys<1.0.0,>=0.4.0 (from XModule==0.1.1->-r requirements/edx/local.in (line 10))
  edx-opaque-keys<2.0.0,>=1.0.0 (from edx-user-state-client==1.1.1->-r requirements/edx/base.in (line 84))
  edx-opaque-keys<2.0.0,>=1.0.1 (from edx-ccx-keys==0.2.2->-r requirements/edx/base.in (line 69))
  edx-opaque-keys==1.0.1 (from -r requirements/edx/paver.txt (line 9))
  edx-opaque-keys>=0.1.2 (from edx-organizations==2.1.0->-r requirements/edx/base.in (line 79))
  edx-opaque-keys>=0.2.1 (from edx-milestones==0.2.3->-r requirements/edx/base.in (line 77))
  edx-opaque-keys>=0.4 (from edx-proctoring==2.0.6->-r requirements/edx/base.in (line 80))
  edx-opaque-keys[django] (from edx-completion==2.0.0->-r requirements/edx/base.in (line 71))
  edx-opaque-keys[django] (from edx-enterprise==1.8.6->-r requirements/edx/base.in (line 76))

...

**Comment by atugushev** [comment]
Hello @Srinidhi1994,

Thanks for the report! It seems `make upgrade` is from https://github.com/edx/edx-enterprise/blob/bd56ba2908e1b028e7c73ce9ce17413419a5b850/Makefile#L84-L91, right?

Could you please attach all your `requirements/edx/*` files you've been trying to compile? It would help to reproduce the issue locally.

**Comment by krasnovmv** [comment]
I think problem in XModule package that have in setup_requires edx-opaque-keys<1.0.0,>=0.4.0, but other setup_requires incompatible with this version, and pip-tools cant find version, which resolve all conditions.

**Comment by atugushev** [comment]
@krasnovmv 

You are right, XModule==0.1.2 has updated `edx-opaque-keys` dependency and has removed `<1.0.0`. See for details https://github.com/edx/edx-platform/commit/45e390d0eaf3a543ba50f893823c296c5de4e29f.

**Comment by atugushev** [comment]
I'll close this. Feel free to reopen it if you have any questions.
