### ISSUE TITLE
show via for direct deps

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#881]
Currently when compiling, direct deps do not include a 'via' declaration. eg:

```
git grep "# via"
...
requirements.txt:    # via entrypoints, flake8, importlib-metadata, pylint
...
```

however it is missing from direct dependencies.

I propose:

```
# via ./requirements.in, etc, etc
```
for direct deps

**Comment by graingert** [comment]
Or:

```
# directly and via etc, etc
```

to avoid squatting any possible future package name namespace

**Comment by atugushev** [comment]
Hello @graingert! What do you mean by "direct deps"?

**Comment by graingert** [comment]
Deps discovered in the .in file

**Comment by atugushev** [comment]
I see. Could you please provide a real example the current behavior and what is you proposing?

**Comment by graingert** [comment]
The current behaviour is that some dependencies in the generated requirements.txt do not include a # via comment.  I'd prefer it if all dependencies included a # via comment

**Comment by atugushev** [comment]
> The current behaviour is that some dependencies in the generated requirements.txt do not include a # via comment.

Could you show an example?

**Comment by graingert** [comment]
No it's not possible because the comment is missing

**Comment by atugushev** [comment]
Okay, let's suppose:

```bash
$ cat requiremets.in
django

$ pip-compile
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
django==2.2.4
pytz==2019.2              # via django
sqlparse==0.3.0           # via django
```

The `django` is a "direct dependency" (or primary package). So, do you want to see "# via requirements.in" in front of the "django" in requirements.txt? For example:

```bash
$ cat requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
django==2.2.4             # via requirements.in
pytz==2019.2              # via django
sqlparse==0.3.0           # via django
```

**Comment by graingert** [comment]
> Okay, let's suppose:
> 
> ```shell
> $ cat requiremets.in
> django
> ```
```
  django-debug-toolbar
```
> ```
> $ pip-compile
> #
> # This file is autogenerated by pip-compile
> # To update, run:
> #
> #    pip-compile
> #
> django==2.2.4
> pytz==2019.2              # via django
> sqlparse==0.3.0           # via django
> ```
> 
 The `django` is a "direct dependency" (or primary package). So, do you want to see "# via requirements.in" close to the "django" in requirements.txt? For example:
> 
> ```shell
> $ cat requirements.txt
> #
> # This file is autogenerated by pip-compile
> # To update, run:
> #
> #    pip-compile
> #
> ```
```
  django==2.2.4             # directly and via django-debug-toolbar
```
> ```
> pytz==2019.2              # via django
> sqlparse==0.3.0           # via django
> ```
```
  django-debug-toolbar==...
```

**Comment by prebeta** [comment]
I would like to see a feature like this. It'd be nice to know the dependencies between my explicitly declared packages.

**Comment by AndydeCleyre** [comment]
I welcome feedback on the state of #1058. At the time of this comment:

```console
$ cat requirements.in
django
django-debug-toolbar
$ pip-compile --no-header requirements.in
asgiref==3.2.3            # via django
django-debug-toolbar==2.2  # via -r requirements.in (line 2)
django==3.0.3             # via -r requirements.in (line 1), django-debug-toolbar
pytz==2019.3              # via django
sqlparse==0.3.0           # via django, django-debug-toolbar
```
