### ISSUE TITLE
Refresh "Pin Your Packages" article

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#883]
Hello @nvie. In the [README](https://github.com/jazzband/pip-tools/blob/master/README.rst) we've got very first paragraph:

> A set of command line tools to help you keep your `pip`-based packages fresh,
even when you've pinned them. [You do pin them, right?](https://nvie.com/posts/pin-your-packages/).

... with a [link](https://nvie.com/posts/pin-your-packages/) to your great article about pinning packages and some basis of pip-tools. It's outdated now, since pip-dump and pip-review are no longer exist. How could we help you to update it?

**Comment by nvie** [comment]
Hey @atugushev! Thanks for reaching out. If you want to keep linking it to a blog post that provides context, you could link it to the follow-up post instead: https://nvie.com/posts/better-package-management/

**Comment by atugushev** [comment]
@nvie thanks for quick answer! How would you like to link it in the text?

**Comment by nvie** [comment]
I don't personally maintain this library anymore – it's a jazzband collective now! But I would suggest you open a PR for it and make everyone part of the discussion.

**Comment by atugushev** [comment]
I've seen you've updated the article:

> Update: A newer blog post about the future of pip-tools is available too: [Better Package Management](https://nvie.com/posts/better-package-management/).

This, probably, should be enough.

**Comment by atugushev** [comment]
Thanks @nvie!
