### ISSUE TITLE
annotations not working

### ISSUE THREAD

**Issue by henrymwang** [jazzband/pip-tools#890]
Describe the issue briefly here.

##### Environment Versions

1. MacOS 
1. Python version: `$ python -V`: `Python 3.7.1`
1. pip version:  `$ pip --version`: `pip 19.2.3`
1. pip-tools version: `$ pip-compile --version`: `pip-compile, version 4.1.0`

##### Steps to replicate

1. run `pip-compile --annotate requirements.in`

##### Expected result

annotations should appear

##### Actual result

no annotations

**Comment by henrymwang** [comment]
Here is my `requirements.in` file:

```
aspy.yaml==1.3.0
cachetools==3.1.1
certifi==2019.6.16
cfgv==2.0.1
chardet==3.0.4
Click==7.0
google-api-core==1.14.2
google-auth==1.6.3
google-cloud-bigquery==1.19.0
google-cloud-core==1.0.3
google-resumable-media==0.4.0
googleapis-common-protos==1.6.0
identify==1.4.7
idna==2.8
importlib-metadata==0.21
more-itertools==7.2.0
nodeenv==1.3.3
pip-tools==4.1.0
pre-commit==1.18.3
protobuf==3.9.1
pyasn1==0.4.7
pyasn1-modules==0.2.6
pytz==2019.2
PyYAML==5.1.2
requests==2.22.0
rsa==4.0
six==1.12.0
toml==0.10.0
urllib3==1.25.3
virtualenv==16.7.5
zipp==0.6.0
```

**Comment by atugushev** [comment]
Thanks for submitting this. It looks like you are using pip-tools in a wrong way. Several recommendations:

1. in requirements.in you should put only top-level dependencies like `pre-commit`
1. Do not include in requirements.in sub-dependencies (eg aspy.yaml is a dependency of pre-commit), let do all the work for dependencies to `pip-compile`. All sub-dependencies `pip-compile` puts in requirements.txt and mark them `via {top-level-package}` annotation.
1. Do not pin top-level packages in requirements.in, unless it is necessary.

Some good articles to read: 
https://nvie.com/posts/better-package-management/#virtue-1-declare-only-your-top-level-dependencies
https://nvie.com/posts/pin-your-packages/

**Comment by atugushev** [comment]
Also the annotations will be lost if you run by mistake pip-compile with the output `requirements.txt` :) Check the extension please, make sure sure you do run with the input `requirements.in` file.

**Comment by henrymwang** [comment]
Thanks, it works now!

**Comment by atugushev** [comment]
@henrymwang what was the problem actually?

**Comment by henrymwang** [comment]
I started my `requirements.in` file with `pip freeze > requirements.in`, so all of the non-top-level dependencies were already present.
