### ISSUE TITLE
dry-run output goes to stderr

### ISSUE THREAD

**Issue by Redoubts** [jazzband/pip-tools#892]
Describe the issue briefly here.

I updated to V 4.1.0, and I find that the --dry-run output goes to standard error. I could have sworn the 3.* series went to stdout. Why the change, was this intentional? I would expect the dry run content to go to stdout, but any notices and logging to stay in stderr.

##### Environment Versions

1. OS Type: macOS
1. Python version: `Python 2.7.16 :: Anaconda, Inc.`
1. pip version:  `pip 19.2.2 from ~/anaconda/lib/python2.7/site-packages/pip (python 2.7)`
1. pip-tools version: `pip-compile, version 4.1.0`

##### Steps to replicate

1. `pip-compile -n  =(echo "-e .[Server,Orchestrator,Tests]") 2>/dev/null`

##### Expected result

Output

##### Actual result

No output

**Comment by atugushev** [comment]
Hello @Redoubts,

Thanks for bringing up this. There was a breaking change (or a bugfix) in #834.

**Comment by Redoubts** [comment]
Cool. Looks like the solution is `-o -`, which makes sense.

**Comment by Redoubts** [comment]
It looks like I can get back to where I was with `-o - -q, which makes sense.

**Comment by atugushev** [comment]
That depends on what you are trying to achieve. Would you describe your case, why do you use `--dry-run`?

**Comment by Redoubts** [comment]
I have a library with downstream users, and for them I want my setup.py to have `install_requirements` as loose as possible. But I've constantly run into reproducibility issues in my CI, so in that environment I pin everything exactly. I use pip-compile to build this list, and I stick the output in my setup.py as well. So something like

```
## setup.py

install_requirements = [
    'dependency', 
    ...
]

if os.getenv("MY_CI"):
    # This is for reproducible builds Use gen_requirements.sh to build this list.
    install_requirements = [
        'dependency=1.2.3',
        ...
    ]
```

Then the pins get manually bumped. I've seen several other strategies on how to handle this, but as a matter of taste I don't like putting requirements across several files.

**Comment by Redoubts** [comment]
I suppose now I wouldn't do `-n` either, but I would now do something like

`pip-compile -i https://internal.pypi =(echo "-e .[Server,Orchestrator,Tests]") -o - -q --no-header | grep -vE "^-|^#" | sed -E 's/^([^[:space:]]+) *(.*)$/"\1",  \2/g'` to get text I can copy and paste into setup.py.

**Comment by atugushev** [comment]
I see. Thanks for the clarification! Yeah, `pip-compile -qo-` should work for your case.

**Comment by atugushev** [comment]
I'll close this since you've found a workaround. Please let us know if you have any other issues. Thanks!
