### ISSUE TITLE
Add @pytest.mark.network to tests which require the internet

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#895]
#### What's the problem this feature will solve?

It would be good to split the parameterized, and revise the tests unnecessarily using online data, and mark any real unavoidable online tests with a pytest marker called 'internet' or 'online' so that I (and other packagers) could use the following.

_Posted in its original form by @jayvdb in https://github.com/jazzband/pip-tools/issues/887#issue-491806159._

#### Describe the solution you'd like

Add `@pytest.mark.network` to the following tests:

- test_allow_unsafe_option
- test_annotate_option
- test_editable_package
- test_editable_package_vcs
- test_editable_top_level_deps_preserved
- test_filter_pip_markers
- test_generate_hashes_all_platforms
- test_generate_hashes_verbose
- test_generate_hashes_with_editable
- test_generate_hashes_with_url
- test_generate_hashes_without_interfering_with_each_other
- test_get_hashes_local_repository_cache_miss
- test_input_file_without_extension
- test_locally_available_editable_package_is_not_archived_in_cache_dir
- test_no_candidates
- test_no_candidates_pre
- test_pre_option
- test_realistic_complex_sub_dependencies
- test_stdin
- test_url_package

#### Additional context

Following up #887.

**Comment by peymanslh** [comment]
Hello  
Can I work on this issue and send a pull request?

**Comment by atugushev** [comment]
Hello @peymanslh,

Sure! Please, feel free to.

**Comment by peymanslh** [comment]
@atugushev 
I sent a pr: [#917 ](https://github.com/jazzband/pip-tools/pull/917)

**Comment by atugushev** [comment]
Thanks for the contribution @peymanslh! Would you like to work on [another issue](https://github.com/jazzband/pip-tools/issues?q=is%3Aissue+is%3Aopen+label%3A%22PR+wanted%22)? 😎

**Comment by peymanslh** [comment]
@atugushev 
Yes, sure!
