### ISSUE TITLE
pip-compile --no-header <blank requirements.in> neither creates nor overwrites requirements.txt

### ISSUE THREAD

**Issue by AndydeCleyre** [jazzband/pip-tools#900]
If `requirements.in` is empty, running `pip-compile` will create or clobber `requirements.txt`, thereby removing all requirements, but if `--no-header` is passed to `pip-compile`, `requirements.txt` will not be affected in any way, no matter its state.

#### Environment Versions

1. Linux
1. Python version: `3.7.4`
1. pip version:  `19.2.3`
1. pip-tools version: `4.1.0`

#### Steps to replicate

```bash
touch requirements.in
pip-compile --no-header
# no txt file created (unexpected)
pip-compile
# txt file created (as expected)
echo plumbum > requirements.in
pip-compile
echo > requirements.in
pip-compile --no-header
cat requirements.txt
```
full, unexpected:
```python
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
plumbum==1.6.7
```

**Comment by atugushev** [comment]
Hello @AndydeCleyre,

Thanks for the report! That's a good catch!

**Comment by AndydeCleyre** [comment]
I'll submit a pull request for this today. Would it be preferable for the writer line iterator to simply always yield a final extra newline, or to actually keep track of whether or not it has yielded any real lines along the way, and only add the newline in that case?

@atugushev

**Comment by atugushev** [comment]
@AndydeCleyre 

> Would it be preferable for the writer line iterator to simply always yield a final extra newline, or to actually keep track of whether or not it has yielded any real lines along the way, and only add the newline in that case?

I'd prefer the second suggestion.
