### ISSUE TITLE
Use egg info in annotations for VCS dependencies

### ISSUE THREAD

**Issue by cbows** [jazzband/pip-tools#901]
#### What's the problem this feature will solve?
Annotations of subdependencies of VCS dependencies are missing in `requirements.txt`.

#### Describe the solution you'd like
Consider using the egg name specified either as

```
egg_name @ <vcs_url>
```

or 

```
<vcs_url>#egg=egg_name
```

in the annotations in the `requirements.txt`, e.g.

```
package_name  # via egg_name
```

**Comment by atugushev** [comment]
Hello @cbows,

Thanks for the issue! This is a duplicate of #293.
