### ISSUE TITLE
Auto rerun network tests in CI

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#918]
#### What's the problem this feature will solve?

Sometimes tests that require the internet are [failing](https://travis-ci.org/jazzband/pip-tools/jobs/594325372) on network error. This happens quite regularly. AFAIK the contributors cannot rerun CI jobs manually, so that requires a member action. Would be nice to auto rerun failed network tests N times with M seconds delay.

#### Describe the solution you'd like

Use one of the [pytest plugin](https://docs.pytest.org/en/latest/flaky.html#plugins) to restart flaky tests. [Pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) might be suitable for us. Also, pip also uses this plugin and it works good.

 
Add to `conftest.py` a hook `pytest_collection_modifyitems` which marks all network tests as flaky and rerun them 5 times with 2 seconds delay:

```python
def pytest_collection_modifyitems(config, items):
    for item in items:
        if item.get_closest_marker("network") and "CI" in os.environ:
            item.add_marker(pytest.mark.flaky(reruns=5, reruns_delay=2))
```

Update `tox.ini`:

```ini
[tox]
deps = 
    ...
    pytest-rerunfailures
...

[testenv]
passenv = CI
...
```

#### Alternative Solutions

N/A

#### Additional context

N/A

**Comment by peymanslh** [comment]
I can work on this issue

**Comment by atugushev** [comment]
@peymanslh thanks! Appreciate it!
