### ISSUE TITLE
Suggest adding atugushev as pip-tools maintainer

### ISSUE THREAD

**Issue by davidovich** [jazzband/pip-tools#937]
Hi, 

I was one of the first Jazzband era pip-tools maintainer with @vphilippon, and have since moved to projects where I don't use Python, so even less pip-tools.

In this situation, I am just a bystander, and although I would be ready to step in if we had a maintainer deadlock, I cannot offer time to pip-tools. 

@atugushev has been doing a very nice job and thoroughly maintaining pip-tools, adding features and giving leadership to new additions. @vphilippon and I were discussing that we should invite and formalize @atugushev de-facto maintainer status.

In light of this, I believe that we should invite @atugushev as core maintainer to the project.

**Comment by vphilippon** [comment]
As David said, we both discussed this, I'd be more than happy to see @atugushev take up the Project Lead role, if he's interested of course :)

@jezdez Heads up, here's a proposal.

**Comment by atugushev** [comment]
Thank you very much, @davidovich and @vphilippon! I'd be happy and deeply honored to take this up!

**Comment by jezdez** [comment]
@davidovich @vphilippon Great, thank you, I believe this is the first time a project has extended its project leads on its own, congrats!

@atugushev Many thanks for stepping up, and congratulations! I've just added you as project lead: https://jazzband.co/projects/pip-tools

**Comment by atugushev** [comment]
Thanks, @jezdez!
