### ISSUE TITLE
Pip-compile ignores environment-marked requirements in setup.py

### ISSUE THREAD

**Issue by jbai14** [jazzband/pip-tools#946]
Pip-compile ignores environment-marked requirements in `setup.py`'s `install_requires` section, even when the condition succeeds. However, this does not happen when using a `requirements.in` file with the same requirements.

#### Environment Versions

1. macOS Mojave
1. Python version: 3.6.0
1. pip version:  19.3
1. pip-tools version: 4.2.0

#### Steps to replicate

1. Create a `requirements.in` file with `requests>1.0;python_version=='3.6'`. Run `pip-compile` with Python 3.6 .
2. In a separate folder, create a `setup.py` file with
```
from setuptools import setup
setup(
    name="my-package",
    install_requires=["requests>=1.0;python_version=='3.6'"],
)
```
Run `pip-compile` with Python 3.6 .

#### Expected result

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
certifi==2019.9.11        # via requests
chardet==3.0.4            # via requests
idna==2.8                 # via requests
requests==2.22.0 ; python_version == "3.6"
urllib3==1.25.6           # via requests
```
for both.

#### Actual result

The above for the `requirements.in` file, just the top comments (no actual requirements) for the `setup.py` file.

**Comment by atugushev** [comment]
Hello @jbai14,

Thanks for the detailed issue! It duplicates #625.

**Comment by jbai14** [comment]
Ah, thanks! I'll close this then.
