### ISSUE TITLE
Add python 3.8 support

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#948]
#### What's the problem this feature will solve?

Python 3.8 is released, so it's time to support it. 

#### Describe the solution you'd like

1. add "py37" env to `tox.ini`
1. remove 3.8-dev from `.travis.yml`
1. add "Programming Language :: Python :: 3.8" classifier to `setup.py`
1. add "3.8" dimension to `.travis.yml` (supported, see https://travis-ci.community/t/add-python-3-8-support/5463)
1. add "py37" dimension to `.appveyor.yml` (not supported yet, but will be on the nex image update, tracking issue: https://github.com/appveyor/ci/issues/3142)
1. add "3.8" to python-version list in `.github/workflows/cron.yml` (not supported yet, tracking issue: https://github.com/actions/setup-python/issues/30)

#### Alternative Solutions

N/A

#### Additional context

https://discuss.python.org/t/python-3-8-0-is-now-available/2478

**Comment by hramezani** [comment]
@atugushev I can work on this.

**Comment by atugushev** [comment]
Thanks, @hramezani! Appreciate it.

**Comment by hugovk** [comment]
🚀 Python 3.8 is now available on AppVeyor:

* https://github.com/appveyor/ci/issues/3142#issuecomment-552049896

**Comment by atugushev** [comment]
@hugovk Yeah! Finally, all opened issues are closed 😊
