### ISSUE TITLE
pip-compile -P <package> *installs* package if it's not declared in requirements.in

### ISSUE THREAD

**Issue by tuukkamustonen** [jazzband/pip-tools#950]
E.g. `pip-compile -P flask` _installs_ it if it's not declared in `requirements.in`.

#### Environment Versions

1. OS Type: 
1. Python version: `3.7.2`
1. pip version:  `19.2.3`
1. pip-tools version: `4.2.0`

#### Steps to replicate

Prepare virtualenv:

```shell
$ pyenv virtualenv 3.7.2 py37
$ pyenv activate py37
$ pip install -U pip pip-tools
```

Run:

```shell
$ touch requirements.in
$ pip-compile --no-header --no-index -P flask
click==7.0                # via flask
flask==1.1.1
itsdangerous==1.1.0       # via flask
jinja2==2.10.3            # via flask
werkzeug==0.16.0          # via flask
```

So, `flask` gets installed, if it doesn't exist. But if the option is called `--upgrade-package` then I think it should only upgrade, not install.

If the behavior is intentional and it _should_ install non-existent package, could we have option to _only upgrade_ specified packages (I don't want to upgrade all with `-U`)?

Use case: I have multiple python projects in single repository (~monorepo) and I want to upgrade certain dependencies in all of them (looping over them and calling `pip-compile -P <package>`). Not all projects use/define certain libraries (e.g. `flask`) so I don't want to _install_ them where they don't exist, only upgrade where the libraries are already used.

**Comment by atugushev** [comment]
Hello @tuukkamustonen,

Thanks for reporting this! It's duplicate of #759.

**Comment by tuukkamustonen** [comment]
Doh, my search-fu wasn't sufficient to find that. Let's close this then.

Thanks for quick response!
