### ISSUE TITLE
Unable to run checkqa with python3 other than 3.7

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#954]
#### What's the problem this feature will solve?

If a user does not have python3.7 version (but has one of the others of python3), then he/she will get the following error on `tox -e checkqa`:

```bash
$ tox -e `checkqa`

...

An unexpected error has occurred: CalledProcessError: Command: ('/home/runner/work/pip-tools/pip-tools/.tox/checkqa/bin/python', '-mvirtualenv', '/home/runner/.cache/pre-commit/repo6e2pqtpw/py_env-python3.7', '-p', 'python3.7')
Return code: 3
Expected return code: 0
Output: 
    The path python3.7 (from --python=python3.7) does not exist
    
Errors: (none)

...

```

This error happens, because of `language_version` stuck to python3.7, see: https://github.com/jazzband/pip-tools/blob/db5ff37e1f1cf730c4f40040d0b4f85d6c7659e9/.pre-commit-config.yaml#L6

and pre-commit resolves python to 3.7, which may be not presented at the system.

#### Describe the solution you'd like

Change `language_version: python3.7` to `language_version: python3` in `.pre-commit-config.yaml`.

#### Alternative Solutions

N/A

#### Additional context

See https://github.com/jazzband/pip-tools/issues/938#issuecomment-541286891, where this issue caught.

**Comment by ammarnajjar** [comment]
hi @atugushev , I just went out on a limb and submitted a PR 😄

**Comment by atugushev** [comment]
@ammarnajjar thanks a lot!
