### ISSUE TITLE
Remove a dead code from test/conftest.py

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#958]
#### What's the problem this feature will solve?

Since `Distribution.as_requirement()` method usage has been removed in 3db17678aa05f0e986e12b6ae7b2d2b8e0831ecf, thus we should remove it from `FakeInstalledDistribution` in `test/conftes.py` to increase tests coverage.

#### Describe the solution you'd like

Remove `FakeInstalledDistribution.as_requirement()` method in `test/conftes.py` module.

#### Alternative Solutions

N/A

#### Additional context

N/A

**Comment by hramezani** [comment]
I created a PR.
