### ISSUE TITLE
Add a test for FakeRepository.get_hashes()

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#960]
#### What's the problem this feature will solve?

`FakeRepository.get_hashes()` has no test in `tests/test_fake_index.py`.

#### Describe the solution you'd like

Add a test to `tests/test_fake_index.py`:

```python
def test_get_hashes(from_line, repository):
    ireq = from_line("django==1.8")
    assert repository.get_hashes(ireq) == ...
```

#### Alternative Solutions

N/A

#### Additional context

- https://github.com/jazzband/pip-tools/pull/383/files#r79352023
- https://github.com/jazzband/pip-tools/commit/4d002e517265481d8c550c739cee24f9d895d213

**Comment by hramezani** [comment]
I made a PR for this.
