### ISSUE TITLE
Move tests from test_repositories.py to test_repository_pypi.py

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#969]
#### What's the problem this feature will solve?

Currently, we have two files, `test_repositories.py` and `test_repository_pypi.py` with tests related to `PyPIRepository`. Better to have them in one logical place.

#### Describe the solution you'd like

Move tests from `test_repositories.py` to `test_repository_pypi.py`.

#### Alternative Solutions

N/A

#### Additional context

N/A

**Comment by phayaran** [comment]
#970

**Comment by atugushev** [comment]
@phayaran 

> Created PR #970 for this issue.

Thank you so much!

**Comment by phayaran** [comment]
@atugushev , Thanks a lot for taking the time to review it, and giving valuable feedback. Being a newbie to opensource, it is really helpful.

I have created a new commit 9346cfe1b6344e767b83255b24a924034b578484 with the changes you suggested, please, let me know if any other action I need to take. Thanks!!
