### ISSUE TITLE
pip-tools fails on simple example with scikit-learn/tpot

### ISSUE THREAD

**Issue by jimmywan** [jazzband/pip-tools#985]
pip-tools fails on a seemingly trivial example. It appears to "save" the unconstrained requirement as a fixed one in later iterations.

#### Environment Versions

1. OS Type
MacOS Catalina 10.15.1
```bash
$ python --version
Python 3.6.6 :: Anaconda, Inc.
$ pip-compile --version
pip-compile, version 4.2.0
$ pip -V | cut -d ' ' -f -2
pip 19.2.2
```
#### Steps to replicate

1. create input files with and without an extra constraint on `tpot`.
```bash
$ cat test_unconstrained_tpot.input.txt
scikit-learn>=0.19,<0.20
tpot
$ cat test_constrained_tpot.input.txt
scikit-learn>=0.19,<0.20
tpot<0.11
```
2. run `pip-compile` on the following inputs:
```
$ pip-compile -v -r test_unconstrained_tpot.input.txt -o test_unconstrained_tpot.txt  2>&1 | tail -n +4 > test_unconstrained_tpot.log.txt
$ pip-compile -v -r test_constrained_tpot.input.txt -o test_constrained_tpot.txt 2>&1 | tail -n +4 > test_constrained_tpot.log.txt
```
NOTE: I used `tail -n +4` just to strip out debug info about my locally configured pypi repos, but it shouldn't be relavent.

3. Get results
I've attached logs below.

#### Expected result

I expect the results to be the same either way as tpot 0.11.0 has a dependency on scikit-learn>=0.21.0

#### Actual result

unconstrained fails and constrained succeeds.

Some snippets from the unconstrained log:
```
                          ROUND 1
Current constraints:
  scikit-learn<0.20,>=0.19 (from -r test_unconstrained_tpot.input.txt (line 1))
  tpot (from -r test_unconstrained_tpot.input.txt (line 2))
...
                          ROUND 2
Current constraints:
  scikit-learn<0.20,>=0.19,>=0.21.0 (from -r test_unconstrained_tpot.input.txt (line 1))
  tpot (from -r test_unconstrained_tpot.input.txt (line 2))
...
Could not find a version that matches scikit-learn<0.20,>=0.19,>=0.21.0 (from -r test_unconstrained_tpot.input.txt (line 1))
...
There are incompatible versions in the resolved dependencies:
  scikit-learn<0.20,>=0.19 (from -r test_unconstrained_tpot.input.txt (line 1))
  scikit-learn>=0.21.0 (from tpot==0.11.0->-r test_unconstrained_tpot.input.txt (line 2))
```

Note how on that very last line "==0.11.0" got added even though that's not actually from the original input. It's as though it never looked for alternate versions of tpot.

[test_constrained_tpot.input.txt](https://github.com/jazzband/pip-tools/files/3848151/test_constrained_tpot.input.txt)
[test_constrained_tpot.log.txt](https://github.com/jazzband/pip-tools/files/3848152/test_constrained_tpot.log.txt)
[test_unconstrained_tpot.input.txt](https://github.com/jazzband/pip-tools/files/3848153/test_unconstrained_tpot.input.txt)
[test_unconstrained_tpot.log.txt](https://github.com/jazzband/pip-tools/files/3848154/test_unconstrained_tpot.log.txt)

**Comment by atugushev** [comment]
Hello @jimmywan 

Thanks for the detailed report and the attached files! That's because pip and pip-tools don't have a proper dependency resolver. See #693 and https://github.com/pypa/pip/issues/988 for details.

**Comment by jimmywan** [comment]
Thanks @atugushev . I admittedly hadn't read how the tools were constructed all that carefully. I didn't realize this was something that pip-tools didn't handle on its own.

**Comment by atugushev** [comment]
@jimmywan fortunately, that should be fixed in 2020, see https://twitter.com/ThePSF/status/1194593273291190272.

**Comment by atugushev** [comment]
I'll close this in favor of #693. Feel free to reach us out if you have any other issues. Thanks!
