### ISSUE TITLE
Reduce tests which require the network

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#990]
#### What's the problem this feature will solve?

Currently, we have 13 tests that require the internet. We could reduce this number to 3. All tests marked as `@pytest.mark.network` could be refactored to use local package `small-fake-with-deps`, except probably those tests, which related to URL/VCS packages:
- test_editable_package_vcs
- test_generate_hashes_with_url

or do realistic (functional) tests, which is `test_realistic_complex_sub_dependencies`.

#### Describe the solution you'd like

1. Replace `six` and `setuptools` requirements with `small-fake-a` and `small-fake-b` in `tests/test_data/packages/small_fake_with_deps/setup.py`
2. Refactor the following tests to use `small-fake-with-deps` package:
- test_editable_package
- test_locally_available_editable_package_is_not_archived_in_cache_dir
- test_generate_hashes_with_editable
- test_generate_hashes_verbose
- test_allow_unsafe_option
- test_get_hashes_local_repository_cache_miss
- test_generate_hashes_all_platforms
- test_generate_hashes_without_interfering_with_each_other
- test_editable_top_level_deps_preserved
3. Move parameters related to `small-fake-with-deps` from `test_url_package` to a separate test `test_local_url_package` and replace `six` to `small-fake-a`.
4. Remove `small-fake-with-deps-a` package and its wheels, and refactor `test_annotate_option` to use `small-fake-with-deps`.

#### Alternative Solutions

N/A

#### Additional context

N/A

**Comment by atugushev** [comment]
@hramezani would you like to pick up this one?

**Comment by hramezani** [comment]
@atugushev, yes. Assign it to me.

**Comment by atugushev** [comment]
@hramezani, thanks!
