### ISSUE TITLE
Clean up piptools/_vendored mentions

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#993]
#### What's the problem this feature will solve?

Since `piptools/_vendored` does not exist anymore in the codebase, this should be cleaned up:
https://github.com/jazzband/pip-tools/blob/ef529778f90cb1ac0a6affb09e4d9d3fb56c1e76/tests/__init__.py#L1-L2
https://github.com/jazzband/pip-tools/blob/ef529778f90cb1ac0a6affb09e4d9d3fb56c1e76/.coveragerc#L6
https://github.com/jazzband/pip-tools/blob/ef529778f90cb1ac0a6affb09e4d9d3fb56c1e76/setup.cfg#L8

#### Describe the solution you'd like

1. clean up `tests/__init__.py`
1. remove `piptools/_vendored` mentions in [setup.cfg](https://github.com/jazzband/pip-tools/blob/ef529778f90cb1ac0a6affb09e4d9d3fb56c1e76/setup.cfg#L8) and [.coveragerc](https://github.com/jazzband/pip-tools/blob/ef529778f90cb1ac0a6affb09e4d9d3fb56c1e76/.coveragerc#L6
)

#### Alternative Solutions

N/A

#### Additional context

N/A

---

_This is a good issue for the first time contributors to work on. Feel free to ask any questions, we'd gladly help you make your first contributions._

**Comment by peymanslh** [comment]
Hi @atugushev 
I can work on this issue.

**Comment by atugushev** [comment]
Hello @peymanslh! Sure, go for it! 👍
