### ISSUE TITLE
pip-compile does not pick up pytest dependencies

### ISSUE THREAD

**Issue by mlenzen** [jazzband/pip-tools#995]
Compiling with pytest in the input does not result in pytest's dependencies in the output.

#### Environment Versions

1. OS Type: Linux (Ubuntu) & Macs
1. Python version: Python 3.7.4
1. pip version:  pip 19.3.1
1. pip-tools version: pip-compile, version 4.2.0

#### Steps to replicate

1. `echo 'pytest==5.2.4' >requirements.in`
2. `pip-compile requirements.in`
3. `cat requirements.txt`

#### Expected result
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.in
#
pytest==5.2.4
py==...
packaging==...
attrs==...
more-itertools==...
atomicwrites==...
...
```

#### Actual result
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.in
#
pytest==5.2.4
```

**Comment by atugushev** [comment]
Hello @mlenzen,

Thanks for the report! Could you try `--rebuild` flag with `pip-compile` command? Sounds like your cache was corrupted.

**Comment by mlenzen** [comment]
Yeah, that solved it.
